# -*- coding: utf-8 -*-
"""Unit 8 SAQ cards 53-58 (book pp.46-47) and Star-Q SAQ 188-190 (book p.68)."""
from eelib import *

S = "SAQ"

# ── 53 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_greenhouse_effect", S, 46, 53,
     "Describe Green House Effect.",
     app((2017, "ap_ipe"), (2014, None)),
     [("Definition", 1), ("Radiation reaching the earth", 1),
      ("Role of the greenhouse gases", 1), ("Result", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "The greenhouse effect is a naturally",
             "occurring phenomenon that is responsible for",
             "the heating of the earth's surface and its",
             "atmosphere.",
             "It is named after a glass greenhouse, which",
             "lets sunlight in and holds the heat inside.",
         ],
             "The word naturally is placed first because the greenhouse effect is not itself a pollution problem; only the increase in the gases is, and a student who calls the effect harmful has answered the global warming question instead.",
             ["Writing that the greenhouse effect is caused by pollution. The effect itself is natural.",
              "Confusing it with global warming. Global warming is the RISE in the effect above normal."],
             "The atmosphere works like the glass of a greenhouse: light passes in, heat does not pass out.",
             "One sentence with the word naturally in it. Do not start on global warming here."),
         step("s2_radiation", "text", "Radiation reaching the earth", 1, "Radiation", [
             "When sunlight reaches the outermost layer of",
             "the atmosphere, some radiation is absorbed",
             "there.",
             "About one fourth of the solar radiation is",
             "reflected back by the clouds and gases.",
             "Only about half of the incoming solar",
             "radiation reaches the earth's surface, and",
             "the earth gets heated.",
         ],
             "The three fractions are the physical account of the effect, and giving them in order — absorbed, reflected, reaching the ground — shows the examiner the answer is describing a process and not just naming it.",
             ["Writing that all the sunlight reaches the ground. Only about half of it does.",
              "Swapping the fractions. About one fourth is reflected; about half reaches the surface."],
             "Some absorbed, one fourth reflected, one half arrives — that is the sunlight's journey down.",
             "Three short statements with the fractions attached. Keep them in order."),
         step("s3_gases", "text", "Role of the greenhouse gases", 1, "Gases", [
             "The heated earth sends a part of this heat",
             "back into the atmosphere.",
             "The greenhouse gases, mainly carbon dioxide",
             "(CO₂) and methane (CH₄), absorb this heat.",
             "They reflect a major part of it back to the",
             "earth's surface instead of letting it",
             "escape into space.",
         ],
             "This step is the mechanism and therefore the heart of the answer: the gases act on the heat going UP, not on the sunlight coming down, and that direction is what the mark is for.",
             ["Writing that the greenhouse gases stop the sunlight. They act on the HEAT leaving the earth.",
              "Naming only carbon dioxide. Methane is the second named greenhouse gas here."],
             "Light goes in easily, heat cannot get out. The gases work on the way UP, not the way down.",
             "Name the two gases and say clearly that they send the heat back DOWN."),
         step("s4_result", "boxed_final", "Result", 1, "Result", [
             boxed("Heat is trapped, so the earth warms up"),
             "Because of this, the earth's surface heats up",
             "once again.",
             "This whole phenomenon is called the",
             "greenhouse effect.",
             "Without it the earth would be far too cold",
             "for living things.",
         ],
             "Closing with the name of the phenomenon completes the answer as the question asked it, and the last line makes clear why the effect is described as natural and useful.",
             ["Ending with the harmful effects. Those belong to the global warming question.",
              "Not naming the phenomenon at the end. The examiner looks for the closing sentence."],
             "Natural and useful at the normal level; harmful only when the gases increase.",
             "Close by naming the phenomenon. One line on why it is needed."),
     ],
     "Keep this answer separate from global warming: the greenhouse effect is the natural process, and global warming is what happens when the gases rise above their normal level."),

# ── 54 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_global_warming_causes_effects", S, 46, 54,
     "Discuss the causes and effects of global warming. What measures need to be taken to control 'Global Warming'?",
     app((2015, "ts_ipe"), (2015, "ap_ipe"), (2016, "ap_ipe")),
     [("Definition", 1), ("Causes", 1), ("Effects", 1), ("Control measures", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Global warming is the rise of the",
             "temperature of the atmosphere above its",
             "normal level.",
             "It happens because of the increase in the",
             "emission of greenhouse gases.",
         ],
             "The question has three parts, so the definition is kept to two lines; naming the greenhouse gases here also links this answer to the greenhouse effect without repeating it.",
             ["Defining global warming as the greenhouse effect. Global warming is the RISE above the normal level.",
              "Leaving out the greenhouse gases. They are the named reason for the rise."],
             "Three-part question, three-part answer: causes, effects, measures. Split the page before writing.",
             "Two lines only. The three asked parts each need their own space."),
         step("s2_causes", "text", "Causes", 1, "Causes", [
             "Carbon dioxide (CO₂) is the air pollutant",
             "chiefly responsible for global warming.",
             "It is produced by:",
             "(i) incomplete combustion of fossil fuels",
             "(ii) automobile exhaust",
             "(iii) factory fumes",
             "(iv) emissions from power plants",
             "(v) forest fires",
         ],
             "The causes are all sources of one gas, so naming carbon dioxide first and listing the sources under it keeps the answer short and shows the examiner they are not five separate causes.",
             ["Listing the sources without naming carbon dioxide first.",
              "Naming chlorofluorocarbons. Those are the ozone question, not this one."],
             "One gas, five taps: engines, factories, power plants, fires and unburnt fuel.",
             "Name the gas, then the sources as a numbered list. A list scores as fast as sentences."),
         step("s3_effects", "text", "Effects", 1, "Effects", [
             "(i) Climatic changes across the world.",
             "(ii) The El Nino effect.",
             "(iii) Melting of the snow caps of mountains",
             "and of the polar ice.",
             "This raises the sea level and results in the",
             "submergence of coastal areas.",
         ],
             "Three effects is enough for one mark, and the melting one is written with its consequence attached because the rise in sea level is the fact examiners look for.",
             ["Writing only that the earth gets hotter. That is the definition, not an effect.",
              "Leaving out the sea level. Melting ice matters because coastal land goes under water."],
             "Warmer air changes three things: the climate, the ocean currents and the ice.",
             "Three effects, one line each, with the sea level attached to the melting one."),
         step("s4_measures", "boxed_final", "Control measures", 1, "Measures", [
             boxed("Burn less, plant more, and hold to the limits"),
             "(i) Reducing the use of fossil fuels.",
             "(ii) Improving the efficiency of energy use.",
             "(iii) Planting trees and avoiding",
             "deforestation.",
             "(iv) Slowing the growth of the human",
             "population.",
             "(v) The Kyoto Protocol: 191 countries signed",
             "it at Kyoto in Japan, agreeing to cut",
             "greenhouse gas emissions to the 1990 level.",
         ],
             "The Kyoto Protocol is the only named agreement in this part of the syllabus, so it is written last and in full with its number and its target — those two facts are what mark it out from a general statement.",
             ["Leaving out the Kyoto Protocol. It is the named measure and carries most of this mark.",
              "Writing the Kyoto Protocol without its target. The agreed level is that of 1990."],
             "Four ordinary measures and one named agreement: Kyoto, 191 countries, back to 1990 levels.",
             "Four short measures, then the Kyoto Protocol with its number and its target year."),
     ],
     "The question asks three things and the marks are split evenly, so a long answer on the causes and nothing on the measures scores about half."),

# ── 55 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_ozone_depletion_effects", S, 46, 55,
     "What are the deleterious effects of depletion of ozone in the stratosphere?",
     app((2014, None), (2019, "ts_ipe"), (2019, "ap_ipe")),
     [("Depletion of the ozone layer", 1), ("Effect on DNA", 1),
      ("Effect on the skin", 1), ("Effect on the eyes", 1)],
     [
         step("s1_depletion", "text", "Depletion of the ozone layer", 1, "Depletion", [
             "The ozone layer lies in the stratosphere and",
             "absorbs the ultraviolet (UV) radiation of",
             "sunlight.",
             "When the ozone layer is depleted markedly it",
             "leads to an ozone hole.",
             "The layer becomes very thin and can no",
             "longer stop the UV radiation completely.",
             "The shorter wavelength rays, UV-B, then",
             "reach the earth's surface.",
         ],
             "Every harmful effect that follows is caused by UV-B, so this step must get the radiation to the ground first; an answer that lists the effects without naming UV-B has left out the cause.",
             ["Writing that the ozone hole itself burns the skin. The harm is done by the UV-B that passes through.",
              "Naming UV-A. The harmful shorter wavelength radiation here is UV-B."],
             "Thin layer, more UV-B through, and every effect below follows from that one fact.",
             "Get UV-B to the ground before listing any effect. Four short lines."),
         step("s2_dna", "text", "Effect on DNA", 1, "DNA", [
             "UV rays damage the DNA of the cells.",
             "This may lead to mutations.",
             "Mutations change the working of the cell and",
             "can be passed on when the cell divides.",
         ],
             "DNA damage is placed first among the effects because it is the deepest one — the changes to the skin and the eyes are what a person sees, but the damage begins in the molecule.",
             ["Writing that UV kills the cell outright. It DAMAGES the DNA and causes mutations.",
              "Leaving out the word mutation, which is the named result here."],
             "Work from the inside out: DNA first, then the skin, then the eyes.",
             "Two short lines. The word mutation must appear."),
         step("s3_skin", "text", "Effect on the skin", 1, "Skin", [
             "UV rays cause ageing of the skin.",
             "They damage the skin cells and can cause",
             "skin cancer.",
             "They also cause sunburn on exposed skin.",
         ],
             "Skin cancer is the effect examiners look for by name, so it is written in full rather than being left inside a general statement about damage.",
             ["Writing damage to the skin without naming skin cancer.",
              "Writing that UV causes leprosy or any infection. UV damage is not an infection."],
             "Skin gets three things from UV: it ages, it burns, and it may turn cancerous.",
             "Three short effects. Skin cancer must be named in words."),
         step("s4_eyes", "boxed_final", "Effect on the eyes", 1, "Eyes", [
             boxed("UV-B harms the DNA, the skin and the eyes"),
             "A high concentration of UV-B causes",
             "inflammation of the cornea.",
             "This leads to snow blindness and to",
             "cataract.",
             "Sometimes it damages the cornea permanently.",
         ],
             "The eye effects are the ones with named conditions attached, and naming the cornea shows exactly which part of the eye is struck, which is what separates a full answer from a vague one.",
             ["Writing that UV causes blindness. The named conditions are snow blindness and cataract.",
              "Naming the retina. The part named in this answer is the CORNEA."],
             "Three eye words in order: cornea inflamed, snow blindness, cataract.",
             "Name the cornea and both conditions. The box gathers the three targets of UV-B."),
     ],
     "Every effect must be traced back to UV-B — an answer that says the ozone hole causes cancer without naming the radiation loses the first mark."),

# ── 56 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_summer_stratification", S, 47, 56,
     "What is summer stratification? Explain.",
     app((2017, "ts_ipe"), (2020, "ts_ipe"), (2018, "ap_ipe"), (2020, "ap_ipe")),
     [("Definition and the three layers", 1), ("Epilimnion", 1),
      ("Thermocline and hypolimnion", 1), ("Autumn overturn", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Summer stratification is the formation of",
             "three layers of water in a temperate lake",
             "during summer.",
             "In summer the temperature of the lake rises",
             "up to about 25°C.",
             "The periodic circulation of the water then",
             "stops, and three layers are formed:",
             "1) Epilimnion  2) Thermocline",
             "3) Hypolimnion",
         ],
             "The three names in order from the top down are the plan of the whole answer, so they are written before any of them is described, and the temperature is given because it is what stops the water mixing.",
             ["Writing the three layers in the wrong order. Epilimnion is at the top, hypolimnion at the bottom.",
              "Leaving out the word temperate. The layering is described for temperate lakes."],
             "Epi is above, hypo is below, and the thermocline is the temperature step between them.",
             "Definition, temperature, then the three names in order. Name them before describing them."),
         step("s2_diagram", "diagram", "Diagram — the three layers", 0, None, None,
              "The three layers stack in a fixed order with the temperature falling downwards, and a drawing fixes that order in a way a list of names cannot; the layers must be seen as bands, not as separate boxes.",
              ["Drawing the layers side by side. They are stacked one above the other.",
               "Putting the warm layer at the bottom. The warm epilimnion is the TOP layer."],
              "Warm on top, cold at the bottom — warm water floats, so the order can never be the other way round.",
              "The question does not ask for a diagram, so this figure is not marked. Draw it to fix the order of the layers.",
              figure=getfig("ee_summer_stratification")),
         step("s3_epilimnion", "text", "Epilimnion", 1, "Epilimnion", [
             "Epilimnion is the upper layer of water.",
             "It is warm and rich in oxygen.",
             "Its temperature ranges from 21°C to 25°C.",
         ],
             "Each layer is described by the same two properties — its temperature and its oxygen — so that the three descriptions can be compared, which is what makes the layering visible.",
             ["Writing that the top layer is poor in oxygen. It is in contact with the air, so it is RICH in oxygen.",
              "Leaving out the temperature range. The numbers are what separate the layers."],
             "Top layer: warm, bright and full of oxygen, because it touches the air and the sun.",
             "Three short lines: name, properties, temperature range."),
         step("s4_thermo_hypo", "text", "Thermocline and hypolimnion", 1, "Middle and bottom", [
             "Thermocline is the layer below the",
             "epilimnion. It is also called the",
             "metalimnion.",
             "In it the temperature falls at the rate of",
             "1°C per metre of depth.",
             "Hypolimnion is the bottom layer, where the",
             "temperature is about 7°C.",
             "Its water is stagnant, cool and rich in",
             "nutrients, and it has a low oxygen content",
             "because there is no photosynthesis there.",
         ],
             "The thermocline is defined by a RATE, not by a temperature, and that rate is the one number in this answer a student is likely to leave out; the hypolimnion is then described with the same two properties as the top layer, in reverse.",
             ["Giving the thermocline a fixed temperature. It is defined by the fall of 1°C per metre.",
              "Writing that the bottom layer is rich in oxygen. It is LOW in oxygen and rich in nutrients."],
             "Down the lake: 25°C at the top, 1°C lost per metre through the middle, about 7°C at the bottom.",
             "The rate for the thermocline and the temperature for the hypolimnion. Both numbers are needed."),
         step("s5_overturn", "boxed_final", "Autumn overturn", 1, "Overturn", [
             boxed("Autumn overturn mixes the lake again"),
             "In autumn the temperature of the surface",
             "water falls to 4°C.",
             "Water is heaviest at 4°C, so this surface",
             "water sinks to the bottom.",
             "The bottom water, carrying its nutrients,",
             "rises to the surface.",
             "This circulation is called the autumn",
             "overturn, and it makes the temperature,",
             "the nutrients and the oxygen uniform",
             "through the lake again.",
         ],
             "Summer stratification is one half of a yearly cycle, and the overturn is the half that undoes it; the answer needs the 4°C fact because that is the physical reason the surface water sinks.",
             ["Writing that the overturn happens in summer. It follows the summer, in AUTUMN.",
              "Leaving out 4°C. Water is heaviest at that temperature, which is why the surface water sinks."],
             "At 4°C water is at its heaviest, so the cooled top layer sinks and turns the lake over.",
             "The 4°C fact first, then the sinking, then the result. Close with the word uniform."),
     ],
     "The three layer names in top-to-bottom order and the 1°C per metre rate are the two things checked first; the autumn overturn is a full mark on its own and is the part most often left out."),

# ── 57 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_freshwater_vs_seawater_adaptations", S, 47, 57,
     "Compare the adaptations of animals with freshwater and seawater mode of life.",
     app((2016, "ts_ipe")),
     [("The freshwater problem", 1), ("Freshwater adaptations", 1),
      ("The seawater problem", 1), ("Seawater adaptations", 1)],
     [
         step("s1_fresh_problem", "text", "The freshwater problem", 1, "Problem", [
             "Fresh water holds less salt than the body",
             "fluids of the animals living in it.",
             "So water passes INTO their bodies through",
             "the body surface. This is endosmosis.",
             "A freshwater animal therefore has to remove",
             "the extra water that keeps entering.",
         ],
             "Both halves of this answer are the same story told in opposite directions, so the problem is stated first in each half; every adaptation that follows is a way of solving that one problem.",
             ["Writing that fresh water is saltier than the body. It holds LESS salt than the body fluids.",
              "Using the word exosmosis here. Water moves IN, so it is endosmosis."],
             "Water always moves towards the saltier side. In fresh water the animal is the salty side, so water comes in.",
             "State the direction of the water first. Every adaptation below answers it."),
         step("s2_fresh_adapt", "text", "Freshwater adaptations", 1, "Adaptations", [
             "(i) Freshwater fishes have glomerular",
             "kidneys, which remove the excess water as a",
             "large amount of dilute urine.",
             "(ii) Freshwater sponges produce gemmules to",
             "survive the summer.",
             "(iii) The African lung fish undergoes",
             "aestivation by forming a gelatinous cocoon",
             "to survive the summer.",
         ],
             "The first adaptation answers the water problem directly; the other two answer a second freshwater problem — a pond may dry up — which is why they are about surviving the summer and not about salt.",
             ["Writing that freshwater fishes have aglomerular kidneys. Those belong to the MARINE fishes.",
              "Leaving out the gemmules and the cocoon. Drying up is a freshwater problem too."],
             "Glomerular kidney for the water, gemmule and cocoon for the dry season.",
             "Three adaptations, one line each. Keep the kidney first."),
         step("s3_sea_problem", "text", "The seawater problem", 1, "Problem", [
             "Sea water holds more salt than the body",
             "fluids of the animals living in it.",
             "So water passes OUT of their bodies. This is",
             "exosmosis.",
             "A marine animal therefore keeps losing water",
             "and has to save it.",
         ],
             "Writing this half in the same shape as the freshwater half makes the comparison the question asks for visible on the page, with only the direction of the water changed.",
             ["Using endosmosis here. In sea water the water moves OUT, so it is exosmosis.",
              "Writing that marine animals gain water. They lose it continuously."],
             "Same rule, opposite direction: the sea is the salty side, so the water leaves the animal.",
             "Mirror the freshwater half exactly, with the direction reversed."),
         step("s4_sea_adapt", "boxed_final", "Seawater adaptations", 1, "Adaptations", [
             boxed("Fresh water: take water in. Sea water: keep it"),
             "(i) Marine fishes have aglomerular kidneys",
             "with fewer nephrons, so little water is",
             "lost as urine.",
             "(ii) They have salt-secreting chloride cells",
             "in the gills, which throw out the extra",
             "salt.",
             "(iii) Marine birds and penguins pass out",
             "salt drops through the nostrils.",
             "(iv) Sharks retain urea and trimethylamine",
             "oxide (TMO) in the body fluids to keep the",
             "salt balance.",
         ],
             "Four adaptations are given because they solve two different sides of the same problem — saving water and getting rid of salt — and an answer with only the kidney has covered one side.",
             ["Writing that marine fishes pass a lot of urine. They pass very little, to save water.",
              "Leaving out the shark. Retaining urea and TMO is the named example in this answer."],
             "Two jobs at sea: hold the water in (kidney) and push the salt out (gills, nostrils).",
             "Four adaptations, one line each. The box states the whole comparison in one line."),
     ],
     "The question says compare, so write the two halves in the same order with the same headings — a page of freshwater adaptations followed by nothing on the sea scores half."),

# ── 58 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_detritus_food_chain_note", S, 47, 58,
     "Write a note on DFC. Give the significance in a terrestrial ecosystem.",
     app((2018, "ap_ipe"), (2018, "ts_ipe")),
     [("What DFC is", 1), ("Detritus", 1), ("Decomposers", 1),
      ("Significance and examples", 1)],
     [
         step("s1_dfc", "text", "What DFC is", 1, "Identity", [
             "DFC stands for Detritus Food Chain.",
             "It is a food chain that begins with dead",
             "organic matter instead of with a living",
             "green plant.",
             "It is the important food chain of a",
             "terrestrial ecosystem.",
         ],
             "The letters must be expanded first, and the one line that matters is where the chain STARTS — that starting point is the whole difference between a detritus chain and a grazing chain.",
             ["Writing that a DFC starts with green plants. That is the GRAZING food chain.",
              "Giving only the letters. The expansion carries the mark."],
             "Grazing chains start with something alive; detritus chains start with something dead.",
             "Expand the letters, then say where the chain starts. Three lines."),
         step("s2_detritus", "text", "Detritus", 1, "Detritus", [
             "Detritus is the dead organic matter of an",
             "ecosystem.",
             "It is formed from leaf litter, dead bodies",
             "and the faeces of animals.",
         ],
             "Detritus is a named material, so the answer lists what it is made of; a student who writes only dead matter has not shown what falls to the forest floor.",
             ["Writing that detritus is soil. It is the dead ORGANIC matter lying on and in the soil.",
              "Leaving out the faeces, which are one of the three named sources."],
             "Three sources of detritus: fallen leaves, dead bodies and droppings.",
             "One definition line and one list line. Keep it to two lines."),
         step("s3_decomposers", "text", "Decomposers", 1, "Decomposers", [
             "Detritus carries decomposers, which are",
             "heterotrophic organisms. Ex: fungi and",
             "bacteria.",
             "They meet their energy and nutrition needs",
             "by degrading the detritus, so they are",
             "called saprotrophs.",
             "They secrete enzymes that break the detritus",
             "down into simple absorbable substances.",
         ],
             "The decomposers are what turn detritus into a food chain, and the word saprotroph is the named term the answer must carry along with the two examples.",
             ["Calling the decomposers producers. They are heterotrophs and cannot make their own food.",
              "Leaving out the word saprotroph, which is the named term for this feeding mode."],
             "Saprotroph: enzymes go out on to the dead matter, the digested food comes back in.",
             "Name the decomposers, the examples and the word saprotroph. Three short statements."),
         step("s4_significance", "boxed_final", "Significance and examples", 1, "Significance", [
             boxed("The DFC returns the dead matter to the soil"),
             "The DFC breaks down the dead matter of a",
             "terrestrial ecosystem and returns its",
             "nutrients to the soil for the plants.",
             "Without it, dead leaves and bodies would",
             "pile up and the nutrients would be locked",
             "away.",
             "Ex-1: Detritus → Earthworms → Frogs →",
             "Snakes.",
             "Ex-2: Dead animals → Flies and maggots →",
             "Frogs → Snakes.",
         ],
             "The question asks for the significance separately, so the recycling of nutrients is stated in its own step; the two chains are written last because they are the proof that detritus really does feed a chain of animals.",
             ["Giving the chains and calling that the significance. The significance is the RETURN of nutrients to the soil.",
              "Drawing the arrows backwards. An arrow points FROM the eaten TO the eater."],
             "Detritus feeders are the second trophic level: earthworms, flies and maggots come straight after the dead matter.",
             "One statement of significance, then the two example chains with the arrows pointing forward."),
     ],
     "The question has two halves — the note and the significance — and the significance is the recycling of nutrients, not the example chains.",
     note_extra="SAME-UNIT OVERLAP: the detritus food chain is also one third of LAQ 10 (types of food chains, book p.26). This card is not a cut of that answer — it adds the significance in a terrestrial ecosystem, which the long answer does not ask for."),

# ── Star-Q 188 ───────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_vant_hoff_rule", S, 68, 188,
     "Explain Van't Hoff rule.",
     app((2019, "ap_ipe")),
     [("The rule", 1), ("Stated in reverse", 1),
      ("Temperature coefficient Q₁₀", 1), ("Value in living organisms", 1)],
     [
         step("s1_rule", "text", "The rule", 1, "The rule", [
             "Van't Hoff's rule states that for every rise",
             "of 10°C in temperature, the rate of the",
             "metabolic activities of an animal doubles.",
         ],
             "The rule is one sentence and it holds three numbers — the step of 10°C, the factor of two, and the direction of the change — so all three go into the first line.",
             ["Writing that the rate doubles for every 1°C. The step is 10°C.",
              "Writing that the temperature doubles. It is the RATE of metabolism that doubles."],
             "Ten up, rate times two. Ten down, rate halved.",
             "One sentence with both numbers in it. Do not start on Q₁₀ yet."),
         step("s2_reverse", "text", "Stated in reverse", 1, "Reverse", [
             "Stated in reverse, for every fall of 10°C in",
             "temperature the rate of the metabolic",
             "reactions is halved.",
             "So the rule works in both directions.",
         ],
             "Writing the rule the other way round is a separate mark in this answer because it shows the rule is a relation between temperature and rate, not a one-way effect of heating.",
             ["Writing that cooling stops metabolism. It HALVES the rate for each 10°C fall.",
              "Repeating the first statement in the same direction."],
             "Same rule, mirror image: double going up, half coming down.",
             "One sentence, reversed. Two lines are enough."),
         step("s3_q10", "text", "Temperature coefficient Q₁₀", 1, "Q₁₀", [
             "The effect of temperature on the rate of a",
             "reaction is expressed in terms of the",
             "temperature coefficient Q₁₀.",
             "Q₁₀ is the ratio between the rate of the",
             "reaction at X°C and the rate at (X − 10)°C.",
         ],
             "Q₁₀ is the number that MEASURES the rule, so it must be defined as a ratio of two rates ten degrees apart; a definition without the two temperatures does not say what is being compared.",
             ["Calling Q₁₀ a temperature. It is a RATIO of two reaction rates.",
              "Leaving out the 10°C gap between the two rates being compared."],
             "Q₁₀ is a ratio, so it has no units: the rate now divided by the rate ten degrees colder.",
             "Name the coefficient and define it as a ratio with the two temperatures."),
         step("s4_value", "boxed_final", "Value in living organisms", 1, "Value", [
             boxed("Q₁₀ ≈ 2 in living organisms"),
             "In living organisms the value of Q₁₀ is",
             "about 2.0.",
             "That is, the rate of metabolism doubles for",
             "every rise of 10°C in temperature.",
             "This is the same statement as the rule",
             "itself, now written as a number.",
         ],
             "Closing with the value of about 2.0 ties the coefficient back to the rule, showing they are one statement in two forms — words and a number.",
             ["Giving Q₁₀ a value of 10. The value in living organisms is about 2.",
              "Not linking the value back to the rule. The number 2 IS the doubling."],
             "Q₁₀ of 2 and the word doubles say the same thing.",
             "The number first, then one line tying it back to the rule."),
     ],
     "Q₁₀ is the part of this answer most often left out, and it carries half the marks — define it as a ratio and give its value of about 2.",
     src_label="Star Questions Plus, SAQ 188"),

# ── Star-Q 189 ───────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_terrestrial_dehydration_protection", S, 68, 189,
     "How do terrestrial animals protect themselves from the danger of dehydration of bodies?",
     app((2022, "ts_ipe")),
     [("Why water matters", 1), ("Behavioural adaptation", 1),
      ("Body covering", 1), ("Excretory adaptation", 1)],
     [
         step("s1_water", "text", "Why water matters", 1, "The problem", [
             "Water is a very important ingredient of the",
             "body of an animal.",
             "Any reduction in the amount of body water",
             "leads to dehydration, and the animal dies.",
             "Land animals lose water all the time through",
             "the body surface and in the urine, so they",
             "have evolved adaptations to conserve it.",
         ],
             "The question asks how animals protect themselves, so the answer names the two routes by which water is lost — the skin and the urine — because every adaptation below closes one of those two routes.",
             ["Starting straight with the examples. The problem must be stated first.",
              "Writing that land animals do not lose water. They lose it through the skin and the urine."],
             "Water leaves by two doors: the body surface and the urine. Every adaptation shuts one of them.",
             "Two or three lines. Name both routes of water loss before listing anything."),
         step("s2_behaviour", "text", "Behavioural adaptation", 1, "Behaviour", [
             "Certain desert animals are active only",
             "during the night.",
             "The night air is cooler and more humid, so",
             "less water is lost from the body surface.",
             "They stay in burrows during the hot day.",
         ],
             "This adaptation changes the animal's timing rather than its body, so it is written separately from the structural ones; it also explains itself, because a cooler night means slower evaporation.",
             ["Writing only that desert animals are active at night, without the reason.",
              "Calling this hibernation. Being active at night is a daily habit, not a winter sleep."],
             "Same body, different clock: come out when the air is cool and damp.",
             "One line for the habit and one for the reason. Do not leave the reason out."),
         step("s3_covering", "text", "Body covering", 1, "Covering", [
             "(i) Reptiles have a dry scaly skin, which",
             "prevents the escape of water.",
             "(ii) Birds have a dry skin, which prevents",
             "the escape of water.",
             "(iii) Insects and other arthropods have a",
             "cuticle over the body, which prevents the",
             "escape of water.",
         ],
             "Three groups are given because the question is about terrestrial animals in general, and naming a covering for each group shows the same solution reached in three different ways.",
             ["Naming only one group. Reptiles, birds and insects are all expected.",
              "Writing that reptiles have a moist skin. That is the amphibians, which is why they stay near water."],
             "Three coverings, one job: dry scales, dry skin and cuticle all stop water leaving.",
             "One line per group, each with the covering named. A list scores as fast as sentences."),
         step("s4_excretion", "boxed_final", "Excretory adaptation", 1, "Excretion", [
             boxed("Uric acid is passed out with almost no water"),
             "All these groups of animals release dry uric",
             "acid as their excretory product.",
             "Uric acid needs very little water to be",
             "passed out, unlike ammonia or urea.",
             "So very little water is lost in excretion.",
         ],
             "The urine is the second route of water loss named at the start, and uric acid is how it is closed; comparing it with ammonia and urea shows why the choice of waste product matters.",
             ["Writing that these animals excrete urea. Land animals that must save water excrete URIC ACID.",
              "Naming uric acid without saying why. It needs very little water to be passed out."],
             "Ammonia needs a lot of water, urea needs some, uric acid needs almost none.",
             "Name uric acid, then one line on why it saves water. Close the second route here."),
     ],
     "Uric acid is the answer the examiner is looking for and is the point most often missed — write it by name and say that it needs almost no water.",
     src_label="Star Questions Plus, SAQ 189"),

# ── Star-Q 190 ───────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_euryhaline_vs_stenohaline", S, 68, 190,
     "Distinguish between euryhaline and stenohaline animals.",
     app((2022, "ts_ipe")),
     [("Euryhaline", 1), ("Euryhaline examples", 1),
      ("Stenohaline", 1), ("Stenohaline examples", 1)],
     [
         step("s1_eury", "text", "Euryhaline", 1, "Euryhaline", [
             "Euryhaline animals are adapted to withstand",
             "wide fluctuations of salinity.",
             "They can live in water whose salt content",
             "changes over a wide range.",
         ],
             "The whole distinction is the width of the salinity range an animal can bear, so the definition must carry the word wide; the two Greek beginnings, eury and steno, then do the rest of the work.",
             ["Writing that euryhaline animals live only in the sea. They live across a WIDE range of salinity.",
              "Leaving out the word salinity. The range being described is a range of salt content."],
             "Eury means wide, steno means narrow. Haline means salt. Wide-salt and narrow-salt.",
             "One sentence with the word wide in it. Keep the examples for the next step."),
         step("s2_eury_ex", "text", "Euryhaline examples", 1, "Examples", [
             "Ex: brackish water fishes such as salmon",
             "and Hilsa.",
             "They withstand fresh water during low tide",
             "and saline water during high tide.",
             "Migrating fishes move from the sea into",
             "fresh water to breed. This is anadromous",
             "migration.",
         ],
             "The examples are the proof of the definition, and the migration is included because a fish that swims from the sea into a river passes through the whole range of salinity in one journey.",
             ["Naming the fishes without saying what range they cross.",
              "Calling the movement from the sea into fresh water catadromous. It is ANADROMOUS migration."],
             "Anadromous: up the river from the sea to breed. Salmon and Hilsa both do it.",
             "Name the fishes, then the tide line and the named migration."),
         step("s3_steno", "text", "Stenohaline", 1, "Stenohaline", [
             "Stenohaline animals are unable to tolerate",
             "fluctuations in salinity.",
             "They can live only within a narrow range of",
             "salt content.",
         ],
             "The second half is written in the same shape as the first with the one word changed from wide to narrow, which is what makes a distinguish answer read as a comparison.",
             ["Writing that stenohaline animals live only in fresh water. They may be marine or freshwater; the point is the NARROW range.",
              "Swapping the two terms. Steno is the narrow one."],
             "Steno is the same beginning as in stenosis, a narrowing. Narrow range of salt.",
             "Mirror the euryhaline sentence with wide changed to narrow."),
         step("s4_steno_ex", "boxed_final", "Stenohaline examples", 1, "Examples", [
             boxed("Eury = wide range, Steno = narrow range"),
             "Ex: marine fishes die when they are placed",
             "in fresh water.",
             "Ex: freshwater fishes die when they are",
             "placed in sea water.",
             "Each of them can live only in the salinity",
             "it is adapted to.",
         ],
             "The stenohaline examples are stated as what happens when the animal is moved, because the narrow range shows itself only when the salinity is changed.",
             ["Naming a fish species. The examples here are the two groups, marine and freshwater fishes.",
              "Writing that stenohaline fishes can adjust slowly. They cannot tolerate the change."],
             "Move a stenohaline fish across the salinity line and it dies. That is the test.",
             "Both directions of the test, one line each. The box states the whole distinction."),
     ],
     "This is a distinguish question, so write the two definitions in the same shape with only wide and narrow changed — the paired examples then carry the other two marks.",
     src_label="Star Questions Plus, SAQ 190"),

print("SAQ batch done")
