# -*- coding: utf-8 -*-
"""Unit 8 VSAQ cards 148-160 (book pp.60-61)."""
from eelib import *

V = "VSAQ"

# ── 148 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_primordial_source_of_energy", V, 60, 148,
     "What is the primordial source of energy for all organisms?",
     app(),
     [("Source", 1), ("Transfer", 1)],
     [
         step("s1_sunlight", "text", "The source", 1, "Source", [
             "Sunlight is the primordial source of energy",
             "for all organisms on the earth.",
             "Green plants trap this light energy and",
             "store it as chemical energy in food.",
         ],
             "Every food chain begins with light, so naming the sun first fixes the direction of the whole answer: energy enters an ecosystem only through the producers.",
             ["Writing that plants are the source of energy. Plants are the producers; the sun is the source.",
              "Answering with the word food. The question asks for a source of ENERGY."],
             "One sun, one entry point: the light goes into the green plants first.",
             "One sentence naming the sun, then one line on how plants take it in."),
         step("s2_transfer", "boxed_final", "Passing on", 1, "Transfer", [
             boxed("Sunlight — the primordial source of energy"),
             "This energy is passed on from the producers",
             "to each higher trophic level in turn.",
             "About 10% of it moves up at each step.",
         ],
             "The second mark is for what happens to the energy after it enters, so the answer must say that it moves up the trophic levels and does not stay in the plants.",
             ["Stopping at the sun. The second mark is for the transfer between trophic levels."],
             "Sun in, then up the levels one step at a time.",
             "Name the sun in the box, then one line on the transfer between trophic levels."),
     ],
     "Two marks, two ideas — the sun as the source and the transfer up the trophic levels. A student who writes only the word sunlight scores one."),

# ── 149 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_biological_rhythms", V, 60, 149,
     "What are biological rhythms?",
     app(),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Biological rhythms are the behavioural",
             "activities of organisms that repeat at",
             "regular intervals of time.",
         ],
             "The two words that carry the mark are repeat and regular: an activity that happens once, or at random, is not a rhythm.",
             ["Writing only that the activity repeats. It must repeat at REGULAR intervals.",
              "Naming a single event such as birth. A rhythm is a repeating activity."],
             "Rhythm means the same beat again and again — regular, not random.",
             "One sentence. The words repeat and regular intervals must both appear."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("A biological rhythm repeats at fixed times"),
             "Ex: the circadian rhythm — the sleep and",
             "wake cycle, which repeats every 24 hours.",
             "Other rhythms follow the tides, the month",
             "or the year.",
         ],
             "A named example proves the definition, and the circadian rhythm is the one the syllabus asks about separately, so it is the safest example to give.",
             ["Giving no example. One mark of the two is for the example.",
              "Calling the sleep and wake cycle a circadian rhythm without saying it takes 24 hours."],
             "Circadian is the 24-hour one; tidal, monthly and yearly rhythms are the longer ones.",
             "One named example with its time period. Two or three lines are enough."),
     ],
     "The examiner looks for the words regular intervals in the definition and for one named example with its period beside it."),

# ── 150 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_circadian_rhythms", V, 60, 150,
     "What are circadian rhythms?",
     app((2015, "ts_ipe"), (2022, "ts_ipe")),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Circadian rhythms are the biological",
             "rhythms that repeat in a period of about",
             "24 hours.",
             "Biological rhythms are the activities of an",
             "organism that repeat at regular intervals.",
         ],
             "Circadian is only one kind of biological rhythm, so the answer defines the larger term first and then fixes the period at 24 hours — that period IS the whole difference.",
             ["Leaving out the 24 hours. Without the period the answer defines any rhythm, not a circadian one.",
              "Writing that the rhythm lasts 24 hours. It REPEATS every 24 hours."],
             "Circa means about and diem means a day: circadian is the about-a-day rhythm.",
             "One sentence with the period in it, then one line placing it inside biological rhythms."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("Circadian rhythm: a 24-hour rhythm"),
             "Ex: the sleep and wake cycle of man.",
             "Ex: the daily opening and closing of the",
             "stomata of leaves.",
         ],
             "The example must itself take a day, so the sleep and wake cycle is the one to give — it shows the period without needing another sentence.",
             ["Giving the migration of birds as the example. That is a yearly rhythm, not a circadian one."],
             "Ask of any example: does it come round once a day? If yes, it is circadian.",
             "One example is enough. Name it and stop."),
     ],
     "Both marks turn on the number 24 — a definition without the period scores nothing, however well it is written."),

# ── 151 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_photoperiodism", V, 60, 151,
     "What is Photoperiodism?",
     app(),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Photoperiod is the number of light hours",
             "in a day.",
             "Photoperiodism is the response shown by an",
             "organism to the photoperiod.",
         ],
             "Photoperiodism is named after the photoperiod, so defining the photoperiod first makes the second sentence a single short line instead of a long one.",
             ["Defining photoperiodism as the length of the day. That is the photoperiod; photoperiodism is the RESPONSE to it.",
              "Writing about light intensity. The photoperiod is about the DURATION of light."],
             "Photoperiod is the day length; photoperiodism is what the animal does about it.",
             "Two short sentences: the photoperiod first, then the response to it."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("Photoperiodism: the response to day length"),
             "Ex: the migration of birds.",
             "In winter the days are short in Siberia, so",
             "the birds move southward to a place with a",
             "longer day for feeding and breeding.",
         ],
             "The example has to show a response that follows the day length and not the temperature, so the sentence must say why the birds move — the short day, not the cold.",
             ["Saying the birds migrate because of the cold. In this answer the trigger is the SHORT DAY.",
              "Giving no example at all. One of the two marks is the example."],
             "Short days push the birds towards the longer day: photoperiodism moves them, not the cold.",
             "Name the example and give the reason in one line. Three lines are enough."),
     ],
     "The mark for the example is lost when a student writes that the birds migrate because of the cold — the answer must tie the migration to the day length."),

# ── 152 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_advantages_of_uv_rays", V, 60, 152,
     "Mention the advantages of some UV rays to us.",
     app((2016, "ts_ipe"), (2020, "ts_ipe"), (2014, None)),
     [("Killing microbes", 1), ("Vitamin D", 1)],
     [
         step("s1_microbes", "text", "Killing microbes", 1, "Microbes", [
             "UV rays kill the micro organisms present on",
             "the body surface of animals.",
             "This keeps the skin surface free of harmful",
             "bacteria.",
         ],
             "The question asks for advantages in the plural, so two separate uses are needed; this is the first and it is the one students forget because UV is usually taught as a harm.",
             ["Writing only about the harmful effects of UV. The question asks for the ADVANTAGES.",
              "Writing that UV kills germs inside the body. It acts on the body SURFACE."],
             "Two uses, two places: on the skin it kills microbes, in the skin it makes vitamin D.",
             "One short sentence per advantage. Do not write about ozone here."),
         step("s2_vitamin_d", "boxed_final", "Vitamin D", 1, "Vitamin D", [
             boxed("UV rays make vitamin D in the skin"),
             "UV rays convert the sterols present in the",
             "skin into vitamin D.",
             "Vitamin D is needed for the absorption of",
             "calcium and so for strong bones.",
         ],
             "Naming the starting material, the sterols, is what separates a full answer from the half answer that only says sunlight gives vitamin D.",
             ["Writing that UV rays contain vitamin D. They CONVERT the sterols in the skin into it.",
              "Leaving out the word sterols, which is the named material in this step."],
             "Sterols in the skin plus UV gives vitamin D; vitamin D then brings in the calcium.",
             "Name the sterols and the vitamin. One extra line on what the vitamin does."),
     ],
     "This is a two-point question and each point is a separate mark, so a student who writes four lines on vitamin D alone still scores only one."),

# ── 153 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_cyclomorphosis_daphnia", V, 60, 153,
     "What is cyclomorphosis? Explain its importance in Daphnia.",
     app((2019, "ap_ipe"), (2022, "ap_ipe"), (2017, "ts_ipe")),
     [("Definition", 1), ("Importance in Daphnia", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Cyclomorphosis is the cyclic seasonal change",
             "in the body shape of an organism.",
             "Ex: Daphnia, the water flea.",
         ],
             "The word has two halves — cyclo for the cycle and morphosis for the change of shape — and the definition must carry both, because a seasonal change that does not come back is not cyclomorphosis.",
             ["Writing that the animal changes colour. Cyclomorphosis is a change of SHAPE.",
              "Leaving out the word seasonal. The change follows the seasons and returns each year."],
             "Cyclo = the cycle comes round again, morphosis = the shape changes.",
             "One sentence with the words cyclic and seasonal, then the example."),
         step("s2_importance", "boxed_final", "Importance in Daphnia", 1, "Importance", [
             boxed("The hood of Daphnia grows and shrinks"),
             "The hood is an adaptation to the changing",
             "density of the water.",
             "Winter: the head is round.",
             "Spring: a hood starts to grow.",
             "Summer: a large hood is formed.",
             "Autumn: the hood begins to shrink, and by",
             "winter the head is round again.",
         ],
             "The four seasons in order show the cycle closing, which is the point of the word cyclomorphosis; a list without the return to the round head does not show a cycle.",
             ["Describing only the summer hood. The mark is for the full round of seasons.",
              "Writing that the hood is for swimming faster. It answers the changing DENSITY of the water."],
             "Round, growing, largest, shrinking — winter, spring, summer, autumn, then round again.",
             "The four seasons in order, one short line each. End back at the round head."),
     ],
     "The season list is what earns the second mark, and it must close the loop — a student who stops at the summer hood has not shown a cycle."),

# ── 154 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_commensalism_definition", V, 60, 154,
     "Define commensalism. Give one example.",
     app((2017, "ap_ipe")),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Commensalism is an interaction between two",
             "different species in which one species is",
             "benefited and the other is neither benefited",
             "nor harmed.",
         ],
             "The definition is fixed by the SECOND species, not the first: the whole answer turns on the words neither benefited nor harmed, which separate commensalism from mutualism and from parasitism.",
             ["Writing that the other species is harmed. That is parasitism.",
              "Writing that both are benefited. That is mutualism."],
             "Count the gains: commensalism has one gain and one zero.",
             "One sentence. The words neither benefited nor harmed must appear."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("One species gains, the other is unaffected"),
             "Ex: barnacles growing on the back of a whale.",
             "The barnacles get a place to live and food",
             "from the moving water.",
             "The whale is not affected by them.",
         ],
             "The example must be explained in the same terms as the definition, so the answer states what one partner gains and then states plainly that the other is unaffected.",
             ["Naming the example without saying who gains what. The explanation carries the mark.",
              "Choosing bees and flowers as the example. Both gain there, so that is mutualism."],
             "Barnacle on the whale: the barnacle gets a free ride, the whale notices nothing.",
             "Name the example, then one line on the gain and one on the unaffected partner."),
     ],
     "The three interaction terms are marked as a set, so the safest answer says in words what happens to BOTH partners, not just to the one that gains."),

# ── 155 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_mutualism_definition", V, 60, 155,
     "Define mutualism. Give one example.",
     app((2015, "ap_ipe"), (2017, "ts_ipe")),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Mutualism is an interaction between two",
             "different species in which BOTH species are",
             "benefited.",
         ],
             "One word does all the work here — both — so the definition is short, and the space saved goes into the example where the second mark sits.",
             ["Writing that one is benefited and the other is unaffected. That is commensalism.",
              "Writing about two members of the SAME species. The interaction is between DIFFERENT species."],
             "Mutual means on both sides: in mutualism both partners gain.",
             "One sentence only. The word both is the mark."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("Both species gain"),
             "Ex: bees and flowering plants.",
             "The bee gets nectar and pollen from the",
             "flower.",
             "The plant gets pollinated by the bee.",
         ],
             "Because both partners gain, the example needs two statements of gain — one for each partner — and a student who writes only the bee's gain has shown commensalism, not mutualism.",
             ["Writing only that the bee gets nectar. The plant's gain must be written too.",
              "Giving barnacles and a whale. The whale gains nothing, so that is commensalism."],
             "Bee and flower: nectar goes one way, pollen goes the other. Two gains, two lines.",
             "Name the example, then one line of gain for each partner."),
     ],
     "The mark for the example needs BOTH gains written out — one line for the bee and one for the plant."),

# ── 156 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_osmotrophic_nutrition", V, 61, 156,
     "What is meant by osmotrophic nutrition?",
     app((2017, "ap_ipe")),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Osmotrophic nutrition is the mode of",
             "nutrition in which an organism takes in",
             "pre-digested food through its body wall from",
             "the surrounding medium.",
         ],
             "Two things make this mode different from every other one — the food is already digested, and it comes in through the body wall — and both must be in the sentence or the definition fits ordinary absorption.",
             ["Leaving out the words pre-digested. Food taken in undigested is not osmotrophic nutrition.",
              "Writing that the food enters through a mouth. It passes through the BODY WALL."],
             "Osmo is about soaking in through the wall; trophic is about food. Food soaked in through the wall.",
             "One sentence. It must carry both pre-digested and body wall."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("Digested outside the body, absorbed inside"),
             "Ex: fungi.",
             "They secrete enzymes on to dead and waste",
             "material and break it down outside the body.",
             "They then absorb the digested food through",
             "the body wall.",
         ],
             "The example has to show WHERE the digestion happens, because outside-the-body digestion is what makes the food pre-digested by the time it is absorbed.",
             ["Writing that the fungus swallows the food. It digests the food outside and then absorbs it.",
              "Giving Amoeba as the example. Amoeba engulfs solid food, which is a different mode."],
             "Enzymes go out, digested food comes in. The digestion happens outside the fungus.",
             "Name the example, then two lines: enzymes out, digested food in."),
     ],
     "The examiner looks for the two words pre-digested and body wall; a student who describes ordinary absorption without them loses the definition mark."),

# ── 157 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_what_is_an_ecosystem", V, 61, 157,
     "What is an ecosystem?",
     app((2018, "ts_ipe")),
     [("Definition", 1), ("Parts and example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "An ecosystem is a functional unit of the",
             "biosphere in which the members of a",
             "community interact among themselves and with",
             "the surrounding environment, in relation to",
             "the flow of energy.",
         ],
             "The phrase functional unit is what marks an ecosystem out from a community: a community is only the living members, while an ecosystem is those members working together with their surroundings.",
             ["Defining an ecosystem as all the plants and animals of an area. That is a community.",
              "Leaving out the surrounding environment. The non-living part belongs to the ecosystem."],
             "Community is the living members alone; ecosystem is those members plus their surroundings.",
             "One sentence. It must contain both interact and surrounding environment."),
         step("s2_parts", "boxed_final", "Parts and example", 1, "Parts", [
             boxed("Community + environment = ecosystem"),
             "An ecosystem has a living (biotic) part and",
             "a non-living (abiotic) part.",
             "Ex: a lake, a pond, a forest.",
         ],
             "Splitting the ecosystem into its biotic and abiotic parts turns the definition into something that can be checked against an example, and the lake is the example the long-answer question uses.",
             ["Giving only living things as the example. A named place such as a lake carries both parts.",
              "Writing the words biotic and abiotic without saying what they mean."],
             "Two parts, two words: biotic is the living half, abiotic is the non-living half.",
             "Name the two parts and give one example. Three lines are enough."),
     ],
     "A lake is the example to give: it is also the eight-mark question in this chapter, so the same words carry over."),

# ── 158 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_lotic_vs_lentic_habitats", V, 61, 158,
     "Distinguish between lotic and lentic habitats.",
     app((2018, "ap_ipe")),
     [("Lentic", 1), ("Lotic", 1)],
     [
         step("s1_lentic", "text", "Lentic habitats", 1, "Lentic", [
             "Lentic habitats are the STILL water bodies.",
             "The water in them does not flow from place",
             "to place.",
             "Ex: ponds, lakes and reservoirs.",
         ],
             "The pair is marked as a contrast, so each side needs the same two things — whether the water moves, and a named example — and writing them in the same order makes the contrast visible to the examiner.",
             ["Giving a river as a lentic habitat. A river flows, so it is lotic.",
              "Writing only the examples with no statement about the water."],
             "Lentic and level both start the same way: level water is still water.",
             "One line on the water, one line of examples. Keep both sides in the same order."),
         step("s2_lotic", "boxed_final", "Lotic habitats", 1, "Lotic", [
             boxed("Lentic = still water, Lotic = flowing water"),
             "Lotic habitats are the FLOWING water bodies.",
             "The water in them moves in one direction.",
             "Ex: streams and rivers.",
         ],
             "Naming the direction of the water is the whole distinction, so the second half repeats the first half's shape with the one word changed from still to flowing.",
             ["Swapping the two terms. Lotic is the flowing one.",
              "Giving a reservoir as lotic. A reservoir holds still water, so it is lentic."],
             "LOtic = flOwing. The other one, lentic, is the still one.",
             "Answer as a two-line contrast. The box gives the examiner the difference at a glance."),
     ],
     "A one-word slip loses both marks here, so fix the flowing one first: lotic is the moving water."),

# ── 159 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_phototaxis_vs_photokinesis", V, 61, 159,
     "Distinguish the terms phototaxis and photokinesis.",
     app((2019, "ts_ipe")),
     [("Phototaxis", 1), ("Photokinesis", 1)],
     [
         step("s1_phototaxis", "text", "Phototaxis", 1, "Phototaxis", [
             "Phototaxis is the influence of light on the",
             "DIRECTIONAL movement of an organism, either",
             "towards the light or away from it.",
             "Ex: Euglena moves towards light — positive",
             "phototaxis.",
             "Ex: the cockroach moves away from light —",
             "negative phototaxis.",
         ],
             "The two examples are chosen to sit on opposite sides of the same term, which shows the examiner that the movement has a direction and that the direction can go either way.",
             ["Writing that phototaxis is movement towards light only. It may be towards OR away.",
              "Leaving out the words positive and negative, which name the two directions."],
             "Taxis has a direction: towards is positive, away is negative.",
             "One sentence, then the two examples with their signs. Keep each example to one line."),
         step("s2_photokinesis", "boxed_final", "Photokinesis", 1, "Photokinesis", [
             boxed("Taxis sets the direction, kinesis the speed"),
             "Photokinesis is the influence of the",
             "INTENSITY of light on the non-directional",
             "movement of an organism.",
             "Ex: the larva of Pinnotheres maculatus, the",
             "mussel crab, moves faster as the light gets",
             "brighter, but keeps its own direction.",
         ],
             "The contrast is not light against no light but direction against speed, so the second half must say non-directional and must tie the change to the INTENSITY of the light.",
             ["Writing that the organism moves towards brighter light. In photokinesis the direction does not change.",
              "Leaving out the word intensity. Photokinesis answers how BRIGHT the light is, not where it is."],
             "Kinesis is like kinetic — it is about speed. Taxis is about which way.",
             "One sentence with non-directional and intensity in it, then the named example."),
     ],
     "The distinction the examiner marks is direction against speed — a student who writes towards the light in both halves loses one mark."),

# ── 160 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_camouflage_significance", V, 61, 160,
     "What is camouflage? Give its significance.",
     app((2019, "ap_ipe")),
     [("Definition", 1), ("Significance", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Camouflage is the phenomenon in which the",
             "colour of an animal matches the colour of",
             "its surroundings.",
             "Some animals change colour to match the",
             "surrounding; others are naturally coloured",
             "to suit it.",
             "Ex: chameleon, leaf insect, stick insect.",
         ],
             "Camouflage covers two different cases — a colour that changes and a colour that is fixed from birth — and naming both stops the answer from being read as being only about the chameleon.",
             ["Writing that every camouflaged animal changes colour. The leaf insect is coloured that way from birth.",
              "Giving no example. The named animals are part of the definition mark."],
             "Two kinds: the chameleon changes its colour, the leaf insect was born with it.",
             "One sentence, one line for the two kinds, then the examples."),
         step("s2_significance", "boxed_final", "Significance", 1, "Significance", [
             boxed("The animal matches its background"),
             "An animal whose colour matches its",
             "background is hard for a predator to see.",
             "This lowers its chance of being eaten.",
             "A predator may also use camouflage to come",
             "close to its prey.",
         ],
             "The significance is a survival value and must be stated in terms of being seen, because that is the physical fact the colour changes — not the animal's behaviour.",
             ["Writing that the animal becomes invisible. It becomes HARD TO SEE, not invisible.",
              "Giving only the prey side. A predator may use camouflage too."],
             "Matching the background works both ways: prey are not seen, and predators are not seen either.",
             "Two short lines on the prey, one on the predator. Do not repeat the examples here."),
     ],
     "The significance is the second mark and needs the words predator or prey in it — a student who only repeats the definition scores one."),

dump_manifest_stub = None
print("batch A done")
