# -*- coding: utf-8 -*-
"""Unit 8 LAQ cards 9-12 (book pp.25-28)."""
from eelib import *

L = "LAQ"

# ── 9 ────────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_laq_lake_as_an_ecosystem", L, 25, 9,
     "Describe lake as an ecosystem by giving examples for the various zones and the biotic components in it.",
     app((2019, "ap_ipe"), (2019, "ts_ipe"), (2015, "ts_ipe"), (2017, "ts_ipe")),
     [("Lake ecosystem", 1), ("Diagram", 2), ("The three zones", 2),
      ("Flora of the littoral zone", 1), ("Fauna of the littoral zone", 1),
      ("Biota of the limnetic and profundal zones", 1)],
     [
         step("s1_lake", "text", "The lake ecosystem", 1, "Identity", [
             "Lakes are large inland water bodies that",
             "contain still water, and they hold water",
             "throughout the year.",
             "A lake ecosystem performs all the functions",
             "of an ecosystem: photosynthesis,",
             "heterotrophs feeding on autotrophs,",
             "decomposition, mineralization, recycling of",
             "minerals and circulation of nutrients.",
             "A deep water lake has three distinct zones:",
             "1) Littoral zone  2) Limnetic zone",
             "3) Profundal zone",
         ],
             "The three zone names in order from the shore outwards and downwards are the plan of the whole answer, so they are written before anything is described and every later part is filed under one of them.",
             ["Describing a lake only as a body of water. The answer must say it is a complete ecosystem.",
              "Naming the zones in the wrong order. Littoral is at the shore, limnetic is the open middle, profundal is the deep bottom."],
             "Three zones, from the edge inwards and then downwards: littoral, limnetic, profundal.",
             "One line on what a lake is, one on the functions, then the three names. Do not describe the zones yet."),
         step("s2_diagram", "diagram", "Diagram — zones of a lake", 2, "Diagram", None,
              "The three zones are defined by depth and by how far the light reaches, so a drawing settles in one picture what a list of names cannot: the littoral zone is shallow and at the edge, the limnetic zone is the lit open water, and the profundal zone is the dark water beneath it.",
              ["Drawing the three zones as separate boxes. They are bands of one body of water and must touch.",
               "Putting the profundal zone at the shore. It is the DEEP zone, below the limnetic zone.",
               "Leaving out the benthic region. The lake floor is a named part of the figure."],
              "Draw the bowl of the lake first, then cut it with two lines: one down from the shore, one across at the light limit.",
              "Label the three zones, the benthic region and the light limit. The labels carry the two marks.",
              figure=getfig("ee_lake_ecosystem")),
         step("s3_zones", "text", "The three zones", 2, "Zones", [
             "1) Littoral zone: the shallow part of the",
             "lake, close to the shore. Light reaches",
             "right down to its bottom, so it is the",
             "euphotic or good light zone. It has rich",
             "vegetation, a high rate of photosynthesis",
             "and is rich in oxygen.",
             "2) Limnetic zone: the central, largest and",
             "open zone, away from the shore. It does not",
             "touch the bottom. It extends down to the",
             "level of effective light penetration.",
             "The zone of compensation is its lower",
             "limit, where the rate of photosynthesis is",
             "equal to the rate of respiration.",
             "3) Profundal zone: the deep water zone below",
             "the limnetic zone. Light is absent, so",
             "photosynthesis does not take place, and it",
             "is poor in oxygen.",
         ],
             "The three zones are separated by ONE thing — how much light reaches them — so each is described by its light first and by its oxygen second; that order makes the fall in oxygen from top to bottom follow from the light.",
             ["Writing that the limnetic zone reaches the bottom. It does not touch the lake floor.",
              "Leaving out the zone of compensation, which is the named boundary between the lit and dark water.",
              "Writing that the profundal zone is rich in oxygen. Without photosynthesis it is POOR in oxygen."],
             "Follow the light down: full light, fading light, no light. The oxygen falls with it.",
             "One paragraph per zone with its light and its oxygen. This is two marks, so do not shorten it."),
         step("s4_flora", "text", "Flora of the littoral zone", 1, "Flora", [
             "The littoral zone holds the richest biota.",
             "Flora — plants, with examples:",
             "i) Free floating hydrophytes — Pistia,",
             "Lemna, Salvinia",
             "ii) Rooted hydrophytes with floating leaves",
             "— Nymphaea, Victoria regia",
             "iii) Submerged suspended hydrophytes —",
             "Hydrilla, Utricularia",
             "iv) Submerged rooted hydrophytes —",
             "Vallisneria",
             "v) Amphibious plants, rooted below the water",
             "with the shoot above it — Sagittaria, Typha",
             "vi) Phytoplankton — diatoms, green algae",
         ],
             "The question asks for examples by name, so the plants are grouped by HOW they sit in the water — floating, rooted, submerged, amphibious — and each group carries its own named example, which is the form the marks are given in.",
             ["Writing the plant names as one list with no groups. The grouping is what is marked.",
              "Putting Vallisneria with the free floating plants. It is submerged and ROOTED."],
             "Six groups by position: floating on top, rooted with floating leaves, suspended, rooted below, half in half out, and the drifting phytoplankton.",
             "Six groups, each with its examples. A list scores as fast as sentences, so use the dash form."),
         step("s5_fauna", "text", "Fauna of the littoral zone", 1, "Fauna", [
             "Fauna — animals, with examples:",
             "i) Zooplankton, the drifting animals —",
             "Daphnia (water flea), rotifers, ostracods",
             "ii) Neuston, epineuston, living on the water",
             "surface — water bugs, beetles",
             "iii) Neuston, hyponeuston, hanging below the",
             "air-water interface — mosquito larvae",
             "iv) Nekton, the free swimming forms —",
             "fishes, snakes",
             "v) Periphyton, attached to the plants —",
             "hydras, nymphs",
             "vi) Benthos, living on the bottom — red",
             "annelids, crayfishes",
         ],
             "The animals are grouped by where in the water column each one lives, from the surface down to the floor, so the list runs in the same downward order as the zones themselves.",
             ["Calling the mosquito larvae nekton. They belong to the neuston, just below the surface film.",
              "Leaving out the benthos. The animals of the lake bottom are a named group here."],
             "Top to bottom: drifting, on the film, under the film, swimming, stuck to plants, on the floor.",
             "Six groups with their examples. Keep them in top-to-bottom order so none is missed."),
         step("s6_other_biota", "boxed_final", "Limnetic and profundal biota", 1, "Other zones", [
             boxed("Light falls, and the biota thins with it"),
             "2) Biota of the limnetic zone: it holds",
             "phytoplankton, zooplankton and nekton.",
             "Phytoplankton — euglenoids, diatoms,",
             "cyanobacteria, dinoflagellates, green algae.",
             "Zooplankton — copepods.",
             "Nekton — fishes, frogs, water snakes.",
             "3) Biota of the profundal zone: decomposers,",
             "detritus feeders, chironomid larvae,",
             "phantom larvae (Chaoborus) and clams.",
             "All of them are able to live at low oxygen",
             "levels.",
         ],
             "The other two zones are described together because the point is the same in both: with less light there are fewer kinds of organism, and in the dark profundal zone there are no producers at all, only decomposers and feeders on dead matter.",
             ["Giving green plants in the profundal zone. There is no light there, so there are no producers.",
              "Leaving out the last line. The low oxygen tolerance is what all the profundal animals share."],
             "No light means no producers: the deep zone lives on what falls from above.",
             "Two short blocks with their examples. Close with the low oxygen line, which ties the zone to its light."),
     ],
     "The examples are the marks in this question — a student who describes the three zones beautifully but names no plants or animals loses about half the paper."),

# ── 10 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_laq_types_of_food_chains", L, 26, 10,
     "Describe different types of food chains that exist in an ecosystem.",
     app((2022, "ts_ipe"), (2019, "ap_ipe"), (2019, "ts_ipe"), (2017, "ap_ipe"),
         (2016, "ap_ipe"), (2016, "ts_ipe"), (2014, None)),
     [("Food chain and trophic levels", 2), ("Diagram", 2),
      ("Grazing food chain", 2), ("Parasitic food chain", 1),
      ("Detritus food chain and food web", 1)],
     [
         step("s1_food_chain", "text", "Food chain and trophic levels", 2, "Basis", [
             "The sun is the main source of energy for an",
             "ecosystem.",
             "The biological systems of the environment",
             "have several food levels called trophic",
             "levels.",
             "A trophic level is made of organisms that",
             "have the same source of energy and the same",
             "number of transferring steps. There are",
             "generally 3 to 5 trophic levels.",
             "A given species may sometimes occupy more",
             "than one trophic level. Ex: the sparrow.",
             "Food energy always passes from a lower",
             "trophic level to a higher one.",
             "When the food path is linear, the parts",
             "resemble the links of a chain, and so it is",
             "called a food chain.",
             "A food chain generally ends in decomposers.",
             "Types of food chains:",
             "1) Grazing  2) Parasitic  3) Detritus",
         ],
             "A food chain is defined by its trophic levels, so those come first; the direction of the energy, always from lower to higher, is what fixes which way the arrows point in every chain written below.",
             ["Writing that a food chain starts with the sun. The sun is the energy source; the FIRST trophic level is the producers.",
              "Drawing the arrow from the eater to the eaten. The arrow always points FROM the eaten TO the eater.",
              "Leaving out the three types at the end. Naming them sets up the rest of the answer."],
             "The arrow follows the energy: it always points from the one being eaten to the one eating.",
             "Build up to the definition, then name the three types. Two marks, so keep all the points."),
         step("s2_diagram", "diagram", "Diagram — the three food chains", 2, "Diagram", None,
              "The three types differ only in what sits at the first trophic level and in which way the energy travels along the chain, and three chains drawn one above the other make that difference visible at a glance.",
              ["Drawing the arrows the wrong way. An arrow points FROM the eaten TO the eater in every chain.",
               "Drawing the parasitic chain from small to large. Its energy passes from the LARGE organism to the small one.",
               "Starting the detritus chain with a green plant. It starts with dead matter."],
              "Draw the boxes of one chain first, then the arrows, then the next chain below it. Keep the three chains parallel.",
              "Three chains, each labelled with its name. The arrow directions carry the marks here.",
              figure=getfig("ee_food_chains")),
         step("s3_grazing", "text", "Grazing food chain", 2, "Type 1", [
             "The grazing food chain is also called the",
             "predator food chain.",
             "The first trophic level is occupied by green",
             "plants, the producers.",
             "The second trophic level is occupied by",
             "herbivores.",
             "The third, fourth and fifth trophic levels",
             "are occupied by primary, secondary and",
             "tertiary carnivores respectively.",
             "Ex-1: Rose bush → aphids → spiders → small",
             "birds → hawks",
             "Ex-2: Grass → grasshopper → frog → snake →",
             "hawk",
             "Ex-3: Grass → goat → man",
             "Ex-4: Plants → caterpillar → lizard → snake",
             "Ex-5: Grass → deer → tiger",
         ],
             "This is the chain the syllabus treats as the standard one, so the trophic levels are numbered rather than merely listed, and the examples show chains of three, four and five links so the range of 3 to 5 levels is proved.",
             ["Putting the herbivores at the first trophic level. The producers are first.",
              "Calling every meat eater a carnivore without a rank. They are primary, secondary and tertiary carnivores.",
              "Writing the chains with the arrows reversed."],
             "Count up from the plant: producer, herbivore, then three ranks of carnivore.",
             "Number the four trophic levels, then give two or three chains. Two marks, the largest section."),
         step("s4_parasitic", "text", "Parasitic food chain", 1, "Type 2", [
             "In the parasitic food chain, the food energy",
             "passes from large organisms to small",
             "organisms.",
             "The first trophic level is occupied by large",
             "trees. They provide shelter and food to a",
             "variety of birds, reptiles and mammals.",
             "These animals form the second trophic level.",
             "Each of these animals hosts many ecto and",
             "endo parasites, which form the next level.",
             "Ex: Tree → birds, lizards, mammals →",
             "parasites",
         ],
             "This chain runs the opposite way in size from the grazing chain — large to small instead of small to large — and that reversal is the single fact the mark is given for.",
             ["Writing that the energy passes from small to large. In this chain it goes from LARGE to small.",
              "Leaving out the parasites at the end. They are the trophic level the chain is named for."],
             "Grazing goes small to large; parasitic goes large to small. Same arrows, opposite sizes.",
             "State the direction first, then the three levels, then the example chain."),
         step("s5_detritus", "boxed_final", "Detritus food chain and food web", 1, "Type 3", [
             boxed("Grazing starts alive, detritus starts dead"),
             "The detritus food chain begins with detritus,",
             "the dead organic matter of leaves, dead",
             "bodies and the faeces of animals.",
             "Detritus carries decomposers, which secrete",
             "enzymes that break it down into simple",
             "absorbable substances.",
             "The detritus feeders are earthworms, flies",
             "and maggots. They form the second trophic",
             "level.",
             "Ex: Detritus → earthworms → frogs → snakes",
             "→ hawks",
             "Food web: food chains are not isolated. They",
             "are interconnected and form a web called a",
             "food web, because omnivores such as man,",
             "the bear and the crow feed at more than one",
             "trophic level.",
         ],
             "The detritus chain is the one that starts with dead matter, and the food web is added at the end because it explains why real chains cross: an omnivore belongs to several chains at once.",
             ["Writing that the detritus chain starts with decomposers. It starts with the DETRITUS itself.",
              "Leaving out the food web. It is the closing point of this answer.",
              "Naming a herbivore as an omnivore example. Man, the bear and the crow eat at several levels."],
             "Three starts, three chains: living plant, large tree, dead matter.",
             "The chain first, then the food web in two lines. Close with the omnivore examples."),
     ],
     "Every arrow in this answer must point FROM the organism eaten TO the organism eating it — a reversed arrow is the commonest way marks are lost in this question."),

# ── 11 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_laq_flow_of_energy", L, 27, 11,
     "Give an account of flow of energy in an ecosystem.",
     app((2015, "ap_ipe")),
     [("Source of energy and PAR", 1), ("Diagram", 2),
      ("First law of thermodynamics", 1), ("Second law and energy flow", 2),
      ("Standing crop", 1), ("The 10% law", 1)],
     [
         step("s1_source", "text", "Source of energy and PAR", 1, "Source", [
             "The sun is the only source of energy for all",
             "the ecosystems on the earth.",
             "The solar energy captured by plants passes",
             "through the different organisms of an",
             "ecosystem.",
             "Less than 50% of the incident solar energy",
             "is Photosynthetically Active Radiation",
             "(PAR).",
             "Plants capture only 2 to 10% of PAR, and",
             "this sustains the entire living world.",
             "All heterotrophs depend on the producers for",
             "their food, either directly or indirectly.",
         ],
             "Energy flow is a one-way street from the sun, so the answer starts at the sun and follows the energy down through two losses — the part of sunlight that is not PAR, and the part of PAR the plant cannot capture.",
             ["Writing that plants capture 2 to 10% of sunlight. It is 2 to 10% of PAR, not of all sunlight.",
              "Calling the sun the main source. In this answer it is the ONLY source."],
             "Two cuts before the food chain even starts: under half of sunlight is PAR, and only 2 to 10% of that is captured.",
             "Both percentages with the quantity each belongs to. Five short statements."),
         step("s2_diagram", "diagram", "Diagram — energy flow", 2, "Diagram", None,
              "Energy flow is a quantity that shrinks at every step, so the picture that carries it is a stack of tiers that narrow upwards; drawing it to scale makes the 10% law visible instead of merely stated.",
              ["Drawing the tiers the same width. Each level must be visibly smaller than the one below it.",
               "Putting the producers at the top. The producers are the widest tier at the BOTTOM.",
               "Leaving the energy values off. The numbers 100, 10 and 1 kJ are what show the 10% law."],
              "Draw the widest tier at the bottom first, then stack narrower ones on it. Write the energy inside each tier.",
              "Label the trophic levels and write the energy in each tier. The 10% arrows carry the marks.",
              figure=getfig("ee_energy_flow")),
         step("s3_first_law", "text", "First law of thermodynamics", 1, "First law", [
             "The first law of thermodynamics is the law",
             "of conservation of energy.",
             "It states that energy is neither created nor",
             "destroyed. It may change from one form to",
             "another.",
             "The energy that reaches the earth is",
             "balanced by the energy that leaves it as",
             "heat radiation.",
             "Transfer of energy is essential for the",
             "survival of life, and it needs a continuous",
             "flow of energy.",
         ],
             "The first law explains why energy has to keep arriving: none of it is lost from the universe, but it changes into forms an organism cannot use, so the supply must be continuous.",
             ["Writing that energy is destroyed at each level. It is not destroyed; it CHANGES FORM.",
              "Leaving out the balance between energy arriving and heat leaving."],
             "First law says nothing is lost; second law says what is left is not always usable.",
             "State the law, then the balance, then why the flow must be continuous."),
         step("s4_second_law", "text", "Second law and energy flow", 2, "Second law", [
             "The second law of thermodynamics states that",
             "there is degradation of energy at each",
             "level.",
             "The degraded energy is in the form of",
             "unavailable heat energy.",
             "It constitutes entropy, that is, energy that",
             "is not available for work.",
             "The transfer of energy through a food chain",
             "is known as energy flow.",
             "The amount of energy available decreases at",
             "successive trophic levels.",
             "When an organism dies, it becomes a source",
             "of energy for its decomposers.",
         ],
             "This step defines energy flow itself and gives the reason it runs one way only: at every transfer some energy is degraded to heat, so less is available at each level up.",
             ["Writing that entropy is heat. Entropy is the energy that is NOT AVAILABLE for work.",
              "Writing that energy increases up the chain. It DECREASES at successive trophic levels.",
              "Leaving out the decomposers. Dead organisms pass their energy on to them."],
             "At every step some energy turns into heat that no organism can use. That is why the chain is short.",
             "Two marks, so keep all six points. Define energy flow in the middle of them."),
         step("s5_standing_crop", "text", "Standing crop", 1, "Standing crop", [
             "Each trophic level has a certain mass of",
             "living material, and this is called the",
             "standing crop.",
             "The standing crop is the biomass of that",
             "level.",
             "Biomass can be expressed in terms of fresh",
             "weight or dry weight.",
             "Dry weight is more accurate, because the",
             "water content of a body varies.",
         ],
             "Energy at a trophic level is measured through the mass of living material there, so the standing crop is the bridge between the energy account and something that can actually be weighed.",
             ["Calling the standing crop the number of organisms. It is their MASS.",
              "Writing that fresh weight is more accurate. DRY weight is the accurate measure."],
             "Standing crop is what is standing there now, weighed. Dry weight, because water is not food.",
             "Define it, name it as biomass, then the two weights with dry weight preferred."),
         step("s6_ten_percent", "boxed_final", "The 10% law", 1, "10% law", [
             boxed("Only 10% passes up; 90% is spent as heat"),
             "The 10% law was introduced by Lindeman.",
             "During the transfer of energy, only 10% of",
             "the energy is stored in the next trophic",
             "level. The rest is used for metabolic",
             "activities such as respiration.",
             "Lindeman's 10% rule is the most widely used",
             "measure of ecological efficiency.",
             "Ex: if the net primary production of the",
             "plants is 100 kJ, the biomass available to",
             "the herbivores is 10 kJ, and the next",
             "carnivores get only 1 kJ.",
         ],
             "The 10% law puts a number on everything said above, and the worked example with 100, 10 and 1 kJ is what proves the loss at each step rather than just asserting it.",
             ["Writing that 10% is lost. Ten per cent is what is PASSED ON; ninety per cent is used up.",
              "Leaving out Lindeman's name, which the question paper looks for.",
              "Giving the law without the worked numbers."],
             "100, 10, 1 — drop a zero at every trophic level.",
             "Name Lindeman, state the law, then the three numbers. Close the answer here."),
     ],
     "Two things are checked by name in this answer: Lindeman for the 10% law, and the worked example of 100 kJ, 10 kJ and 1 kJ."),

# ── 12 ───────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_laq_major_air_pollutants", L, 28, 12,
     "List out the major air pollutants and describe their effects on human beings.",
     app((2017, "ap_ipe"), (2020, "ap_ipe"), (2017, "ts_ipe"),
         (2018, "ap_ipe"), (2018, "ts_ipe")),
     [("Air pollution and the list", 2), ("Carbon monoxide", 1),
      ("Carbon dioxide", 1), ("Sulphur dioxide", 1),
      ("Nitrogen oxides", 1), ("Aerosols", 1), ("Noise pollution", 1)],
     [
         step("s1_list", "text", "Air pollution and the list", 2, "The list", [
             "Air pollution: any deviation from the",
             "natural composition of the air that causes",
             "adverse effects to humans and plants is",
             "called air pollution.",
             "The agents that carry air pollution are",
             "called air pollutants.",
             "Major air pollutants:",
             "1) Carbon monoxide (CO)",
             "2) Carbon dioxide (CO₂)",
             "3) Sulphur dioxide (SO₂)",
             "4) Nitrogen oxides (NO, N₂O, NO₂)",
             "5) Aerosols (particulate matter)",
             "6) Noise pollution",
         ],
             "The question says list out first, so the six names are written as a numbered list before any of them is described; the list is worth two marks on its own and also becomes the order of the rest of the answer.",
             ["Describing the pollutants without listing them first. The list is asked for by name.",
              "Leaving out the definition of air pollution, which opens the answer.",
              "Naming chlorofluorocarbons. They are not in this book's list of six."],
             "Two carbon gases, one sulphur gas, the nitrogen oxides, the particles and the noise. Six items.",
             "Definition in two sentences, then the six names as a numbered list. Two marks."),
         step("s2_co", "text", "Carbon monoxide", 1, "CO", [
             "Carbon monoxide (CO) is produced by the",
             "incomplete combustion of fossil fuels.",
             "Sources: automobile exhausts, factory fumes,",
             "emissions from power plants, forest fires",
             "and the burning of fire wood.",
             "Harmful effects:",
             "i) In the presence of carbon monoxide the",
             "oxygen carrying capacity of haemoglobin is",
             "reduced.",
             "ii) At lower concentrations it causes",
             "headache and blurred vision.",
             "iii) At higher concentrations it leads to",
             "coma and sometimes to death.",
             "Every pollutant below follows the same",
             "order: source, then harmful effects.",
         ],
             "Carbon monoxide acts on one target only, the haemoglobin, so that fact is written first and the two levels of effect follow from it in order of dose — mild at low concentration, fatal at high.",
             ["Writing that carbon monoxide comes from complete combustion. It comes from INCOMPLETE combustion.",
              "Writing that it damages the lungs. It acts on the HAEMOGLOBIN of the blood.",
              "Giving the effects without separating the low and high concentrations."],
             "Carbon monoxide takes the seat oxygen should have on the haemoglobin. Low dose: headache. High dose: coma.",
             "Source line, then three effects in order of dose. Keep the same shape for all six pollutants."),
         step("s3_co2", "text", "Carbon dioxide", 1, "CO₂", [
             "Carbon dioxide (CO₂) is produced by the",
             "respiration of living beings, but plants use",
             "it for photosynthesis.",
             "Sources: burning of fossil fuels such as",
             "gasoline, automobiles, aeroplanes and power",
             "plants.",
             "Harmful effects:",
             "i) When its concentration rises above the",
             "normal level it results in global warming.",
             "ii) Global warming brings many adverse",
             "effects on mankind, such as climatic change",
             "and the melting of the polar ice.",
         ],
             "Carbon dioxide is the one pollutant on the list that is also a normal part of the air, so the answer says plants use it before saying it is harmful — the harm is in the EXCESS, not in the gas.",
             ["Writing that carbon dioxide is poisonous like carbon monoxide. Its harm is global warming, not poisoning.",
              "Leaving out the words above the normal level. Ordinary carbon dioxide is not a pollutant."],
             "Carbon monoxide poisons the blood; carbon dioxide warms the planet. One letter, two different harms.",
             "Note that plants use it, then the sources, then global warming as the effect."),
         step("s4_so2", "text", "Sulphur dioxide", 1, "SO₂", [
             "Sulphur dioxide (SO₂) is produced mainly by",
             "the burning of fossil fuels, the melting of",
             "sulphur ores and metal smelting.",
             "Harmful effects:",
             "i) Breathing problems such as asthma.",
             "ii) Aggravation of cardiovascular problems.",
             "iii) Corrosion of buildings and monuments.",
         ],
             "Sulphur dioxide is the pollutant whose effects reach both people and stone, so the three effects are written to cover the lungs, the heart and the buildings.",
             ["Writing that sulphur dioxide causes global warming. That is carbon dioxide.",
              "Giving only the effects on people. The corrosion of buildings is one of the three."],
             "Sulphur dioxide attacks two things: the breathing passages and the stone of buildings.",
             "Source line, then three effects. Keep this one short; it is a single mark."),
         step("s5_nox", "text", "Nitrogen oxides", 1, "Nitrogen oxides", [
             "Nitrogen oxides (NO, N₂O, NO₂) are produced",
             "by automobile exhaust.",
             "Harmful effects:",
             "i) The oxides of nitrogen together with",
             "sulphur dioxide produce acid rain.",
             "ii) Acid rain acidifies water bodies and",
             "spoils crops, buildings and monuments made",
             "of marble and limestone.",
             "iii) Nitrogen dioxide with hydrocarbons and",
             "sunlight in foggy conditions produces",
             "photochemical smog. Spots form on leaves,",
             "photosynthesis is reduced and the crop",
             "yield falls.",
             "iv) Nitrogen oxides combine with secondary",
             "pollutants to form PAN (peroxy acetyl",
             "nitrate), which irritates the eyes and the",
             "respiratory tract.",
         ],
             "The nitrogen oxides are the busiest pollutant on the list because they produce three named products — acid rain, photochemical smog and PAN — and each of those has to be named, since the marks are given for the names.",
             ["Writing that nitrogen oxides alone make acid rain. Sulphur dioxide acts together with them.",
              "Leaving out PAN. Its full name, peroxy acetyl nitrate, is the one the examiner looks for.",
              "Leaving out photochemical smog, which needs sunlight and fog together with the hydrocarbons."],
             "Three products from one family: acid rain, photochemical smog and PAN.",
             "Name all three products in full. This mark is dense, so use short numbered lines."),
         step("s6_aerosols", "text", "Aerosols", 1, "Aerosols", [
             "Aerosols, also called particulate matter,",
             "are colloidal particles dispersed in a gas.",
             "Sources: combustion of fossil fuels, fly ash",
             "from thermal plants, cement factories and",
             "asbestos plants.",
             "Harmful effects:",
             "i) They decrease lung function.",
             "ii) They aggravate asthma and cause chronic",
             "bronchitis.",
             "iii) They cause premature death in patients",
             "with heart and lung disease, and an",
             "irregular heart beat.",
         ],
             "Aerosols are solid particles rather than a gas, so the definition names them as particles first; every effect that follows is then a physical effect of particles lodging in the lungs.",
             ["Calling aerosols a gas. They are solid or liquid PARTICLES dispersed in a gas.",
              "Leaving out the sources. Fly ash, cement and asbestos are the named ones."],
             "Aerosols are dust, not gas: they settle in the lungs, so the effects are lung effects.",
             "Definition, sources, then three effects. One mark, so keep the lines short."),
         step("s7_noise", "boxed_final", "Noise pollution", 1, "Noise", [
             boxed("Above 120 dB is noise; above 150 dB damages"),
             "Noise pollution is caused by undesirable",
             "high sounds, above 120 dB.",
             "Harmful effects:",
             "i) Extremely high sounds, above 150 dB,",
             "damage the ear drums and cause permanent",
             "hearing impairment.",
             "ii) Noise also causes auditory fatigue,",
             "anxiety, sleeplessness (insomnia) and",
             "stress.",
         ],
             "The two decibel figures are the whole of this step, so both are given with the effect each one produces. Note that noise is strictly a separate kind of pollution and not a chemical air pollutant; this book lists it sixth among the major air pollutants, so it is answered here as the paper asks.",
             ["Giving only one decibel figure. 120 dB is where noise pollution begins; 150 dB is where damage begins.",
              "Writing that noise pollution only affects hearing. It also causes anxiety, insomnia and stress."],
             "120 to start, 150 to damage. Two numbers, two lines.",
             "Both decibel numbers with their effects. Close the answer here."),
     ],
     "The six names are worth two marks on their own, so write the numbered list before describing anything — and inside each pollutant the examiner looks for the source line followed by the effects.",
     note_extra="RULE 35 (globally neutral content): the book's acid rain line cites the Taj Mahal by name as the monument damaged. This card writes the effect in general terms instead — 'buildings and monuments made of marble and limestone' — which states WHY the stone is attacked and keeps the answer portable across syllabi. A student who writes the Taj Mahal is not wrong. BOOK POSITION: the book lists 'Noise pollution' as the sixth major AIR pollutant. Noise is strictly a separate kind of pollution and not a chemical constituent of the air; it is answered here because the board's expected answer for this question lists it, and the point is recorded in that step's why field."),

print("LAQ batch done")
