# -*- coding: utf-8 -*-
"""Unit 8 VSAQ cards 161-172 (book pp.61-62)."""
from eelib import *

V = "VSAQ"

# ── 161 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_acid_rain_pollutants", V, 61, 161,
     "Which air pollutants are chiefly responsible for acid rains?",
     app((2016, "ap_ipe")),
     [("The pollutants", 1), ("Effects of acid rain", 1)],
     [
         step("s1_pollutants", "text", "The pollutants", 1, "Pollutants", [
             "Sulphur dioxide (SO₂) and the oxides of",
             "nitrogen (NO, NO₂) are the air pollutants",
             "chiefly responsible for acid rain.",
             "They come mainly from the burning of fossil",
             "fuels and from automobile exhaust.",
         ],
             "The question names one thing only — which pollutants — so both gases must be written with their formulae, and the source line shows the examiner they were not guessed.",
             ["Naming carbon dioxide. Carbon dioxide causes global warming, not acid rain.",
              "Naming only one of the two gases. Both sulphur dioxide and the nitrogen oxides are asked."],
             "Acid rain has two parents: sulphur dioxide and the nitrogen oxides. S and N, not C.",
             "Name the two gases with their formulae, then one line on where they come from."),
         step("s2_effects", "boxed_final", "Effects of acid rain", 1, "Effects", [
             boxed("SO₂ and nitrogen oxides make acid rain"),
             "Acid rain acidifies lakes and streams, and",
             "the fish in them die.",
             "It speeds up the corrosion of buildings and",
             "monuments.",
             "It also spoils standing crops.",
         ],
             "A two-mark question wants a second point, and the effects are the natural one because they explain why these two gases are singled out from every other pollutant.",
             ["Stopping after the names of the gases. The second mark is for what acid rain does.",
              "Writing that acid rain causes skin cancer. That is the effect of UV after ozone depletion."],
             "Acid attacks three things: water bodies, stone buildings and crops.",
             "Three short effects, one line each. Do not write the chemistry of the reaction."),
     ],
     "Carbon dioxide is the wrong answer here and is the commonest one written — acid rain comes from the sulphur and nitrogen gases."),

# ── 162 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_what_is_bod", V, 61, 162,
     "What is BOD?",
     app(),
     [("Expansion and use", 1), ("What it measures", 1)],
     [
         step("s1_expansion", "text", "What BOD stands for", 1, "Expansion", [
             "BOD stands for Biochemical Oxygen Demand.",
             "It is an index used to measure the pollution",
             "load of sewage and of a water body.",
         ],
             "The expansion of the letters is a mark on its own, so it is written first and in full. The book expands BOD as 'Biological Oxygen Demand'; NCERT and standard usage write 'Biochemical Oxygen Demand', and both forms are seen in papers, so the biochemical form is the safer one to write.",
             ["Writing Biological Oxygen Deficiency. The last word is Demand.",
              "Giving only the letters. The expansion carries the mark."],
             "Three words for three letters: Biochemical, Oxygen, Demand.",
             "One line for the expansion, one for what it is used for."),
         step("s2_meaning", "boxed_final", "What it measures", 1, "Meaning", [
             boxed("BOD = oxygen needed to break down the waste"),
             "BOD is the amount of dissolved oxygen needed",
             "by aerobic organisms to break down the",
             "organic matter in a given water sample, at a",
             "stated temperature and over a stated time.",
             "A high BOD means heavy organic pollution.",
         ],
             "BOD is an indirect measure — it counts the oxygen the microbes will USE, not the pollution itself — so the sentence must say oxygen needed and must name the organic matter being broken down.",
             ["Writing that BOD is the oxygen present in the water. It is the oxygen NEEDED.",
              "Leaving out the last line. The link between high BOD and heavy pollution is the useful part."],
             "More waste means more microbes, more microbes means more oxygen demanded. High BOD, dirty water.",
             "The definition in one long sentence, then the one line that reads the number."),
     ],
     "The last line is the one an examiner looks for: a high BOD means the water is heavily polluted."),

# ── 163 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_biological_magnification", V, 61, 163,
     "What is biological magnification?",
     app((2020, "ap_ipe")),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Biological magnification is the gradual",
             "increase in the concentration of a pollutant",
             "at each successive trophic level of a food",
             "chain.",
             "It happens because the pollutant is not",
             "broken down and is not passed out of the",
             "body.",
         ],
             "The words successive trophic level are the definition: the pollutant does not simply build up in one animal, it becomes more concentrated at every step UP the chain.",
             ["Writing that the pollutant increases in the water. It increases in the ORGANISMS along the chain.",
              "Leaving out the reason. The pollutant builds up because the body cannot break it down."],
             "Each level eats many of the level below, so the poison of many bodies ends up in one.",
             "One sentence for the increase, one for the reason. Use the words trophic level."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("The pollutant rises at every trophic level"),
             "Ex: DDT in an aquatic food chain.",
             "Its concentration in the water is about",
             "0.003 ppb.",
             "In the fish-eating birds at the top of the",
             "chain it reaches about 5 ppm.",
         ],
             "The two numbers make the word magnification concrete, and the jump from parts per billion to parts per million is the single fact that shows how large the increase is.",
             ["Giving the numbers without their units. ppb and ppm are what make the jump visible.",
              "Naming a gas such as carbon dioxide. The standard example is DDT in a water food chain."],
             "0.003 ppb in the water, 5 ppm in the birds: billion becomes million on the way up.",
             "Name DDT and give both numbers with their units. Four lines are enough."),
     ],
     "The two DDT numbers are what the examiner is looking for, and they must carry their units — ppb in the water and ppm in the birds."),

# ── 164 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_incinerators_in_hospitals", V, 62, 164,
     "Why are incinerators used in hospitals?",
     app((2019, "ts_ipe")),
     [("Hospital waste", 1), ("What the incinerator does", 1)],
     [
         step("s1_waste", "text", "Hospital waste", 1, "The waste", [
             "Hospitals produce hazardous waste such as",
             "used disinfectants, chemicals and material",
             "carrying disease-causing microorganisms.",
             "This waste must be treated before it is",
             "thrown out.",
         ],
             "The question asks why, so the answer must start with the problem: the waste is hazardous, and that is the reason an ordinary bin will not do.",
             ["Writing only that hospitals produce a lot of waste. It is the HAZARDOUS kind that matters.",
              "Starting with the incinerator. The reason comes first, the device second."],
             "Answer a why question in two halves: the problem first, then the device that solves it.",
             "Name two or three kinds of waste, then say it must be treated."),
         step("s2_incinerator", "boxed_final", "What the incinerator does", 1, "The device", [
             boxed("An incinerator burns hospital waste"),
             "An incinerator burns the waste at a high",
             "temperature.",
             "The heat destroys the disease-causing",
             "microorganisms and reduces the waste to ash.",
             "So the waste does not pollute the",
             "surroundings or spread infection.",
         ],
             "Burning is only half the answer; the mark is for what the burning achieves — the microorganisms are destroyed — because that is what makes the waste safe.",
             ["Writing that the incinerator stores the waste. It BURNS it.",
              "Leaving out the microorganisms. Destroying them is the point of the high temperature."],
             "High heat does two jobs: it kills the microorganisms and it cuts the waste down to ash.",
             "One line on the burning, one on what the heat destroys, one on the result."),
     ],
     "This is a why question, so an answer that only describes an incinerator scores half — say what the waste is and what the heat destroys."),

# ── 165 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_parasitism_definition", V, 62, 165,
     "Define parasitism. Give one example.",
     app(),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Parasitism is an interaction between two",
             "organisms of different species in which one",
             "is benefited and the other is harmed.",
             "The one that gains is the parasite; the one",
             "that is harmed is the host.",
         ],
             "Naming the two partners in the definition itself saves a sentence later and shows the examiner that the words parasite and host are being used correctly.",
             ["Writing that the other partner is unaffected. That is commensalism.",
              "Calling the host the parasite. The host is the one that is harmed."],
             "Count the gains again: mutualism two, commensalism one and a zero, parasitism one and a minus.",
             "One sentence, then one line naming the parasite and the host."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("The parasite gains, the host is harmed"),
             "Ex: Plasmodium vivax, the malarial parasite,",
             "in the body of man.",
             "The parasite gets food and shelter from the",
             "man.",
             "The man gets malaria, so he is harmed.",
         ],
             "The example must show the harm as well as the gain, because the harm is the one thing that separates parasitism from the other two interactions.",
             ["Naming the parasite without saying what harm it does. The harm carries the mark.",
              "Giving a lion and a deer. The lion kills the deer outright, so that is predation."],
             "Plasmodium in man: food and shelter for the parasite, malaria for the host.",
             "Name the parasite and the host, then one line of gain and one of harm."),
     ],
     "Parasitism, predation, commensalism and mutualism are marked as a set — always write what happens to BOTH partners."),

# ── 166 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_optimum_temperature", V, 62, 166,
     "What is optimum temperature?",
     app(),
     [("Definition", 1), ("Value in man", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Optimum temperature is the temperature at",
             "which the metabolic activities of an",
             "organism take place at their greatest level.",
             "Above it and below it the rate of these",
             "activities falls.",
         ],
             "The word optimum means best, not highest, so the second line — the rate falls on BOTH sides — is what stops the answer from being read as the maximum temperature the animal can stand.",
             ["Writing that it is the highest temperature the animal can survive. That is the maximum, not the optimum.",
              "Leaving out the word metabolic. The definition is about the rate of metabolic activity."],
             "Optimum is the peak of a hill: the rate falls whether you go up or down from it.",
             "One sentence for the definition and one line saying the rate falls on both sides."),
         step("s2_value", "boxed_final", "Value in man", 1, "Value", [
             boxed("Optimum body temperature of man: 37°C"),
             "The optimum temperature of the human body is",
             "about 37°C (98.6°F).",
             "Each species has its own optimum",
             "temperature.",
         ],
             "A named number turns a general definition into a checkable answer, and the human body temperature is the one value in the syllabus every student already knows.",
             ["Writing 37°F. The value is 37 degrees CELSIUS.",
              "Writing that every animal has the same optimum. Each species has its own."],
             "37 in Celsius, about 98.6 in Fahrenheit — one body, two scales.",
             "Give the number with its unit. One extra line that the value differs between species."),
     ],
     "Give the number: a definition with no value attached usually scores one of the two marks.",
     note_extra="BOOK DIFFERENCE: the book prints the human optimum as 98.4°F (or) 37°C. 37°C is exactly 98.6°F, and 98.6°F is the standard value, so this card writes 37°C first with 98.6°F beside it; a paper that expects 98.4°F still accepts 37°C."),

# ── 167 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_photoperiod_vs_critical", V, 62, 167,
     "Distinguish between photoperiod and critical photoperiod.",
     app(),
     [("Photoperiod", 1), ("Critical photoperiod", 1)],
     [
         step("s1_photoperiod", "text", "Photoperiod", 1, "Photoperiod", [
             "Photoperiod is the duration of the light",
             "hours in a day.",
             "It changes with the season and with the",
             "place on the earth.",
         ],
             "The photoperiod is simply a measured length of time, so the definition stays short; the second line prepares the contrast by pointing out that this length keeps changing.",
             ["Writing that the photoperiod is the intensity of light. It is the DURATION of light.",
              "Writing that the photoperiod is fixed. It changes with season and place."],
             "Photoperiod is a reading on a clock: how many hours of light today.",
             "One sentence and one line. Keep the space for the second half."),
         step("s2_critical", "boxed_final", "Critical photoperiod", 1, "Critical", [
             boxed("Critical photoperiod: the day length needed"),
             "Critical photoperiod is the specific day",
             "length that is essential to start a seasonal",
             "event.",
             "Ex: the day length at which flowering,",
             "breeding or migration begins.",
         ],
             "The word critical means a threshold, so the second half needs the word specific and needs a named event — without an event there is nothing for the day length to be critical FOR.",
             ["Writing that the critical photoperiod is the longest day of the year. It is the length that TRIGGERS an event.",
              "Giving no event. Flowering, breeding or migration must be named."],
             "Photoperiod is any day length; critical photoperiod is the ONE day length that starts something.",
             "One sentence with the word specific, then one named event."),
     ],
     "The word specific is the difference between the two terms, and an answer without a named seasonal event usually loses the second mark."),

# ── 168 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_what_is_par", V, 62, 168,
     "What is PAR?",
     app(),
     [("Expansion", 1), ("How much of it", 1)],
     [
         step("s1_expansion", "text", "What PAR stands for", 1, "Expansion", [
             "PAR stands for Photosynthetically Active",
             "Radiation.",
             "It is the part of sunlight that green plants",
             "can use for photosynthesis.",
         ],
             "The expansion is one mark on its own, and the second line explains why only part of sunlight counts — a plant cannot use every wavelength that reaches it.",
             ["Writing Photosynthetic Active Rays. The words are Photosynthetically Active Radiation.",
              "Writing that PAR is all the sunlight that reaches the earth. It is only the usable part."],
             "Three words for three letters: Photosynthetically, Active, Radiation.",
             "The expansion in full, then one line on what it means."),
         step("s2_percentages", "boxed_final", "How much of it", 1, "Amounts", [
             boxed("PAR is under 50% of the incoming sunlight"),
             "PAR is less than 50% of the incident solar",
             "radiation that reaches the earth.",
             "Of this PAR, green plants capture only",
             "2 to 10%.",
         ],
             "Two different percentages are asked about PAR in this chapter and they are easily swapped, so both are written together with the word they belong to beside each.",
             ["Writing that plants capture 50% of PAR. Fifty per cent is the share of SUNLIGHT that is PAR.",
              "Giving 2 to 10% of sunlight. It is 2 to 10% of PAR, not of all the sunlight."],
             "Less than half the sunlight is PAR; only 2 to 10% of THAT is captured by plants.",
             "Both numbers with the thing each one is a percentage of. Two lines."),
     ],
     "The two percentages belong to different quantities — under 50% of sunlight is PAR, and 2 to 10% of PAR is captured — and swapping them is the usual mistake."),

# ── 169 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_percentage_of_par", V, 62, 169,
     "What is the percentage of PAR in the incident solar radiation?",
     app(),
     [("The percentage", 1), ("What plants capture", 1)],
     [
         step("s1_percentage", "text", "The percentage", 1, "Percentage", [
             "PAR is less than 50% of the incident solar",
             "radiation available on the earth.",
             "PAR is Photosynthetically Active Radiation,",
             "the part of sunlight that plants can use",
             "for photosynthesis.",
         ],
             "The question asks for one number, so it is written in the first line; the expansion follows because a bare percentage with no named quantity is not a complete answer.",
             ["Answering 2 to 10%. That is the share of PAR that plants capture, not the share of sunlight that is PAR.",
              "Giving the number without expanding PAR."],
             "Less than half of the sunlight arriving is even usable by a plant.",
             "The percentage in the first line, then the expansion. Two short sentences."),
         step("s2_capture", "boxed_final", "What plants capture", 1, "Capture", [
             boxed("Under 50% of sunlight is PAR"),
             "Of this PAR, green plants capture only",
             "2 to 10%.",
             "This small fraction supports the whole",
             "living world.",
         ],
             "The second number completes the picture and is the one the long answer on energy flow uses, so writing both here keeps the two figures fixed to the right quantities.",
             ["Adding the two percentages together. They are percentages of DIFFERENT quantities.",
              "Leaving the second number out. A two-mark answer needs a second point."],
             "Two steps down: sunlight to PAR, then PAR to what the plant actually keeps.",
             "The second percentage and one line on why so little matters."),
     ],
     "This question and the PAR definition question are asked separately in the book, so keep the answers different: this one leads with the percentage.",
     note_extra="BOOK REDUNDANCY: VSAQ 168 ('What is PAR?') and VSAQ 169 ('What is the percentage of PAR...') are printed as two separate questions on book p.62 with nearly the same one-line answer. Both are authored because both are in the asked bank; this card leads with the percentage and 168 leads with the expansion. The book's own printed wording for 169 is 'What is the percentage of PAR, in the incident solar radiation.' — cleaned to a question here."),

# ── 170 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_neuston_vs_nekton", V, 62, 170,
     "Distinguish between neuston and nekton.",
     app(),
     [("Neuston", 1), ("Nekton", 1)],
     [
         step("s1_neuston", "text", "Neuston", 1, "Neuston", [
             "Neustons are the animals that live at the",
             "air-water interface, that is at the surface",
             "of the water.",
             "Ex: water striders, beetles and water bugs",
             "live above the surface — epineuston.",
             "Ex: mosquito larvae stay just below the",
             "surface — hyponeuston.",
         ],
             "Neuston is fixed to one place, the surface film, and it has two named halves — above and below the film — so both are given, since either may be asked for by name.",
             ["Writing that neustons swim in the water. They live AT the surface.",
              "Mixing up the two halves. Epi is above the surface, hypo is below it."],
             "Epi is on top, hypo is under: the water strider walks on the film, the mosquito larva hangs below it.",
             "One line for the place, then one example each for above and below."),
         step("s2_nekton", "boxed_final", "Nekton", 1, "Nekton", [
             boxed("Neuston at the surface, nekton swimming"),
             "Nektons are the animals that can swim",
             "freely in the water.",
             "They move against the current under their",
             "own power.",
             "Ex: fishes, amphibians and water snakes.",
         ],
             "The distinction is where the animal lives and whether it can swim, so the second half states both — free swimming and moving against the current — which also separates nekton from plankton, which only drift.",
             ["Calling plankton nekton. Plankton drift with the water; nekton swim against it.",
              "Giving mosquito larvae as nekton. They belong to the neuston, below the surface film."],
             "Neuston lives on the line between air and water; nekton lives in the water and swims.",
             "One line for swimming, one for the current, then the examples."),
     ],
     "The contrast is surface against open water — a student who writes swims for both terms loses one mark."),

# ── 171 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_gause_principle", V, 62, 171,
     "What is Gause's principle? When is it applicable?",
     app(),
     [("The principle", 1), ("When it applies", 1)],
     [
         step("s1_principle", "text", "The principle", 1, "Principle", [
             "Gause's principle, also called the",
             "competitive exclusion principle, states that",
             "two closely related species competing for",
             "the same resources cannot co-exist",
             "indefinitely.",
             "The weaker competitor is eliminated in due",
             "course of time.",
         ],
             "The principle has a result as well as a statement, so the second line is needed: it names what happens to the loser, which is the part that makes the principle useful.",
             ["Writing that the two species cannot live in the same place at all. They cannot co-exist INDEFINITELY.",
              "Leaving out the outcome. The weaker competitor is eliminated."],
             "Same resource, same place, long enough time — one of the two species goes.",
             "The statement in one sentence, then one line on what happens to the weaker species."),
         step("s2_condition", "boxed_final", "When it applies", 1, "Condition", [
             boxed("It holds only when resources are limited"),
             "The principle is applicable only when the",
             "resources are limited.",
             "If the resources are plentiful, both species",
             "can live together, because they are no",
             "longer competing.",
         ],
             "The second half of the question is a condition, and it is the part most often left out; without a shortage there is no competition, so the principle simply does not apply.",
             ["Writing that the principle always applies. It applies only when resources are LIMITED.",
              "Answering only the first half of the question. The condition is a separate mark."],
             "No shortage, no competition. The principle needs the resources to run short.",
             "One line for the condition and one for why. Both halves of the question must be answered."),
     ],
     "The question has two halves and the second one, the condition, carries a full mark — never stop after the statement."),

# ── 172 ──────────────────────────────────────────────────────────────────────
card("ts_ipe_z1_ee_predation_definition", V, 62, 172,
     "What is predation? Give an example.",
     app(),
     [("Definition", 1), ("Example", 1)],
     [
         step("s1_definition", "text", "Definition", 1, "Definition", [
             "Predation is an interaction between two",
             "different species in which one animal, the",
             "predator, kills and eats the other, the",
             "prey.",
             "The predator is benefited and the prey is",
             "killed.",
         ],
             "Predation differs from parasitism in one fact: the prey is killed, not merely harmed. The book calls predation a 'feeding strategy'; this card writes what happens instead, because the mark is for the interaction and not for a plan.",
             ["Writing that the prey is harmed. In predation the prey is KILLED.",
              "Writing that the predator lives on the prey. That describes a parasite."],
             "Parasite harms and stays; predator kills and leaves.",
             "One sentence naming the predator and the prey, then one line on who gains."),
         step("s2_example", "boxed_final", "Example", 1, "Example", [
             boxed("The predator kills, the prey is eaten"),
             "Ex: the lion (predator) and the deer (prey).",
             "Predation keeps the number of prey animals",
             "under control in an ecosystem.",
         ],
             "The example is short, so the space left goes to the ecological value of predation, which is the extra point that lifts a one-line answer to two marks.",
             ["Giving Plasmodium in man. That is parasitism, because the host is not killed outright.",
              "Naming the two animals without saying which is which."],
             "Say the pair with the roles attached: lion is the predator, deer is the prey.",
             "Name the pair with roles marked, then one line on population control."),
     ],
     "Mark the roles beside the names — lion (predator), deer (prey) — because an unlabelled pair can be read either way.",
     note_extra="WORDING: the book defines predation as 'a feeding strategy ... in which predator gets benefited at the cost of the prey'. The word strategy suggests a plan, so this card states the event instead — the predator kills and eats the prey (Rule 41, plain literal language)."),

print("batch B done")
