export const CONCEPT_KEYWORD_MAP: Record<string, string> = {
    // Vectors
    "vector addition": "vector_addition",
    "add vectors": "vector_addition",
    "vector_addition": "vector_addition",
    "resultant vector": "vector_addition",
    "parallelogram law": "vector_addition",
    "triangle law": "vector_addition",
    "vector sum": "vector_addition",
    "vector subtraction": "vector_addition",
    "vector components": "vector_components",
    "resolution of vector": "vector_components",
    "resolving forces": "vector_components",
    "components of vector": "vector_components",
    "displacement vector": "vector_components",
    "position vector": "vector_components",
    "dot product": "dot_product",
    "scalar product": "dot_product",
    "cross product": "cross_product",
    "vector product": "cross_product",
    "scalar": "scalar_vs_vector",
    "scalar vs vector": "scalar_vs_vector",
    "vector basics": "vector_basics",
    "shm": "simple_harmonic_motion",
    "simple harmonic": "simple_harmonic_motion",

    // Kinematics
    "v²=u²+2as": "kinematics_equations",
    "v2=u2+2as": "kinematics_equations",
    "equations of motion": "kinematics_equations",
    "third equation": "kinematics_equations",
    "velocity time graph": "kinematics_graphs",
    "position time graph": "kinematics_graphs",
    "relative motion": "relative_motion",
    "relative velocity": "relative_motion",
    "river boat": "river_boat_problems",
    "river crossing": "river_boat_problems",
    "boat crossing river": "river_boat_problems",
    "minimum time to cross": "river_boat_problems",
    "rain umbrella": "rain_umbrella",
    "displacement": "distance_vs_displacement",
    "acceleration": "uniform_acceleration",
    "uniform acceleration": "uniform_acceleration",
    "constant acceleration": "uniform_acceleration",
    "projectile": "projectile_motion",
    "projectile motion": "projectile_motion",
    "time of flight": "projectile_motion",
    "range of projectile": "projectile_motion",
    "pendulum": "simple_pendulum",
    "simple pendulum": "simple_pendulum",
    "pendulum swings": "simple_pendulum",
    "uniform circular motion": "circular_motion",
    "centripetal": "circular_motion",
    "centrifugal": "circular_motion",

    // Laws of Motion
    "nlm": "laws_of_motion",
    "newton's law": "laws_of_motion",
    "newtons law": "laws_of_motion",
    "free body diagram": "laws_of_motion",
    "fbd": "laws_of_motion",
    "pseudo force": "pseudo_forces",
    "non inertial": "pseudo_forces",
    "friction": "friction",
    "static friction": "friction",
    "kinetic friction": "friction",

    // Work Energy Power
    "wep": "work_energy_power",
    "work energy": "work_energy_power",
    "work done": "work_energy_power",
    "kinetic energy": "work_energy_theorem",
    "potential energy": "work_energy_theorem",
    "work energy theorem": "work_energy_theorem",
    "conservation of energy": "conservation_of_energy",
    "power": "work_energy_power",

    // Current Electricity
    "ohm's law": "ohms_law",
    "ohms law": "ohms_law",
    "drift velocity": "drift_velocity",
    "resistivity": "resistivity",
    "resistance": "resistance",
    "series circuit": "series_resistance",
    "parallel circuit": "parallel_resistance",
    "kvl": "kirchhoffs_voltage_law",
    "kirchhoff voltage": "kirchhoffs_voltage_law",
    "loop rule": "kirchhoffs_voltage_law",
    "kcl": "kirchhoffs_current_law",
    "kirchhoff current": "kirchhoffs_current_law",
    "junction rule": "kirchhoffs_current_law",
    "wheatstone": "wheatstone_bridge",
    "potentiometer": "potentiometer",
    "internal resistance": "internal_resistance",
    "emf": "internal_resistance",

    // Fields and Magnetism
    "electric field": "electric_field",
    "gauss law": "gauss_law",
    "field inside a shell": "gauss_law_sphere",
    "field outside a charged sphere": "gauss_law_sphere",
    "charged shell": "gauss_law_sphere",
    "electrostatic shielding": "gauss_law_sphere",
    "field inside a solid sphere": "gauss_law_solid_sphere",
    "uniformly charged solid sphere": "gauss_law_solid_sphere",
    "uniformly charged ball": "gauss_law_solid_sphere",
    "insulating charged sphere": "gauss_law_solid_sphere",
    "infinite line charge": "gauss_law_line",
    "field near a charged wire": "gauss_law_line",
    "linear charge density": "gauss_law_line",
    "field of a line charge": "gauss_law_line",
    "e proportional to 1/r": "gauss_law_line",
    "infinite charged sheet": "gauss_law_sheet",
    "field of a charged plane": "gauss_law_sheet",
    "e = sigma/2 epsilon": "gauss_law_sheet",
    "why doesn't the field fall off": "gauss_law_sheet",
    "uniform field from a sheet": "gauss_law_sheet",
    "electric potential": "electric_potential_meaning",
    "what is potential": "electric_potential_meaning",
    "what is electric potential": "electric_potential_meaning",
    "voltage at a point": "electric_potential_meaning",
    "potential at a point": "electric_potential_meaning",
    "work per unit charge": "electric_potential_meaning",
    "is potential a vector": "electric_potential_meaning",
    "potential vs potential energy": "electric_potential_meaning",
    "equipotential surface": "electric_potential_meaning",
    "capacitor": "capacitors",
    "magnetic field": "magnetic_field",
    "emi": "electromagnetic_induction",
    "electromagnetic induction": "electromagnetic_induction",
    "faraday": "electromagnetic_induction",
    "lenz law": "electromagnetic_induction",
    "transformer": "electromagnetic_induction",

    // Waves and Optics
    "wave motion": "wave_motion",
    "sound wave": "sound_waves",
    "doppler": "doppler_effect",
    "doppler effect": "doppler_effect",
    "reflection": "reflection",
    "refraction": "refraction",
    "snell's law": "refraction",
    "total internal reflection": "total_internal_reflection",
    "tir": "total_internal_reflection",
    "lens": "lenses",
    "mirror": "mirrors",
    "interference": "wave_interference",
    "diffraction": "diffraction",

    // Modern Physics
    "photoelectric": "photoelectric_effect",
    "photoelectric effect": "photoelectric_effect",
    "de broglie": "de_broglie_wavelength",
    "bohr model": "bohr_model",
    "bohrs model": "bohr_model",
    "radioactive": "radioactivity",
    "nuclear fission": "nuclear_physics",
    "nuclear fusion": "nuclear_physics",
    "half life": "radioactivity",

    // Thermodynamics
    "first law thermodynamics": "first_law_thermodynamics",
    "carnot": "carnot_engine",
    "heat engine": "carnot_engine",
    "ideal gas": "ideal_gas_laws",
    "pv diagram": "thermodynamics_pv",
};
