# -*- coding: utf-8 -*-
"""Unit 6 — Plant Growth and Development. Book SAQ ch.8 (pp.26-27) + Star Q Plus (p.51).
Globals 20-25 (SAQ) and 159-162 (VSAQ)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main

U = 6
C = []

C.append(Q(U, 'auxin_applications', 'SAQ', 'saq1', 20, 26,
    "Write a note on agricultural and horticultural applications of auxins.",
    years=[('ts',2020),('ts',2022),('ap',2017),('ap',2019),('ap',2022)],
    split=[("What auxins are",1),("Rooting and fruit growth",1),("Weed control and lawns",1),("Apical dominance in practice",1)],
    insider="This question is a LIST, and the marks are in the number of distinct uses. Six named uses "
            "beats two well-explained ones here.",
    steps=[
      S('s1_what','text','What auxins are',1,'What they are',
        lines=["Auxins are plant growth hormones produced at",
               "the STEM TIPS and ROOT TIPS.",
               "The natural auxin is indole-3-acetic acid (IAA).",
               "2,4-D and IBA are synthetic auxins."],
        why="Auxins are made at the growing tips and move down, which is why almost every use below is "
            "about a tip, a cutting, or the buds a tip controls.",
        mistakes=["Saying auxins are made in the leaves. They are made at the STEM and ROOT TIPS.",
                  "Naming no example. IAA, IBA and 2,4-D are the three worth writing."],
        tip="Made at the tips, and every use follows from that.",
        note="Source, the natural one, two synthetic ones. Four lines."),
      S('s2_rooting','text','Rooting and fruit growth',1,'Rooting, fruit',
        lines=["1. Auxins start ROOT formation in stem cuttings.",
               "This is widely used in horticulture to propagate",
               "plants from cuttings.",
               "2. Auxins promote fruit growth, for example in",
               "tomatoes.",
               "3. Auxins prevent PREMATURE FRUIT DROP.",
               "4. Auxins control xylem differentiation and help",
               "in growth."],
        why="A cutting has no roots and no root tip, so supplying auxin from outside does the job the "
            "missing tip would have done.",
        mistakes=["Saying auxins prevent fruit growth. They PROMOTE it.",
                  "Leaving out the cutting. Rooting a cutting is the main horticultural use."],
        tip="A cutting has no tip, so the auxin is supplied by hand.",
        note="Four numbered uses. Keep the numbering running across all three steps."),
      S('s3_weeds','text','Weed control and lawns',1,'Weedicide',
        lines=["5. The synthetic auxin 2,4-D kills DICOT weeds",
               "but does not affect mature MONOCOTS.",
               "6. So 2,4-D is used to prepare and maintain",
               "lawns, where the grass is a monocot and the",
               "weeds are dicots."],
        why="A grass lawn is monocot and its weeds are dicots, so a weedkiller that only harms dicots "
            "clears the lawn without harming it.",
        mistakes=["Saying 2,4-D kills all plants. It kills DICOT weeds and spares mature monocots.",
                  "Leaving out the lawn. It is the named horticultural application."],
        tip="Grass is a monocot, so a dicot killer leaves the lawn standing.",
        note="Say which group is killed and which is spared. That contrast is the mark."),
      S('s4_apical','boxed_final','Apical dominance in practice',1,'Apical dominance',
        lines=[{"text":"Remove the tip and the side buds grow","style":"boxed"},
               "7. The shoot tip produces auxin that suppresses",
               "the growth of lateral buds. This is APICAL",
               "DOMINANCE.",
               "8. Removing the shoot tip removes that",
               "suppression, so the lateral buds grow.",
               "9. This is applied in TEA plantations and in",
               "hedge-making, to get bushy growth."],
        why="Cutting the tip removes the source of the auxin, so the buds below are released and the "
            "plant spreads sideways instead of upward.",
        mistakes=["Saying removing the tip stops growth. It REDIRECTS growth into the lateral buds.",
                  "Naming no application. Tea plantations and hedges are the named ones."],
        tip="Cut the top and the plant grows outward instead of upward.",
        note="Name apical dominance, then the two applications. This is the last mark.")]))

C.append(Q(U, 'gibberellin_responses', 'SAQ', 'saq2', 21, 26,
    "Write the physiological responses of gibberellins in plants.",
    years=[('ap',2019),('ts',2015)],
    split=[("What gibberellins are",1),("Stem and fruit responses",1),("Industrial and crop uses",1),("Senescence and maturity",1)],
    note_extra="BOOK NOTE: the guide's first line lists \"Leaf and fruit senescence\" among the effects "
               "of gibberellins and its own point 7 then says \"They delay senescence.\" NCERT is clear "
               "that gibberellins DELAY senescence; the card writes the delay and records the "
               "contradiction. The guide also prints \"fruit repining\" for ripening.",
    insider="The named numbers are what lift this answer: GA3 in brewing, and 20 tonnes an acre in "
            "sugarcane. Write at least one of them.",
    steps=[
      S('s1_what','text','What gibberellins are',1,'What they are',
        lines=["Gibberellins are plant growth hormones.",
               "There are more than a hundred of them, written",
               "GA1, GA2, GA3 and so on.",
               "GA3 was the first one discovered and is the",
               "most studied."],
        why="Gibberellins are a numbered family rather than one molecule, which is why answers name a "
            "particular one, GA3, when a use is specific.",
        mistakes=["Writing gibberellin as a single compound. It is a large family, numbered GA1, GA2, GA3.",
                  "Confusing GA3 with 2,4-D. 2,4-D is a synthetic AUXIN."],
        tip="A numbered family, and GA3 is the one that does the named jobs.",
        note="Name the family and the numbering. Four lines."),
      S('s2_stem','text','Stem and fruit responses',1,'Stem, fruit',
        lines=["1. Gibberellins cause elongation of the stem",
               "axis. They increase the length of grape stalks.",
               "2. They cause fruits such as apple to elongate",
               "and improve their shape.",
               "3. They promote fruit ripening.",
               "4. They cause BOLTING, the elongation of",
               "internodes just before flowering."],
        why="Every one of these is the same underlying action — internode elongation — which is why "
            "grapes, apples and bolting all appear on one list.",
        mistakes=["Saying gibberellins shorten the stem. They ELONGATE it.",
                  "Leaving out bolting. It is the named response and appears as a question on its own."],
        tip="One action, many uses: gibberellin makes things longer.",
        note="Four numbered responses. Bolting is worth naming explicitly."),
      S('s3_industry','text','Industrial and crop uses',1,'Industry, crops',
        lines=["5. GA3 speeds up the MALTING process in the",
               "brewing industry.",
               "6. Spraying GA on sugarcane stems increases",
               "stem length and raises the yield by about",
               "20 tonnes per acre.",
               "7. GA hastens the maturity period of conifers,",
               "so seed is produced earlier."],
        why="Sugarcane stores its sugar in the stem, so anything that lengthens the stem directly raises "
            "the sugar harvested.",
        mistakes=["Giving no figures. The 20 tonnes per acre is what makes this a real answer.",
                  "Saying GA slows maturity in conifers. It HASTENS it."],
        tip="Longer sugarcane stem means more stored sugar.",
        note="Three named uses with the numbers. The numbers are the mark."),
      S('s4_senescence','boxed_final','Senescence and maturity',1,'Senescence',
        lines=[{"text":"Gibberellins DELAY senescence","style":"boxed"},
               "8. Gibberellins DELAY senescence, so fruits can",
               "be left on the tree longer and still be",
               "transported.",
               "9. They break seed and bud dormancy.",
               "10. They induce flowering in long day plants."],
        why="Delaying senescence keeps the tissue alive and working longer, which is the opposite of what "
            "ethylene and abscisic acid do.",
        mistakes=["Writing that gibberellins promote senescence. They DELAY it. The guide's own list "
                  "contradicts itself on this line.",
                  "Confusing this with ethylene, which PROMOTES senescence and abscission."],
        tip="Gibberellin delays the end; ethylene brings it on.",
        note="State the delay clearly. The guide prints both answers, so be unambiguous.")]))

C.append(Q(U, 'cytokinin_effects', 'SAQ', 'saq3', 22, 26,
    "Write any four physiological effects of cytokinins in plants.",
    years=[('ts',2019),('ap',2016),('ap',2017)],
    split=[("What cytokinins are and where they are made",1),("Cell division and new organs",1),
           ("Delaying senescence",1),("Overcoming apical dominance",1)],
    insider="The question asks for FOUR. Number them one to four and stop — an examiner marking four "
            "effects will not hunt through a paragraph for the fourth.",
    steps=[
      S('s1_what','text','What cytokinins are',1,'What they are',
        lines=["Cytokinins are plant growth hormones that",
               "promote CELL DIVISION.",
               "They are made where rapid cell division occurs:",
               "root tips, shoot buds and young fruits.",
               "Zeatin is a natural cytokinin."],
        why="They are made exactly where cells are dividing fastest, which is the clearest evidence of "
            "what their main job is.",
        mistakes=["Saying cytokinins cause cell elongation. That is auxin and gibberellin; cytokinin "
                  "causes cell DIVISION.",
                  "Saying they are made at the shoot tip only. Root tips, shoot buds and young fruits."],
        tip="Cytokinin means cell division: kinesis is division.",
        note="Definition, the three sites, one named example."),
      S('s2_division','text','Cell division and new organs',1,'Division',
        lines=["1. They promote cell division in root tips and",
               "shoot tips.",
               "2. They help produce new LEAVES and",
               "CHLOROPLASTS in leaves.",
               "3. They help lateral shoot growth and",
               "adventitious shoot formation."],
        why="New leaves and new chloroplasts both need new cells first, so they follow directly from the "
            "cell-division effect.",
        mistakes=["Listing only 'cell division'. The question asks for four separate EFFECTS.",
                  "Leaving out chloroplast formation. It is one of the named effects."],
        tip="More divisions means more leaves, and more chloroplasts inside them.",
        note="Three numbered effects. Keep the numbering going into the next steps."),
      S('s3_senescence','text','Delaying senescence',1,'Senescence',
        lines=["4. They promote nutrient movement into the",
               "leaf, which DELAYS leaf senescence.",
               "A leaf treated with cytokinin stays green while",
               "the leaves around it yellow.",
               "This is called the Richmond-Lang effect."],
        why="Cytokinin pulls nutrients toward the treated leaf, so that leaf keeps its chlorophyll while "
            "untreated leaves lose theirs.",
        mistakes=["Saying cytokinins cause yellowing. They DELAY it.",
                  "Giving no mechanism. The nutrient movement is what makes the delay happen."],
        tip="The treated leaf stays green because the food goes to it.",
        note="Name the effect and say why it happens. The named effect is a bonus, not required."),
      S('s4_apical','boxed_final','Overcoming apical dominance',1,'Apical dominance',
        lines=[{"text":"Cytokinin releases the buds auxin suppresses","style":"boxed"},
               "5. Cytokinins help OVERCOME apical dominance.",
               "They release the lateral buds that auxin from",
               "the shoot tip was suppressing.",
               "So the plant produces side branches and grows",
               "BUSHY."],
        why="Auxin and cytokinin work against each other on the same lateral buds, so raising the "
            "cytokinin has the same effect as removing the auxin source.",
        mistakes=["Saying cytokinin causes apical dominance. Auxin causes it; cytokinin OVERCOMES it.",
                  "Leaving out the bushy growth. That is the visible result."],
        tip="Auxin holds the side buds down; cytokinin lets them up.",
        note="Name the opposition with auxin. That contrast is what earns this mark.")]))

C.append(Q(U, 'ethylene_processes', 'SAQ', 'saq4', 23, 27,
    "What are the physiological processes that are regulated by ethylene in plants?",
    years=[('ts',2017),('ap',2015),('ap',2020)],
    split=[("What ethylene is",1),("Ripening and senescence",1),("Seedling and dormancy effects",1),("Growth in water plants and roots",1)],
    insider="Ethylene is the only gaseous hormone, and that is worth the first line. Fruit ripening is "
            "the effect an examiner will not accept an answer without.",
    steps=[
      S('s1_what','text','What ethylene is',1,'What it is',
        lines=["Ethylene is a simple GASEOUS plant growth",
               "regulator.",
               "It is produced in large amounts by ripening",
               "fruits and by ageing tissues.",
               "Because it is a gas, it spreads from one fruit",
               "to the fruits around it."],
        why="Being a gas is what lets one ripe fruit ripen a whole basket, which no liquid hormone could do.",
        mistakes=["Calling ethylene a liquid hormone. It is a GAS, and that is its defining feature.",
                  "Saying it is made only in seeds. Ripening fruits and ageing tissues make the most."],
        tip="The only gas among the hormones, so it travels through the air.",
        note="Gas, source, and why the gas matters. Five lines."),
      S('s2_ripening','text','Ripening and senescence',1,'Ripening',
        lines=["1. Ethylene is highly effective in FRUIT",
               "RIPENING.",
               "2. It raises the rate of respiration during",
               "ripening. This rise is called the RESPIRATORY",
               "CLIMACTIC.",
               "3. It promotes SENESCENCE and ABSCISSION of",
               "leaves and flowers."],
        why="Ripening is an active process that needs energy, so the burst of respiration is what pays "
            "for it — which is why the two always appear together.",
        mistakes=["Saying ethylene delays ripening. It PROMOTES ripening.",
                  "Leaving out abscission. Ethylene causes leaves and flowers to fall."],
        tip="Ethylene ends things: ripens, ages, and drops.",
        note="Three numbered effects. Ripening and the respiratory climactic are the two to name."),
      S('s3_seedling','text','Seedling and dormancy effects',1,'Seedlings',
        lines=["4. In dicot seedlings it causes horizontal",
               "growth, swelling of the axis, and APICAL HOOK",
               "formation.",
               "5. It BREAKS seed and bud dormancy.",
               "6. It starts germination in peanut seeds and",
               "sprouting in potato tubers."],
        why="The apical hook protects the shoot tip as the seedling pushes up through soil, so ethylene "
            "is what shapes a seedling to survive emergence.",
        mistakes=["Saying ethylene causes dormancy. It BREAKS dormancy.",
                  "Leaving out the apical hook. It is the named seedling response."],
        tip="Hook, swell, and break dormancy: all of it happens underground.",
        note="Three numbered effects. The hook is the one most often forgotten."),
      S('s4_growth','boxed_final','Growth in water plants and roots',1,'Growth',
        lines=[{"text":"Ethylene ripens, ages, drops and elongates","style":"boxed"},
               "7. In water plants it promotes rapid PETIOLE",
               "and INTERNODE elongation, so leaves stay above",
               "rising water.",
               "8. It promotes root growth and ROOT HAIR",
               "formation, which increases absorption."],
        why="A deep-water rice plant that cannot grow taller than the flood will drown, so ethylene-driven "
            "elongation is a survival response, not just a growth effect.",
        mistakes=["Saying ethylene stops root growth. It PROMOTES root and root hair growth.",
                  "Leaving out the water plants. The elongation response is a named application."],
        tip="Rising water, rising stem: the leaves stay in the air.",
        note="Two more numbered effects. Eight in total is a full answer.")]))

C.append(Q(U, 'seed_dormancy', 'SAQ', 'saq5', 24, 27,
    "Write short notes on seed dormancy.",
    years=[('ts',2017)],
    split=[("What seed dormancy is",1),("Causes: the seed coat",1),("Causes: chemical inhibitors and cold",1),("Breaking dormancy",1)],
    note_extra="BOOK NOTE: the guide names the tomato germination inhibitor \"lycopane\". The card says "
               "\"chemical inhibitors present in the seed\", which is what NCERT states, and records the "
               "guide's word here rather than repeating a name that is not standard.",
    insider="Dormancy and quiescence are a favourite pair. If you have room, add one line saying "
            "dormancy is INTERNAL and quiescence is external — it costs nothing and often earns credit.",
    steps=[
      S('s1_define','text','What seed dormancy is',1,'Definition',
        lines=["Seed dormancy is the inability of a seed to",
               "germinate, or the delay in its germination,",
               "even when conditions are favourable.",
               "It is caused by INTERNAL factors of the seed",
               "itself.",
               "Dormancy differs from QUIESCENCE, where the",
               "seed fails to germinate because the outside",
               "conditions are wrong."],
        why="The cause being internal is what separates dormancy from quiescence, and that distinction "
            "is the whole basis of the answer.",
        mistakes=["Saying dormancy is caused by dry or cold weather. That is QUIESCENCE.",
                  "Saying a dormant seed is dead. It is alive and will germinate once dormancy is broken."],
        tip="Dormancy is the seed's own decision; quiescence is the weather's.",
        note="Definition, internal cause, and the contrast with quiescence."),
      S('s2_coat','text','Causes: the seed coat',1,'Seed coat',
        lines=["1. HARD SEED COAT:",
               "A tough, impermeable seed coat stops water and",
               "oxygen from entering.",
               "Without water and oxygen the embryo cannot",
               "start growing."],
        why="Germination begins with the uptake of water, so a coat that keeps water out prevents even "
            "the first step.",
        mistakes=["Saying the hard coat kills the embryo. It only keeps water and oxygen OUT.",
                  "Naming only the coat and stopping. There are other causes to give."],
        tip="No water in, no germination out.",
        note="Name the cause and say what it blocks. Four lines."),
      S('s3_chemical','text','Causes: chemical inhibitors and cold',1,'Inhibitors',
        lines=["2. CHEMICAL INHIBITORS:",
               "Some seeds, such as tomato, contain chemicals",
               "that stop germination. Abscisic acid is one.",
               "3. NEED FOR CHILLING:",
               "Seeds such as Polygonum will not germinate for",
               "weeks or months until they have been kept cold",
               "and moist."],
        why="A seed that needs a cold period cannot germinate in autumn, so the chilling requirement is "
            "a clock that holds the seedling back until spring.",
        mistakes=["Saying the inhibitor is in the soil. It is inside the SEED.",
                  "Saying chilling kills dormancy instantly. It takes weeks of cold, moist conditions."],
        tip="Some seeds carry their own brake; others wait out a winter.",
        note="Two more causes with an example each."),
      S('s4_breaking','boxed_final','Breaking dormancy',1,'Breaking it',
        lines=[{"text":"Scarify the coat, or chill the seed","style":"boxed"},
               "A hard coat can be broken by SCARIFICATION:",
               "rubbing, chipping or acid treatment.",
               "A chilling requirement is met by",
               "STRATIFICATION, also called prechilling:",
               "layering the seeds in moist sand or peat",
               "through the winter.",
               "Gibberellins also break seed dormancy."],
        why="Each treatment removes one named cause, so the way dormancy is broken tells you what was "
            "causing it.",
        mistakes=["Confusing scarification with stratification. Scarification breaks the COAT; "
                  "stratification supplies the COLD.",
                  "Leaving out gibberellins. They are the hormone that breaks dormancy."],
        tip="Scarify the shell, stratify in the cold.",
        note="Both named treatments, matched to their causes, plus the hormone.")]))

C.append(Q(U, 'which_growth_regulator', 'SAQ', 'saq6', 25, 27,
    "Which one of the plant growth regulators would you use if you are asked to "
    "(a) induce rooting in a twig (b) quickly ripen a fruit (c) delay leaf senescence "
    "(d) induce growth in axillary buds (e) bolt a rosette plant (f) induce immediate "
    "stomatal closure in leaves (g) overcome apical dominance (h) kill dicotyledonous weeds?",
    split=[("Parts a and b",1),("Parts c and d",1),("Parts e and f",1),("Parts g and h",1)],
    insider="Eight one-word answers, half a mark each. Answer every part even if you are unsure — a "
            "blank scores nothing, and a named hormone that is close often scores something.",
    steps=[
      S('s1_ab','text','Parts a and b',1,'a, b',
        lines=["(a) Induce rooting in a twig:",
               "    AUXIN, such as IBA or NAA.",
               "(b) Quickly ripen a fruit:",
               "    ETHYLENE."],
        why="A twig has no root tip to make its own auxin, and a fruit ripens on ethylene, so each answer "
            "names the hormone that does that one job.",
        mistakes=["Answering (a) with gibberellin. ROOTING is an auxin effect.",
                  "Answering (b) with abscisic acid. RIPENING is ethylene."],
        tip="Rooting is auxin; ripening is ethylene.",
        note="Repeat the part letter with each answer so nothing is mismarked."),
      S('s2_cd','text','Parts c and d',1,'c, d',
        lines=["(c) Delay leaf senescence:",
               "    CYTOKININ.",
               "(d) Induce growth in axillary buds:",
               "    CYTOKININ."],
        why="Both are cytokinin because both are about keeping tissue actively dividing rather than "
            "letting it age or stay suppressed.",
        mistakes=["Answering (c) with ethylene. Ethylene PROMOTES senescence; cytokinin delays it.",
                  "Answering (d) with auxin. Auxin SUPPRESSES axillary buds."],
        tip="Cytokinin keeps things young and keeps side buds growing.",
        note="Two parts, one hormone. Say cytokinin for both without hesitating."),
      S('s3_ef','text','Parts e and f',1,'e, f',
        lines=["(e) Bolt a rosette plant:",
               "    GIBBERELLIN.",
               "(f) Induce immediate stomatal closure:",
               "    ABSCISIC ACID (ABA)."],
        why="Bolting is internode elongation, which is gibberellin's signature effect, and immediate "
            "stomatal closure is the one thing abscisic acid is named for.",
        mistakes=["Answering (e) with auxin. Bolting is a GIBBERELLIN effect.",
                  "Answering (f) with cytokinin. Stomatal closure is ABSCISIC ACID."],
        tip="Bolting is gibberellin; shutting the pore is ABA.",
        note="Two parts. ABA is also called the stress hormone, which is worth adding."),
      S('s4_gh','boxed_final','Parts g and h',1,'g, h',
        lines=[{"text":"Auxin suppresses buds; cytokinin releases them","style":"boxed"},
               "(g) Overcome apical dominance:",
               "    CYTOKININ.",
               "(h) Kill dicotyledonous weeds:",
               "    2,4-D, a synthetic AUXIN."],
        why="Part (h) is the one trap in the list: the answer is an auxin, even though (d) and (g) were "
            "about escaping auxin's effect.",
        mistakes=["Answering (h) with ethylene. 2,4-D is the weedkiller, and it is a synthetic AUXIN.",
                  "Answering (g) with auxin. Auxin CAUSES apical dominance; cytokinin overcomes it."],
        tip="The same family both suppresses buds and kills weeds: auxin does both.",
        note="Two parts. Naming 2,4-D specifically is better than writing 'auxin' alone.")]))

def vs(slug, ref, gno, page, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, page, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('vernalisation','vsaq1',159,51,
   "What do you understand by vernalisation? Write its significance.",
   [("What it is",1),("Its significance",1)],
   "Two halves and the second is easy to forget. The significance is one sentence about timing.",
   [S('s1_what','text','What vernalisation is',1,'Definition',
      lines=["Vernalisation is the method of inducing flowering",
             "in plants by a period of PRE-CHILLING, that is,",
             "low temperature treatment."],
      why="A cold requirement means the plant can only flower after a winter has passed, which is what "
          "the treatment imitates.",
      mistakes=["Saying vernalisation uses heat. It uses COLD.",
                "Saying it induces germination. It induces FLOWERING."],
      tip="Vernal means spring: cold first, flowers after.",
      note="Definition with the word chilling in it. Three lines."),
    S('s2_sig','boxed_final','Its significance',1,'Significance',
      lines=[{"text":"It stops the plant flowering too early","style":"boxed"},
             "It prevents precocious reproductive development",
             "late in the growing season.",
             "So the plant has enough time to reach maturity",
             "before it flowers."],
      why="A plant that flowers before it is big enough cannot fill its seed, so the cold requirement "
          "makes sure growth comes first.",
      mistakes=["Saying it speeds up flowering in every plant. It PREVENTS early flowering.",
                "Giving no significance at all. It is a whole mark."],
      tip="Grow first, flower after: the cold enforces the order.",
      note="One clear line on timing. Do not skip this half.")],
   years=[('ts',2019)])

vs('bolting','vsaq2',160,51,
   "What is meant by bolting? Which hormone causes bolting?",
   [("What bolting is",1),("The hormone",1)],
   "Two facts and a definition that must include 'internodes'. One line each.",
   [S('s1_what','text','What bolting is',1,'Definition',
      lines=["Bolting is the sudden ELONGATION OF INTERNODES",
             "just before flowering.",
             "It is seen in rosette plants such as cabbage and",
             "beet, whose internodes are normally very short."],
      why="A rosette plant has almost no visible stem, so the sudden elongation before flowering is "
          "dramatic and easy to name.",
      mistakes=["Saying bolting is the growth of roots. It is INTERNODE elongation.",
                "Leaving out 'just before flowering'. The timing is part of the definition."],
      tip="The stem shoots up right before the flower opens.",
      note="Definition with internodes and the timing. One example helps."),
    S('s2_hormone','boxed_final','The hormone',1,'Hormone',
      lines=[{"text":"Gibberellins cause bolting","style":"boxed"},
             "GIBBERELLINS are responsible for bolting.",
             "This is the same elongation effect that lengthens",
             "grape stalks and sugarcane stems."],
      why="Bolting is internode elongation, and internode elongation is what gibberellin does everywhere "
          "else in the chapter, so it is the same effect under a different name.",
      mistakes=["Naming auxin. Bolting is a GIBBERELLIN effect.",
                "Naming no hormone. Half the question is the hormone."],
      tip="Anything that gets longer is gibberellin.",
      note="Name the hormone and link it to the elongation effect.")],
   years=[('ts',2017),('ts',2022)])

vs('quiescence_vs_dormancy','vsaq3',161,51,
   "Define the terms quiescence and dormancy.",
   [("Quiescence",1),("Dormancy",1)],
   "Outside against inside. That single contrast is the whole answer, so put it in both definitions.",
   [S('s1_quiescence','text','Quiescence',1,'Quiescence',
      lines=["QUIESCENCE is a delayed seed germination that",
             "happens when the EXTERNAL conditions are wrong:",
             "too dry, too warm or too cold.",
             "Give the seed the right conditions and it",
             "germinates at once."],
      why="Nothing is wrong with the seed, so correcting the surroundings is enough to start germination "
          "immediately.",
      mistakes=["Saying quiescence is caused by something inside the seed. That is DORMANCY.",
                "Leaving out the named conditions. Dry, warm or cold is what the definition specifies."],
      tip="Quiescence is the weather's fault.",
      note="Definition, the external cause, and how quickly it ends."),
    S('s2_dormancy','boxed_final','Dormancy',1,'Dormancy',
      lines=[{"text":"Outside conditions cause quiescence; the seed","style":"boxed"},
             {"text":"itself causes dormancy","style":"boxed"},
             "DORMANCY is the INNATE inhibition of germination,",
             "even when the seed is placed in the most",
             "favourable environment.",
             "Its causes are inside the seed: a hard coat,",
             "chemical inhibitors, or a need for chilling."],
      why="The word innate is what carries the definition: the block is built into the seed, so good "
          "conditions alone cannot remove it.",
      mistakes=["Defining dormancy by bad weather. Dormancy persists in the BEST conditions.",
                "Leaving out the word innate or internal. It is what separates the two terms."],
      tip="Dormancy is the seed's own fault.",
      note="Mirror the quiescence lines. The word 'innate' is the mark.")],
   years=[('ap',2015)])

vs('plasticity','vsaq4',162,51,
   "Define plasticity. Give an example.",
   [("Definition",1),("Example",1)],
   "Heterophylly is the example. Name the plants — cotton and coriander — because the example without "
   "a plant is only half an example.",
   [S('s1_define','text','Plasticity defined',1,'Definition',
      lines=["PLASTICITY is the ability of a plant to follow",
             "different pathways, in response to the",
             "environment or to its phase of life, and so to",
             "form different kinds of structures."],
      why="The same plant with the same genes builds different structures in different conditions, which "
          "is what makes the ability worth naming.",
      mistakes=["Saying plasticity is a genetic change. The genes do not change; only the structure does.",
                "Leaving out 'in response to the environment'. The response is the definition."],
      tip="Same plant, same genes, different shape.",
      note="Definition in four lines. Mention both triggers: environment and phase of life."),
    S('s2_example','boxed_final','Example',1,'Example',
      lines=[{"text":"Heterophylly: different leaves on one plant","style":"boxed"},
             "Example: HETEROPHYLLY in cotton and coriander.",
             "The juvenile leaves of these plants are shaped",
             "differently from the adult leaves on the same",
             "plant.",
             "In buttercup, leaves grown under water differ",
             "from those grown in air."],
      why="One plant carrying two leaf shapes at once is the clearest possible demonstration that the "
          "difference comes from conditions and not from genes.",
      mistakes=["Naming heterophylly without a plant. Cotton and coriander are the named ones.",
                "Calling it a difference between two plants. It is a difference within ONE plant."],
      tip="Two leaf shapes on one plant is plasticity you can see.",
      note="Name the term and at least two plants. The water example is a useful extra.")])

main(C, U)
