# -*- coding: utf-8 -*-
"""Unit 13 — Strategies for Enhancement in Food Production. Book LAQ ch.3 (pp.17-19) +
VSAQ ch.20 (p.47). Globals 5, 6 (LAQ) and 125-134 (VSAQ).
Global 6 is the MOST REPEATED question in the whole book: eleven printed appearances."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main
import figs_u13 as G

U = 13
C = []

C.append(Q(U, 'laq_release_new_variety', 'LAQ', 'laq1', 5, 17,
    "You are a Botanist working in the area of plant breeding. Describe the various steps that "
    "you will undertake to release a new variety.",
    years=[('ts',2016),('ts',2017),('ap',2017)],
    split=[("The five steps",1),("Collection of variability",2),("Evaluation and selection of parents",1),
           ("Cross hybridisation",1),("Selection and testing of recombinants",2),
           ("Testing, release and commercialisation",1)],
    insider="Five steps, and the marks follow them. List all five first — an examiner who can see the "
            "five headings will find every mark, and the list alone is worth one.",
    steps=[
      S('s1_five','text','The five steps',1,'The list',
        lines=["Releasing a new crop variety takes FIVE steps:",
               "1. Collection of variability",
               "2. Evaluation and selection of parents",
               "3. Cross hybridisation among the selected",
               "   parents",
               "4. Selection and testing of superior",
               "   recombinants",
               "5. Testing, release and commercialisation of",
               "   the new cultivars"],
        why="The five steps run in one order — gather, choose, cross, select, release — and every later "
            "step depends on the one before it.",
        mistakes=["Naming three steps. There are FIVE, and each is a heading in the answer.",
                  "Putting selection before hybridisation. You must cross before you can select "
                  "recombinants."],
        tip="Gather, choose, cross, select, release.",
        note="All five, numbered, before any explanation. Eight lines and one mark secured."),
      S('s2_variability','text','Collection of variability',2,'Variability',
        lines=["1. COLLECTION OF VARIABILITY",
               "Genetic variability is the raw material of any",
               "breeding programme — without differences there",
               "is nothing to select from.",
               "Pre-existing variability is available in the",
               "WILD RELATIVES of crop plants.",
               "Collecting and preserving all the wild varieties",
               "and species is a PRE-REQUISITE, because it is",
               "the only way to exploit the natural genes in the",
               "population.",
               "The entire collection of plants or seeds having",
               "all the DIVERSE ALLELES for all genes in a given",
               "crop is called the GERM PLASM COLLECTION."],
        why="A breeder can only recombine alleles that already exist somewhere, so the size of the "
            "germplasm collection sets the limit on what can ever be bred.",
        mistakes=["Saying variability can be created at will. It is COLLECTED from wild relatives.",
                  "Leaving out germplasm collection. It is the named term and this mark is largely for it.",
                  "Saying wild relatives are useless. They carry the genes for disease resistance."],
        tip="You can only breed with alleles somebody has already collected.",
        note="Two marks here. Define germplasm collection in full — it is asked as a VSAQ on its own."),
      S('s3_evaluation','text','Evaluation and selection of parents',1,'Evaluation',
        lines=["2. EVALUATION AND SELECTION OF PARENTS",
               "The germplasm is EVALUATED to identify plants",
               "with the desired characters.",
               "The selected plants are MULTIPLIED and used in",
               "hybridisation.",
               "PURE LINES are created by continuous SELF",
               "POLLINATION, so the parents are homozygous and",
               "of known genotype."],
        why="A cross can only be interpreted if both parents breed true, so purifying the parents comes "
            "before any crossing.",
        mistakes=["Skipping the pure lines. Self pollination to homozygosity is what this step is for.",
                  "Saying evaluation means testing the yield of hybrids. It means examining the "
                  "GERMPLASM for useful characters."],
        tip="Pick them, then purify them, then cross them.",
        note="Evaluation, multiplication, and pure lines by self pollination."),
      S('s4_hybridisation','text','Cross hybridisation',1,'Hybridisation',
        lines=["3. CROSS HYBRIDISATION AMONG SELECTED PARENTS",
               "The desired characters from different parents",
               "are combined by crossing them.",
               "Example: a high yielding parent is crossed with",
               "a disease resistant one.",
               "It is very TIME CONSUMING and LABORIOUS: each",
               "cross needs emasculation and hand pollination.",
               "It is also uncertain — usually only ONE cross in",
               "a few hundred gives the desired combination."],
        why="Each cross is done by hand on individual flowers, so the low success rate translates "
            "directly into years of work.",
        mistakes=["Saying hybridisation always works. Only about one in a few hundred crosses succeeds.",
                  "Leaving out the difficulty. The time and the low success rate are part of the mark."],
        tip="Hundreds of crosses for one useful combination.",
        note="What is combined, an example, and both difficulties."),
      S('s5_selection','text','Selection and testing of recombinants',2,'Selection',
        lines=["4. SELECTION AND TESTING OF SUPERIOR RECOMBINANTS",
               "Plants with the desired combination of characters",
               "are selected from among the hybrids.",
               "This is the CRITICAL step, and it needs careful",
               "scientific evaluation of the progeny.",
               "It yields offspring SUPERIOR TO BOTH PARENTS.",
               "The selected plants are then SELF POLLINATED for",
               "several generations to reach HOMOZYGOSITY,",
               "so that the characters no longer SEGREGATE in",
               "the progeny and the variety breeds true."],
        why="A hybrid that is still heterozygous will not breed true, so its good characters would "
            "scatter in the next generation unless homozygosity is reached first.",
        mistakes=["Stopping at 'the best plants are selected'. The self pollination to homozygosity is "
                  "half this mark.",
                  "Saying the offspring resemble one parent. They are SUPERIOR TO BOTH.",
                  "Leaving out segregation. Preventing it is why homozygosity is needed."],
        tip="Select the best, then make it breed true.",
        note="Two marks. Selection, superiority to both parents, and the homozygosity that stops "
             "segregation."),
      S('s6_release','boxed_final','Testing, release and commercialisation',1,'Release',
        lines=[{"text":"Research field, then farmer's field, then","style":"boxed"},
               {"text":"certification","style":"boxed"},
               "5. TESTING, RELEASE AND COMMERCIALISATION",
               "The newly selected lines are evaluated for YIELD",
               "and DISEASE RESISTANCE.",
               "They are first grown in RESEARCH FIELDS, under",
               "controlled conditions.",
               "The hybrid line is then tested in FARMERS'",
               "FIELDS, in at least three different seasons and",
               "at several locations.",
               "The material is compared with the best available",
               "LOCAL CULTIVAR.",
               "Only after this evaluation and CERTIFICATION is",
               "the variety released."],
        why="A variety that performs well in one research plot may fail in a farmer's field, so the "
            "comparison against the best local cultivar is the real test.",
        mistakes=["Releasing straight from the research field. Farmers' field trials come first.",
                  "Leaving out the comparison with the local cultivar. A new variety must BEAT what "
                  "farmers already grow.",
                  "Forgetting certification. Release follows certification, not the other way round."],
        tip="It must beat what the farmer already grows, in the farmer's own field.",
        note="Both kinds of field, the comparison, and certification before release.")]))

C.append(Q(U, 'laq_tissue_culture', 'LAQ', 'laq2', 6, 18,
    "Describe the tissue culture technique. What are the advantages of tissue culture over the "
    "conventional method of plant breeding in crop improvement programmes?",
    years=[('ap',2015),('ap',2016),('ap',2017),('ap',2019),('ap',2019),('ap',2020),('ap',2022),
           ('ts',2015),('ts',2017),('ts',2019),('ts',2020)],
    split=[("What tissue culture is",1),("Medium and sterilisation",1),("Explant and inoculation",1),
           ("Incubation and callus",1),("Organogenesis and embryogenesis",1),
           ("Acclimatisation",1),("Advantages",2)],
    note_extra="The MOST REPEATED question in the book: eleven printed appearances across both boards, "
               "and it is set in all five of the book's guess papers.",
    insider="Two questions in one, and the second half is worth two marks. Budget the time: six steps "
            "for six marks, then at least five advantages for the last two. An answer that describes "
            "the technique beautifully and stops has thrown away a quarter of the marks.",
    steps=[
      S('s1_what','text','What tissue culture is',1,'Definition',
        lines=["TISSUE CULTURE is the technique of growing,",
               "culturing and maintaining cells, tissues and",
               "organs IN VITRO — in glass, outside the plant.",
               "It is based on the property of TOTIPOTENCY: the",
               "ability of any living plant cell to regenerate",
               "into a complete plant.",
               "The six steps of the technique are:",
               "1. prepare the medium  2. sterilise it",
               "3. prepare the explant 4. inoculate",
               "5. incubate for growth 6. acclimatise and",
               "   transfer to pots."],
        why="Totipotency is what makes the whole technique possible: without it a fragment of tissue "
            "could never become a whole plant.",
        mistakes=["Leaving out totipotency. It is the principle the technique rests on.",
                  "Saying tissue culture works only on seeds. ANY living plant part can be used.",
                  "Naming fewer than six steps. Six is what the book gives and six is what the marks follow."],
        tip="Any living cell can rebuild the whole plant: that is totipotency.",
        note="Definition, totipotency, and all six steps listed. This opening is worth a mark by itself."),
      S('s2_medium','text','Medium and sterilisation',1,'Medium',
        lines=["1. PREPARATION OF THE NUTRIENT MEDIUM",
               "The medium must supply a CARBON SOURCE such as",
               "SUCROSE, inorganic salts, vitamins, amino acids,",
               "and growth regulators such as AUXINS and",
               "CYTOKININS.",
               "2. STERILISATION OF THE MEDIUM",
               "A nutrient rich medium attracts micro organisms,",
               "so it must be sterilised.",
               "Sterilisation is done in an AUTOCLAVE for 15",
               "minutes at 121°C and 15 lb pressure."],
        why="The medium is a perfect food for bacteria and fungi as well as for the plant tissue, so "
            "anything not sterilised will be overgrown before the explant can start.",
        mistakes=["Leaving out the autoclave figures. 15 minutes, 121°C and 15 lb are the numbers asked for.",
                  "Saying the medium contains glucose. The carbon source given is SUCROSE.",
                  "Forgetting the growth regulators. Auxins and cytokinins are part of the medium."],
        tip="Rich food feeds the contaminants too, so sterilise everything.",
        note="Every component of the medium, then the three autoclave figures."),
      S('s3_explant','text','Explant and inoculation',1,'Explant',
        lines=["3. PREPARATION OF THE EXPLANT",
               "Any living part of a plant used as the inoculum",
               "is called an EXPLANT — a piece of root, stem,",
               "leaf or a shoot tip.",
               "The explant is surface sterilised.",
               "4. INOCULATION OF THE EXPLANT",
               "Transferring the explant onto the sterile medium",
               "is called INOCULATION.",
               "It is carried out in a LAMINAR AIR FLOW CHAMBER,",
               "which supplies filtered, sterile air."],
        why="Every transfer is a chance for contamination, so the one step where the culture is open to "
            "the air is done under a filtered air stream.",
        mistakes=["Not defining explant. It is a named term and often asked alone.",
                  "Leaving out the laminar air flow chamber. It is where inoculation must happen.",
                  "Saying the explant is sterilised in the autoclave. It is SURFACE sterilised; an "
                  "autoclave would kill it."],
        tip="The explant is the piece you start from, and it goes in under sterile air.",
        note="Define explant, give examples, and name the laminar air flow chamber."),
      S('s4_callus','text','Incubation and callus',1,'Callus',
        lines=["5. INCUBATION FOR GROWTH",
               "The cultures are incubated for 3 to 4 WEEKS.",
               "During this time the explant cells absorb",
               "nutrients, grow, and divide repeatedly by",
               "MITOSIS.",
               "They produce an UNDIFFERENTIATED mass of cells",
               "called the CALLUS."],
        why="The callus is undifferentiated on purpose: a mass of unspecialised cells can be pushed down "
            "any developmental path by changing the hormones.",
        mistakes=["Saying the callus is differentiated tissue. It is an UNDIFFERENTIATED mass.",
                  "Leaving out the time. Three to four weeks is the figure given."],
        tip="A shapeless lump of cells that can still become anything.",
        note="The time, the divisions, and the definition of callus."),
      S('s5_organogenesis','text','Organogenesis and embryogenesis',1,'Two paths',
        lines=["From the callus there are TWO paths:",
               "(i) ORGANOGENESIS: adding AUXINS and CYTOKININS",
               "to the medium induces the callus to produce",
               "ORGANS — roots and shoots.",
               "(ii) EMBRYOGENESIS: the explant may develop an",
               "embryonic callus, from which EMBRYOIDS are",
               "produced.",
               "Because these embryoids develop from SOMATIC",
               "(body) tissue and not from gametes, they are",
               "called SOMATIC EMBRYOS.",
               "Somatic embryos can be coated to make ARTIFICIAL",
               "SEEDS."],
        why="Which path the callus takes depends only on the balance of hormones in the medium, so one "
            "callus can be steered either way.",
        mistakes=["Confusing the two paths. ORGANOGENESIS gives organs; EMBRYOGENESIS gives embryoids.",
                  "Saying somatic embryos come from gametes. They come from SOMATIC tissue — that is "
                  "what the name means.",
                  "Leaving out artificial seeds. They are the practical product of somatic embryos."],
        tip="Somatic means body: these embryos had no gametes.",
        note="Both paths named and distinguished, plus artificial seeds."),
      S('s6_acclimatise','text','Acclimatisation',1,'Acclimatisation',
        lines=["6. ACCLIMATISATION AND TRANSFER TO POTS",
               "Plants raised in culture have grown in warm,",
               "humid, sterile conditions and are not ready for",
               "the open field.",
               "They are HARDENED OFF gradually — first in a",
               "glass house, then in pots, then in the field.",
               "Without acclimatisation the plantlets die when",
               "they are transferred."],
        why="A plantlet grown in a sealed tube has a thin cuticle and few functioning stomata, so it "
            "would dry out at once in open air.",
        mistakes=["Transferring straight to the field. The plantlets must be hardened off first.",
                  "Leaving out the reason. The plantlets die without it, and that is why the step exists."],
        tip="A plant raised in a jar cannot survive a field on its first day.",
        note="The gradual transfer and the reason. This is the last step of the technique half."),
      S('s7_diagram','diagram','Diagram — the tissue culture flow chart',0,None,
        figure=G.TISSUE_CULTURE,
        why="The flow chart shows what a list of six steps hides: the two paths out of the callus rejoin, "
            "so both organogenesis and embryogenesis end in plantlets.",
        mistakes=["Drawing one path out of the callus. There are TWO, and they rejoin at the plantlet stage.",
                  "Putting sterilisation after inoculation. The medium is sterilised BEFORE the explant "
                  "goes in.",
                  "Ending at 'plantlets'. Acclimatisation and transfer to the field are the last box."],
        tip="One chain, one fork, one merge, one field.",
        note="No diagram mark. Draw it if you have time: it is the fastest way to check all six steps "
             "are in your answer and in the right order."),
      S('s8_advantages','boxed_final','Advantages',2,'Advantages',
        lines=[{"text":"Fast, virus free, identical, and it works","style":"boxed"},
               {"text":"where sexual crossing cannot","style":"boxed"},
               "ADVANTAGES OF TISSUE CULTURE OVER CONVENTIONAL",
               "BREEDING:",
               "1. Many more plants can be produced in a SHORT",
               "TIME and in a small space (MICROPROPAGATION).",
               "2. VIRUS FREE plants can be raised from SHOOT",
               "TIP cultures, because meristems are free of virus.",
               "3. SEEDLESS plants can be multiplied, which",
               "sexual reproduction cannot do at all.",
               "4. FEMALE plants can be produced selectively.",
               "5. SOMATIC HYBRIDS can be raised where sexual",
               "hybridisation is impossible.",
               "6. Medicinal plants can be cultured to yield",
               "high value products of industrial and medicinal",
               "importance.",
               "7. The plants produced are SOMACLONES —",
               "genetically identical to the parent."],
        why="Each advantage comes from the same fact: tissue culture bypasses sexual reproduction "
            "entirely, so it is not limited by what can be crossed with what.",
        mistakes=["Giving fewer than five advantages. Two marks need a real list.",
                  "Saying tissue culture produces variation. It produces SOMACLONES — genetically "
                  "IDENTICAL plants.",
                  "Leaving out virus free plants. It is the advantage examiners ask about separately."],
        tip="No sex means no limits on what can be multiplied.",
        note="Two marks. At least five numbered advantages, each with its reason. Do not let the "
             "technique half eat the time this half needs.")]))

# ═══════════════════ VSAQ (Section A, 2 marks) ═══════════════════
def vs(slug, ref, gno, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, 47, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('hidden_hunger','vsaq1',125,
   "What is meant by 'hidden hunger'?",
   [("What it is",1),("Why it is called hidden",1)],
   "The word 'hidden' is the whole question: the deficiency is there but nothing shows. Say that.",
   [S('s1_what','text','What it is',1,'Definition',
      lines=["HIDDEN HUNGER is a situation in which a crop, or",
             "a person, NEEDS MORE of a given nutrient but shows",
             "NO deficiency symptoms yet."],
      why="A shortage that has not yet reached the level where symptoms appear is still a shortage, and "
          "it is already limiting growth.",
      mistakes=["Saying hidden hunger means having no food. It means a hidden NUTRIENT deficiency.",
                "Leaving out 'no symptoms'. That is what makes it hidden."],
      tip="The shortage is real; only the symptom is missing.",
      note="Definition with both halves: needs more, shows nothing."),
    S('s2_why','boxed_final','Why it is called hidden',1,'Why hidden',
      lines=[{"text":"No symptom, so nobody treats it","style":"boxed"},
             "Because there is no visible symptom, the shortage",
             "goes unnoticed and untreated.",
             "The crop yields less, or the person is less",
             "healthy, without anyone knowing why.",
             "BIOFORTIFICATION — breeding crops with more",
             "vitamins and minerals — is one answer to it."],
      why="An invisible deficiency is never corrected, which is why breeding the nutrient into the staple "
          "crop works better than trying to diagnose it.",
      mistakes=["Giving no consequence. The point is that it is not treated.",
                "Leaving out biofortification. It is the named remedy and links to the next question."],
      tip="What nobody sees, nobody fixes.",
      note="The consequence and the remedy. Six lines.")],
   years=[('ap',2019),('ap',2019)])

vs('semi_dwarf_rice','vsaq2',126,
   "Name two semi-dwarf varieties of rice developed in India.",
   [("The two varieties",1),("Why semi-dwarf",1)],
   "Two names, then one line on why a short plant yields more. That reason is the second mark.",
   [S('s1_names','text','The two varieties',1,'Names',
      lines=["Two semi-dwarf rice varieties developed in India:",
             "1. JAYA",
             "2. RATNA"],
      why="Both were bred in India during the green revolution, which is why they are the named pair for "
          "this question.",
      mistakes=["Naming Sonalika and Kalyan Sona. Those are WHEAT varieties.",
                "Naming basmati. Basmati is the patent case, not a semi-dwarf variety."],
      tip="Jaya and Ratna for rice; Sonalika and Kalyan Sona for wheat.",
      note="Both names. Three lines."),
    S('s2_why','boxed_final','Why semi-dwarf',1,'Reason',
      lines=[{"text":"A short stem can carry a heavy head of grain","style":"boxed"},
             "A semi-dwarf plant has a SHORT, STRONG stem.",
             "So it can carry a heavy head of grain without",
             "LODGING — falling over.",
             "That is what lets heavy fertiliser use turn into",
             "extra yield instead of a flattened field."],
      why="A tall plant given heavy fertiliser grows a head too heavy for its stem and falls over, so "
          "shortening the stem is what made high fertiliser use possible.",
      mistakes=["Saying semi-dwarf means low yielding. It is HIGH yielding, precisely because it does "
                "not lodge.",
                "Giving no reason. The reason is the second mark."],
      tip="Short stem, heavy head, no falling over.",
      note="Name lodging and explain the link to fertiliser. Six lines.")],
   years=[('ap',2020)])

vs('wheat_varieties','vsaq3',127,
   "Give two examples of wheat varieties introduced in India which are high yielding and disease resistant.",
   [("The two varieties",1),("What they achieved",1)],
   "Two names. Adding one line about the green revolution turns a bare list into an answer.",
   [S('s1_names','text','The two varieties',1,'Names',
      lines=["Two high yielding, disease resistant wheat",
             "varieties introduced in India:",
             "1. SONALIKA",
             "2. KALYAN SONA"],
      why="Both are semi-dwarf wheats derived from the Mexican varieties Borlaug developed, which is why "
          "they arrived together.",
      mistakes=["Naming Jaya and Ratna. Those are RICE varieties.",
                "Naming one variety. The question asks for two."],
      tip="Sonalika and Kalyan Sona are wheat; Jaya and Ratna are rice.",
      note="Both names. Four lines."),
    S('s2_achieved','boxed_final','What they achieved',1,'Result',
      lines=[{"text":"They are what the green revolution in wheat","style":"boxed"},
             {"text":"was made of","style":"boxed"},
             "Both are SEMI-DWARF and high yielding.",
             "They were introduced in the 1960s and raised",
             "Indian wheat production sharply.",
             "They are the varieties behind the GREEN",
             "REVOLUTION in wheat."],
      why="These varieties are the concrete content of the green revolution, so naming them and naming "
          "the revolution together shows the connection.",
      mistakes=["Giving the names with no context. The link to the green revolution is the second mark.",
                "Saying they were developed abroad and used unchanged. They were bred for Indian conditions."],
      tip="These two names ARE the wheat green revolution.",
      note="Semi-dwarf, high yielding, and the green revolution link.")],
   years=[('ap',2018)])

vs('scp_fungi','vsaq4',128,
   "Give two examples of fungi used in SCP production.",
   [("The two fungi",1),("What SCP is",1)],
   "Two names and the expansion of SCP. Both halves are short, so there is no excuse for missing either.",
   [S('s1_fungi','text','The two fungi',1,'Fungi',
      lines=["Two fungi used in single cell protein production:",
             "1. CANDIDA UTILIS, the torula yeast",
             "2. SACCHAROMYCES CEREVISIAE, the baker's yeast"],
      why="Both are yeasts that grow fast on cheap substrates, which is what a protein source has to do "
          "to be worth producing.",
      mistakes=["Naming a bacterium. The question asks for FUNGI.",
                "Naming Spirulina. Spirulina is a cyanobacterium, not a fungus."],
      tip="Two yeasts: torula and baker's.",
      note="Both scientific names with their common names."),
    S('s2_scp','boxed_final','What SCP is',1,'SCP',
      lines=[{"text":"Protein grown from microbes, as food","style":"boxed"},
             "SCP stands for SINGLE CELL PROTEIN.",
             "It is protein obtained from microbial biomass —",
             "algae, fungi or bacteria — grown on cheap",
             "substrates and used as food or animal feed.",
             "It is an alternative protein source for a growing",
             "population."],
      why="Microbes double in hours where a crop takes a season, so growing protein from them is far "
          "faster than growing it in a field.",
      mistakes=["Expanding SCP wrongly. It is SINGLE CELL PROTEIN.",
                "Saying SCP comes only from fungi. Algae and bacteria are used too."],
      tip="Protein from single cells, grown in a tank.",
      note="The expansion, the definition, and the purpose. Six lines.")],
   years=[('ap',2015),('ap',2017),('ap',2017),('ts',2017)])

vs('sugarcane_species','vsaq5',129,
   "Which two species of sugarcane were crossed for better yield?",
   [("The two species",1),("What each contributed",1)],
   "Two species names. Saying what each contributed is the second mark and it is the point of the cross.",
   [S('s1_names','text','The two species',1,'Species',
      lines=["SACCHARUM BARBERI and SACCHARUM OFFICINARUM were",
             "crossed to get a better yield."],
      why="Two species of the same genus can be crossed, which is what let breeders combine their "
          "separate advantages.",
      mistakes=["Naming a different genus. Both are SACCHARUM species.",
                "Naming one species. The question asks which TWO."],
      tip="Both are Saccharum: barberi and officinarum.",
      note="Both full names. Two lines."),
    S('s2_contributed','boxed_final','What each contributed',1,'Contributions',
      lines=[{"text":"North Indian hardiness plus tropical sugar","style":"boxed"},
             "Saccharum BARBERI grew in north India but had",
             "poor sugar content.",
             "Saccharum OFFICINARUM, the tropical canes, had",
             "thicker stems and HIGHER SUGAR content.",
             "The cross combined the two: high sugar canes that",
             "grow in the north."],
      why="Each parent supplied what the other lacked, which is the whole logic of a deliberate "
          "interspecific cross.",
      mistakes=["Saying both had high sugar. Only OFFICINARUM did.",
                "Giving the names with no reason for the cross. The reason is the second mark."],
      tip="One brought the climate, the other brought the sugar.",
      note="What each parent had and what the cross achieved.")])

vs('totipotency_and_explant','vsaq6',130,
   "Define totipotency and explant.",
   [("Totipotency",1),("Explant",1)],
   "Two definitions and they belong together: totipotency is why an explant works at all.",
   [S('s1_toti','text','Totipotency',1,'Totipotency',
      lines=["TOTIPOTENCY is the ability of a single cell to",
             "REGENERATE INTO A COMPLETE PLANT.",
             "Every living plant cell carries the whole genome,",
             "so in principle any of them can do it."],
      why="Each cell carries a complete copy of the genome, so nothing is missing that would stop it "
          "rebuilding the whole organism.",
      mistakes=["Saying totipotency means a cell can divide. It means it can become a WHOLE PLANT.",
                "Saying only meristem cells are totipotent. Any living plant cell is, in principle."],
      tip="One cell, one whole plant.",
      note="Definition plus the reason it is possible."),
    S('s2_explant','boxed_final','Explant',1,'Explant',
      lines=[{"text":"Totipotency is the property; the explant is","style":"boxed"},
             {"text":"the piece you start from","style":"boxed"},
             "An EXPLANT is any part of a plant that is taken",
             "out and grown in a test tube, under STERILE",
             "conditions, in a special NUTRIENT MEDIUM, to",
             "generate a whole plant.",
             "Examples: a piece of root, stem, leaf, or a shoot",
             "tip."],
      why="The explant is only useful because its cells are totipotent, which is why the two terms are "
          "always defined together.",
      mistakes=["Saying an explant is a seed. It is any living PART of a plant.",
                "Leaving out the sterile conditions. They are part of the definition."],
      tip="Totipotency is why it works; the explant is what you start with.",
      note="Definition with sterile conditions and the medium, plus examples.")])

vs('micropropagation_somaclones','vsaq7',131,
   "Define micropropagation and somaclones.",
   [("Micropropagation",1),("Somaclones",1)],
   "Two definitions. The word to get right in the second is IDENTICAL — somaclones are not variants.",
   [S('s1_micro','text','Micropropagation',1,'Micropropagation',
      lines=["MICROPROPAGATION is the technique of producing a",
             "LARGE NUMBER of plants in a VERY SHORT TIME and",
             "in a LIMITED SPACE, using tissue culture.",
             "It uses somatic embryos or small explants."],
      why="Thousands of plants can be raised from one explant on a laboratory bench, which is what the "
          "micro in the name refers to.",
      mistakes=["Saying micropropagation means growing small plants. It means propagating from small "
                "pieces, in quantity.",
                "Leaving out the speed or the space. Both are part of the definition."],
      tip="Many plants, little time, little space.",
      note="All three features: number, time, space."),
    S('s2_somaclones','boxed_final','Somaclones',1,'Somaclones',
      lines=[{"text":"Somaclones are genetically IDENTICAL to the","style":"boxed"},
             {"text":"parent plant","style":"boxed"},
             "SOMACLONES are the plants grown through tissue",
             "culture that are GENETICALLY IDENTICAL to the",
             "original source plant.",
             "They are identical because they arise by MITOSIS",
             "from somatic tissue, with no fusion of gametes."],
      why="Mitosis copies the genome exactly and no gametes are involved, so there is nothing in the "
          "process that could produce variation.",
      mistakes=["Saying somaclones show variation. They are genetically IDENTICAL. (Somaclonal VARIATION "
                "is a separate, rarer phenomenon.)",
                "Leaving out the reason. Mitosis with no gametes is why they are identical."],
      tip="Mitosis only, so no variation.",
      note="Definition plus the mitotic reason. Six lines.")])

vs('germplasm_collection','vsaq8',132,
   "What is meant by germplasm collection?",
   [("Definition",1),("Why it matters",1)],
   "A definition to write almost word for word. 'All the diverse alleles for all genes' is the phrase.",
   [S('s1_define','text','Germplasm collection defined',1,'Definition',
      lines=["A GERMPLASM COLLECTION is the entire collection of",
             "plants or seeds having ALL THE DIVERSE ALLELES",
             "for ALL GENES in a given crop.",
             "It includes wild relatives, landraces and modern",
             "varieties."],
      why="A breeder can only work with alleles that exist somewhere, so the collection is the whole "
          "pool of what is possible.",
      mistakes=["Saying it is a collection of the best varieties. It is a collection of ALL the diversity.",
                "Leaving out wild relatives. They carry most of the useful disease resistance genes."],
      tip="Everything, not just the best.",
      note="The full definition plus what it includes."),
    S('s2_why','boxed_final','Why it matters',1,'Importance',
      lines=[{"text":"You can only breed with alleles somebody has","style":"boxed"},
             {"text":"already collected","style":"boxed"},
             "It is a PRE-REQUISITE for any breeding programme:",
             "the first of the five steps in releasing a new",
             "variety.",
             "An allele that is not in the collection cannot be",
             "bred into a crop, and once a wild population is",
             "lost its alleles are gone for good."],
      why="Extinction is irreversible, so a wild relative lost today removes options from every future "
          "breeding programme.",
      mistakes=["Giving no significance. The second mark is for why it matters.",
                "Saying collections can be rebuilt later. Once a wild population is lost, its alleles "
                "are lost."],
      tip="Lose the wild relative and you lose the allele for ever.",
      note="Its place in breeding, and why loss is permanent.")],
   years=[('ts',2015)])

vs('biofortification','vsaq9',133,
   "What is meant by biofortification?",
   [("Definition",1),("Examples",1)],
   "Definition plus at least two named examples. Atlas 66 wheat and golden rice are the safe pair.",
   [S('s1_define','text','Biofortification defined',1,'Definition',
      lines=["BIOFORTIFICATION is the breeding of crops with",
             "HIGHER LEVELS of vitamins and minerals, or higher",
             "protein or healthier fats, in order to improve",
             "PUBLIC HEALTH."],
      why="Improving the nutritional value of the staple crop reaches everyone who already eats it, with "
          "no change in diet or behaviour needed.",
      mistakes=["Saying biofortification means adding vitamins to food after harvest. It is BRED INTO "
                "the crop.",
                "Leaving out public health. That is the purpose."],
      tip="Put the nutrient in the crop, not in a pill.",
      note="Definition with all the nutrient types and the purpose."),
    S('s2_examples','boxed_final','Examples',1,'Examples',
      lines=[{"text":"Atlas 66 wheat, golden rice, vitamin-enriched","style":"boxed"},
             {"text":"carrots and bitter gourd","style":"boxed"},
             "Examples:",
             "ATLAS 66 wheat has a high PROTEIN content.",
             "GOLDEN RICE contains beta-carotene, which the body",
             "turns into VITAMIN A.",
             "Vitamin A enriched CARROTS and vitamin C enriched",
             "BITTER GOURD."],
      why="Each example fortifies a crop people already eat every day, which is what makes the approach "
          "work at scale.",
      mistakes=["Naming one example. The book gives four.",
                "Saying Atlas 66 is a rice variety. Atlas 66 is WHEAT."],
      tip="Wheat for protein, rice for vitamin A.",
      note="At least three named examples with the nutrient each supplies.")])

vs('virus_free_plants','vsaq10',134,
   "Which part of the plant is best suited for making virus-free plants and why?",
   [("The part",1),("The reason",1)],
   "Meristem is the answer and the reason is that it divides too fast for the virus to keep up. Both "
   "halves in four lines.",
   [S('s1_part','text','The part',1,'Part',
      lines=["The APICAL and AXILLARY MERISTEMS are best suited",
             "for making virus-free plants.",
             "A SHOOT TIP culture is the standard method."],
      why="Even in a plant that is systemically infected, the meristem itself is usually free of virus, "
          "which is why it is the part to culture.",
      mistakes=["Naming the leaf or the root. It is the MERISTEM — the apical or axillary one.",
                "Not naming shoot tip culture. It is the named technique."],
      tip="Take the very tip, where the virus has not reached.",
      note="Both meristems named and the technique. Three lines."),
    S('s2_reason','boxed_final','The reason',1,'Reason',
      lines=[{"text":"Meristem cells divide faster than the virus","style":"boxed"},
             {"text":"can spread into them","style":"boxed"},
             "Meristematic regions show ACTIVE, RAPID CELL",
             "DIVISION.",
             "The cells divide faster than the virus can move",
             "into them, and meristems have no vascular",
             "connection for the virus to travel along.",
             "So the meristem cells are NOT INFECTED, and a",
             "plant raised from them is virus free."],
      why="A virus spreads mainly through the vascular tissue, and a meristem has none yet — so it stays "
          "ahead of the infection.",
      mistakes=["Saying the meristem kills the virus. It simply outgrows it and is never infected.",
                "Giving the part with no reason. The question says 'and why'."],
      tip="The tip grows away from the infection faster than it can follow.",
      note="Both reasons: the speed of division and the missing vascular connection.")],
   years=[('ts',2016),('ts',2019)])

main(C, U)
