# -*- coding: utf-8 -*-
"""Unit 7 — Bacteria. Book VSAQ ch.15 (p.41). Globals 72-81.
The blue print gives Bacteria 2 marks — one VSAQ — so this unit is VSAQ only and the book
sources no SAQ or LAQ for it. None is invented."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main

U = 7
C = []


def vs(slug, ref, gno, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, 41, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('occurrence_of_microorganisms','vsaq1',72,
   "Write briefly on the occurrence of micro organisms.",
   [("Where they occur",1),("What that means",1)],
   "The word to reach for is omnipresent. Then give the extremes — that is what shows the range.",
   [S('s1_where','text','Where they occur',1,'Occurrence',
      lines=["Micro organisms such as bacteria and viruses occur",
             "in ALL climatic conditions.",
             "They are found in soil, in water, in air, and",
             "inside the bodies of other organisms.",
             "They live in hot springs, in deserts, in deep",
             "oceans and under snow."],
      why="Naming the extremes rather than the ordinary places is what shows the range is genuinely "
          "everywhere and not just everywhere convenient.",
      mistakes=["Saying microbes live only in warm, wet places. They live in hot springs AND under snow.",
                "Listing habitats without any extreme. The extremes are what make the answer."],
      tip="Hot springs to snow: nowhere is ruled out.",
      note="Habitats plus at least two extremes. Five lines."),
    S('s2_meaning','boxed_final','What that means',1,'Omnipresent',
      lines=[{"text":"Micro organisms are omnipresent","style":"boxed"},
             "Because they occur everywhere, micro organisms",
             "are said to be OMNIPRESENT.",
             "This is why sterilisation is needed before any",
             "culture work."],
      why="If microbes are everywhere then any surface or medium is already contaminated, which is why "
          "sterilisation comes first in every technique in this book.",
      mistakes=["Leaving the word omnipresent out. It is the term the question is asking for.",
                "Giving no consequence. The link to sterilisation makes the fact useful."],
      tip="Everywhere means every culture starts contaminated.",
      note="Name the term, then one line on why it matters.")],
   years=[('ts',2017)])

vs('microbiology_definition','vsaq2',73,
   "Define Microbiology.",
   [("Definition",1),("What it covers",1)],
   "A definition question with a list attached. Name at least three groups of organisms.",
   [S('s1_define','text','Microbiology defined',1,'Definition',
      lines=["MICROBIOLOGY is the branch of biological science",
             "that deals with MICRO ORGANISMS — organisms too",
             "small to be seen with the unaided eye."],
      why="The subject is defined by the size of what it studies rather than by any one group, which is "
          "why it covers organisms as different as bacteria and protozoans.",
      mistakes=["Saying microbiology is the study of bacteria only. It covers viruses and protozoans too.",
                "Leaving out the size. Being too small to see is what puts an organism in this subject."],
      tip="One subject, defined by size and not by group.",
      note="Definition with the size criterion in it. Three lines."),
    S('s2_covers','boxed_final','What it covers',1,'Scope',
      lines=[{"text":"Bacteria, viruses, fungi and protozoans","style":"boxed"},
             "It includes the study of BACTERIA, VIRUSES,",
             "FUNGI, ALGAE and PROTOZOANS.",
             "Louis Pasteur and Robert Koch are regarded as",
             "the founders of microbiology."],
      why="The groups listed have nothing in common but their size, which is exactly the point the "
          "definition already made.",
      mistakes=["Naming one group. The list is the second mark.",
                "Naming no founder. Pasteur and Koch are worth one line."],
      tip="Nothing in common but being small.",
      note="Name the groups, then the founders. Four lines.")])

vs('ecoli_in_intestine','vsaq3',74,
   "Name the bacteria which is a common inhabitant of the human intestine. How is it used in biotechnology?",
   [("The bacterium",1),("Its use",1)],
   "Escherichia coli is the answer to both halves, but the second half needs the WORD 'vector' or "
   "'host', not just the name again.",
   [S('s1_name','text','The bacterium',1,'Name',
      lines=["ESCHERICHIA COLI (E. coli) is a common inhabitant",
             "of the human intestine.",
             "It lives harmlessly in the large intestine and",
             "helps in the production of some vitamins."],
      why="A bacterium that already lives safely in people is easy and cheap to grow, which is part of "
          "why it became the standard laboratory organism.",
      mistakes=["Spelling it Escherichia coly. The species is Escherichia COLI.",
                "Saying it is always harmful. Most strains are harmless residents."],
      tip="A gut resident that became the laboratory workhorse.",
      note="Full name, location, and one line on what it does there."),
    S('s2_use','boxed_final','Its use',1,'Use',
      lines=[{"text":"The standard HOST in rDNA technology","style":"boxed"},
             "E. coli is used as the HOST ORGANISM in",
             "recombinant DNA technology.",
             "Its plasmids, such as pBR322, are used as CLONING",
             "VECTORS.",
             "It multiplies quickly, so a cloned gene is copied",
             "many times in a few hours."],
      why="A host that divides every twenty minutes turns one recombinant cell into millions overnight, "
          "which is what makes gene cloning practical.",
      mistakes=["Saying E. coli is itself a plasmid. It is a BACTERIUM; its plasmids are the vectors.",
                "Giving the name without any use. The second half is a whole mark."],
      tip="The bacterium is the host; its plasmid is the vector.",
      note="Say host, say vector, and say why speed matters. Do not merge the two roles.")])

vs('pleomorphic_bacteria','vsaq4',75,
   "What are pleomorphic bacteria? Give an example.",
   [("Definition",1),("Example",1)],
   "Definition plus one named genus. Acetobacter is the book's example and the safest to write.",
   [S('s1_define','text','Pleomorphic bacteria defined',1,'Definition',
      lines=["PLEOMORPHIC bacteria are bacteria that can CHANGE",
             "THEIR SHAPE, depending on the environmental",
             "conditions and the nutrition available."],
      why="Most bacteria hold one shape for life, so the ones that do not need a name of their own.",
      mistakes=["Saying pleomorphic means many species. Pleo-morphic means many SHAPES.",
                "Leaving out the cause. The shape changes with conditions and nutrition."],
      tip="Pleo means many, morph means shape.",
      note="Definition with both causes named. Three lines."),
    S('s2_example','boxed_final','Example',1,'Example',
      lines=[{"text":"Acetobacter is pleomorphic","style":"boxed"},
             "Example: ACETOBACTER.",
             "Ordinary bacteria keep one fixed shape — coccus,",
             "bacillus, vibrio or spirillum — throughout life."],
      why="Setting the example against the fixed shapes makes clear what is unusual about it.",
      mistakes=["Naming no example. The question asks for one.",
                "Naming a virus. The question is about BACTERIA."],
      tip="Acetobacter is the one that will not hold a shape.",
      note="One named example plus the contrast with fixed-shape bacteria.")],
   years=[('ts',2018),('ts',2020),('ap',2017)])

vs('sex_pilus','vsaq5',76,
   "What is sex pilus? What is its function?",
   [("What it is",1),("Its function",1)],
   "Name the two cell types, F+ and F−. Those two symbols carry the second mark almost by themselves.",
   [S('s1_what','text','What a sex pilus is',1,'Structure',
      lines=["A SEX PILUS is a hollow tube on the surface of a",
             "bacterium, used in conjugation.",
             "It is also called a conjugation tube.",
             "It is produced by the DONOR cell, which is called",
             "the F+ cell."],
      why="Only the donor makes the tube, so the pilus is what marks which of the two cells is the donor.",
      mistakes=["Saying both cells make a pilus. Only the DONOR (F+) makes it.",
                "Calling it a flagellum. A flagellum moves the cell; a pilus joins two cells."],
      tip="Only the giver builds the bridge.",
      note="Structure, alternative name, which cell makes it."),
    S('s2_function','boxed_final','Its function',1,'Function',
      lines=[{"text":"It carries DNA from the F+ cell to the F− cell","style":"boxed"},
             "The F+ donor cell uses the pilus to make contact",
             "with the recipient, the F− cell.",
             "Genetic material then passes through the tube",
             "from donor to recipient.",
             "This process is called CONJUGATION."],
      why="Bacteria have no gametes, so a physical tube is the only way one cell can hand genetic "
          "material to another.",
      mistakes=["Saying DNA passes both ways. It passes from F+ TO F− only.",
                "Not naming conjugation. The process name is part of the mark."],
      tip="F plus gives, F minus receives.",
      note="Name both cell types, the direction, and the process.")])

vs('genophore','vsaq6',77,
   "What is a genophore?",
   [("What it is",1),("How it differs from a chromosome",1)],
   "The second half is the mark most answers miss: say NAKED, meaning no histone proteins.",
   [S('s1_what','text','What a genophore is',1,'Definition',
      lines=["The GENOPHORE is the main genetic material of a",
             "bacterium.",
             "It is also called the bacterial chromosome or the",
             "nucleoid.",
             "It is a single, circular, double stranded DNA",
             "molecule."],
      why="Circular and single is the shape that lets a bacterium copy its whole genome from one starting "
          "point, unlike the many linear chromosomes of a eukaryote.",
      mistakes=["Saying the genophore is linear. It is CIRCULAR.",
                "Confusing it with a plasmid. The genophore is the MAIN genetic material; a plasmid is extra."],
      tip="One circle of DNA, and it is the main one.",
      note="Definition, alternative names, and the shape. Four lines."),
    S('s2_naked','boxed_final','How it differs from a chromosome',1,'Difference',
      lines=[{"text":"Naked DNA: no histones, no nuclear membrane","style":"boxed"},
             "The genophore is NAKED — it carries no histone",
             "proteins.",
             "It is not enclosed by a nuclear membrane.",
             "A eukaryotic chromosome has histones and lies",
             "inside a nucleus."],
      why="Bacteria have no nucleus and no histones, so their genetic material has to be described "
          "differently from a true chromosome.",
      mistakes=["Saying the genophore has histones. It is NAKED DNA.",
                "Saying it lies in a nucleus. Bacteria have no nuclear membrane."],
      tip="No histones and no nucleus: that is why it is not called a chromosome.",
      note="Both differences named. The word naked is the shortest way to earn this.")],
   years=[('ap',2019),('ap',2022)])

vs('plasmid','vsaq7',78,
   "What is a plasmid? What is its significance?",
   [("What it is",1),("Its significance",1)],
   "Four adjectives make this definition: self-duplicating, naked, circular, double stranded. Then the "
   "use in one line.",
   [S('s1_what','text','What a plasmid is',1,'Definition',
      lines=["A PLASMID is a small, SELF-DUPLICATING, NAKED,",
             "CIRCULAR, DOUBLE STRANDED DNA fragment found in",
             "bacteria, separate from the genophore."],
      why="Self-duplicating is the load-bearing word: because a plasmid copies itself independently, "
          "anything inserted into it is copied too.",
      mistakes=["Saying a plasmid is the main bacterial chromosome. That is the GENOPHORE.",
                "Leaving out 'self-duplicating'. It is what makes a plasmid useful as a vector."],
      tip="A small extra circle that copies itself.",
      note="All four adjectives plus 'separate from the genophore'."),
    S('s2_sig','boxed_final','Its significance',1,'Significance',
      lines=[{"text":"Plasmids are the cloning vectors of","style":"boxed"},
             {"text":"genetic engineering","style":"boxed"},
             "Plasmids are used as VECTORS in genetic",
             "engineering.",
             "A gene inserted into a plasmid is carried into a",
             "host cell and copied every time the plasmid",
             "copies itself.",
             "Plasmids also carry antibiotic resistance genes."],
      why="A vector has to get into a cell and then multiply there, and a self-copying circle does both "
          "without any help.",
      mistakes=["Giving only the definition. The significance is a whole mark.",
                "Saying plasmids are essential to the bacterium. They are EXTRA; the cell survives without them."],
      tip="Put a gene in the circle and the circle copies it for you.",
      note="Name the vector role and one more use. Four lines.")],
   years=[('ts',2017),('ts',2019)])

vs('conjugation','vsaq8',79,
   "What is conjugation? Who discovered it and in which organism?",
   [("What it is",1),("Who and where",1)],
   "Three facts: the process, two names, one organism. Lederberg and Tatum, in E. coli.",
   [S('s1_what','text','What conjugation is',1,'Definition',
      lines=["CONJUGATION is the transfer of genetic material",
             "between two bacterial cells through DIRECT",
             "CONTACT, using a sex pilus."],
      why="Direct contact is what separates conjugation from the other two transfers: transformation "
          "needs no contact and transduction uses a virus.",
      mistakes=["Saying conjugation needs a virus. That is TRANSDUCTION.",
                "Leaving out 'direct contact'. It is what defines conjugation."],
      tip="Cell to cell, touching: that is conjugation.",
      note="Definition with 'direct contact' and the pilus. Three lines."),
    S('s2_who','boxed_final','Who and where',1,'Discovery',
      lines=[{"text":"Lederberg and Tatum, in Escherichia coli","style":"boxed"},
             "It was discovered by LEDERBERG and TATUM.",
             "They worked on ESCHERICHIA COLI."],
      why="The same Lederberg also worked on transduction with Zinder, which is why the two discoveries "
          "are so easily confused.",
      mistakes=["Naming Griffith. Griffith discovered TRANSFORMATION.",
                "Naming Salmonella. That is the transduction organism; conjugation was in E. coli."],
      tip="Lederberg and Tatum in E. coli; Lederberg and Zinder in Salmonella.",
      note="Both names and the organism. Three lines.")],
   years=[('ap',2017),('ap',2019)])

vs('transformation','vsaq9',80,
   "What is transformation? Who discovered it and in which organism?",
   [("What it is",1),("Who and where",1)],
   "The one of the three transfers that needs NO contact and NO virus. Say that and the definition is done.",
   [S('s1_what','text','What transformation is',1,'Definition',
      lines=["TRANSFORMATION is the uptake of NAKED DNA",
             "fragments by a bacterium directly from its",
             "surroundings.",
             "No contact with another cell and no virus is",
             "needed."],
      why="Free DNA lying in the surroundings can be absorbed by a competent cell, which is why this is "
          "the only transfer that needs no second living partner.",
      mistakes=["Saying transformation needs a pilus. That is CONJUGATION.",
                "Saying the DNA comes from a virus. That is TRANSDUCTION."],
      tip="Loose DNA picked up from outside: nothing else involved.",
      note="Definition plus the two things it does NOT need."),
    S('s2_who','boxed_final','Who and where',1,'Discovery',
      lines=[{"text":"Griffith, in Streptococcus pneumoniae","style":"boxed"},
             "It was discovered by FREDERICK GRIFFITH in 1928.",
             "He worked on STREPTOCOCCUS PNEUMONIAE, the",
             "bacterium that causes pneumonia.",
             "His experiment is the one that first pointed to",
             "DNA as the genetic material."],
      why="Griffith's transformation experiment is the starting point of the whole molecular biology "
          "chapter, which is why the same name appears there too.",
      mistakes=["Naming Lederberg. Lederberg discovered CONJUGATION and TRANSDUCTION.",
                "Naming E. coli. Griffith worked on Streptococcus pneumoniae."],
      tip="Griffith, pneumonia, 1928.",
      note="Name, organism, and the link forward to the DNA chapter.")],
   years=[('ap',2020)])

vs('transduction','vsaq10',81,
   "What is transduction? Who discovered it and in which organism?",
   [("What it is",1),("Who and where",1)],
   "The third transfer, and the one that uses a virus. Lederberg and Zinder, in Salmonella typhimurium.",
   [S('s1_what','text','What transduction is',1,'Definition',
      lines=["TRANSDUCTION is the transfer of genetic material",
             "from one bacterium to another THROUGH A",
             "BACTERIOPHAGE, that is, through a virus."],
      why="The virus does the carrying, so no contact between the two bacteria is needed at any point.",
      mistakes=["Writing 'bacterio phase'. The carrier is a BACTERIOPHAGE, a virus.",
                "Saying the two cells touch. In transduction they never need to meet."],
      tip="The virus is the postman.",
      note="Definition naming the bacteriophage. Three lines."),
    S('s2_who','boxed_final','Who and where',1,'Discovery',
      lines=[{"text":"Lederberg and Zinder, in Salmonella","style":"boxed"},
             {"text":"typhimurium","style":"boxed"},
             "It was discovered by LEDERBERG and ZINDER.",
             "They worked on SALMONELLA TYPHIMURIUM.",
             "The three transfers together are conjugation,",
             "transformation and transduction."],
      why="Listing all three at the end is the fastest check that the right names have gone with the "
          "right process, because Lederberg appears in two of them.",
      mistakes=["Naming Tatum. Tatum worked with Lederberg on CONJUGATION, not transduction.",
                "Naming E. coli. Transduction was shown in Salmonella typhimurium."],
      tip="Zinder goes with Salmonella; Tatum goes with E. coli.",
      note="Both names, the organism, and the three-way list as a check.")],
   years=[('ap',2016),('ap',2018)])

main(C, U)
