# -*- coding: utf-8 -*-
"""Unit 1 — Transport in Plants. Book SAQ ch.4 (pp.21-22) + VSAQ ch.13 (pp.38-39).
Globals 7-12 (SAQ) and 49-62 (VSAQ). 20 cards."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main
import figs_u1

U = 1
C = []

# ═══════════════════ SAQ (Section B, 4 marks) ═══════════════════

C.append(Q(U, 'water_potential', 'SAQ', 'saq1', 7, 21,
    "Define and explain water potential.",
    years=[('ts',2019),('ap',2018),('ap',2019)],
    split=[("Definition and unit",1),("Solute potential",1),("Pressure potential",1),("The equation",1)],
    insider="Two components, two signs. Solute potential is ALWAYS negative and pressure potential is "
            "positive — an answer that gives both values without their signs loses the easiest mark here.",
    steps=[
      S('s1_define','text','Water potential defined',1,'Definition',
        lines=["Water potential (psi w) measures the tendency",
               "of water to move from one part of a plant to",
               "another.",
               "It drives diffusion, osmosis and absorption.",
               "It is measured in pascals (Pa).",
               "Pure water at standard temperature and",
               "pressure has a water potential of ZERO."],
        why="Pure water is fixed at zero so every real solution can be compared against one agreed "
            "starting point; that is what makes water potential a scale and not just a description.",
        mistakes=["Giving no unit. Water potential is measured in pascals (Pa).",
                  "Saying pure water has the highest positive value. It is set at ZERO, and every "
                  "solution falls BELOW it."],
        tip="Pure water is the zero mark on the scale; adding anything to it can only push the value down.",
        note="Definition, what it drives, unit, and the zero reference. Six or seven lines."),
      S('s2_solute','text','Solute potential',1,'Solute potential',
        lines=["Water potential has two components.",
               "1. Solute potential (psi s):",
               "When a solute is dissolved in pure water, the",
               "concentration of free water molecules falls.",
               "So the water potential also falls.",
               "This fall is called solute potential.",
               "It is ALWAYS negative."],
        why="Dissolving anything reduces the free water available, so the value can only drop — which is "
            "why solute potential can never be a positive number.",
        mistakes=["Writing solute potential as positive. It is always NEGATIVE.",
                  "Confusing it with concentration. It is the FALL in water potential the solute causes."],
        tip="Solute pulls the value down: add solute, subtract potential.",
        note="Name it, say what causes it, and state the sign. The sign is the mark."),
      S('s3_pressure','text','Pressure potential',1,'Pressure potential',
        lines=["2. Pressure potential (psi p):",
               "When water enters a plant cell, it presses",
               "against the cell wall.",
               "The cell becomes turgid (swollen).",
               "This rise in water potential is called",
               "pressure potential.",
               "It is always positive.",
               "It is seen in the ascent of water through the",
               "stem."],
        why="The wall pushes back on the water inside, and that push adds to the potential — the opposite "
            "sign to solute potential, which is why the two are listed as a pair.",
        mistakes=["Writing pressure potential as negative. It is POSITIVE.",
                  "Leaving out turgidity. The pressure comes from the swollen cell pushing on its wall."],
        tip="Pressure pushes the value up; solute pulls it down. Opposite causes, opposite signs.",
        note="Name it, the cause, the sign, and one place it is seen. Do not skip 'turgid'."),
      S('s4_equation','boxed_final','The equation',1,'Equation',
        lines=[{"text":"psi w  =  psi s  +  psi p","style":"boxed"},
               "Total water potential is the sum of solute",
               "potential and pressure potential.",
               "Because psi s is negative and psi p is",
               "positive, the two work against each other."],
        why="The equation is the whole answer in one line: it says the two components are added, and the "
            "signs already established decide which way each one pulls.",
        mistakes=["Writing the two terms as a subtraction. They are ADDED; the minus is already inside psi s.",
                  "Leaving the equation out. It is the line the examiner scans for."],
        tip="One sum, two signs: a negative solute term plus a positive pressure term.",
        note="Box the equation and say the two terms are added. Four lines is enough.")]))

C.append(Q(U, 'plasmolysis', 'SAQ', 'saq2', 8, 21,
    "What is meant by plasmolysis? How is it practically useful to us?",
    years=[('ap',2016)],
    split=[("Definition",1),("The solution that causes it",1),("What happens in the cell",1),("Practical uses",1)],
    insider="The question has two halves and the second one is a single line of examples — write the "
            "uses even if the explanation runs short, because they are a whole mark on their own.",
    steps=[
      S('s1_define','text','Plasmolysis defined',1,'Definition',
        lines=["Plasmolysis is the shrinkage of the protoplast",
               "of a cell caused by loss of water and turgor.",
               "The cell is then said to be plasmolysed."],
        why="The definition names the part that moves — the protoplast, not the cell — and that "
            "distinction carries the rest of the answer.",
        mistakes=["Saying the CELL shrinks. The rigid cell wall holds its shape; the PROTOPLAST inside shrinks.",
                  "Leaving out 'loss of turgor'. Turgor loss is half the definition."],
        tip="The wall stays, the bag inside pulls away.",
        note="One clean definition sentence plus the name of the state. Three lines."),
      S('s2_solution','text','The solution that causes it',1,'Cause',
        lines=["Plasmolysis happens when a plant cell is placed",
               "in a HYPERTONIC solution.",
               "A hypertonic solution is more concentrated than",
               "the cell sap.",
               "So water molecules inside the cell move OUT",
               "into the solution."],
        why="Water leaves because the outside solution has the lower water potential, which is the same "
            "rule stated in the water potential answer applied to one cell.",
        mistakes=["Writing hypotonic. A hypotonic solution makes the cell swell, not shrink.",
                  "Saying the solute enters the cell. It is WATER that leaves."],
        tip="Hyper means more outside, so water goes out.",
        note="Name the solution type, define it, and say which way water moves."),
      S('s3_cell','text','What happens in the cell',1,'In the cell',
        lines=["As water leaves, the cell membrane pulls away",
               "from the cell wall.",
               "The protoplast separates from the wall and",
               "shrinks towards the centre.",
               "The space between the wall and the membrane",
               "fills with the outside solution."],
        why="Naming the two structures that separate is what shows the examiner the mechanism was "
            "understood rather than the word memorised.",
        mistakes=["Saying the cell wall shrinks. The wall is rigid and does not move.",
                  "Stopping at 'water leaves'. The separation of membrane from wall IS plasmolysis."],
        tip="Membrane in, wall stays put: the gap between them is the proof.",
        note="Three or four lines naming membrane, wall and the gap that opens between them."),
      S('s4_uses','boxed_final','Practical uses',1,'Uses',
        lines=[{"text":"Plasmolysis preserves food by drawing","style":"boxed"},
               {"text":"water out of spoilage microbes","style":"boxed"},
               "1. Salting of pickles.",
               "2. Preservation of fish, meat and prawns.",
               "Salt or sugar makes the surroundings",
               "hypertonic, so microbes lose water and cannot",
               "grow."],
        why="The uses all work the same way: raise the outside concentration and the microbes plasmolyse, "
            "so the same mechanism answers the second half of the question.",
        mistakes=["Listing uses without saying WHY they work. The reason is the mark.",
                  "Giving only one example. The question asks how it is useful, so give at least two."],
        tip="Salt and sugar preserve by making the outside stronger than the microbe inside.",
        note="Two named examples plus one line of reason. This half is a full mark.")]))

C.append(Q(U, 'ascent_of_sap', 'SAQ', 'saq3', 9, 21,
    "How does ascent of sap occur in tall trees?",
    years=[('ap',2019),('ap',2015),('ts',2015)],
    split=[("Definition",1),("Cohesion and adhesion",1),("Transpiration pull",1),("Why it works in tall trees",1)],
    insider="Three named physical properties carry three of the four marks. Name all three even if you "
            "explain only briefly — a missing name cannot be recovered by a longer sentence about the others.",
    steps=[
      S('s1_define','text','Ascent of sap defined',1,'Definition',
        lines=["Ascent of sap is the upward movement of water",
               "from the roots to the leaves.",
               "It moves through the XYLEM.",
               "It moves against the force of gravity."],
        why="Naming the tissue and the direction fixes what has to be explained: an upward flow with no "
            "pump, which is why the rest of the answer is about physical properties of water.",
        mistakes=["Writing phloem. Water rises through the XYLEM; phloem carries food.",
                  "Leaving out 'against gravity'. That is the difficulty the answer has to explain."],
        tip="Sap goes up the xylem; food goes down the phloem.",
        note="Definition, tissue, and the direction. Three or four lines."),
      S('s2_cohesion','text','Cohesion and adhesion',1,'Cohesion, adhesion',
        lines=["The ascent depends on three physical",
               "properties of water.",
               "1. Cohesion: the mutual attraction between",
               "water molecules. It holds the water column",
               "together as one unbroken thread.",
               "2. Adhesion: the attraction of water molecules",
               "to polar surfaces, such as the walls of the",
               "tracheal elements."],
        why="Cohesion holds the column together and adhesion holds it against the wall, so between them "
            "the water in a tall xylem vessel behaves like a single rope rather than loose drops.",
        mistakes=["Swapping the two. COHESION is water to water; ADHESION is water to the wall.",
                  "Defining only one. The mark asks for both names with their meanings."],
        tip="Cohesion is water holding water; adhesion is water holding the wall.",
        note="Both names, both meanings, one line each. Do not merge them into one sentence."),
      S('s3_pull','text','Transpiration pull',1,'Transpiration pull',
        lines=["3. Transpiration pull:",
               "Water evaporates from the leaf surface during",
               "transpiration.",
               "This creates a tension at the top of the water",
               "column.",
               "The tension pulls the whole column upward.",
               "Transpiration pull is the driving force for the",
               "upward movement of water."],
        why="Transpiration is what actually supplies the force; cohesion and adhesion only make it "
            "possible for that force to be felt all the way down to the root.",
        mistakes=["Calling it a push from the roots. Root pressure is small; the main force is a PULL from the top.",
                  "Leaving out evaporation. The pull begins when water leaves the leaf."],
        tip="The leaf pulls, the column follows; nothing pushes from below.",
        note="Evaporation, tension, pull. Name it as the driving force in the last line."),
      S('s4_tall','boxed_final','Why it works in tall trees',1,'In tall trees',
        lines=[{"text":"High tensile strength plus high capillarity","style":"boxed"},
               "Together these properties give water a high",
               "tensile strength and high capillarity.",
               "So the water column does not break even in a",
               "very tall tree.",
               "Photosynthesis needs a steady water supply,",
               "and the xylem from root to leaf delivers it."],
        why="The question says TALL trees, so the answer has to close on the reason height is not a "
            "problem: the column has enough tensile strength to hold together over that distance.",
        mistakes=["Not answering the 'tall' part. The last mark is for why the column does not break.",
                  "Writing that a pump lifts the water. There is no pump in a plant."],
        tip="An unbroken rope of water can be pulled from the top however long it is.",
        note="Close on tensile strength and capillarity. This is the mark for the word 'tall'.")]))

C.append(Q(U, 'transpiration_necessary_evil', 'SAQ', 'saq4', 10, 22,
    "\"Transpiration is a necessary evil\". Explain.",
    years=[('ap',2017),('ap',2017),('ap',2020),('ap',2022),('ts',2016)],
    split=[("Why it is necessary",2),("Why it is harmful",2)],
    insider="Two halves, two marks each. An answer that lists five advantages and no disadvantage scores "
            "half. Split the page down the middle before you start writing.",
    steps=[
      S('s1_advantages','text','Why transpiration is necessary',2,'Advantages',
        lines=["Transpiration has both benefits and harms, so",
               "it is called a necessary evil.",
               "ADVANTAGES:",
               "1. It creates the transpiration pull that",
               "absorbs and transports water in the plant.",
               "2. It supplies water for photosynthesis.",
               "3. It carries minerals from the soil to every",
               "part of the plant.",
               "4. It cools the leaf surface by evaporative",
               "cooling.",
               "5. It keeps cells turgid, so the plant holds",
               "its shape."],
        why="Each advantage is a job no other process in the plant does, which is what makes the loss of "
            "water unavoidable rather than merely tolerated.",
        mistakes=["Listing fewer than four advantages. Two marks need a full list.",
                  "Writing only 'it cools the plant'. The transport of water and minerals is the bigger point."],
        tip="Pull, supply, carry, cool, hold: five jobs one evaporation does.",
        note="At least four numbered advantages. Two marks sit here, so do not rush this half."),
      S('s2_disadvantages','boxed_final','Why transpiration is harmful',2,'Disadvantages',
        lines=[{"text":"Necessary for transport, harmful in excess","style":"boxed"},
               "DISADVANTAGES:",
               "1. Excessive transpiration makes cells flaccid.",
               "2. Flaccid cells slow the growth of the plant.",
               "3. A large amount of water is lost as vapour.",
               "4. Photosynthesis is then limited by the",
               "shortage of water.",
               "So transpiration is necessary for transport but",
               "harmful when it is excessive."],
        why="The harm is not transpiration itself but its excess, and saying so is what turns two lists "
            "into the single sentence the question actually asks for.",
        mistakes=["Giving no disadvantages at all. That is two marks lost.",
                  "Writing that transpiration is useless. The question calls it NECESSARY as well as evil."],
        tip="Evil only in excess: a little is transport, too much is drought.",
        note="At least three disadvantages, then one closing line that joins both halves.")]))

C.append(Q(U, 'transpiration_photosynthesis_compromise', 'SAQ', 'saq5', 11, 22,
    "Transpiration and Photosynthesis — a compromise. Explain.",
    years=[('ts',2019)],
    split=[("The plant's need for water",1),("Why stomata must open",1),("What opening costs",1),("The compromise",1)],
    insider="This is a chain of four steps, not a list. Write them in order — need water, open stomata, "
            "lose water, pull more water — because the last mark is for closing the loop.",
    steps=[
      S('s1_need','text','The plant needs water',1,'Need for water',
        lines=["Photosynthesis needs a continuous supply of",
               "water.",
               "A plant needs water all the time, and never",
               "stops needing it."],
        why="The whole compromise starts from a demand that cannot be switched off, so the plant has no "
            "option of simply closing up and waiting.",
        mistakes=["Saying water is needed only sometimes. The need is continuous.",
                  "Starting the answer at the stomata. The need for water comes first in the chain."],
        tip="The demand never stops, so the trade never stops either.",
        note="Two or three lines. Establish the demand before anything opens."),
      S('s2_stomata','text','Why stomata must open',1,'Stomata open',
        lines=["To photosynthesise, the plant must take in",
               "carbon dioxide from the air.",
               "So the plant opens its stomata to exchange",
               "gases."],
        why="Carbon dioxide can only enter through an open pore, so the stoma has to be open for "
            "photosynthesis to happen at all.",
        mistakes=["Saying stomata open to release oxygen. They open mainly to take in carbon dioxide.",
                  "Leaving out gas exchange. That is the reason the pore opens."],
        tip="No open pore, no carbon dioxide, no sugar.",
        note="Two lines: what has to come in, and what has to open to let it in."),
      S('s3_cost','text','What opening costs',1,'Water is lost',
        lines=["An open stoma also lets water escape by",
               "evaporation.",
               "This is transpiration.",
               "The loss of water pulls more water up from the",
               "soil, through the xylem."],
        why="The same open pore that admits carbon dioxide lets water out, so the cost and the benefit "
            "cannot be separated — they share one opening.",
        mistakes=["Treating the water loss as an accident. It is unavoidable once the pore is open.",
                  "Not linking the loss to the upward pull. That link is what makes the loss useful."],
        tip="One door, two directions: carbon dioxide in, water vapour out.",
        note="Three lines. End on the pull, because the next step uses it."),
      S('s4_compromise','boxed_final','The compromise',1,'Compromise',
        lines=[{"text":"One open pore serves both processes","style":"boxed"},
               "The water pulled up by transpiration is the",
               "same water photosynthesis uses.",
               "So the plant trades water loss for carbon gain.",
               "Transpiration and photosynthesis are therefore",
               "a compromise with each other."],
        why="The loop closes because the water lost is what drags up the water used, so the cost pays for "
            "part of the benefit rather than just cancelling it.",
        mistakes=["Ending without the word compromise. The question asks for it by name.",
                  "Saying the two processes are unrelated. They share the same open stoma."],
        tip="What the plant loses through the pore is what draws up what it needs.",
        note="Close the loop and use the word 'compromise'. Four lines.")]))

C.append(Q(U, 'stomata_structure_mechanism', 'SAQ', 'saq6', 12, 22,
    "Explain the structure and mechanism of opening and closing of stomata.",
    years=[('ts',2015)],
    split=[("Structure of the stoma",1),("Opening: potassium moves in",1),("Closing: potassium moves out",1),("Water stress and succulents",1)],
    insider="Name the theory. \"Levitt's potassium ion pump theory\" is worth writing in the first line, "
            "and an answer that describes the ion movement without naming the theory reads as guesswork.",
    steps=[
      S('s1_structure','text','Structure of the stoma',1,'Structure',
        lines=["A stoma is a pore in the leaf epidermis.",
               "It is bounded by two GUARD CELLS.",
               "In dicots the guard cells are bean shaped; in",
               "monocots they are dumb-bell shaped.",
               "The wall facing the pore (the inner wall) is",
               "THICK and inelastic.",
               "The outer wall is THIN and elastic.",
               "Guard cells contain chloroplasts.",
               "Around them lie the subsidiary cells."],
        why="The two walls differ in thickness, and that difference alone decides that a swollen guard "
            "cell must bow outward and open the pore rather than swell evenly.",
        mistakes=["Saying both walls are the same. The inner wall is THICK, the outer wall is THIN.",
                  "Leaving out the guard cells. The pore is defined by the pair that surrounds it."],
        tip="Thick inside, thin outside: the thin side stretches, so the pair bends apart.",
        note="Pore, guard cells, the two wall thicknesses, subsidiary cells. The wall difference is the mark."),
      S('s2_opening','text','Opening: potassium moves in',1,'Opening',
        lines=["Levitt's potassium ion pump theory explains",
               "the mechanism.",
               "In light, K+ ions move INTO the guard cells",
               "from the subsidiary cells.",
               "H+ ions are pumped OUT, so the pH of the guard",
               "cells RISES.",
               "Cl- ions enter passively along with K+.",
               "The water potential of the guard cells falls.",
               "Water enters and the guard cells become turgid.",
               "The thin outer walls stretch, the pair bows",
               "apart, and the pore OPENS."],
        why="Ions come in first and water follows them, so the order of the answer has to be ions, then "
            "water potential, then water, then shape.",
        mistakes=["Saying water enters first. The IONS move first and the water follows them.",
                  "Writing that the pH falls during opening. Protons leave, so the pH RISES."],
        tip="Potassium in, protons out, water follows, pore opens.",
        note="Name the theory, then the ion order. Do not let water move before the ions."),
      S('s3_closing','text','Closing: potassium moves out',1,'Closing',
        lines=["At night, in the absence of light, K+ and Cl-",
               "ions move OUT of the guard cells.",
               "The water potential of the guard cells rises.",
               "Water moves out and the guard cells lose",
               "turgor.",
               "The pair straightens and the pore CLOSES.",
               "The pH of the guard cells falls."],
        why="Closing is the same sequence run backwards, so it is checked by whether every arrow in the "
            "opening step has been reversed.",
        mistakes=["Describing closing as a separate mechanism. It is the reverse of opening.",
                  "Forgetting the pH. It falls on closing, having risen on opening."],
        tip="Run every arrow backwards and the pore shuts.",
        note="The reverse of the opening step, in the same order. Six lines."),
      S('s4_stress','boxed_final','Water stress and succulents',1,'ABA, succulents',
        lines=[{"text":"ABA shuts the pore under water stress","style":"boxed"},
               "Under water stress, abscisic acid (ABA) drives",
               "K+ ions OUT of the guard cells, so the stomata",
               "close.",
               "In succulent plants the pattern is reversed.",
               "Organic acids collect at night and make the",
               "guard cells turgid, so the stomata open at",
               "NIGHT and close by day."],
        why="ABA and the succulents are the two cases where the light rule does not hold, so they are "
            "what the last mark tests.",
        mistakes=["Leaving out ABA. It is the named hormone for water stress and a whole mark.",
                  "Saying succulents open by day. They open at NIGHT, which is how they save water."],
        tip="Dry day shuts the pore; a succulent opens it at night instead.",
        note="Two special cases: ABA under stress, and the reversed succulent pattern."),
      S('s5_diagram','diagram','Diagram — stomatal opening and closing',0,None,
        figure=figs_u1.STOMATA,
        why="Drawing the open pair beside the closed pair shows in one picture that the same two cells "
            "make both states, and that the arrows simply reverse.",
        mistakes=["Drawing the guard cells as identical rectangles. The pore-side wall must look thicker.",
                  "Drawing the same arrow directions on both panels. They are opposites.",
                  "Drawing the open pore as a gap between straight cells. The pair BOWS apart."],
        tip="Two panels, one pair of cells, every arrow reversed.",
        note="The question says explain, not draw, so there is NO diagram mark; all four marks sit on the "
             "written steps. Draw it anyway if time allows: the two panels replace a paragraph of words.")]))

# ═══════════════════ VSAQ (Section A, 2 marks) ═══════════════════

C.append(Q(U, 'porins', 'VSAQ', 'vsaq1', 49, 38,
    "What are porins? What role do they play in diffusion?",
    years=[('ap',2017),('ap',2019),('ts',2018),('ts',2020)],
    split=[("What porins are",1),("Their role",1)],
    insider="Two halves, one mark each. The second half must say 'without using energy' or the answer "
            "reads as active transport.",
    steps=[
      S('s1_what','text','What porins are',1,'What they are',
        lines=["Porins are proteins that form large pores in",
               "a membrane.",
               "They are found in the outer membranes of",
               "plastids, mitochondria and some bacteria."],
        why="Naming them as pore-forming proteins is what separates them from carrier proteins, which "
            "move one molecule at a time.",
        mistakes=["Calling porins a kind of lipid. They are PROTEINS.",
                  "Saying they are found in every membrane. They sit in OUTER membranes of plastids, "
                  "mitochondria and some bacteria."],
        tip="Porin makes a pore: the name is the structure.",
        note="Two lines: what they are made of, and where they sit."),
      S('s2_role','boxed_final','Their role in diffusion',1,'Role',
        lines=[{"text":"A big open pore, so no energy is needed","style":"boxed"},
               "The pore is large enough to let even small",
               "sized proteins pass through.",
               "Molecules move through it by simple diffusion,",
               "down the concentration gradient, without using",
               "energy."],
        why="The pore is permanently open, so movement through it needs no carrier and no ATP — which is "
            "exactly what makes it diffusion and not transport.",
        mistakes=["Saying porins pump molecules across. Nothing is pumped; molecules DIFFUSE through.",
                  "Leaving out the size. The point of a porin is that even small proteins fit."],
        tip="A hole does not push; things fall through it on their own.",
        note="Say what fits through and say no energy is used. Both halves of the mark.")]))

C.append(Q(U, 'diffusion_definition_factors', 'VSAQ', 'vsaq2', 50, 38,
    "Define diffusion. Write any two factors that affect it.",
    split=[("Definition",1),("Two factors",1)],
    insider="The question asks for exactly two factors. Give three if you like, but the definition must "
            "be there first — it is the mark students most often skip in a hurry.",
    steps=[
      S('s1_define','text','Diffusion defined',1,'Definition',
        lines=["Diffusion is the movement of molecules from a",
               "region of higher concentration to a region of",
               "lower concentration.",
               "It is a passive process and needs no energy."],
        why="Diffusion is defined by the direction of movement, so the definition has to name both ends "
            "of the gradient rather than just say molecules move.",
        mistakes=["Saying molecules move from low to high. That is the opposite of diffusion.",
                  "Calling it an active process. Diffusion is PASSIVE."],
        tip="Downhill only: high to low, no energy spent.",
        note="Direction of movement plus the word passive. Four lines."),
      S('s2_factors','boxed_final','Two factors that affect it',1,'Factors',
        lines=[{"text":"Temperature and concentration gradient","style":"boxed"},
               "1. Temperature: a higher temperature makes",
               "molecules move faster, so diffusion is faster.",
               "2. Concentration gradient: a steeper gradient",
               "makes diffusion faster.",
               "Pressure also affects the rate."],
        why="Both named factors change the same thing — how fast molecules cross the gradient — so each "
            "one is stated with its effect on the rate.",
        mistakes=["Naming a factor without saying what it does to the rate. The effect is the mark.",
                  "Naming only one factor. The question asks for two."],
        tip="Hotter and steeper both mean faster.",
        note="Two named factors, each with its effect on the rate.")]))

C.append(Q(U, 'osmosis_vs_diffusion', 'VSAQ', 'vsaq3', 51, 38,
    "Differentiate osmosis from diffusion.",
    years=[('ts',2016),('ts',2019),('ap',2017)],
    split=[("Osmosis",1),("Diffusion",1)],
    insider="Three points separate them: what moves, which way, and whether a membrane is needed. The "
            "membrane is the one examiners look for.",
    steps=[
      S('s1_osmosis','text','Osmosis',1,'Osmosis',
        lines=["Osmosis is the movement of SOLVENT (water)",
               "molecules from a lower concentrated solution",
               "to a higher concentrated solution.",
               "It REQUIRES a semipermeable membrane."],
        why="Osmosis is defined by the solvent moving toward the stronger solution, which is only "
            "possible when a membrane holds the solute back.",
        mistakes=["Saying the solute moves. In osmosis the SOLVENT (water) moves.",
                  "Leaving out the membrane. Osmosis cannot happen without a semipermeable membrane."],
        tip="Osmosis moves water toward the stronger side, and only through a membrane.",
        note="What moves, which way, and the membrane. Four lines."),
      S('s2_diffusion','boxed_final','Diffusion',1,'Diffusion',
        lines=[{"text":"Osmosis needs a membrane; diffusion does not","style":"boxed"},
               "Diffusion is the movement of SOLUTE molecules",
               "from a higher concentrated solution to a lower",
               "concentrated solution.",
               "It need NOT require a membrane."],
        why="Diffusion runs the opposite way with the opposite particle and needs no barrier, so every "
            "part of the osmosis line is reversed here.",
        mistakes=["Writing that diffusion also needs a membrane. It does not.",
                  "Giving the same direction for both. Osmosis is low to high solution; diffusion is high to low."],
        tip="Water to the strong side with a membrane; solute to the weak side without one.",
        note="Mirror the osmosis lines point for point. The contrast is the mark.")]))

C.append(Q(U, 'apoplast_and_symplast', 'VSAQ', 'vsaq4', 52, 38,
    "What are apoplast and symplast?",
    years=[('ap',2015),('ap',2016),('ap',2020),('ts',2017),('ts',2022)],
    split=[("Apoplast",1),("Symplast",1)],
    insider="Each half needs three facts: the path, whether membranes are crossed, and the speed. Miss "
            "the membrane and the two halves stop being different.",
    steps=[
      S('s1_apoplast','text','Apoplast',1,'Apoplast',
        lines=["The apoplast is the path of water transport in",
               "a plant that does NOT cross any membrane.",
               "Water moves through cell walls and the spaces",
               "between cells.",
               "It is a FAST process."],
        why="Nothing has to be crossed, so the water is never slowed by a membrane — which is the whole "
            "reason this route is the fast one.",
        mistakes=["Saying the apoplast crosses membranes. It does NOT; that is the symplast.",
                  "Calling the apoplast slow. It is the FASTER of the two paths."],
        tip="Apoplast is the outside lane: walls and gaps, no membranes, fast.",
        note="Path, no membrane, fast. Four lines."),
      S('s2_symplast','boxed_final','Symplast',1,'Symplast',
        lines=[{"text":"Apoplast goes around cells, symplast through","style":"boxed"},
               "The symplast is the path of water transport in",
               "a plant that DOES cross membranes.",
               "Water moves through the living cytoplasm, from",
               "cell to cell through plasmodesmata.",
               "It is a SLOW process."],
        why="Every membrane crossed costs time, so the route through the living cytoplasm is necessarily "
            "the slower one.",
        mistakes=["Saying the symplast is the wall route. That is the apoplast.",
                  "Leaving out the speed. Fast against slow is half the contrast."],
        tip="Symplast is the inside lane: through the living cells, so slow.",
        note="Mirror the apoplast lines: path, membranes crossed, slow.")]))

C.append(Q(U, 'guttation_vs_transpiration', 'VSAQ', 'vsaq5', 53, 38,
    "How does guttation differ from transpiration?",
    years=[('ts',2017),('ts',2019),('ap',2016)],
    split=[("Guttation",1),("Transpiration",1)],
    insider="Three contrasts: the form the water takes, the time of day, and whether the plant controls "
            "it. Liquid against vapour is the one to write first.",
    steps=[
      S('s1_guttation','text','Guttation',1,'Guttation',
        lines=["In guttation, water is lost from the leaves in",
               "the form of liquid WATER DROPLETS.",
               "It occurs at NIGHT.",
               "It is an UNCONTROLLED process."],
        why="Guttation pushes liquid water out through fixed pores that cannot close, which is why it is "
            "both liquid and uncontrolled.",
        mistakes=["Saying guttation releases vapour. It releases liquid DROPLETS.",
                  "Saying it happens by day. Guttation occurs at NIGHT."],
        tip="Guttation is drops at night; transpiration is vapour by day.",
        note="Form, time, control. Three lines and the contrast is complete."),
      S('s2_transpiration','boxed_final','Transpiration',1,'Transpiration',
        lines=[{"text":"Drops at night against vapour by day","style":"boxed"},
               "In transpiration, water is lost from the leaves",
               "in the form of WATER VAPOUR.",
               "It occurs during the DAY.",
               "It is a CONTROLLED process, because the",
               "stomata can close."],
        why="Transpiration goes through stomata, and because a stoma can shut, the plant has control "
            "over it in a way it never has over guttation.",
        mistakes=["Calling transpiration uncontrolled. The stomata can close, so it IS controlled.",
                  "Giving only the form and not the time. All three contrasts carry the mark."],
        tip="A pore that can shut is a process that can be controlled.",
        note="Mirror all three points, and say WHY it is controlled.")]))

C.append(Q(U, 'ascent_physical_factors', 'VSAQ', 'vsaq6', 54, 39,
    "What are the physical factors responsible for the ascent of sap through xylem in plants?",
    years=[('ts',2017)],
    split=[("Cohesion and adhesion",1),("Transpiration pull",1)],
    insider="Three named factors for two marks, so every name counts. Write the name first and the "
            "one-line meaning after it.",
    steps=[
      S('s1_cohesion','text','Cohesion and adhesion',1,'Two attractions',
        lines=["1. Cohesion: the mutual attraction BETWEEN",
               "water molecules.",
               "2. Adhesion: the attraction of water molecules",
               "TO the surface of the tracheal elements."],
        why="Both are attractions, and naming what each attracts to what is the only way to keep them "
            "apart in an answer this short.",
        mistakes=["Swapping them. Cohesion is water to water; adhesion is water to the wall.",
                  "Writing the names with no meaning. The one-line meaning is what earns the mark."],
        tip="Cohesion: water to water. Adhesion: water to wall.",
        note="Both names with a one-line meaning each. Four lines."),
      S('s2_pull','boxed_final','Transpiration pull',1,'Transpiration pull',
        lines=[{"text":"Two attractions hold the column, one pull moves it","style":"boxed"},
               "3. Transpiration pull: the driving force for",
               "the upward movement of water, created when",
               "water evaporates from the leaf."],
        why="Cohesion and adhesion only hold the column together; transpiration pull is the one factor "
            "that actually supplies force, so it is named last and separately.",
        mistakes=["Naming only two factors. There are THREE.",
                  "Calling transpiration pull a push. It is a PULL from the leaf end."],
        tip="Two hold, one pulls.",
        note="Name the third factor and say it is the driving force.")]))

C.append(Q(U, 'imbibition_pea_wheat', 'VSAQ', 'vsaq7', 55, 39,
    "Compare imbibing capacities of pea and wheat seeds.",
    years=[('ts',2016)],
    split=[("Which imbibes more",1),("The reason",1)],
    insider="One mark for the comparison and one for the reason. An answer that says pea swells more and "
            "stops there scores half.",
    steps=[
      S('s1_which','text','Which imbibes more',1,'Comparison',
        lines=["Pea seeds are PROTEINACEOUS.",
               "Wheat seeds are STARCHY.",
               "Pea seeds imbibe more water and swell more",
               "than wheat seeds."],
        why="The comparison follows from what each seed is made of, so naming the two storage materials "
            "before the result makes the reason almost automatic.",
        mistakes=["Saying wheat imbibes more. PEA imbibes more.",
                  "Not naming what each seed stores. Protein against starch is what the answer rests on."],
        tip="Pea stores protein and drinks more; wheat stores starch and drinks less.",
        note="Name both storage materials, then state which swells more."),
      S('s2_reason','boxed_final','The reason',1,'Reason',
        lines=[{"text":"Protein imbibes more than carbohydrate","style":"boxed"},
               "The imbibing capacity of proteins is greater",
               "than that of carbohydrates.",
               "So a protein rich seed takes up more water."],
        why="The rule is about the materials and not the seeds, which is why it also predicts the answer "
            "for any other pair of seeds.",
        mistakes=["Giving no reason. The reason is a whole mark on a two-mark question.",
                  "Saying pea seeds are bigger. Size is not the reason; the storage material is."],
        tip="It is the protein doing the drinking, not the pea.",
        note="State the rule about protein against carbohydrate, not about the seeds.")]))

C.append(Q(U, 'source_and_sink', 'VSAQ', 'vsaq8', 56, 39,
    "With reference to transportation of food within a plant, what are source and sink?",
    years=[('ts',2019)],
    split=[("Source",1),("Sink",1)],
    insider="Each half needs a definition AND an example. The examples are short, so there is no reason "
            "to leave them out.",
    steps=[
      S('s1_source','text','Source',1,'Source',
        lines=["The source is the place in the plant body",
               "where food material is PREPARED.",
               "Example: a leaf."],
        why="Food is made where photosynthesis happens, so the leaf is the source by definition rather "
            "than by convention.",
        mistakes=["Calling the root the source. The root usually stores food, so it is a sink.",
                  "Leaving out the example. The example is part of the mark."],
        tip="Source makes it, sink keeps it.",
        note="Definition plus one example. Three lines."),
      S('s2_sink','boxed_final','Sink',1,'Sink',
        lines=[{"text":"Source makes food; sink stores it","style":"boxed"},
               "The sink is the place in the plant body where",
               "food material is STORED or used.",
               "Examples: fruits and buds.",
               "Source and sink can change with the season, so",
               "phloem transport runs in both directions."],
        why="A part can be a source in one season and a sink in another, which is why phloem transport "
            "is not fixed to one direction the way xylem transport is.",
        mistakes=["Naming only one example. The question uses the plural.",
                  "Saying phloem always moves food downward. It moves toward whichever part is the sink."],
        tip="Whichever end is storing today is the sink today.",
        note="Definition, examples, and one line on why the roles can swap.")]))

C.append(Q(U, 'transpiration_at_night', 'VSAQ', 'vsaq9', 57, 39,
    "Does transpiration occur at night? Give an example.",
    split=[("The answer",1),("The example",1)],
    insider="A one-word question with a one-word answer, so the whole risk is forgetting the example. "
            "Write the plant names first if you are short of time.",
    steps=[
      S('s1_answer','text','The answer',1,'Yes',
        lines=["Yes, transpiration occurs at night.",
               "Some plants keep their stomata open at night",
               "and closed during the day."],
        why="The general rule that stomata open in light has exceptions, and this question exists to "
            "check that the exception is known.",
        mistakes=["Answering simply 'no'. Transpiration DOES occur at night in some plants.",
                  "Giving the answer without any reason. One line on the open stomata makes it an answer."],
        tip="The rule has exceptions, and the exceptions open at night.",
        note="Yes, plus one line of reason. Do not answer with a bare yes."),
      S('s2_example','boxed_final','The example',1,'Example',
        lines=[{"text":"Bryophyllum and cacti open at night","style":"boxed"},
               "Examples: Bryophyllum and cacti.",
               "These are succulent plants. Opening at night",
               "and closing by day saves water in dry places."],
        why="Both examples are succulents from dry places, so the night opening is a water-saving pattern "
            "rather than a random exception.",
        mistakes=["Giving no example. The question asks for one by name.",
                  "Naming an ordinary mesophyte. The examples must be succulents."],
        tip="Dry-place plants trade daylight for water.",
        note="Name both plants and give the one-line reason. Four lines.")]))

C.append(Q(U, 'guard_cell_ph', 'VSAQ', 'vsaq10', 58, 39,
    "Compare the pH of guard cells during the opening and closing of stomata.",
    split=[("During opening",1),("During closing",1)],
    insider="Two lines, opposite directions. Get the opening direction right and the closing one follows.",
    steps=[
      S('s1_opening','text','During opening',1,'Opening',
        lines=["The pH of the guard cells INCREASES during the",
               "opening of stomata.",
               "H+ ions are pumped out as K+ ions enter, so the",
               "guard cells become less acidic."],
        why="Protons leaving is what makes the inside less acidic, so the pH rise is a direct consequence "
            "of the ion pump that opens the pore.",
        mistakes=["Saying the pH falls on opening. It RISES.",
                  "Giving the direction with no cause. The proton efflux is what makes it rise."],
        tip="Protons out means acid out means pH up.",
        note="Direction plus the ion that causes it. Three lines."),
      S('s2_closing','boxed_final','During closing',1,'Closing',
        lines=[{"text":"pH up on opening, down on closing","style":"boxed"},
               "The pH of the guard cells DECREASES during the",
               "closing of stomata.",
               "H+ ions return as K+ ions leave."],
        why="Closing reverses the same pump, so the pH must move the other way.",
        mistakes=["Giving the same direction for both. They are opposites.",
                  "Confusing pH with concentration of potassium. Potassium leaves; the pH falls."],
        tip="Reverse the pump and you reverse the pH.",
        note="The mirror of the opening line. Three lines.")]))

C.append(Q(U, 'c4_water_efficiency', 'VSAQ', 'vsaq11', 59, 39,
    "In the wake of transpirational loss, why are C4 plants more efficient than C3 plants?",
    split=[("Less water lost",1),("The measured comparison",1)],
    insider="The number is the answer. \"Half as much water for the same carbon dioxide fixed\" is what "
            "makes this an efficiency answer rather than a general statement.",
    steps=[
      S('s1_less','text','Less water lost',1,'Water saved',
        lines=["C4 plants minimise water loss.",
               "So they can fix more carbon dioxide than C3",
               "plants for the same amount of water."],
        why="Efficiency here means carbon gained per unit of water lost, so the answer has to compare the "
            "two quantities and not just say C4 plants are better.",
        mistakes=["Saying C4 plants photosynthesise faster. The question is about WATER, not speed.",
                  "Giving no comparison at all. The word 'efficient' asks for a ratio."],
        tip="Efficiency is carbon gained for water spent.",
        note="Say what is saved and what is gained. Three lines."),
      S('s2_number','boxed_final','The measured comparison',1,'The figure',
        lines=[{"text":"Half the water for the same carbon fixed","style":"boxed"},
               "A C4 plant loses only HALF as much water as a",
               "C3 plant for the same amount of carbon dioxide",
               "fixed."],
        why="A single figure settles the comparison, and it is the line an examiner can mark without "
            "reading the rest of the answer.",
        mistakes=["Leaving the number out. 'Half' is the mark.",
                  "Writing twice as much. C4 plants lose HALF, not double."],
        tip="Same carbon, half the water.",
        note="One line with the figure in it. Box it.")]))

C.append(Q(U, 'transport_saturation', 'VSAQ', 'vsaq12', 60, 39,
    "What is meant by transport saturation? How does it influence facilitated diffusion?",
    split=[("Transport saturation",1),("Its effect on facilitated diffusion",1)],
    note_extra="BOOK ERROR, corrected on this card: the book answers the second half with \"Transport "
               "saturation INCREASES the facilitated diffusion.\" That is backwards. Once every carrier "
               "protein is occupied the rate cannot rise any further — saturation sets a CEILING, and "
               "that ceiling is exactly what distinguishes facilitated diffusion from simple diffusion, "
               "whose rate keeps climbing with concentration. The card writes it correctly and records "
               "the book's printed position here.",
    insider="This is the one question in the chapter where the guide's own answer is wrong. Saturation "
            "LIMITS the rate; it does not increase it. Write the ceiling.",
    steps=[
      S('s1_define','text','Transport saturation',1,'Definition',
        lines=["Facilitated diffusion uses protein transporters",
               "in the membrane.",
               "When ALL the transporters are occupied, the",
               "rate of transport reaches its maximum and",
               "cannot rise any further.",
               "This state is called transport saturation."],
        why="There is a fixed number of carrier proteins, so once each one is busy the membrane has no "
            "spare capacity left however much solute is added outside.",
        mistakes=["Saying saturation means transport has stopped. Transport is at its MAXIMUM, not zero.",
                  "Leaving out the transporters. The limit exists because their number is fixed."],
        tip="Every carrier busy means no room for one more.",
        note="Carriers, all occupied, maximum rate. The word 'all' is the mark."),
      S('s2_effect','boxed_final','Its effect on facilitated diffusion',1,'Effect',
        lines=[{"text":"Saturation LIMITS the rate; it is a ceiling","style":"boxed"},
               "Transport saturation sets an upper limit on",
               "facilitated diffusion.",
               "Beyond this point, raising the concentration",
               "outside does NOT raise the rate.",
               "Simple diffusion shows no such limit, so",
               "saturation is what tells the two apart."],
        why="Simple diffusion has no carriers to run out of, so a rate that stops climbing is direct "
            "evidence that carriers are involved.",
        mistakes=["Writing that saturation increases facilitated diffusion. It LIMITS it. The guide "
                  "prints the opposite; the ceiling is the correct answer.",
                  "Saying simple diffusion also saturates. It does not — it has no carriers."],
        tip="A full car park does not fill faster because more cars arrive.",
        note="State the ceiling, then contrast with simple diffusion. The contrast is why the "
             "question is asked.")]))

C.append(Q(U, 'aba_stomatal_closure', 'VSAQ', 'vsaq13', 61, 39,
    "How does ABA bring about the closure of stomata under water stress conditions?",
    years=[('ap',2020)],
    split=[("What ABA does",1),("Why the pore closes",1)],
    insider="One sentence answers this if it names the ion. \"Drives K+ out of the guard cells\" is the "
            "line the examiner is looking for.",
    steps=[
      S('s1_aba','text','What ABA does',1,'ABA acts',
        lines=["ABA is abscisic acid, the stress hormone of",
               "plants.",
               "Under water stress, ABA drives K+ ions OUT of",
               "the guard cells."],
        why="ABA acts on the same potassium pump that opens the pore in light, so a single hormone can "
            "override the light signal.",
        mistakes=["Saying ABA closes the pore directly. It acts through the K+ ions.",
                  "Naming the wrong ion. It is POTASSIUM (K+) that leaves."],
        tip="ABA pulls the potassium out, and the pore follows.",
        note="Name the hormone and the ion it moves. Three lines."),
      S('s2_close','boxed_final','Why the pore closes',1,'Closure',
        lines=[{"text":"Potassium out, water out, pore shut","style":"boxed"},
               "As K+ leaves, the water potential of the guard",
               "cells rises.",
               "Water moves out and the guard cells lose",
               "turgor.",
               "The pair straightens and the stomata close, so",
               "the plant saves water."],
        why="The chain from ion to water to turgor to shape is the same one that opens the pore, run in "
            "reverse — which is why only the first step needed a hormone.",
        mistakes=["Skipping straight from ABA to closure. The water potential and turgor steps are the mark.",
                  "Saying the guard cells become turgid. They LOSE turgor, which is why the pore shuts."],
        tip="Lose the water, lose the bend, lose the pore.",
        note="Four steps in order: ion, water potential, turgor, shape.")]))

C.append(Q(U, 'transpiration_vs_evaporation', 'VSAQ', 'vsaq14', 62, 39,
    "Compare transpiration and evaporation.",
    split=[("Transpiration",1),("Evaporation",1)],
    insider="Best written as a two-column table. Four contrasts fit: the surface, where it happens, what "
            "kind of process it is, and the speed.",
    steps=[
      S('s1_transpiration','text','Transpiration',1,'Transpiration',
        lines=["1. Transpiration is the loss of water from the",
               "LIVING tissues of the aerial parts of a plant.",
               "2. It happens within the plant.",
               "3. It is a physiological process.",
               "4. It is a SLOW process."],
        why="Transpiration is controlled by living stomata, so it is a physiological process and "
            "necessarily slower than plain evaporation from an open surface.",
        mistakes=["Saying transpiration happens from any surface. It happens from LIVING tissue only.",
                  "Calling it a physical process. It is PHYSIOLOGICAL, because the plant controls it."],
        tip="Living, inside, controlled, slow.",
        note="Four numbered points. Keep the numbering so the second column can mirror it."),
      S('s2_evaporation','boxed_final','Evaporation',1,'Evaporation',
        lines=[{"text":"Living and controlled against free and fast","style":"boxed"},
               "1. Evaporation is the loss of water from ANY",
               "free surface, living or non-living.",
               "2. It is a surface level process.",
               "3. It is a physical process.",
               "4. It is comparatively FAST."],
        why="Nothing living regulates evaporation, so it is faster and can happen anywhere water meets "
            "air — which is every contrast in one cause.",
        mistakes=["Saying evaporation happens only from non-living surfaces. It happens from ANY free surface.",
                  "Giving fewer than three contrasts. The comparison needs both columns filled."],
        tip="No living control means nothing to slow it down.",
        note="Mirror the four numbered points exactly. Same order, opposite content.")]))

main(C, U)
