# -*- coding: utf-8 -*-
"""Unit 10 — Molecular Basis of Inheritance. Book SAQ ch.11 (pp.33-34) + VSAQ ch.17
(pp.43-44). Globals 39-44 (SAQ) and 90-106 (VSAQ). The blue print gives this unit 8 marks
(2+2 VSAQ and one SAQ), the largest VSAQ share of any chapter."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main
import figs_u10 as G

U = 10
C = []

C.append(Q(U, 'griffith_transformation', 'SAQ', 'saq1', 39, 33,
    "Define transformation in Griffith's experiment. Discuss how it helps in the identification "
    "of DNA as genetic material.",
    split=[("What transformation is",1),("The two strains",1),("The four injections",1),("The conclusion",1)],
    insider="Four injections, four results. Set them out as four numbered lines — an examiner marking "
            "this looks for the fourth one, where the mice die.",
    steps=[
      S('s1_define','text','What transformation is',1,'Definition',
        lines=["TRANSFORMATION is the genetic alteration of a",
               "cell caused by taking up genetic material",
               "directly from its surroundings, through the",
               "cell membrane.",
               "Frederick Griffith showed it in 1928, working on",
               "STREPTOCOCCUS PNEUMONIAE, the bacterium that",
               "causes pneumonia."],
        why="Something has to physically pass from the dead cells into the living ones, and identifying "
            "what that something is became the whole question of the next twenty years.",
        mistakes=["Saying transformation needs contact between two live cells. That is CONJUGATION.",
                  "Naming the wrong organism. Griffith worked on Streptococcus pneumoniae."],
        tip="Something passes from the dead cells into the living ones.",
        note="Definition, the worker, the year, the organism. Seven lines."),
      S('s2_strains','text','The two strains',1,'Two strains',
        lines=["Griffith grew the bacterium on a culture medium",
               "and found TWO strains:",
               "1. S-type: forms SMOOTH colonies, HAS a capsule,",
               "   and is VIRULENT (it causes disease).",
               "2. R-type: forms ROUGH colonies, has NO capsule,",
               "   and is NON-VIRULENT."],
        why="The capsule is what makes the S strain deadly, and it is also what makes the two strains "
            "tell apart by eye — so one visible difference tracks one lethal one.",
        mistakes=["Saying R-type is virulent. S-type is the virulent one.",
                  "Leaving out the capsule. It is what makes S-type smooth and virulent."],
        tip="Smooth has a coat and kills; rough has none and does not.",
        note="Both strains with all three features each: colony, capsule, virulence."),
      S('s3_injections','text','The four injections',1,'The experiment',
        lines=["1. LIVE S-type injected: the mice got pneumonia",
               "   and DIED.",
               "2. LIVE R-type injected: the mice SURVIVED.",
               "3. HEAT-KILLED S-type injected: the mice",
               "   SURVIVED.",
               "4. HEAT-KILLED S-type MIXED with live R-type:",
               "   the mice DIED, and LIVE S-type bacteria were",
               "   recovered from their bodies."],
        why="Injections 2 and 3 are the controls: each alone is harmless, so only their combination can "
            "explain the death in injection 4.",
        mistakes=["Giving only the fourth injection. The first three are the controls that make it mean "
                  "something.",
                  "Forgetting that LIVE S-type was recovered from the dead mice. That recovery is the "
                  "whole result."],
        tip="Two harmless things mixed became deadly.",
        note="All four injections with their results. The recovery of live S-type is the key line."),
      S('s4_conclusion','boxed_final','The conclusion',1,'Conclusion',
        lines=[{"text":"Something from the dead S cells transformed the","style":"boxed"},
               {"text":"live R cells, and it was heritable","style":"boxed"},
               "Griffith concluded that the R-strain cells had",
               "been TRANSFORMED by something released from the",
               "heat-killed S-strain cells.",
               "He called it the TRANSFORMING PRINCIPLE.",
               "The transformed cells bred true, so the",
               "transferred material was the GENETIC material.",
               "Avery, MacLeod and McCarty later showed the",
               "transforming principle is DNA."],
        why="The transformed bacteria stayed S-type in every later generation, which is what shows the "
            "transferred material was genetic rather than a passing chemical effect.",
        mistakes=["Saying Griffith proved DNA is the genetic material. He did NOT — he showed a "
                  "transforming principle existed. Avery, MacLeod and McCarty identified it as DNA.",
                  "Leaving out the heritability. It is what makes it genetic."],
        tip="Griffith found the parcel; Avery opened it.",
        note="Name the transforming principle, say it was heritable, and credit the identification "
             "correctly. Getting that credit right is what the last mark is for.")]))

C.append(Q(U, 'rna_polymerases', 'SAQ', 'saq2', 40, 33,
    "How many types of RNA polymerases exist in cells? Write their names and functions.",
    years=[('ts',2017)],
    split=[("How many, and where",1),("RNA polymerase I",1),("RNA polymerase II",1),("RNA polymerase III",1)],
    insider="Three enzymes, three products. Write them as a three-row table if you can — it is faster "
            "and impossible to misread.",
    steps=[
      S('s1_how_many','text','How many, and where',1,'Three',
        lines=["In eukaryotic cells there are THREE types of",
               "RNA polymerase.",
               "All three are found in the NUCLEUS.",
               "Each one transcribes a different class of RNA.",
               "(In bacteria a SINGLE RNA polymerase makes all",
               "three kinds.)"],
        why="Eukaryotes divide the work between three enzymes where a bacterium uses one, which is the "
            "point the question is checking.",
        mistakes=["Saying there are three in bacteria. Bacteria have ONE; eukaryotes have three.",
                  "Saying they are in the cytoplasm. All three are in the NUCLEUS."],
        tip="Three in a eukaryote, one in a bacterium.",
        note="The number, the location, and the bacterial contrast."),
      S('s2_pol1','text','RNA polymerase I',1,'Pol I',
        lines=["RNA POLYMERASE I transcribes the ribosomal RNAs:",
               "28S rRNA, 18S rRNA and 5.8S rRNA.",
               "These are the RNAs that build the ribosome."],
        why="The three rRNAs it makes are needed in enormous quantity, which is why one enzyme is given "
            "over to them alone.",
        mistakes=["Saying pol I makes mRNA. That is pol II.",
                  "Leaving out the S numbers. 28S, 18S and 5.8S are what the mark is for."],
        tip="Pol one makes the ribosome's own RNA.",
        note="Name the three rRNAs with their S values. Three lines."),
      S('s3_pol2','text','RNA polymerase II',1,'Pol II',
        lines=["RNA POLYMERASE II transcribes the precursor of",
               "mRNA, which is called heterogeneous nuclear RNA",
               "(hnRNA).",
               "hnRNA is then processed — capped, tailed and",
               "spliced — to become mature mRNA."],
        why="Pol II makes the RNA that will be translated into protein, which is why it is the enzyme "
            "most questions about gene expression concern.",
        mistakes=["Saying pol II makes mRNA directly. It makes hnRNA, the PRECURSOR of mRNA.",
                  "Not expanding hnRNA. Heterogeneous nuclear RNA is the full name."],
        tip="Pol two makes the message, but only a rough draft of it.",
        note="Say precursor, expand hnRNA, and name the processing. Five lines."),
      S('s4_pol3','boxed_final','RNA polymerase III',1,'Pol III',
        lines=[{"text":"I: rRNA. II: hnRNA (mRNA precursor). III: tRNA","style":"boxed"},
               "RNA POLYMERASE III transcribes tRNA, 5S rRNA",
               "and the small nuclear RNAs (snRNAs).",
               "So the three enzymes between them make every",
               "kind of RNA the cell needs."],
        why="Between the three, every class of RNA is accounted for, which is the check that the answer "
            "is complete.",
        mistakes=["Giving pol III the 5.8S rRNA. Pol III makes the 5S rRNA; 5.8S belongs to pol I.",
                  "Leaving out snRNA. It is one of pol III's named products."],
        tip="Pol three makes the small ones: tRNA, 5S and snRNA.",
        note="All three products, then one closing line. Watch 5S against 5.8S.")]))

C.append(Q(U, 'lac_operon_diagram', 'SAQ', 'saq3', 41, 33,
    "Draw the schematic diagrammatic presentation of the lac operon.",
    years=[('ap',2015),('ap',2019),('ts',2016),('ts',2022)],
    split=[("The gene map in order",1),("The repressed state",1),
           ("The induced state",1),("All labels correct",1)],
    note_extra="BOOK ERROR, corrected on this card: the guide's p.33 figure labels BOTH panels \"In "
               "absence of inducer\". The second panel is the INDUCED state — its own content proves "
               "it, since lac mRNA is being transcribed, the three enzymes are being made and the "
               "repressor is drawn inactivated. The card labels it \"In the presence of inducer\". "
               "The guide also prints the gene map as \"p i p o z y a\"; the card uses the standard "
               "NCERT order i-p-o-z-y-a.\n"
               "This is the second of only TWO questions in the paper whose marks sit on the drawing "
               "(the other is the chloroplast, global 17): the book prints no written answer here.",
    insider="Both panels or nothing. A single panel of the repressed operon answers half the question, "
            "because the whole point of an operon is that it switches.",
    steps=[
      S('s1_diagram','diagram','Schematic of the lac operon',4,'Both panels, labelled',
        figure=G.LAC_OPERON,
        why="An operon is a SWITCH, so the drawing has to show both positions of the switch; one panel "
            "shows a gene map, two panels show how it is regulated.",
        mistakes=["Drawing one panel only. The question is about regulation, so both the repressed and "
                  "the induced state are needed.",
                  "Putting the genes in the wrong order. It is i, p, o, z, y, a — regulator, promoter, "
                  "operator, then the three structural genes.",
                  "Labelling both panels 'absence of inducer'. The guide does exactly this; the second "
                  "panel is the PRESENCE of inducer."],
        tip="Two panels: repressor on the operator, then repressor knocked off it.",
        note="All four marks are here. Draw both panels the same width and directly under each other, "
             "so an examiner can see at a glance that only the repressor has moved."),
      S('s2_checklist','text','What the examiner checks',0,None,
        lines=["The labels the drawing must carry:",
               "i = regulator gene   p = promoter",
               "o = operator         z, y, a = structural genes",
               "z codes β-galactosidase, y codes permease,",
               "a codes transacetylase.",
               "Panel 1: repressor bound to the operator, so",
               "RNA polymerase cannot transcribe.",
               "Panel 2: inducer (lactose) binds the repressor,",
               "the repressor is inactivated, lac mRNA is made."],
        why="Writing which enzyme each structural gene codes for costs three lines and answers the "
            "follow-up question examiners most often attach to this figure.",
        mistakes=["Labelling the boxes but not saying what the letters mean. The key is part of the labelling mark.",
                  "Saying the inducer binds the operator. The inducer binds the REPRESSOR."],
        tip="The inducer works on the repressor, never on the DNA.",
        note="No marks here — this is the checklist to run over your own drawing before moving on.")]))

C.append(Q(U, 'dna_vs_rna', 'SAQ', 'saq4', 42, 34,
    "What are the differences between DNA and RNA?",
    years=[('ap',2020),('ts',2017),('ts',2020),('ts',2022)],
    split=[("Name, strands and sugar",1),("Stability and size",1),
           ("Replication and function",1),("Types and base pairing",1)],
    note_extra="BOOK NOTE: the guide's row 7 reads \"DNA is genetic material / RNA is non-genetic "
               "material\". As a general claim that is false, and this same book contradicts it — its "
               "own SAQ 27 and VSAQ 95 say TMV, polio virus and HIV carry RNA as their genetic "
               "material. The card qualifies the row: in cellular organisms DNA is the genetic "
               "material, but in many viruses RNA is.",
    insider="Ten rows in the book, four marks on the paper. Tabulate — two columns, numbered rows — and "
            "get at least eight differences down.",
    steps=[
      S('s1_basic','text','Name, strands and sugar',1,'Basics',
        lines=["DNA  |  RNA",
               "1. Deoxyribonucleic acid | Ribonucleic acid",
               "2. DOUBLE stranded helix | SINGLE stranded",
               "3. Sugar is DEOXYRIBOSE  | Sugar is RIBOSE",
               "4. Bases A, T, G, C      | Bases A, U, G, C",
               "   (thymine)             | (uracil replaces thymine)"],
        why="The one missing oxygen in deoxyribose is what makes DNA the more stable molecule, so the "
            "sugar row explains the stability row that follows.",
        mistakes=["Saying RNA has thymine. RNA has URACIL in place of thymine.",
                  "Saying DNA is single stranded. DNA is DOUBLE stranded."],
        tip="Deoxy means one oxygen less, and that is what makes it stable.",
        note="Set up two columns on the first line. Four numbered rows here."),
      S('s2_stability','text','Stability and size',1,'Stability',
        lines=["5. STABLE under alkaline conditions",
               "   | UNSTABLE under alkaline conditions",
               "6. Very large: millions of nucleotides",
               "   | Much smaller: about 75 to 2000 nucleotides",
               "7. Occurs mainly in the NUCLEUS",
               "   | Occurs mainly in the CYTOPLASM"],
        why="The extra hydroxyl group on ribose is what makes RNA break down in alkali, so its "
            "instability follows directly from its sugar.",
        mistakes=["Saying RNA is more stable. DNA is the stable one.",
                  "Giving no size figures. The nucleotide counts are worth writing."],
        tip="One extra oxygen makes RNA easier to break.",
        note="Three more numbered rows. The alkali row is the one examiners like."),
      S('s3_function','text','Replication and function',1,'Function',
        lines=["8. UNDERGOES self replication",
               "   | Does NOT undergo self replication",
               "9. Does NOT take part directly in protein",
               "   synthesis | Takes part DIRECTLY in protein",
               "   synthesis",
               "10. Stores information | Carries and uses",
               "    information"],
        why="DNA stays in the nucleus as the archive and RNA does the work outside it, which is why only "
            "one of them replicates.",
        mistakes=["Saying DNA makes protein directly. It does NOT; RNA does.",
                  "Saying RNA replicates. In cells it does not — it is transcribed from DNA."],
        tip="DNA is the master copy; RNA is the working copy.",
        note="Three more rows. Keep the columns aligned."),
      S('s4_types','boxed_final','Types and base pairing',1,'Types',
        lines=[{"text":"DNA stores; RNA works","style":"boxed"},
               "11. ONE type (metabolically)",
               "    | THREE types: mRNA, tRNA, rRNA",
               "12. Base pairing A = T and G ≡ C",
               "    | Base pairing A = U and G ≡ C",
               "13. In CELLS, DNA is the genetic material.",
               "    In many VIRUSES — TMV, polio, HIV — RNA is",
               "    the genetic material."],
        why="Saying RNA is 'non-genetic' would contradict the virus chapter of this same syllabus, so "
            "the claim has to be limited to cellular organisms.",
        mistakes=["Writing that RNA is never genetic material. TMV, polio and HIV all use RNA. The guide "
                  "prints the unqualified claim.",
                  "Naming two types of RNA. There are THREE: mRNA, tRNA and rRNA."],
        tip="RNA is genetic material too, just not in cells.",
        note="The three RNA types, both base-pairing rules, and the qualified genetic-material row.")]))

C.append(Q(U, 'genetic_code_features', 'SAQ', 'saq5', 43, 34,
    "Write the important features of the genetic code.",
    years=[('ap',2016),('ap',2017),('ap',2018),('ap',2022),('ts',2015),('ts',2018),('ts',2019),('ts',2022)],
    split=[("Triplet and the codon count",1),("Unambiguous and degenerate",1),
           ("Continuous and non-overlapping",1),("Universal, with a start and stops",1)],
    note_extra="The most repeated SAQ in the paper: eight printed appearances across both boards.",
    insider="Every feature has a NAME — triplet, unambiguous, degenerate, non-overlapping, "
            "comma-less, universal. Use the names; a description without the name reads as a guess.",
    steps=[
      S('s1_triplet','text','Triplet and the codon count',1,'Triplet',
        lines=["1. The genetic code is a TRIPLET code: three",
               "bases on the mRNA specify one amino acid.",
               "Each triplet is called a CODON.",
               "2. There are 4 x 4 x 4 = 64 codons in all.",
               "61 codons code for the 20 amino acids.",
               "3 codons code for none — they are STOP codons."],
        why="Four bases taken two at a time give only sixteen combinations, too few for twenty amino "
            "acids, so the code must be at least a triplet.",
        mistakes=["Saying there are 64 amino acids. There are 64 CODONS and 20 amino acids.",
                  "Saying all 64 code for amino acids. THREE are stop codons."],
        tip="Four bases, three at a time: sixty-four codons for twenty amino acids.",
        note="The triplet nature, the arithmetic, and the 61-and-3 split."),
      S('s2_degenerate','text','Unambiguous and degenerate',1,'Degenerate',
        lines=["3. The code is UNAMBIGUOUS and SPECIFIC: one",
               "codon codes for ONE amino acid and no other.",
               "4. The code is DEGENERATE: some amino acids are",
               "coded by MORE THAN ONE codon.",
               "Example: leucine has six codons.",
               "Degeneracy follows from having 61 codons for",
               "only 20 amino acids."],
        why="Sixty-one codons sharing out twenty amino acids means some amino acids must have several "
            "codons, so degeneracy is forced by the arithmetic.",
        mistakes=["Saying degenerate means one codon codes for several amino acids. It is the other way "
                  "round: several codons code for ONE amino acid.",
                  "Treating unambiguous and degenerate as contradictory. They are not — read them in "
                  "opposite directions."],
        tip="One codon, one amino acid; but one amino acid, several codons.",
        note="Both terms with their meanings and one example. The direction is what students reverse."),
      S('s3_continuous','text','Continuous and non-overlapping',1,'Reading',
        lines=["5. The code is read in a CONTINUOUS fashion,",
               "with no punctuation between codons. It is",
               "therefore called COMMA-LESS.",
               "6. The code is NON-OVERLAPPING: each base",
               "belongs to one codon only.",
               "7. The code has a fixed READING FRAME, so adding",
               "or deleting one base shifts every codon after",
               "it."],
        why="With no punctuation and no overlap, the reading frame is everything — which is why a "
            "single insertion or deletion ruins the whole protein.",
        mistakes=["Saying there are commas or gaps between codons. The code is COMMA-LESS.",
                  "Saying bases are shared between codons. The code is NON-OVERLAPPING."],
        tip="No gaps and no sharing, so the frame is everything.",
        note="Both named properties plus the reading-frame consequence."),
      S('s4_universal','boxed_final','Universal, with a start and stops',1,'Universal',
        lines=[{"text":"Nearly universal: UUU is phenylalanine in","style":"boxed"},
               {"text":"bacteria and in humans alike","style":"boxed"},
               "8. The code is nearly UNIVERSAL: it is the same",
               "from bacteria to human beings.",
               "Example: UUU codes for phenylalanine in every",
               "organism.",
               "9. AUG is the INITIATION codon and also codes",
               "for methionine.",
               "10. UAA, UAG and UGA are the STOP codons."],
        why="The code being the same in every organism is the strongest single piece of evidence that "
            "all life shares one ancestor — and it is why a human gene works in a bacterium.",
        mistakes=["Saying the code is completely universal. It is NEARLY universal; mitochondria have a "
                  "few exceptions.",
                  "Leaving out the three stop codons by name. UAA, UAG and UGA are expected."],
        tip="One code for all life, with one start and three stops.",
        note="Universality with an example, then AUG and the three stop codons by name.")]))

C.append(Q(U, 'nucleosome', 'SAQ', 'saq6', 44, 34,
    "Write briefly on nucleosomes.",
    years=[('ap',2017),('ap',2019),('ts',2022)],
    split=[("What a nucleosome is",1),("The histone octamer",1),
           ("Why the DNA winds on",1),("Chromatin and beads on a string",1)],
    note_extra="BOOK NOTE: the guide says a nucleosome holds \"a DNA segment of about 150 base pairs\". "
               "NCERT gives 146 bp wrapped on the histone core, within a repeat of about 200 bp per "
               "nucleosome. The card gives 146 bp wrapped and notes the repeat, and records the "
               "guide's figure.",
    insider="Two numbers carry this answer: EIGHT histones and 146 base pairs. Write both in the first "
            "two lines.",
    steps=[
      S('s1_what','text','What a nucleosome is',1,'Definition',
        lines=["A NUCLEOSOME is the repeating, bead-like unit of",
               "chromatin.",
               "It consists of a core of histone proteins with",
               "DNA wound around it.",
               "Nucleosomes are how a two-metre length of DNA",
               "is packed into a nucleus a few micrometres",
               "across."],
        why="Two metres of DNA has to fit inside a nucleus, and the nucleosome is the first and largest "
            "step of that packing.",
        mistakes=["Calling a nucleosome a chromosome. It is the repeating UNIT of chromatin, far smaller.",
                  "Saying it is made only of DNA. It is DNA plus HISTONE PROTEIN."],
        tip="A bead of protein with DNA wound on it.",
        note="Definition plus the packing problem it solves. Six lines."),
      S('s2_octamer','text','The histone octamer',1,'Octamer',
        lines=["The core is made of EIGHT histone molecules and",
               "is called the HISTONE OCTAMER.",
               "It is two copies each of H2A, H2B, H3 and H4.",
               "About 146 BASE PAIRS of DNA are wound around",
               "this octamer, in about 1.75 turns.",
               "One more histone, H1, sits where the DNA enters",
               "and leaves the bead."],
        why="Two copies each of four histones is what makes eight, so the name octamer is the "
            "composition stated in one word.",
        mistakes=["Saying the octamer includes H1. H1 is OUTSIDE the octamer, at the entry and exit point.",
                  "Giving the wrong count. It is EIGHT histones, two each of four kinds."],
        tip="Two of each of four kinds makes eight; H1 is the ninth, and it sits outside.",
        note="The count, the four histone names, the base pairs, and H1's position."),
      S('s3_charge','text','Why the DNA winds on',1,'Charge',
        lines=["DNA is NEGATIVELY charged, because of its",
               "phosphate groups.",
               "Histones are POSITIVELY charged, because they",
               "are rich in the basic amino acids LYSINE and",
               "ARGININE.",
               "So the DNA is held on the octamer by an",
               "electrical attraction between opposite charges."],
        why="Opposite charges attract, so the wrapping needs no energy and no enzyme — it happens because "
            "of what the two molecules are made of.",
        mistakes=["Saying histones are acidic. They are BASIC, and that is what makes them positive.",
                  "Giving no reason for the winding. The charge attraction is this mark."],
        tip="Negative DNA on positive protein: opposites attract.",
        note="Both charges, the two amino acids, and the attraction. Six lines."),
      S('s4_chromatin','boxed_final','Chromatin and beads on a string',1,'Chromatin',
        lines=[{"text":"Beads on a string, under the electron","style":"boxed"},
               {"text":"microscope","style":"boxed"},
               "DNA together with histone proteins is called",
               "CHROMATIN.",
               "Nucleosomes are the repeating units of",
               "chromatin.",
               "Under the ELECTRON MICROSCOPE, chromatin looks",
               "like BEADS ON A STRING: the nucleosomes are the",
               "beads and the linker DNA is the string.",
               "Further coiling of this gives the chromosome."],
        why="The beads-on-a-string picture is what a nucleosome actually looks like, which is why the "
            "phrase is worth writing exactly.",
        mistakes=["Saying the beads are seen under a light microscope. It is the ELECTRON microscope.",
                  "Confusing chromatin with chromosome. Chromatin coils further to give a chromosome."],
        tip="Beads are nucleosomes; the string is the linker DNA.",
        note="Define chromatin, give the beads-on-a-string phrase, and name the microscope."),
      S('s5_diagram','diagram','Diagram — nucleosome',0,None,
        figure=G.NUCLEOSOME,
        why="Drawing it shows the two facts the words have to carry separately: the DNA goes round more "
            "than once, and H1 sits exactly where it enters and leaves.",
        mistakes=["Drawing the DNA passing through the octamer. It winds AROUND the outside.",
                  "Drawing one full turn. The DNA makes about 1.75 turns.",
                  "Drawing H1 inside the core. H1 sits OUTSIDE, at the entry and exit point."],
        tip="Round the outside, nearly twice, with H1 at the door.",
        note="No diagram mark — the question says 'write briefly'. The bead is worth sketching because "
             "it fixes the 1.75 turns and H1's position in one picture.")]))

# ═══════════════════ VSAQ (Section A, 2 marks) ═══════════════════
def vs(slug, ref, gno, page, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, page, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('heterochromatin_vs_euchromatin','vsaq1',90,43,
   "Distinguish between heterochromatin and euchromatin. Which of the two is transcriptionally active?",
   [("Heterochromatin",1),("Euchromatin, and which is active",1)],
   "The last clause of the question is a direct instruction: name which one is active. Answer it in "
   "its own line.",
   [S('s1_hetero','text','Heterochromatin',1,'Heterochromatin',
      lines=["HETEROCHROMATIN is chromatin that is DENSELY",
             "packed.",
             "It stains DARK.",
             "It is transcriptionally INACTIVE."],
      why="RNA polymerase cannot reach DNA that is tightly packed, so density and inactivity are the "
          "same fact seen two ways.",
      mistakes=["Saying heterochromatin is loosely packed. It is DENSELY packed.",
                "Saying it stains light. It stains DARK."],
      tip="Dense, dark, dormant.",
      note="Packing, staining, activity. Four lines."),
    S('s2_eu','boxed_final','Euchromatin, and which is active',1,'Euchromatin',
      lines=[{"text":"EUCHROMATIN is the transcriptionally active one","style":"boxed"},
             "EUCHROMATIN is LOOSELY packed.",
             "It stains LIGHT.",
             "It is transcriptionally ACTIVE.",
             "So of the two, EUCHROMATIN is the one that is",
             "transcriptionally active."],
      why="Loosely packed DNA is accessible to the transcription machinery, which is why only "
          "euchromatin can be read.",
      mistakes=["Not answering the final question. The examiner asked WHICH one is active — say it.",
                "Swapping the two. Euchromatin is loose, light and active."],
      tip="Loose, light, lively.",
      note="Mirror the first half, then answer the question explicitly in the last line.")],
   years=[('ts',2022),('ap',2020)])

vs('who_proved_dna','vsaq2',91,43,
   "Who proved that DNA is genetic material? What is the organism they worked on?",
   [("The scientists",1),("The organism",1)],
   "Two names and one organism. Getting the organism right is the harder half — and the guide gets it "
   "wrong.",
   [S('s1_who','text','The scientists',1,'Scientists',
      lines=["ALFRED HERSHEY and MARTHA CHASE proved that DNA",
             "is the genetic material, in 1952.",
             "They used radioactive tracers: sulphur-35 to",
             "label protein and phosphorus-32 to label DNA."],
      why="Protein contains sulphur and no phosphorus, DNA contains phosphorus and no sulphur, so "
          "labelling each element tracked each molecule separately.",
      mistakes=["Naming Griffith. Griffith showed transformation existed; Hershey and Chase proved DNA "
                "was the material.",
                "Naming Watson and Crick. They worked out the STRUCTURE, not that DNA was the genetic "
                "material."],
      tip="Hershey and Chase: sulphur for protein, phosphorus for DNA.",
      note="Both names, the year, and the two tracers."),
    S('s2_organism','boxed_final','The organism',1,'Organism',
      lines=[{"text":"The bacteriophage T2 and its host, E. coli","style":"boxed"},
             "They worked on the BACTERIOPHAGE T2 — a VIRUS —",
             "and its host bacterium ESCHERICHIA COLI.",
             "Only the phosphorus label entered the bacterial",
             "cells, so only DNA had gone in."],
      why="Finding the phosphorus inside the bacteria and the sulphur outside is the entire result: the "
          "DNA went in, the protein did not.",
      mistakes=["Calling bacteriophages 'bacteria'. A bacteriophage is a VIRUS. The guide prints "
                "\"bacteria called bacterio phages\", which is wrong.",
                "Naming only the phage. The host E. coli is part of the experiment."],
      tip="A virus and the bacterium it infects, not a bacterium.",
      note="Name the phage AND the host, then the result in one line.")],
   years=[('ts',2019),('ap',2017)])

vs('dna_polymerase_function','vsaq3',92,43,
   "What is the function of DNA polymerase?",
   [("Its function",1),("Speed and accuracy",1)],
   "Two properties: it is fast and it is accurate. Both are worth stating, because the accuracy is what "
   "makes replication reliable.",
   [S('s1_function','text','Its function',1,'Function',
      lines=["DNA POLYMERASE catalyses the polymerisation of",
             "deoxyribonucleotides into a new DNA strand,",
             "during REPLICATION.",
             "It adds nucleotides only in the 5' to 3'",
             "direction."],
      why="The enzyme can only add to a free 3' end, which is why replication runs in one direction "
          "along each strand.",
      mistakes=["Saying it makes RNA. That is RNA polymerase.",
                "Saying it works in both directions. It adds only 5' to 3'."],
      tip="It builds DNA, and only one way along it.",
      note="Name the reaction, the process, and the direction."),
    S('s2_accuracy','boxed_final','Speed and accuracy',1,'Accuracy',
      lines=[{"text":"Fast, and almost never wrong","style":"boxed"},
             "It polymerises a very large number of nucleotides",
             "in a very short time.",
             "It works with a HIGH DEGREE OF ACCURACY: about",
             "one error in a billion base pairs.",
             "Both properties are needed, because an inaccurate",
             "copy would be a mutation in every generation."],
      why="A genome copied quickly but carelessly would accumulate mutations faster than selection could "
          "remove them, so speed alone is not enough.",
      mistakes=["Giving only the speed. The ACCURACY is the second half of the mark.",
                "Saying it never makes errors. It makes very few, not none."],
      tip="Speed without accuracy would be useless.",
      note="Both properties named, then one line on why both matter.")])

vs('nucleotide_components','vsaq4',93,43,
   "What are the components of a nucleotide?",
   [("The three components",1),("How they are joined",1)],
   "Three components is the first mark. Naming the two kinds of nitrogen base is a cheap way to fill "
   "the second.",
   [S('s1_three','text','The three components',1,'Components',
      lines=["A NUCLEOTIDE has THREE components:",
             "1. a NITROGEN BASE",
             "2. a PENTOSE SUGAR (deoxyribose in DNA,",
             "   ribose in RNA)",
             "3. a PHOSPHATE group"],
      why="These same three parts, repeated millions of times, are all a nucleic acid is made of.",
      mistakes=["Naming two components. There are THREE.",
                "Saying the sugar is glucose. It is a PENTOSE: deoxyribose or ribose."],
      tip="Base, sugar, phosphate: three parts every time.",
      note="All three numbered, with the sugar named for both nucleic acids."),
    S('s2_joined','boxed_final','How they are joined',1,'Joining',
      lines=[{"text":"Base + sugar = nucleoside; add phosphate =","style":"boxed"},
             {"text":"nucleotide","style":"boxed"},
             "The nitrogen bases are of two kinds:",
             "PURINES (adenine, guanine) and PYRIMIDINES",
             "(cytosine, thymine, uracil).",
             "A base joined to a sugar is a NUCLEOSIDE.",
             "A nucleoside with a phosphate added is a",
             "NUCLEOTIDE."],
      why="The nucleoside-versus-nucleotide difference is exactly one phosphate group, which is the "
          "shortest way to remember both words.",
      mistakes=["Confusing nucleoside and nucleotide. The nucleoTide has the phosphaTe.",
                "Listing thymine as a purine. Thymine is a PYRIMIDINE."],
      tip="Nucleotide has the T of phosphaTe.",
      note="Both base classes with their members, then the two definitions.")],
   years=[('ts',2017),('ts',2018),('ap',2017),('ap',2018),('ap',2019),('ap',2022)])

vs('complementary_and_mrna','vsaq5',94,43,
   "Given the coding strand of DNA in a transcription unit as 5'-AATGCAGCTATTAGG-3', write the "
   "sequence of (a) its complementary strand (b) the mRNA.",
   [("The complementary strand",1),("The mRNA",1)],
   "Part (b) is the trap and the guide falls into it. The mRNA copies the CODING strand, not the "
   "template. Write the coding strand out and change every T to U.",
   [S('s1_complement','text','The complementary strand',1,'Complement',
      lines=["Coding strand:",
             "5'-A A T G C A G C T A T T A G G-3'",
             "Pair A with T and G with C, and run the answer",
             "the other way:",
             "Complementary (template) strand:",
             "3'-T T A C G T C G A T A A T C C-5'"],
      why="The two strands are antiparallel, so the complement is written 3' to 5' when the coding "
          "strand is written 5' to 3'.",
      mistakes=["Writing the complement 5' to 3'. The two strands run in OPPOSITE directions.",
                "Pairing A with G. A pairs with T, and G pairs with C."],
      tip="Swap each base for its partner, and flip the direction.",
      note="Write both strands with their 5' and 3' ends marked. The direction is part of the mark."),
    S('s2_mrna','boxed_final','The mRNA',1,'mRNA',
      lines=[{"text":"The mRNA copies the CODING strand, with U","style":"boxed"},
             {"text":"in place of T","style":"boxed"},
             "mRNA:",
             "5'-A A U G C A G C U A U U A G G-3'",
             "It is the coding strand with every T replaced",
             "by U.",
             "It is NOT the complementary strand with U."],
      why="RNA polymerase reads the TEMPLATE strand, so what it builds comes out matching the OTHER "
          "strand — the coding strand — which is why that strand is called coding at all.",
      mistakes=["Giving the template strand with U instead of T. That is the guide's printed answer and "
                "it is wrong.",
                "Writing the mRNA 3' to 5'. The mRNA runs 5' to 3', like the coding strand."],
      tip="Coding strand, T becomes U, direction unchanged.",
      note="Write the answer and then the one-line rule. That rule is what stops the mistake recurring.")],
   note_extra="BOOK ERROR, corrected on this card. The guide answers (b) with "
              "3'-UUACGUCGAUAAUCC-5', which is simply part (a) with U for T — that is the TEMPLATE "
              "strand, not the message. The mRNA has the SAME sequence as the CODING strand, with "
              "uracil in place of thymine: 5'-AAUGCAGCUAUUAGG-3'. Part (a) as printed is correct.")

vs('rna_viruses','vsaq6',95,43,
   "Name any three viruses which have RNA as the genetic material.",
   [("Three viruses",1),("What that shows",1)],
   "Three names, then one line saying why they matter. That extra line turns a list into an answer.",
   [S('s1_three','text','Three viruses',1,'Names',
      lines=["Three viruses with RNA as their genetic material:",
             "1. Influenza virus",
             "2. Polio virus",
             "3. Human Immunodeficiency Virus (HIV)",
             "Tobacco Mosaic Virus (TMV) is a fourth."],
      why="All four are common examples, so any three of them answer the question and the fourth is "
          "free insurance.",
      mistakes=["Naming a bacteriophage. T-even phages have DNA, not RNA.",
                "Naming only two. The question asks for THREE."],
      tip="Flu, polio, HIV — and TMV in plants.",
      note="Three named, with a fourth in reserve. Five lines."),
    S('s2_shows','boxed_final','What that shows',1,'Significance',
      lines=[{"text":"RNA can be genetic material too","style":"boxed"},
             "These viruses show that RNA can act as genetic",
             "material, not only DNA.",
             "HIV and other retroviruses copy their RNA back",
             "into DNA using REVERSE TRANSCRIPTASE."],
      why="RNA is thought to have been the first genetic material, which is why viruses that still use "
          "it are of more than passing interest.",
      mistakes=["Saying only DNA can be genetic material. These viruses are the counter-example.",
                "Leaving out the significance. Naming reverse transcriptase costs one line and adds "
                "real content."],
      tip="These are the exceptions to 'DNA is the genetic material'.",
      note="One line on the significance, one on retroviruses.")],
   years=[('ap',2016)])

vs('transcription_unit','vsaq7',96,43,
   "What are the components of a transcription unit?",
   [("The three components",1),("What each does",1)],
   "Three components, three jobs. Promoter, structural gene, terminator — in that order, because the "
   "order is the direction of transcription.",
   [S('s1_three','text','The three components',1,'Components',
      lines=["A TRANSCRIPTION UNIT has THREE components:",
             "1. a PROMOTER",
             "2. the STRUCTURAL GENE",
             "3. a TERMINATOR"],
      why="Transcription needs somewhere to start, something to copy and somewhere to stop, which is "
          "exactly these three.",
      mistakes=["Naming the operator. The operator belongs to an OPERON, not to a transcription unit.",
                "Giving two components. There are THREE."],
      tip="Start, copy, stop.",
      note="All three, numbered, in transcription order."),
    S('s2_does','boxed_final','What each does',1,'Functions',
      lines=[{"text":"Promoter starts it, gene is copied,","style":"boxed"},
             {"text":"terminator stops it","style":"boxed"},
             "The PROMOTER lies at the 5' end and is where RNA",
             "polymerase binds to begin transcription.",
             "The STRUCTURAL GENE is the DNA that is actually",
             "transcribed.",
             "The TERMINATOR lies at the 3' end and defines",
             "where transcription stops."],
      why="The promoter and terminator fix both ends, so between them they define exactly which stretch "
          "of DNA becomes RNA.",
      mistakes=["Saying the promoter is transcribed. It is a BINDING site, not part of the message.",
                "Placing the terminator at the 5' end. It is at the 3' end."],
      tip="Promoter at the 5' end, terminator at the 3'.",
      note="One line each, with the ends named. Seven lines.")],
   years=[('ts',2017),('ts',2017),('ap',2016),('ap',2019)])

vs('exons_and_introns','vsaq8',97,43,
   "What is the difference between exons and introns?",
   [("Exons",1),("Introns",1)],
   "Coding against non-coding, and present against absent in the mature RNA. Two contrasts each.",
   [S('s1_exons','text','Exons',1,'Exons',
      lines=["EXONS are the CODING sequences of a gene.",
             "They APPEAR in the mature, processed RNA.",
             "They are EXPRESSED — which is what the name",
             "comes from."],
      why="Only the exons reach the ribosome, so only they decide the amino acid sequence of the protein.",
      mistakes=["Saying exons are removed. INTRONS are removed; exons are kept.",
                "Saying exons do not code. Exons are the CODING parts."],
      tip="EXons are EXpressed.",
      note="Coding, present in mature RNA, and the name. Four lines."),
    S('s2_introns','boxed_final','Introns',1,'Introns',
      lines=[{"text":"Exons stay in the message; introns are cut out","style":"boxed"},
             "INTRONS are the NON-CODING sequences.",
             "They do NOT appear in the mature, processed RNA.",
             "They are cut out during SPLICING, and the exons",
             "are then joined together.",
             "Introns are INTervening sequences."],
      why="Splicing removes the introns and joins the exons, which is why the mature message is shorter "
          "than the gene it came from.",
      mistakes=["Saying introns are translated. They are removed BEFORE translation.",
                "Not naming splicing. It is the process that removes them."],
      tip="INtrons are INtervening, and they come out.",
      note="Mirror the exon lines, then name splicing.")],
   years=[('ts',2015),('ts',2018),('ts',2022)])

vs('capping_and_tailing','vsaq9',98,44,
   "What is meant by capping and tailing?",
   [("Capping",1),("Tailing",1)],
   "Which end each happens at is the mark: cap at the 5' end, tail at the 3'.",
   [S('s1_capping','text','Capping',1,'Capping',
      lines=["CAPPING is the addition of an unusual nucleotide,",
             "METHYL GUANOSINE TRIPHOSPHATE, to the 5' END of",
             "the hnRNA.",
             "The cap protects the RNA and helps the ribosome",
             "recognise it."],
      why="The cap marks the front of the message, so the ribosome knows which end to start from.",
      mistakes=["Putting the cap at the 3' end. It goes on the 5' end.",
                "Naming the wrong molecule. It is methyl guanosine triphosphate."],
      tip="A cap goes on the head: the 5' end.",
      note="The molecule, the end, and what the cap is for."),
    S('s2_tailing','boxed_final','Tailing',1,'Tailing',
      lines=[{"text":"Cap at the 5' end, tail at the 3' end","style":"boxed"},
             "TAILING is the addition of 200 to 300 ADENYLATE",
             "residues to the 3' END, in a TEMPLATE INDEPENDENT",
             "manner.",
             "This is the poly-A tail.",
             "Template independent means no DNA is read to make",
             "it — the adenines are simply added on."],
      why="No DNA codes for the tail, so it cannot be found in the gene — which is exactly what template "
          "independent means.",
      mistakes=["Leaving out 'independent'. The guide drops it, and 'in a template' means the opposite.",
                "Putting the tail at the 5' end. It goes on the 3' end."],
      tip="Tail at the tail end, and nothing is copied to make it.",
      note="The residues, the count, the end, and what template independent means.")],
   years=[('ts',2016),('ap',2017)],
   note_extra="BOOK NOTE: the guide defines tailing as adding adenylate residues \"in a template\". "
              "NCERT says \"in a template INDEPENDENT manner\", which is the point: no DNA is read to "
              "make the tail. The card restores the word.")

vs('point_mutation_molecular','vsaq10',99,44,
   "What is meant by point mutation? Give an example.",
   [("Definition",1),("Example",1)],
   "The same question appears in the genetics chapter too. One answer serves both: one base pair, "
   "sickle cell anaemia.",
   [S('s1_define','text','Point mutation defined',1,'Definition',
      lines=["A POINT MUTATION is a mutation that occurs in a",
             "SINGLE BASE PAIR of DNA.",
             "It is also called a gene mutation.",
             "It may be a substitution, an insertion or a",
             "deletion of one base."],
      why="Because only one base changes, the change can be traced through to one amino acid and one "
          "protein.",
      mistakes=["Saying it affects the whole gene. It affects ONE base pair.",
                "Confusing it with a chromosomal mutation, which changes chromosome number or structure."],
      tip="A single point on the DNA.",
      note="Definition, the other name, and the three kinds. Five lines."),
    S('s2_example','boxed_final','Example',1,'Example',
      lines=[{"text":"Sickle cell anaemia: GAG becomes GTG","style":"boxed"},
             "Example: SICKLE CELL ANAEMIA.",
             "In the gene for the beta chain of haemoglobin,",
             "one base changes: GAG becomes GTG.",
             "So GLUTAMIC ACID is replaced by VALINE at",
             "position 6 of the chain.",
             "The red blood cell then becomes sickle shaped."],
      why="One base, one codon, one amino acid, one cell shape: this is the clearest chain from a DNA "
          "change to a visible symptom in the whole syllabus.",
      mistakes=["Naming a chromosomal disorder such as Down's syndrome. That is not a point mutation.",
                "Giving no detail. The amino acid substitution is what makes it a worked example."],
      tip="One letter changes and the cell changes shape.",
      note="Name it, give the codon change, the amino acid change, and the result.")],
   years=[('ap',2018),('ts',2019),('ts',2019)],
   note_extra="This question is printed TWICE in the book, once in the Inheritance VSAQ chapter as "
              "global 87 and again here as global 99. Both are authored, in their own units, because "
              "both are printed as asked.")

vs('charging_of_trna','vsaq11',100,44,
   "What is meant by charging of tRNA?",
   [("What charging is",1),("Why it matters",1)],
   "Aminoacylation is the other name and it is worth writing. So is the fact that ATP is needed.",
   [S('s1_what','text','What charging is',1,'Definition',
      lines=["CHARGING of tRNA is the ACTIVATION of an amino",
             "acid, in the presence of ATP, and its linking to",
             "the correct (cognate) tRNA.",
             "It is also called AMINOACYLATION.",
             "A tRNA carrying its amino acid is a CHARGED tRNA,",
             "or aminoacyl-tRNA."],
      why="An amino acid on its own cannot recognise a codon, so it has to be attached to a tRNA that "
          "can — charging is what makes the amino acid readable.",
      mistakes=["Saying charging means giving the tRNA an electrical charge. It means LOADING it with "
                "an amino acid.",
                "Leaving out ATP. The activation step needs it."],
      tip="Charged means loaded, not electrified.",
      note="Definition with ATP and the alternative name. Six lines."),
    S('s2_why','boxed_final','Why it matters',1,'Significance',
      lines=[{"text":"Only a charged tRNA can add its amino acid","style":"boxed"},
             {"text":"to the growing chain","style":"boxed"},
             "Only a CHARGED tRNA can take part in translation.",
             "An uncharged tRNA carries nothing to add to the",
             "protein chain.",
             "Charging is what matches each codon to the right",
             "amino acid."],
      why="The accuracy of the whole genetic code depends on each tRNA being loaded with the correct "
          "amino acid, so charging is where translation can go wrong.",
      mistakes=["Giving only the definition. The significance is a whole mark.",
                "Saying an uncharged tRNA still works. It cannot contribute to the chain."],
      tip="An empty tRNA has nothing to give.",
      note="Say what only a charged tRNA can do, and why the matching matters.")])

vs('codon_aug','vsaq12',101,44,
   "What is the function of the codon AUG?",
   [("It starts translation",1),("It codes for methionine",1)],
   "AUG has TWO functions. Both are needed, and 'initiation codon' plus 'methionine' is the whole "
   "answer.",
   [S('s1_start','text','It starts translation',1,'Initiation',
      lines=["AUG has TWO functions.",
             "1. It acts as the INITIATION codon, or start",
             "codon, of an mRNA.",
             "Translation begins at the first AUG in the",
             "message."],
      why="Every protein has to start somewhere, and a codon that marks the start is what sets the "
          "reading frame for everything after it.",
      mistakes=["Calling AUG a stop codon. The stop codons are UAA, UAG and UGA.",
                "Giving one function only. AUG has two."],
      tip="AUG is where reading begins.",
      note="Say two functions first, then give the first one."),
    S('s2_met','boxed_final','It codes for methionine',1,'Methionine',
      lines=[{"text":"AUG starts the message AND codes for","style":"boxed"},
             {"text":"methionine","style":"boxed"},
             "2. It codes for the amino acid METHIONINE.",
             "So every newly made protein begins with",
             "methionine, though it is often removed later.",
             "AUG is called a DUAL FUNCTION codon."],
      why="Having one codon do both jobs is why every protein begins with the same amino acid, whatever "
          "it goes on to become.",
      mistakes=["Naming a different amino acid. AUG codes for METHIONINE.",
                "Saying the methionine always stays. It is often removed after translation."],
      tip="Start and methionine: two jobs, one codon.",
      note="The second function, its consequence, and the term dual function.")],
   years=[('ap',2020),('ap',2022),('ts',2020)])

vs('stop_codons','vsaq13',102,44,
   "Define stop codon. Write the codons.",
   [("Definition",1),("The three codons",1)],
   "Definition plus three triplets. Write all three — UAA, UAG, UGA — because the question says "
   "'the codons', plural.",
   [S('s1_define','text','Stop codon defined',1,'Definition',
      lines=["A STOP CODON is a codon that TERMINATES protein",
             "synthesis.",
             "Stop codons do NOT code for any amino acid.",
             "They are also called nonsense or termination",
             "codons."],
      why="A stop codon has no matching tRNA, so the ribosome finds nothing to add and the chain is "
          "released.",
      mistakes=["Saying stop codons code for an amino acid. They code for NONE.",
                "Saying there is one stop codon. There are THREE."],
      tip="Nothing matches them, so the chain ends.",
      note="Definition, the no-amino-acid point, and the alternative names."),
    S('s2_three','boxed_final','The three codons',1,'The codons',
      lines=[{"text":"UAA, UAG and UGA","style":"boxed"},
             "The three stop codons are:",
             "UAA, UAG and UGA.",
             "Of the 64 codons, 61 code for amino acids and",
             "these 3 do not."],
      why="Sixty-one coding codons plus three stop codons makes sixty-four, which is the arithmetic "
          "check that the list is complete.",
      mistakes=["Writing AUG among them. AUG is the START codon.",
                "Giving two codons. There are three."],
      tip="Three stops out of sixty-four.",
      note="All three triplets and the 61-and-3 arithmetic.")],
   years=[('ts',2019),('ap',2015),('ap',2019)])

vs('two_dna_rna_differences','vsaq14',103,44,
   "Write any two differences between DNA and RNA.",
   [("First difference",1),("Second difference",1)],
   "The question asks for TWO, so give exactly two and make them sharp. Sugar and strandedness are the "
   "safest pair.",
   [S('s1_first','text','First difference',1,'Sugar',
      lines=["1. DNA contains the sugar DEOXYRIBOSE.",
             "   RNA contains the sugar RIBOSE.",
             "2. DNA is DOUBLE stranded.",
             "   RNA is SINGLE stranded."],
      why="These two are structural facts that hold for every DNA and every RNA, so neither needs a "
          "qualification.",
      mistakes=["Saying DNA has ribose. DNA has DEOXYribose — one oxygen less.",
                "Saying RNA is double stranded. RNA is SINGLE stranded."],
      tip="Deoxy and double for DNA; ribose and single for RNA.",
      note="Two clean differences, one per numbered pair."),
    S('s2_second','boxed_final','Second difference',1,'Function',
      lines=[{"text":"DNA replicates itself; RNA does not","style":"boxed"},
             "3. DNA UNDERGOES self replication.",
             "   RNA does NOT undergo self replication.",
             "4. DNA has thymine; RNA has URACIL instead."],
      why="Only DNA replicates because only DNA is the archive; RNA is made fresh from DNA each time it "
          "is needed.",
      mistakes=["Saying RNA replicates in cells. It is transcribed from DNA, not self replicated.",
                "Naming thymine in RNA. RNA has URACIL."],
      tip="One copies itself, the other is copied from it.",
      note="Two more differences. Four in total is more than the question asks for and costs nothing.")],
   years=[('ap',2017),('ap',2019)])

vs('base_percentages','vsaq15',104,44,
   "In a typical DNA molecule the proportion of thymine is 30% of the nitrogen bases. Find the "
   "percentages of the other bases.",
   [("Adenine",1),("Guanine and cytosine",1)],
   "This is Chargaff's rule as arithmetic. Write the rule first, then the numbers — the rule is worth "
   "credit even if a number slips.",
   [S('s1_adenine','text','Adenine',1,'Adenine',
      lines=["By CHARGAFF'S RULE, A = T and G = C.",
             "Thymine = 30%",
             "So ADENINE = 30% as well."],
      why="Adenine always pairs with thymine, so in a double helix there must be exactly as much of one "
          "as of the other.",
      mistakes=["Pairing adenine with guanine. A pairs with T.",
                "Not stating Chargaff's rule. The rule is what justifies every number here."],
      tip="A equals T, so thirty and thirty.",
      note="State the rule, then the first answer. Three lines."),
    S('s2_gc','boxed_final','Guanine and cytosine',1,'G and C',
      lines=[{"text":"A 30%, T 30%, G 20%, C 20%","style":"boxed"},
             "A + T = 30 + 30 = 60%",
             "So G + C = 100 − 60 = 40%",
             "Since G = C, each is 40 ÷ 2 = 20%.",
             "GUANINE = 20% and CYTOSINE = 20%."],
      why="The four bases must add to 100%, so once A and T are fixed the remainder is shared equally "
          "between G and C.",
      mistakes=["Giving G = 40% and C = 0%. The 40% is SHARED equally, so 20% each.",
                "Not showing the subtraction. The working is what earns the mark if the answer slips."],
      tip="Take the pair away from a hundred, then halve what is left.",
      note="Show the subtraction and the halving. Five lines.")],
   years=[('ap',2015),('ts',2016),('ts',2019),('ts',2022)])

vs('identify_nucleic_acid','vsaq16',105,44,
   "The proportion of nucleotides in a nucleic acid is: adenine 18%, guanine 30%, cytosine 42%, "
   "uracil 10%. Name the nucleic acid and state the number of strands.",
   [("Which nucleic acid",1),("How many strands",1)],
   "Two clues, two answers. Uracil names the molecule; the failed pairing rule names the strand count.",
   [S('s1_which','text','Which nucleic acid',1,'RNA',
      lines=["URACIL is present, and thymine is absent.",
             "Uracil occurs only in RNA.",
             "So the nucleic acid is RNA."],
      why="Uracil is the one base that appears in RNA and never in DNA, so its presence settles the "
          "question by itself.",
      mistakes=["Answering DNA. DNA contains thymine, never uracil.",
                "Not saying why. The reason is what earns the mark."],
      tip="Uracil means RNA.",
      note="Name the clue, then the answer. Three lines."),
    S('s2_strands','boxed_final','How many strands',1,'One strand',
      lines=[{"text":"Chargaff's rule fails, so it cannot be a","style":"boxed"},
             {"text":"double helix","style":"boxed"},
             "In a double stranded molecule A = U and G = C.",
             "Here A = 18% but U = 10%, and G = 30% but",
             "C = 42%.",
             "The pairs are NOT equal, so the molecule cannot",
             "be double stranded.",
             "It has only ONE strand."],
      why="Equal base pairs are a necessary consequence of two strands pairing, so unequal percentages "
          "rule two strands out completely.",
      mistakes=["Answering two strands. The unequal percentages make that impossible.",
                "Giving the answer with no arithmetic. The comparison IS the reasoning."],
      tip="Unequal pairs means nothing is pairing.",
      note="Show both comparisons before the conclusion. Seven lines.")],
   years=[('ts',2017),('ap',2018)])

vs('template_vs_coding_strand','vsaq17',106,44,
   "What is the difference between the template strand and the coding strand in a DNA molecule?",
   [("Template strand",1),("Coding strand",1)],
   "The names are misleading and examiners know it: the CODING strand is the one that is NOT copied. "
   "Say that plainly.",
   [S('s1_template','text','Template strand',1,'Template',
      lines=["During transcription the two strands of DNA",
             "uncoil.",
             "The TEMPLATE strand is the one that is actually",
             "READ by RNA polymerase.",
             "The mRNA is built complementary to it.",
             "It runs 3' to 5'."],
      why="The template is the strand the enzyme reads, so the RNA comes out complementary to it and "
          "identical to the other one.",
      mistakes=["Saying the template strand is the same as the mRNA. The mRNA is COMPLEMENTARY to it.",
                "Giving its direction as 5' to 3'. The template is read 3' to 5'."],
      tip="The template is read, not copied.",
      note="What it is, what is built from it, and its direction."),
    S('s2_coding','boxed_final','Coding strand',1,'Coding',
      lines=[{"text":"The CODING strand is the one NOT read","style":"boxed"},
             "The CODING strand is the OTHER strand, which is",
             "NOT read during transcription.",
             "It is called the coding strand because its",
             "sequence is the SAME as the mRNA, with T in",
             "place of U.",
             "It runs 5' to 3'."],
      why="The strand that codes for nothing is called the coding strand precisely because it matches "
          "the message — a name that describes the sequence, not the job.",
      mistakes=["Saying the coding strand is transcribed. It is NOT read at all.",
                "Not explaining the name. The name is the confusing part and explaining it is the mark."],
      tip="The coding strand does no work; it just matches the message.",
      note="Say it is not read, then explain why it is still called coding.")])

main(C, U)
