# -*- coding: utf-8 -*-
"""Unit 9 — Principles of Inheritance and Variation. Book SAQ ch.10 (pp.30-32) +
VSAQ ch.16 (p.42). Globals 31-38 (SAQ) and 82-89 (VSAQ)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main
import figs_u9 as G

U = 9
C = []

C.append(Q(U, 'pea_plant_advantages', 'SAQ', 'saq1', 31, 30,
    "Mention the advantages of selecting pea plant for experiment by Mendel.",
    years=[('ts',2019),('ts',2020),('ts',2022),('ap',2017)],
    split=[("Contrasting characters",1),("Ease of crossing",1),("Life cycle and progeny",1),("Practical advantages",1)],
    insider="Seven reasons in the book, four marks on the paper. The two that must appear are the seven "
            "pairs of contrasting characters and the ability to self-pollinate.",
    steps=[
      S('s1_contrast','text','Contrasting characters',1,'Characters',
        lines=["1. The garden pea has MANY CONTRASTING",
               "CHARACTERS, each with two clear alternatives.",
               "Mendel used seven pairs: tall or dwarf, round or",
               "wrinkled seed, green or yellow pod, and so on.",
               "Each character is either one form or the other,",
               "with nothing in between."],
        why="A character with only two clear forms can be counted, and counting is what let Mendel turn "
            "breeding results into ratios.",
        mistakes=["Saying pea has many characters. It has many CONTRASTING PAIRS, which is different.",
                  "Giving no example pair. Tall and dwarf is the standard one."],
        tip="Two clear forms means you can count, and counting gives ratios.",
        note="Say contrasting, give the number seven, give one pair. This is the key reason."),
      S('s2_crossing','text','Ease of crossing',1,'Crossing',
        lines=["2. The pea flower is BISEXUAL: it has both male",
               "and female parts in the same flower.",
               "3. It can be SELF POLLINATED easily, which gives",
               "pure breeding lines.",
               "4. It can also be CROSS POLLINATED by hand,",
               "which lets the experimenter choose the parents."],
        why="Being able to both self and cross the same plant is what let Mendel make pure lines first "
            "and then cross them in a controlled way.",
        mistakes=["Saying pea flowers are unisexual. They are BISEXUAL.",
                  "Giving only one of the two. Self AND cross pollination are both needed."],
        tip="Self it to make it pure, cross it to test it.",
        note="Bisexual, self pollination, hand cross pollination. Three numbered points."),
      S('s3_lifecycle','text','Life cycle and progeny',1,'Life cycle',
        lines=["5. It has a SHORT LIFE CYCLE, so many",
               "generations can be raised in a few years.",
               "6. It produces a LARGE NUMBER of offspring, so",
               "the ratios are reliable.",
               "7. It has a SMALL NUMBER of chromosomes (7 pairs)."],
        why="A ratio measured on ten plants proves nothing; on thousands it becomes a law, so the number "
            "of offspring is as important as the plant's other qualities.",
        mistakes=["Leaving out the large number of offspring. Big numbers are why the ratios held.",
                  "Saying pea has many chromosomes. It has SEVEN pairs, which is few."],
        tip="Quick, plentiful, and simple to follow.",
        note="Three more numbered points. The large-progeny point is the statistical one."),
      S('s4_practical','boxed_final','Practical advantages',1,'Practical',
        lines=[{"text":"Two clear forms, easy crosses, many offspring","style":"boxed"},
               "8. It grows easily in ordinary garden conditions",
               "and needs no special laboratory.",
               "9. The characters are easy to see with the naked",
               "eye, so no equipment is needed to score them.",
               "Together these made pea the right plant for the",
               "first experiments in heredity."],
        why="Every advantage points the same way: the experiment could be run at scale, by one person, "
            "with nothing but a garden and careful records.",
        mistakes=["Listing fewer than six reasons in total. This is a list question.",
                  "Naming an advantage without saying why it helped. The reason is what earns the mark."],
        tip="Anyone with a garden could have run it; only Mendel counted.",
        note="Close with the practical points and one line joining them.")]))

C.append(Q(U, 'dominant_recessive_homozygous', 'SAQ', 'saq2', 32, 30,
    "Differentiate between the following: (a) Dominant and Recessive "
    "(b) Homozygous and Heterozygous.",
    years=[('ap',2020)],
    split=[("Dominant",1),("Recessive",1),("Homozygous",1),("Heterozygous",1)],
    insider="Four one-line definitions. Give an example genotype with each — TT, tt, Tt — because a "
            "letter pair proves the definition faster than a sentence.",
    steps=[
      S('s1_dominant','text','Dominant',1,'Dominant',
        lines=["(a) DOMINANT character:",
               "The character that IS EXPRESSED in the F₁",
               "generation of a cross between two pure parents.",
               "Example: tallness (T) in pea."],
        why="Dominance is defined by what shows in the F1, so the definition has to name that generation.",
        mistakes=["Saying the dominant character is the stronger one. It is the one EXPRESSED in F1.",
                  "Saying dominant means more common. Frequency has nothing to do with dominance."],
        tip="Whatever shows in F1 is the dominant one.",
        note="Definition tied to F1, plus a letter example."),
      S('s2_recessive','text','Recessive',1,'Recessive',
        lines=["RECESSIVE character:",
               "The character that is NOT EXPRESSED in the F₁",
               "generation, but reappears in F₂.",
               "Example: dwarfness (t) in pea.",
               "A recessive character shows only when BOTH",
               "alleles are recessive."],
        why="The recessive character reappearing in F2 is what proved it had never been lost, only "
            "hidden — the single most important observation Mendel made.",
        mistakes=["Saying the recessive character disappears. It reappears in F2.",
                  "Saying it shows when one allele is recessive. BOTH must be."],
        tip="Hidden in F1, back in F2: never lost.",
        note="Definition, the F2 return, and the both-alleles condition."),
      S('s3_homozygous','text','Homozygous',1,'Homozygous',
        lines=["(b) HOMOZYGOUS:",
               "An individual carrying TWO SIMILAR alleles for",
               "a character.",
               "Examples: TT (homozygous dominant) and",
               "tt (homozygous recessive).",
               "A homozygote breeds true."],
        why="Two identical alleles can only make one kind of gamete, which is why a homozygote always "
            "breeds true.",
        mistakes=["Saying homozygous means dominant. TT AND tt are both homozygous.",
                  "Leaving out 'for a character'. The term is always about one gene at a time."],
        tip="Homo means same: TT or tt.",
        note="Definition plus BOTH kinds of example. Giving only TT is half an answer."),
      S('s4_heterozygous','boxed_final','Heterozygous',1,'Heterozygous',
        lines=[{"text":"TT and tt are homozygous; Tt is heterozygous","style":"boxed"},
               "HETEROZYGOUS:",
               "An individual carrying TWO DISSIMILAR alleles",
               "for a character.",
               "Example: Tt.",
               "A heterozygote makes two kinds of gamete and",
               "does NOT breed true."],
        why="Two different alleles make two kinds of gamete, which is why a heterozygote's offspring "
            "vary and a homozygote's do not.",
        mistakes=["Saying a heterozygote shows both characters. It shows the DOMINANT one only.",
                  "Confusing heterozygous with co-dominant. A heterozygote is a genotype, not a pattern "
                  "of expression."],
        tip="Hetero means different: Tt.",
        note="Definition, example, and the consequence. The gamete point ties into the next question.")]))

C.append(Q(U, 'law_of_dominance', 'SAQ', 'saq3', 33, 30,
    "Explain the law of Dominance using a monohybrid cross.",
    years=[('ap',2015),('ap',2017),('ap',2019)],
    split=[("What a monohybrid cross is",1),("The cross itself",1),
           ("The law of dominance",1),("What the law explains",1)],
    insider="The law has FOUR statements and the examiner is counting them. Number them, then finish "
            "with the 3:1 ratio.",
    steps=[
      S('s1_what','text','What a monohybrid cross is',1,'Monohybrid',
        lines=["A MONOHYBRID CROSS is a cross between two",
               "individuals differing in ONE character.",
               "Mendel crossed a pure TALL pea plant (TT) with",
               "a pure DWARF pea plant (tt) to study the",
               "inheritance of one gene."],
        why="Following one character at a time is what made the pattern visible; with several characters "
            "at once the ratios would have been hidden in each other.",
        mistakes=["Saying monohybrid means one parent. It means ONE CHARACTER.",
                  "Using impure parents. Both parents must be PURE (homozygous)."],
        tip="Mono means one: one character, followed alone.",
        note="Definition and the actual cross Mendel made. Five lines."),
      S('s2_cross','text','The cross itself',1,'The cross',
        lines=["P generation:  Tall (TT)  ×  Dwarf (tt)",
               "Gametes:  T  and  t",
               "F₁ generation:  ALL Tt, and all TALL.",
               "The dwarf character has disappeared.",
               "F₁ selfed:  Tt × Tt",
               "F₂ generation:  1 TT : 2 Tt : 1 tt",
               "which is 3 TALL : 1 DWARF."],
        why="The dwarf character vanishing in F1 and returning in exactly a quarter of F2 is the "
            "observation the law was written to explain.",
        mistakes=["Writing the F1 as a mixture of tall and dwarf. ALL of F1 is tall.",
                  "Giving the F2 phenotypic ratio as 1:2:1. That is the GENOTYPIC ratio; the phenotypic "
                  "ratio is 3:1."],
        tip="All tall in F1, three to one in F2.",
        note="Write both generations with both ratios. Keep genotype and phenotype separate."),
      S('s3_law','text','The law of dominance',1,'The law',
        lines=["The LAW OF DOMINANCE states:",
               "1. Characters are controlled by discrete units",
               "called FACTORS (now called genes).",
               "2. Factors occur in PAIRS.",
               "3. In a dissimilar pair of factors, ONE member",
               "DOMINATES the other."],
        why="The three statements together explain why one parent's character can disappear entirely in "
            "F1 without being destroyed.",
        mistakes=["Giving fewer than three statements. Each one is part of the mark.",
                  "Saying the recessive factor is destroyed. It is only DOMINATED, and it reappears in F2."],
        tip="Discrete, paired, one dominating: three statements.",
        note="Number the statements exactly as the law is written."),
      S('s4_explains','boxed_final','What the law explains',1,'Explains',
        lines=[{"text":"One character in F₁, both in F₂, in 3 : 1","style":"boxed"},
               "4. The law explains why only ONE parental",
               "character appears in the F₁ generation, and why",
               "BOTH appear in the F₂ generation.",
               "It also explains the 3 : 1 phenotypic ratio",
               "obtained in F₂."],
        why="A law in science is judged by what it explains, so the answer has to end with the two "
            "observations this one accounts for.",
        mistakes=["Ending at the three statements. The fourth point is what the law EXPLAINS.",
                  "Leaving out the 3:1 ratio. It is the number the law was written to account for."],
        tip="The law is only useful because it explains the three to one.",
        note="Close on what is explained, with the ratio named."),
      S('s5_diagram','diagram','Diagram — monohybrid cross',0,None,
        figure=G.MONOHYBRID,
        why="The Punnett square is the shortest honest proof of the 3:1 ratio: four boxes, three of them "
            "tall, and the dwarf one visible in the corner.",
        mistakes=["Writing the F1 as TT. The F1 of TT × tt is Tt.",
                  "Filling the square from the wrong gametes. The heads are the F1's gametes, T and t, "
                  "on BOTH sides.",
                  "Giving one ratio only. The square shows the phenotypic 3:1 AND the genotypic 1:2:1."],
        tip="Four boxes: three tall, one dwarf.",
        note="No diagram mark — the question says 'explain'. Draw the square anyway: it is faster than "
             "writing the F2 out and it earns the ratio marks by itself.")]))

C.append(Q(U, 'test_cross', 'SAQ', 'saq4', 34, 31,
    "Define and design a test-cross.",
    years=[('ap',2016),('ap',2022),('ts',2016),('ts',2022)],
    split=[("Definition",1),("What it is used for",1),("The design",1),("The two ratios",1)],
    insider="'Design' means draw it. A definition without the cross written out will not score the "
            "design marks, however well worded.",
    steps=[
      S('s1_define','text','Definition',1,'Definition',
        lines=["A TEST CROSS is a cross between an individual",
               "showing the DOMINANT character and the",
               "HOMOZYGOUS RECESSIVE parent.",
               "The recessive parent is always used, because it",
               "contributes only recessive alleles."],
        why="A homozygous recessive parent can only give recessive gametes, so anything dominant that "
            "appears in the progeny must have come from the unknown parent.",
        mistakes=["Crossing with a dominant parent. A test cross uses the HOMOZYGOUS RECESSIVE one.",
                  "Leaving out 'homozygous'. A heterozygous partner would not give a clean answer."],
        tip="Cross it with a plant that can hide nothing.",
        note="Definition plus one line on why the recessive parent. Five lines."),
      S('s2_use','text','What it is used for',1,'Purpose',
        lines=["A test cross is used to find out whether an",
               "individual showing the dominant character is",
               "HOMOZYGOUS (TT) or HETEROZYGOUS (Tt).",
               "Both look the same from outside, so the",
               "genotype cannot be told by appearance."],
        why="Two different genotypes can produce the same appearance, so the only way to tell them apart "
            "is to look at what they produce.",
        mistakes=["Saying a test cross finds the phenotype. The phenotype is already visible; the cross "
                  "finds the GENOTYPE.",
                  "Saying it works on recessive individuals. A recessive individual's genotype is "
                  "already known — it must be tt."],
        tip="You can see the phenotype; the cross tells you the genotype.",
        note="Say what is unknown and why it cannot be seen."),
      S('s3_design','text','The design',1,'The design',
        lines=["Unknown violet plant (W_)  ×  white (ww)",
               "CASE 1 — if the unknown is HOMOZYGOUS (WW):",
               "  all offspring are Ww, all violet.",
               "  Ratio 1 : 0",
               "CASE 2 — if the unknown is HETEROZYGOUS (Ww):",
               "  offspring are 1 Ww violet : 1 ww white.",
               "  Ratio 1 : 1"],
        why="The two cases give visibly different progeny, so a single cross settles the question by "
            "inspection.",
        mistakes=["Giving only one case. The test works because the TWO cases differ.",
                  "Saying case 1 gives 3:1. A homozygous dominant parent gives ALL dominant offspring."],
        tip="All dominant means homozygous; half recessive means heterozygous.",
        note="Both cases with both ratios. This is the 'design' the question asks for."),
      S('s4_ratios','boxed_final','The two ratios',1,'Ratios',
        lines=[{"text":"Monohybrid test cross 1 : 1;","style":"boxed"},
               {"text":"dihybrid test cross 1 : 1 : 1 : 1","style":"boxed"},
               "A MONOHYBRID test cross of a heterozygote gives",
               "a phenotypic ratio of 1 : 1.",
               "A DIHYBRID test cross of a double heterozygote",
               "gives 1 : 1 : 1 : 1.",
               "In a test cross the phenotypic and genotypic",
               "ratios are the SAME."],
        why="Because the recessive parent adds nothing visible, every progeny class shows the gamete it "
            "received from the unknown parent — so the ratios cannot differ.",
        mistakes=["Giving 3:1 for a monohybrid test cross. That is a SELFING ratio; a test cross gives 1:1.",
                  "Leaving out the dihybrid case. Both ratios are named in the book."],
        tip="Test cross ratios read the gametes directly, so both ratios match.",
        note="Both ratios plus the reason they are equal. That last line is worth writing."),
      S('s5_diagram','diagram','Diagram — test cross',0,None,
        figure=G.TESTCROSS,
        why="The square has only one row because the recessive parent makes only one kind of gamete, and "
            "that single row is the whole reason a test cross works.",
        mistakes=["Drawing a full 2 by 2 square. The recessive parent gives ONE gamete, so there is one row.",
                  "Giving the recessive parent two different gametes. ww makes only w.",
                  "Labelling the progeny with genotypes but no phenotypes. Both are read off this square."],
        tip="One row, because one parent has only one gamete to give.",
        note="No diagram mark, but 'design a test cross' invites the drawing. The one-row square is the "
             "clearest thing you can put on the page.")]))

C.append(Q(U, 'codominance', 'SAQ', 'saq5', 35, 31,
    "Explain co-dominance with an example.",
    split=[("What co-dominance is",1),("The lentil example",1),("The F1 generation",1),("The F2 ratio",1)],
    note_extra="BOOK ERROR, corrected on this card, and it has two faults in one printed line. The "
               "guide's F2 legend reads \"1 CˢCˢ (spotted) : 2 CˢCᴰ (spotted & dotted) : 3 CᴰCᴰ "
               "(spotted & dotted)\". The third class is ONE, not three — a 2x2 Punnett square cannot "
               "give a 1:2:3 — and CᴰCᴰ is DOTTED, not \"spotted & dotted\". The correct legend is "
               "1 spotted : 2 spotted and dotted : 1 dotted.",
    insider="Co-dominance and incomplete dominance are the pair examiners set against each other. "
            "Co-dominance shows BOTH parent characters; incomplete dominance shows a NEW one in between. "
            "Say which is which.",
    steps=[
      S('s1_what','text','What co-dominance is',1,'Definition',
        lines=["CO-DOMINANCE is the condition in which BOTH",
               "alleles of a pair are EQUALLY dominant.",
               "In the heterozygote, both alleles express",
               "themselves FULLY and INDEPENDENTLY.",
               "Neither allele is dominant or recessive to the",
               "other."],
        why="Both alleles being expressed fully is what makes the heterozygote show two characters at "
            "once rather than one, or a blend.",
        mistakes=["Saying co-dominance gives a blended character. That is INCOMPLETE dominance.",
                  "Saying one allele is partly dominant. In co-dominance BOTH are fully expressed."],
        tip="Both show, and both show completely.",
        note="Definition with the words 'both' and 'fully'. This is the contrast with the next question."),
      S('s2_example','text','The lentil example',1,'Example',
        lines=["Example 1: the ABO blood groups in humans.",
               "The alleles I^A and I^B are co-dominant, so a",
               "person carrying both has blood group AB.",
               "Example 2: seed coat pattern in LENTIL plants.",
               "A pure-breeding SPOTTED lentil (CˢCˢ) is crossed",
               "with a pure-breeding DOTTED lentil (CᴰCᴰ)."],
        why="Blood group AB is the clearest case in the whole of genetics: the person is not "
            "intermediate between A and B but genuinely both.",
        mistakes=["Naming no example. The question asks for one.",
                  "Giving snapdragon flower colour. That is INCOMPLETE dominance, not co-dominance."],
        tip="Blood group AB is both, not in between.",
        note="Give both examples if you have room. The blood group one is the strongest."),
      S('s3_f1','text','The F1 generation',1,'F1',
        lines=["The F₁ heterozygotes (CˢCᴰ) are BOTH SPOTTED",
               "AND DOTTED.",
               "They show the phenotypic features of BOTH",
               "parents at the same time.",
               "Neither the spotted nor the dotted allele is",
               "dominant or recessive to the other."],
        why="The F1 carrying both patterns at once, rather than one of them or a mixture, is the "
            "observation that defines co-dominance.",
        mistakes=["Saying the F1 is intermediate. It is not a blend; it shows BOTH patterns separately.",
                  "Saying the F1 resembles one parent. It resembles BOTH."],
        tip="Not in between, but both at once.",
        note="Say 'both, at the same time'. The word 'blend' must not appear."),
      S('s4_f2','boxed_final','The F2 ratio',1,'F2 ratio',
        lines=[{"text":"F₂ = 1 spotted : 2 both : 1 dotted","style":"boxed"},
               "Selfing the F₁ gives:",
               "1 CˢCˢ  spotted",
               "2 CˢCᴰ  spotted AND dotted",
               "1 CᴰCᴰ  dotted",
               "The phenotypic and genotypic ratios are the",
               "SAME, 1 : 2 : 1, because every genotype has its",
               "own appearance."],
        why="Because each of the three genotypes looks different, the two ratios cannot differ — which "
            "is the same reason incomplete dominance also gives 1:2:1.",
        mistakes=["Writing the third class as 3. A 2 by 2 square gives 1:2:1, never 1:2:3. The guide "
                  "misprints this.",
                  "Calling CᴰCᴰ 'spotted and dotted'. It is DOTTED — it carries no spotted allele.",
                  "Giving 3:1. That is the ratio for complete dominance."],
        tip="Three genotypes, three different looks, so 1:2:1 twice over.",
        note="All three classes with their genotypes and appearances, then the reason the ratios match."),
      S('s5_diagram','diagram','Diagram — co-dominance in lentil',0,None,
        figure=G.CODOMINANCE,
        why="Setting the three F2 genotypes in a square shows immediately that there is one of the third "
            "class and not three, which is where the printed guide goes wrong.",
        mistakes=["Drawing an F1 that looks like one parent. The F1 shows BOTH patterns.",
                  "Writing a 1:2:3 ratio under the square. Four boxes cannot give six offspring.",
                  "Marking the CᴰCᴰ box as spotted and dotted. It is DOTTED."],
        tip="Four boxes, so the classes must add to four: 1 + 2 + 1.",
        note="No diagram mark. Draw it anyway on this question — the square is what protects you from "
             "the wrong ratio the guide prints.")]))

C.append(Q(U, 'incomplete_dominance', 'SAQ', 'saq6', 36, 32,
    "Explain incomplete dominance with an example.",
    years=[('ts',2015),('ts',2017),('ts',2018),('ts',2019)],
    split=[("What incomplete dominance is",1),("The snapdragon example",1),
           ("The F2 generation",1),("Why the ratios change",1)],
    insider="The sentence that earns the last mark is that the PHENOTYPIC ratio changes from 3:1 to "
            "1:2:1 while the GENOTYPIC ratio stays exactly as Mendel found it.",
    steps=[
      S('s1_what','text','What incomplete dominance is',1,'Definition',
        lines=["INCOMPLETE DOMINANCE is the condition in which",
               "NEITHER allele is completely dominant nor",
               "completely recessive.",
               "The heterozygote shows an INTERMEDIATE",
               "character, different from both parents."],
        why="Neither allele fully masking the other is what produces a third appearance that neither "
            "parent had.",
        mistakes=["Saying both characters appear. That is CO-DOMINANCE; here a NEW intermediate appears.",
                  "Saying one allele is recessive. Neither is completely dominant or recessive."],
        tip="A new middle character, not both characters.",
        note="Definition with the word intermediate. This is the contrast with co-dominance."),
      S('s2_example','text','The snapdragon example',1,'Example',
        lines=["Example: flower colour in the DOG FLOWER",
               "(snapdragon, Antirrhinum).",
               "A homozygous RED flowered plant (RR) is crossed",
               "with a homozygous WHITE flowered plant (rr).",
               "The F₁ (Rr) is PINK — a colour neither parent",
               "had."],
        why="Pink is not a mixture of red and white flowers but a colour of its own, produced because one "
            "R allele makes only half the pigment.",
        mistakes=["Naming the ABO blood groups. That is CO-DOMINANCE.",
                  "Saying the F1 is red. The F1 of this cross is PINK."],
        tip="Red and white parents, pink children.",
        note="Name the plant, the cross, and the F1 colour. Five lines."),
      S('s3_f2','text','The F2 generation',1,'F2',
        lines=["Selfing the F₁ pink plants gives:",
               "1 RR  RED",
               "2 Rr  PINK",
               "1 rr  WHITE",
               "So the F₂ ratio is 1 : 2 : 1."],
        why="The genotypes come out in the ordinary Mendelian proportions; only the way they look has "
            "changed.",
        mistakes=["Giving 3:1. The phenotypic ratio here is 1:2:1.",
                  "Saying the pink disappears in F2. Half the F2 plants are pink."],
        tip="Same square, three visible classes instead of two.",
        note="All three classes with genotype and colour. Five lines."),
      S('s4_ratios','boxed_final','Why the ratios change',1,'Ratios',
        lines=[{"text":"Genotypic ratio unchanged at 1 : 2 : 1;","style":"boxed"},
               {"text":"phenotypic ratio changes from 3 : 1 to 1 : 2 : 1","style":"boxed"},
               "The GENOTYPIC ratio is exactly as in Mendel's",
               "monohybrid cross: 1 : 2 : 1.",
               "The PHENOTYPIC ratio has changed from 3 : 1 to",
               "1 : 2 : 1.",
               "This is because R is incompletely dominant over",
               "r, so Rr (pink) can be told apart from RR (red)."],
        why="Mendel's laws still hold — the alleles segregate exactly as he said — and only the "
            "visibility of the heterozygote has changed.",
        mistakes=["Saying incomplete dominance breaks Mendel's laws. The GENOTYPIC ratio is unchanged.",
                  "Giving one ratio only. The whole point is that the two ratios now differ from 3:1."],
        tip="The genes behave exactly as Mendel said; only the heterozygote now shows.",
        note="Both ratios, and the reason. This is the mark that separates a full answer."),
      S('s5_diagram','diagram','Diagram — incomplete dominance',0,None,
        figure=G.INCOMPLETE,
        why="Drawn beside the ordinary monohybrid square it is the same four boxes, and only the colour "
            "written in the two middle ones has changed.",
        mistakes=["Drawing a pink parent. BOTH parents are pure: red and white.",
                  "Marking the Rr boxes red. They are PINK.",
                  "Writing 3:1 under the square. Here it is 1:2:1."],
        tip="Same square as Mendel's; only the middle two boxes look different.",
        note="No diagram mark. The square is worth drawing because the two middle boxes carry the "
             "whole idea.")]))

C.append(Q(U, 'chromosomal_and_gene_mutations', 'SAQ', 'saq7', 37, 32,
    "Write a brief note on chromosomal mutations and gene mutations.",
    years=[('ts',2022)],
    split=[("What a mutation is",1),("Chromosomal mutation",1),("Gene mutation",1),("The difference",1)],
    insider="Scale is the whole answer: a chromosome versus a single base pair. Say that in one line "
            "and both halves fall into place.",
    steps=[
      S('s1_what','text','What a mutation is',1,'Mutation',
        lines=["A MUTATION is a sudden, heritable change in the",
               "genetic material of an organism.",
               "Mutations are of two main kinds:",
               "1. chromosomal mutations  2. gene mutations"],
        why="Both kinds are changes to the same DNA and differ only in how much of it changes, which is "
            "why they belong under one definition.",
        mistakes=["Saying mutations are always harmful. Many are neutral and some are useful.",
                  "Saying mutations are not inherited. A mutation in a germ cell IS inherited."],
        tip="Sudden, heritable, and of two sizes.",
        note="Definition plus the two kinds named. Four lines."),
      S('s2_chromosomal','text','Chromosomal mutation',1,'Chromosomal',
        lines=["1. CHROMOSOMAL MUTATION is a change in the",
               "NUMBER or the STRUCTURE of chromosomes.",
               "Loss or gain of a segment of DNA alters the",
               "chromosome.",
               "Such changes are called chromosomal",
               "ABERRATIONS.",
               "Example: they are commonly seen in CANCER",
               "cells."],
        why="A chromosome carries hundreds of genes, so changing one affects many genes at once — which "
            "is why the effects are usually severe.",
        mistakes=["Saying a chromosomal mutation changes one base. That is a GENE mutation.",
                  "Giving only structure. NUMBER changes are chromosomal mutations too."],
        tip="Whole chromosomes: their number or their shape.",
        note="Both kinds of change, the term aberration, and one example."),
      S('s3_gene','text','Gene mutation',1,'Gene',
        lines=["2. GENE MUTATION is a change in a SINGLE BASE",
               "PAIR of DNA.",
               "It is also called a POINT MUTATION.",
               "Example: SICKLE CELL ANAEMIA in humans, caused",
               "by a single base change in the gene for the",
               "beta chain of haemoglobin."],
        why="One base changed means one amino acid changed, and sickle cell anaemia shows that a "
            "single such change can be enough to cause a disease.",
        mistakes=["Saying a gene mutation affects the whole chromosome. It affects ONE base pair.",
                  "Naming no example. Sickle cell anaemia is the standard one."],
        tip="One base pair, one amino acid, one disease.",
        note="Definition, the other name, and the named disease."),
      S('s4_difference','boxed_final','The difference',1,'Difference',
        lines=[{"text":"Chromosomal: many genes. Gene: one base pair","style":"boxed"},
               "A chromosomal mutation changes many genes at",
               "once, because a chromosome carries many genes.",
               "A gene mutation changes one base pair in one",
               "gene.",
               "The difference between them is one of SCALE."],
        why="Naming the difference as one of scale is the shortest correct summary and shows the two "
            "were not simply memorised as separate facts.",
        mistakes=["Treating the two as unrelated. Both are changes to DNA; only the amount differs.",
                  "Ending without a comparison. The question sets them side by side, so compare them."],
        tip="Same material, different amount of it.",
        note="One line naming scale as the difference. Five lines.")]))

C.append(Q(U, 'segregation_and_assortment', 'SAQ', 'saq8', 38, 32,
    "Define the law of Segregation and the law of Independent Assortment.",
    split=[("Law of segregation",1),("Why it is called purity of gametes",1),
           ("Law of independent assortment",1),("Which cross each comes from",1)],
    insider="Both laws are about GAMETES. Say the word gamete in both definitions and neither can be "
            "confused for the other.",
    steps=[
      S('s1_segregation','text','Law of segregation',1,'Segregation',
        lines=["The LAW OF SEGREGATION states that the two",
               "alleles of a gene, when present together in a",
               "heterozygote, do NOT fuse or blend.",
               "They remain distinct, and SEGREGATE from each",
               "other during MEIOSIS.",
               "Each gamete therefore carries only ONE of the",
               "two alleles."],
        why="If alleles blended, the recessive character could never reappear unchanged in F2 — so the "
            "law is what the F2 observation forces.",
        mistakes=["Saying the alleles blend. The whole law is that they do NOT.",
                  "Leaving out meiosis. Segregation happens during MEIOSIS, when gametes form."],
        tip="They travel together but they never mix.",
        note="Do not blend, do segregate, one per gamete. All three parts."),
      S('s2_purity','text','Why it is called purity of gametes',1,'Purity',
        lines=["The law is also called the LAW OF PURITY OF",
               "GAMETES.",
               "A gamete is PURE because it carries only one",
               "allele of a pair, never both and never a",
               "mixture.",
               "This law has NO exceptions."],
        why="A gamete is haploid, so it can only carry one of the two alleles — the law follows directly "
            "from meiosis rather than being an extra assumption.",
        mistakes=["Saying gametes carry both alleles. A gamete carries ONE.",
                  "Leaving out the alternative name. It is what the question is often asked by."],
        tip="One allele per gamete, so the gamete is pure.",
        note="The alternative name and why it fits. This is a whole mark."),
      S('s3_assortment','text','Law of independent assortment',1,'Assortment',
        lines=["The LAW OF INDEPENDENT ASSORTMENT states that",
               "when two individuals differ in TWO OR MORE",
               "pairs of contrasting characters, the",
               "inheritance of one pair of factors is",
               "INDEPENDENT of the other pair.",
               "So a dihybrid YyRr makes FOUR kinds of gamete —",
               "YR, Yr, yR, yr — in equal numbers."],
        why="Two gene pairs on different chromosomes line up independently at meiosis, so every "
            "combination of them is equally likely in the gametes.",
        mistakes=["Saying the two characters are inherited together. They are inherited INDEPENDENTLY.",
                  "Giving two kinds of gamete for a dihybrid. A double heterozygote makes FOUR."],
        tip="Two coins tossed together: each lands on its own.",
        note="Definition plus the four gamete types. The gamete list proves the law."),
      S('s4_which','boxed_final','Which cross each comes from',1,'Sources',
        lines=[{"text":"Segregation from the monohybrid cross;","style":"boxed"},
               {"text":"assortment from the dihybrid cross","style":"boxed"},
               "The law of SEGREGATION is based on the results",
               "of the MONOHYBRID cross.",
               "The law of INDEPENDENT ASSORTMENT is based on",
               "the results of the DIHYBRID cross, which gives",
               "the 9 : 3 : 3 : 1 ratio in F₂.",
               "Independent assortment holds only for genes on",
               "DIFFERENT chromosomes."],
        why="Genes on the same chromosome tend to travel together, so the law has a real limit — which "
            "is exactly what linkage is.",
        mistakes=["Swapping the two crosses. Segregation comes from the MONOHYBRID cross.",
                  "Saying independent assortment always holds. It fails for LINKED genes on the same "
                  "chromosome."],
        tip="One character gives segregation; two give assortment.",
        note="Both sources, the 9:3:3:1 ratio, and the limitation. The limitation is worth the line."),
      S('s5_diagram','diagram','Diagram — gamete formation',0,None,
        figure=G.GAMETES,
        why="Both laws are statements about gametes, so drawing the gametes a heterozygote and a "
            "dihybrid actually make is the shortest way to show both at once.",
        mistakes=["Drawing a gamete carrying Tt. A gamete carries ONE allele: T or t.",
                  "Drawing two kinds of gamete from YyRr. A dihybrid makes FOUR.",
                  "Drawing the four dihybrid gametes in unequal numbers. They are formed in EQUAL numbers."],
        tip="Two from one gene pair, four from two gene pairs.",
        note="No diagram mark. This little figure is the fastest revision of both laws on one page.")]))

# ═══════════════════ VSAQ (Section A, 2 marks) ═══════════════════
def vs(slug, ref, gno, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, 42, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('test_cross_name_and_use','vsaq1',82,
   "What is the cross between the F1 progeny and the homozygous recessive parent called? How is it useful?",
   [("The name",1),("Its use",1)],
   "One word for the name, one sentence for the use. The word GENOTYPE has to appear in the second half.",
   [S('s1_name','text','The name',1,'Name',
      lines=["Such a cross is called a TEST CROSS."],
      why="The cross has a name of its own because it is a deliberate test rather than an ordinary "
          "breeding step.",
      mistakes=["Calling it a back cross. A back cross is with EITHER parent; a test cross is with the "
                "homozygous RECESSIVE one.",
                "Calling it a monohybrid cross. That names the number of characters, not the purpose."],
      tip="It is a test, so it is called a test cross.",
      note="One line. Do not confuse it with a back cross."),
    S('s2_use','boxed_final','Its use',1,'Use',
      lines=[{"text":"It reveals the GENOTYPE behind a dominant","style":"boxed"},
             {"text":"appearance","style":"boxed"},
             "It is used to determine the GENOTYPE of the test",
             "organism: whether it is homozygous or",
             "heterozygous.",
             "All dominant offspring means homozygous;",
             "a 1 : 1 ratio means heterozygous."],
      why="The recessive parent contributes nothing visible, so every offspring displays the allele it "
          "got from the unknown parent.",
      mistakes=["Saying it finds the phenotype. The phenotype is already visible.",
                "Giving no ratios. The two outcomes are what make it useful."],
      tip="All dominant means pure; half recessive means hybrid.",
      note="Purpose plus both outcomes. Five lines.")],
   years=[('ts',2015),('ts',2017),('ts',2022)])

vs('linked_genes','vsaq2',83,
   "Do you think Mendel's laws of inheritance would have been different if the characters he chose were located on the same chromosome?",
   [("The answer",1),("The reason",1)],
   "Answer YES, then name the law that would have failed. Naming independent assortment specifically "
   "is what earns the second mark.",
   [S('s1_answer','text','The answer',1,'Yes',
      lines=["YES. Mendel's laws would have been different.",
             "Specifically, the LAW OF INDEPENDENT ASSORTMENT",
             "would not have held."],
      why="Only one of the three laws depends on the genes being on different chromosomes, so the answer "
          "has to name which one.",
      mistakes=["Answering with a bare 'yes'. The mark is for naming which law fails.",
                "Saying all three laws would fail. Segregation and dominance still hold for linked genes."],
      tip="Only independent assortment depends on separate chromosomes.",
      note="Yes plus the named law. Three lines."),
    S('s2_reason','boxed_final','The reason',1,'Reason',
      lines=[{"text":"Genes on one chromosome are","style":"boxed"},
             {"text":"inherited TOGETHER","style":"boxed"},
             "Genes located on the SAME chromosome are",
             "inherited TOGETHER, because they travel together",
             "into the same gamete.",
             "They are called LINKED genes, and the phenomenon",
             "is LINKAGE.",
             "So they do not assort independently."],
      why="A chromosome moves as one piece at meiosis, so genes riding on it cannot be separated except "
          "by crossing over.",
      mistakes=["Leaving out the word 'together'. The guide's own sentence drops it and reads as a "
                "fragment; inherited TOGETHER is the point.",
                "Not naming linkage. It is the term for this."],
      tip="Same chromosome, same journey.",
      note="Say inherited together, name linkage, and state the consequence.")])

vs('chromosome_theory','vsaq3',84,
   "Who proposed the Chromosome theory of Inheritance?",
   [("The names",1),("What the theory says",1)],
   "Two names is the first mark. Do not stop there — one line on what they proposed earns the second.",
   [S('s1_names','text','The names',1,'Names',
      lines=["The CHROMOSOME THEORY OF INHERITANCE was proposed",
             "by SUTTON and BOVERI, in 1902."],
      why="Two workers reached the same conclusion independently, which is why both names are always "
          "given together.",
      mistakes=["Naming Mendel. Mendel knew nothing of chromosomes.",
                "Naming Morgan. Morgan proved the theory later with Drosophila; Sutton and Boveri "
                "proposed it."],
      tip="Sutton and Boveri proposed it; Morgan proved it.",
      note="Both names and the year. Two lines."),
    S('s2_says','boxed_final','What the theory says',1,'The theory',
      lines=[{"text":"Mendel's factors are carried on chromosomes","style":"boxed"},
             "The theory states that Mendel's FACTORS (genes)",
             "are located on CHROMOSOMES.",
             "The behaviour of chromosomes during meiosis",
             "exactly parallels the behaviour of Mendel's",
             "factors: both occur in pairs and both segregate."],
      why="Chromosomes pair and separate at meiosis exactly as Mendel said his factors must, and that "
          "parallel is the entire argument of the theory.",
      mistakes=["Saying the theory discovered chromosomes. Chromosomes were already known; the theory "
                "linked them to Mendel's factors.",
                "Giving only the names. The second mark is for the content."],
      tip="Chromosomes behave the way Mendel's factors had to behave.",
      note="State the link and the parallel behaviour. This half is often left out.")],
   years=[('ts',2020),('ts',2022),('ap',2017),('ap',2019),('ap',2022)])

vs('true_breeding','vsaq4',85,
   "Define true breeding. Mention its significance.",
   [("Definition",1),("Significance",1)],
   "Two halves. The significance is about generations — say that the trait stays the same over several "
   "of them.",
   [S('s1_define','text','True breeding defined',1,'Definition',
      lines=["A TRUE BREEDING line is one that, after continuous",
             "SELF POLLINATION, shows the same trait in every",
             "generation.",
             "It is homozygous for that trait."],
      why="Only a homozygote can breed true, because it has just one kind of allele to pass on.",
      mistakes=["Saying true breeding means cross pollination. It is produced by continuous SELF "
                "pollination.",
                "Leaving out homozygous. Being homozygous is what makes a line breed true."],
      tip="Self it long enough and only one allele is left.",
      note="Definition with self pollination and homozygous. Four lines."),
    S('s2_sig','boxed_final','Significance',1,'Significance',
      lines=[{"text":"A known, unchanging starting point for a cross","style":"boxed"},
             "It shows STABLE inheritance and expression of a",
             "trait over several generations.",
             "True breeding lines give an experimenter parents",
             "of KNOWN genotype, which is what Mendel needed",
             "before he could cross anything."],
      why="Without pure parents the F1 would already be mixed, and no ratio in F2 could be interpreted.",
      mistakes=["Giving no significance. It is a whole mark.",
                "Saying it produces variation. True breeding produces the OPPOSITE — uniformity."],
      tip="You cannot read the result unless you knew what went in.",
      note="Stability plus why an experimenter needs it. Five lines.")],
   years=[('ts',2022)])

vs('phenotype_and_genotype','vsaq5',86,
   "Explain the terms phenotype and genotype.",
   [("Phenotype",1),("Genotype",1)],
   "Two definitions and one example that shows why they differ: TT and Tt are different genotypes with "
   "the SAME phenotype.",
   [S('s1_pheno','text','Phenotype',1,'Phenotype',
      lines=["The PHENOTYPE is the physical appearance of a",
             "character in an organism — what can be seen or",
             "measured.",
             "Example: tall, dwarf, red, white."],
      why="The phenotype is what an observer records, which is why it is the only thing Mendel could "
          "count directly.",
      mistakes=["Saying the phenotype is the gene. That is the GENOTYPE.",
                "Giving no example. One word is enough and it fixes the definition."],
      tip="Phenotype is what you can see.",
      note="Definition plus an example. Four lines."),
    S('s2_geno','boxed_final','Genotype',1,'Genotype',
      lines=[{"text":"TT and Tt look the same but are different","style":"boxed"},
             "The GENOTYPE is the genetic make-up of an",
             "organism — the alleles it carries.",
             "Example: TT, Tt, tt.",
             "TT and Tt have the SAME phenotype (tall) but",
             "DIFFERENT genotypes, which is why a test cross",
             "is needed to tell them apart."],
      why="One phenotype can come from more than one genotype, and that gap between the two is the "
          "reason genetics needs both words.",
      mistakes=["Saying every genotype has its own phenotype. TT and Tt look identical.",
                "Giving no letters. The letter examples are what make the two terms concrete."],
      tip="Genotype is what you carry; phenotype is what shows.",
      note="Definition, examples, and the TT-versus-Tt point that links the two.")],
   years=[('ts',2017),('ts',2018),('ts',2022),('ap',2016),('ap',2017),('ap',2019)])

vs('point_mutation_inheritance','vsaq6',87,
   "What is point mutation? Give an example.",
   [("Definition",1),("Example",1)],
   "Two lines. Sickle cell anaemia is the example, and naming the affected molecule sharpens it.",
   [S('s1_define','text','Point mutation defined',1,'Definition',
      lines=["A POINT MUTATION is a mutation that occurs in a",
             "SINGLE BASE PAIR of a DNA fragment.",
             "It is also called a gene mutation."],
      why="Because only one base changes, the effect can be traced to one amino acid — which is what "
          "makes point mutations so well understood.",
      mistakes=["Saying it changes a whole chromosome. That is a CHROMOSOMAL mutation.",
                "Saying it changes several genes. It changes ONE base pair."],
      tip="One point on the DNA, one base pair.",
      note="Definition plus the other name. Three lines."),
    S('s2_example','boxed_final','Example',1,'Example',
      lines=[{"text":"Sickle cell anaemia: one base, one amino acid","style":"boxed"},
             "Example: SICKLE CELL ANAEMIA in humans.",
             "A single base change in the gene for the beta",
             "chain of haemoglobin replaces glutamic acid with",
             "valine at position 6.",
             "That one substitution changes the shape of the",
             "red blood cell."],
      why="One base changing one amino acid changing the shape of a whole cell is the clearest chain "
          "from DNA to phenotype in the syllabus.",
      mistakes=["Naming Down's syndrome. That is a CHROMOSOMAL mutation, not a point mutation.",
                "Giving the name with no detail. The amino acid substitution is what makes it an "
                "example rather than a label."],
      tip="One letter changed, and the cell changes shape.",
      note="Name the disease and the substitution. Six lines.")],
   years=[('ts',2019)])

vs('wrinkled_genotype','vsaq7',88,
   "What is the genotype of the wrinkled phenotype of pea seeds?",
   [("The genotype",1),("Why it must be that",1)],
   "The answer is two letters, so the second mark has to come from the REASON. Say that a recessive "
   "character needs both alleles recessive.",
   [S('s1_geno','text','The genotype',1,'Genotype',
      lines=["The genotype of the wrinkled phenotype is rr —",
             "homozygous recessive.",
             "Round (R) is dominant over wrinkled (r)."],
      why="Wrinkled is the recessive character in Mendel's seed-shape pair, so it can only show in the "
          "homozygous recessive genotype.",
      mistakes=["Writing Rr. Rr would be ROUND, because R is dominant.",
                "Writing RR. RR is round as well."],
      tip="Wrinkled is recessive, so it must be rr.",
      note="Two letters plus which allele is dominant. Three lines."),
    S('s2_why','boxed_final','Why it must be that',1,'Reason',
      lines=[{"text":"A recessive character shows only when BOTH","style":"boxed"},
             {"text":"alleles are recessive","style":"boxed"},
             "A recessive character is expressed only when NO",
             "dominant allele is present.",
             "RR and Rr are both round; only rr is wrinkled.",
             "So a wrinkled seed can have only ONE possible",
             "genotype, and its genotype is known by sight."],
      why="A recessive phenotype is the one case where appearance alone settles the genotype, which is "
          "exactly why a test cross uses a recessive parent.",
      mistakes=["Saying a wrinkled seed could be Rr. It could not; Rr is round.",
                "Giving no reason. The genotype alone is only half the answer."],
      tip="Recessive on the outside means recessive twice on the inside.",
      note="The rule, the three genotypes, and the useful consequence.")],
   years=[('ap',2015),('ap',2020)])

vs('phenotypic_ratios','vsaq8',89,
   "What will be the phenotypic ratio in the offspring obtained from the following crosses: "
   "(a) Aa × aa (b) AA × aa (c) Aa × Aa (d) Aa × AA?",
   [("Parts a and b",1),("Parts c and d",1)],
   "Four ratios, half a mark each. Work each one on a two-second Punnett square in the margin rather "
   "than from memory.",
   [S('s1_ab','text','Parts a and b',1,'a, b',
      lines=["(a) Aa × aa  gives  Aa and aa",
             "    Phenotypic ratio  1 : 1",
             "(b) AA × aa  gives  all Aa",
             "    Phenotypic ratio  1 : 0  (all dominant)"],
      why="Part (a) is a test cross and part (b) is a cross of two pure lines, which is why one splits "
          "evenly and the other does not split at all.",
      mistakes=["Giving 3:1 for (a). Aa × aa is a TEST CROSS and gives 1:1.",
                "Giving 1:1 for (b). AA × aa gives ALL dominant offspring."],
      tip="A test cross halves; two pure parents give one kind.",
      note="Both crosses with the offspring written out, then the ratio."),
    S('s2_cd','boxed_final','Parts c and d',1,'c, d',
      lines=[{"text":"Only Aa × Aa can produce a recessive offspring","style":"boxed"},
             "(c) Aa × Aa  gives  1 AA : 2 Aa : 1 aa",
             "    Phenotypic ratio  3 : 1",
             "(d) Aa × AA  gives  AA and Aa, all dominant",
             "    Phenotypic ratio  1 : 0"],
      why="A recessive offspring needs a recessive allele from BOTH parents, so only the cross where "
          "both parents carry one can produce it.",
      mistakes=["Giving 3:1 for (d). Aa × AA gives ALL dominant, because AA has no recessive allele.",
                "Giving 1:2:1 as the phenotypic ratio for (c). 1:2:1 is the GENOTYPIC ratio; the "
                "phenotypic ratio is 3:1."],
      tip="No recessive allele in one parent means no recessive offspring.",
      note="Both crosses, both ratios, and keep genotype separate from phenotype.")],
   years=[('ts',2016)])

main(C, U)
