# -*- coding: utf-8 -*-
"""Unit 14 — Microbes in Human Welfare. Book VSAQ ch.21 (pp.48-49). Globals 135-150.
The blue print gives this unit 4 marks as 2 + 2 VSAQ; the book prints no SAQ or LAQ for
it and none is invented.

DUPLICATE: globals 146 and 150 are the SAME question with the SAME printed answer, on
facing halves of the same spread. ONE card is authored, from the first occurrence, and
the repeat is recorded on it. So 16 printed numbers give 15 cards."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main

U = 14
C = []


def vs(slug, ref, gno, page, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, page, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('swiss_cheese_holes','vsaq1',135,48,
   "Why does Swiss cheese have big holes? Name the bacteria responsible for it.",
   [("Why the holes",1),("The bacterium",1)],
   "Two facts: carbon dioxide, and Propionibacterium. Both are short, so write both.",
   [S('s1_why','text','Why the holes',1,'The gas',
      lines=["The large holes in Swiss cheese are caused by the",
             "production of large amounts of CARBON DIOXIDE.",
             "The gas is trapped in the setting cheese and",
             "forms bubbles, which become the holes."],
      why="The cheese sets while the bacteria are still producing gas, so the bubbles are trapped where "
          "they form.",
      mistakes=["Saying the holes are made by air. They are made by CARBON DIOXIDE from the bacteria.",
                "Saying the holes are cut into the cheese. They form as the cheese sets."],
      tip="Trapped gas in setting cheese.",
      note="The gas and how it is trapped. Four lines."),
    S('s2_bacterium','boxed_final','The bacterium',1,'Bacterium',
      lines=[{"text":"Propionibacterium makes the carbon dioxide","style":"boxed"},
             "The bacterium responsible is PROPIONIBACTERIUM",
             "(Propionibacterium sharmanii).",
             "The bacteria used for cheese also give it its",
             "characteristic flavour and texture."],
      why="The same fermentation that makes the gas also makes the flavour compounds, which is why one "
          "bacterium is chosen for both.",
      mistakes=["Naming Lactobacillus. Lactobacillus makes curd; PROPIONIBACTERIUM makes the Swiss "
                "cheese holes.",
                "Naming no bacterium. Half the question is the name."],
      tip="Propionibacterium for the holes.",
      note="The genus and the species if you know it, plus the flavour point.")],
   years=[('ts',2017),('ts',2018),('ts',2020),('ap',2016),('ap',2018),('ap',2020)])

vs('fermentors','vsaq2',136,48,
   "What are fermentors?",
   [("What they are",1),("What is made in them",1)],
   "A one-line definition with a list attached. 'Large vessels' plus two products is the whole answer.",
   [S('s1_what','text','What they are',1,'Definition',
      lines=["FERMENTORS (bioreactors) are LARGE VESSELS in",
             "which microbes are grown on an industrial scale.",
             "They control temperature, pH, oxygen and stirring,",
             "so the microbes grow under the best conditions.",
             "They may hold 100 to 1000 litres."],
      why="Growing microbes in a flask makes grams; growing them in a controlled thousand-litre vessel "
          "makes a saleable quantity.",
      mistakes=["Saying a fermentor is a small flask. They are LARGE industrial vessels.",
                "Leaving out the controlled conditions. That is what distinguishes a fermentor from a tank."],
      tip="A tank with the conditions controlled.",
      note="Size, what is controlled, and the volume figure."),
    S('s2_products','boxed_final','What is made in them',1,'Products',
      lines=[{"text":"Beverages, antibiotics, enzymes and hormones","style":"boxed"},
             "Fermentors are used to produce BEVERAGES and",
             "ANTIBIOTICS on a large scale.",
             "They are also used for industrial ENZYMES,",
             "organic acids and hormones such as insulin."],
      why="Anything a microbe can make becomes a product once it can be made in a thousand-litre vessel "
          "under controlled conditions.",
      mistakes=["Naming one product. Beverages AND antibiotics are both in the book's answer.",
                "Saying fermentors are only for alcohol. Antibiotics and enzymes are equally important."],
      tip="If a microbe makes it, a fermentor makes it in quantity.",
      note="Both named products plus two more. Five lines.")],
   years=[('ts',2022),('ap',2017),('ap',2022)])

vs('statins','vsaq3',137,48,
   "Name a microbe used for statin production. How do statins lower blood cholesterol level?",
   [("The microbe",1),("How statins work",1)],
   "The mechanism is the second mark and it is one phrase: competitive inhibition of the enzyme that "
   "makes cholesterol.",
   [S('s1_microbe','text','The microbe',1,'Microbe',
      lines=["The microbe used for statin production is",
             "MONASCUS PURPUREUS.",
             "NCERT and this book describe it as a yeast; it is",
             "in fact a filamentous fungus, the red mould of",
             "red yeast rice."],
      why="Statins were found as a natural product of a mould long before anyone set out to design a "
          "cholesterol drug.",
      mistakes=["Naming Penicillium. Penicillium makes PENICILLIN; Monascus purpureus makes statins.",
                "Spelling it Monascus purpurus. The species is purpureus."],
      tip="Monascus purpureus, the red mould.",
      note="The full name, and one line on what kind of organism it is."),
    S('s2_how','boxed_final','How statins work',1,'Mechanism',
      lines=[{"text":"They block the enzyme that makes cholesterol","style":"boxed"},
             "Statins lower blood cholesterol by COMPETITIVELY",
             "INHIBITING the enzyme responsible for the",
             "SYNTHESIS of cholesterol.",
             "Because the statin resembles the enzyme's own",
             "substrate, it occupies the active site and the",
             "enzyme cannot work.",
             "Less cholesterol is made, so the blood level falls."],
      why="Statins are a real example of the competitive inhibition defined in the enzymes chapter, "
          "which is why the two topics are worth reading together.",
      mistakes=["Saying statins destroy cholesterol already in the blood. They stop it being MADE.",
                "Leaving out 'competitively'. The word links this to the enzyme inhibitor question."],
      tip="It sits in the enzyme's seat, so nothing gets made.",
      note="Name competitive inhibition and say what is blocked. This is the mark.")],
   years=[('ap',2015),('ts',2016),('ts',2018),('ts',2019),('ts',2022)],
   note_extra="BOOK NOTE: the guide calls Monascus purpureus a yeast, following NCERT. It is in fact a "
              "filamentous FUNGUS, the red mould of red yeast rice. NCERT's wording is kept and the "
              "biology is noted.")

vs('biological_treatment','vsaq4',138,48,
   "Why do we prefer to call secondary waste water treatment biological treatment?",
   [("Why biological",1),("What it achieves",1)],
   "Microbes do the work, and BOD is the measure. Expand BOD correctly: Biochemical Oxygen Demand.",
   [S('s1_why','text','Why biological',1,'Reason',
      lines=["Secondary waste water treatment is called",
             "BIOLOGICAL treatment because LIVING MICROBES do",
             "the work.",
             "The effluent is agitated and aerated, which allows",
             "vigorous growth of useful AEROBIC microbes into",
             "masses called FLOCS."],
      why="Primary treatment is purely physical settling, so the point of the name is that the second "
          "stage uses living organisms instead of machinery.",
      mistakes=["Saying chemicals do the work. Living MICROBES do it, which is why it is biological.",
                "Leaving out flocs. They are the named structures the microbes form."],
      tip="The second stage is done by living things, not machines.",
      note="Name the microbes, the aeration, and the flocs."),
    S('s2_bod','boxed_final','What it achieves',1,'BOD',
      lines=[{"text":"It reduces the BOD of the effluent","style":"boxed"},
             "The microbes consume the organic matter in the",
             "effluent.",
             "This REDUCES the BOD — the BIOCHEMICAL OXYGEN",
             "DEMAND — of the water.",
             "BOD is the amount of oxygen that would be used up",
             "by microbes to break down the organic matter, so a",
             "low BOD means clean water."],
      why="BOD measures how much organic matter is left, so a fall in BOD is a direct measurement that "
          "the treatment worked.",
      mistakes=["Expanding BOD as 'Biological Oxygen Demand'. It is BIOCHEMICAL Oxygen Demand.",
                "Saying treatment raises the BOD. It REDUCES it."],
      tip="Less organic matter left means less oxygen would be demanded.",
      note="Expand BOD correctly, say it falls, and say what a low BOD means.")])

vs('nucleopolyhedrovirus','vsaq5',139,48,
   "What is Nucleopolyhedrovirus being used for nowadays?",
   [("What it is used for",1),("Why it is preferred",1)],
   "Biological control is the answer, and IPM is the programme. Both terms in four lines.",
   [S('s1_use','text','What it is used for',1,'Use',
      lines=["NUCLEOPOLYHEDROVIRUSES are used for the",
             "BIOLOGICAL CONTROL of insect pests.",
             "They infect and kill the pest insect, and they",
             "are species specific."],
      why="A virus that attacks only one insect species can remove a pest without touching anything "
          "else in the field.",
      mistakes=["Saying it is used to treat plant diseases. It is used to KILL insect pests.",
                "Saying it kills all insects. It is species SPECIFIC — that is the point."],
      tip="A virus used as an insecticide.",
      note="Biological control, and the specificity. Four lines."),
    S('s2_why','boxed_final','Why it is preferred',1,'IPM',
      lines=[{"text":"Species specific, so it fits an IPM programme","style":"boxed"},
             "It is desirable in an INTEGRATED PEST MANAGEMENT",
             "(IPM) programme.",
             "Because it has NO ill effect on plants, mammals,",
             "birds, fish or non-target insects, it can be used",
             "where beneficial insects must be preserved.",
             "It is especially useful in ecologically sensitive",
             "areas."],
      why="A chemical insecticide kills the pest's predators as well, which often makes the next "
          "outbreak worse; a species-specific virus does not.",
      mistakes=["Not expanding IPM. Integrated Pest Management is the term.",
                "Saying it is harmful to other species. Its lack of harm is exactly why it is used."],
      tip="It leaves the useful insects alone.",
      note="Expand IPM, list what it does not harm, and say where it matters most.")],
   years=[('ts',2017),('ts',2020),('ap',2019)])

vs('acid_producing_microbes','vsaq6',140,48,
   "Write the most important characteristic that Aspergillus niger, Clostridium butylicum and Lactobacillus share.",
   [("The shared characteristic",1),("Which acid each makes",1)],
   "One shared property and three acids. Naming each acid with its organism is the second mark.",
   [S('s1_shared','text','The shared characteristic',1,'Shared',
      lines=["All three are ACID PRODUCERS.",
             "Each of them is used industrially to produce a",
             "different ORGANIC ACID by fermentation."],
      why="All three convert a cheap sugar substrate into an acid, which is why they are grouped "
          "together despite being a fungus and two bacteria.",
      mistakes=["Saying they are all bacteria. Aspergillus niger is a FUNGUS.",
                "Saying they all make the same acid. Each makes a DIFFERENT one."],
      tip="Three organisms, three acids, one shared job.",
      note="The shared property plus the word fermentation."),
    S('s2_acids','boxed_final','Which acid each makes',1,'The acids',
      lines=[{"text":"Citric, butyric and lactic acid","style":"boxed"},
             "ASPERGILLUS NIGER, a fungus, produces CITRIC ACID.",
             "CLOSTRIDIUM BUTYLICUM, a bacterium, produces",
             "BUTYRIC ACID.",
             "LACTOBACILLUS, a bacterium, produces LACTIC ACID.",
             "In each case the name of the acid is a clue to the",
             "name of the organism, or the other way round."],
      why="Two of the three names carry their product — butylicum gives butyric acid and Lactobacillus "
          "gives lactic acid — which makes them easy to keep apart.",
      mistakes=["Matching the wrong acid to the wrong organism. Aspergillus is CITRIC, Clostridium "
                "butylicum is BUTYRIC, Lactobacillus is LACTIC.",
                "Naming only the acids. Each acid must be matched to its organism."],
      tip="Butylicum makes butyric; Lactobacillus makes lactic.",
      note="All three pairs, and the naming clue. Six lines.")])

vs('gm_crops','vsaq7',141,48,
   "Name any two genetically modified crops.",
   [("Two crops",1),("What each was modified for",1)],
   "Two names, then what each does. The second half turns a bare list into an answer.",
   [S('s1_two','text','Two crops',1,'Names',
      lines=["Two genetically modified crops:",
             "1. BT COTTON",
             "2. BT BRINJAL",
             "Golden rice and Flavr Savr tomato are two more."],
      why="Both carry a Bt gene, which is why they share the prefix and why the name says what was done "
          "to them.",
      mistakes=["Naming a hybrid variety such as Sonalika. A hybrid is BRED, not genetically modified.",
                "Naming one crop. The question asks for two."],
      tip="Bt cotton and Bt brinjal: the Bt is the modification.",
      note="Both names plus two spares. Four lines."),
    S('s2_for','boxed_final','What each was modified for',1,'Purpose',
      lines=[{"text":"Both carry a Bt gene for insect resistance","style":"boxed"},
             "BT COTTON carries cry genes and resists the",
             "cotton BOLLWORM.",
             "BT BRINJAL carries a cry gene and resists the",
             "fruit and shoot BORER.",
             "In both, the plant makes its own insecticidal",
             "protein."],
      why="In both crops the same idea is used against a different pest, which is why the cry gene has "
          "to be matched to the insect.",
      mistakes=["Saying Bt crops are sprayed with Bt. The PLANT makes the protein itself.",
                "Giving no purpose. The reason for the modification is the second mark."],
      tip="Same trick, different pest.",
      note="Each crop with its pest, and the self-made insecticide point.")])

vs('industrial_enzymes','vsaq8',142,49,
   "Name any two industrially important enzymes.",
   [("Two enzymes",1),("What each is used for",1)],
   "Two names, then two uses. Streptokinase is worth naming because its use is dramatic.",
   [S('s1_two','text','Two enzymes',1,'Names',
      lines=["Two industrially important enzymes:",
             "1. LIPASES",
             "2. STREPTOKINASE",
             "AMYLASE and PECTINASE are two more."],
      why="All four are made by microbes in fermentors, which is what makes them industrially available "
          "at all.",
      mistakes=["Naming an enzyme from a plant. The question is about industrially produced ones.",
                "Naming one enzyme. The question asks for two."],
      tip="Lipase, streptokinase, amylase, pectinase.",
      note="Both names plus two spares. Four lines."),
    S('s2_uses','boxed_final','What each is used for',1,'Uses',
      lines=[{"text":"Lipase in detergents; streptokinase clears","style":"boxed"},
             {"text":"blood clots","style":"boxed"},
             "LIPASES are used in DETERGENT formulations, to",
             "remove oily stains from laundry.",
             "STREPTOKINASE, from Streptococcus, is used as a",
             "CLOT BUSTER to remove clots from the blood vessels",
             "of heart attack patients.",
             "PECTINASES and proteases are used to CLARIFY",
             "bottled fruit juices."],
      why="Each enzyme does industrially exactly what it does biologically — lipase digests fat, "
          "streptokinase dissolves fibrin — so the use follows from the name.",
      mistakes=["Giving names with no uses. The uses are the second mark.",
                "Saying streptokinase is used in detergents. It is a medical clot buster."],
      tip="Lipase for fat, streptokinase for clots, pectinase for juice.",
      note="At least two named uses, each matched to its enzyme.")],
   years=[('ts',2017),('ts',2022),('ap',2017),('ap',2019),('ap',2022)])

vs('immunosuppressive_agent','vsaq9',143,49,
   "Name an immunosuppressive agent. From where is it obtained?",
   [("The agent",1),("Its source and use",1)],
   "Cyclosporin A from Trichoderma polysporum. Both names are needed, and the use is a free extra.",
   [S('s1_agent','text','The agent',1,'Agent',
      lines=["CYCLOSPORIN A is used as an immunosuppressive",
             "agent."],
      why="An immunosuppressant is needed because a transplanted organ is foreign tissue that the "
          "recipient's immune system would otherwise destroy.",
      mistakes=["Naming a statin. Statins lower cholesterol; cyclosporin A suppresses the immune system.",
                "Spelling it cyclosporine B. It is cyclosporin A."],
      tip="Cyclosporin A.",
      note="One line. Get the letter A right."),
    S('s2_source','boxed_final','Its source and use',1,'Source',
      lines=[{"text":"From the fungus Trichoderma polysporum","style":"boxed"},
             "It is produced by the FUNGUS TRICHODERMA",
             "POLYSPORUM.",
             "It is used in ORGAN TRANSPLANT patients, to stop",
             "the body rejecting the transplanted organ."],
      why="A fungal product turned out to suppress exactly the immune response that rejects transplants, "
          "which is what made routine organ transplantation possible.",
      mistakes=["Saying it comes from a bacterium. It comes from a FUNGUS.",
                "Giving the name with no source. The question asks where it is obtained from."],
      tip="A fungus made the drug that made transplants possible.",
      note="The organism in full, and the medical use. Five lines.")],
   years=[('ap',2016),('ts',2019)])

vs('methanogens','vsaq10',144,49,
   "What is the group of bacteria found in both the rumen of cattle and the sludge of sewage treatment?",
   [("The group",1),("What they do",1)],
   "One word answers it. The second mark is what they produce — and it is the same gas in both places.",
   [S('s1_group','text','The group',1,'Group',
      lines=["The group is the METHANOGENS.",
             "They are anaerobic bacteria, found in the RUMEN of",
             "cattle and in the ANAEROBIC SLUDGE of sewage",
             "treatment plants."],
      why="Both places are oxygen-free and full of organic matter, which is exactly the habitat these "
          "bacteria need.",
      mistakes=["Naming Lactobacillus. Methanogens are the answer.",
                "Saying they need oxygen. They are ANAEROBIC."],
      tip="No oxygen, plenty of organic matter: methanogens.",
      note="The name and both habitats. Four lines."),
    S('s2_do','boxed_final','What they do',1,'What they make',
      lines=[{"text":"They make BIOGAS, which is mostly methane","style":"boxed"},
             "Methanogens break down cellulose and other organic",
             "matter and produce METHANE.",
             "In cattle they help digest cellulose in the rumen.",
             "In sewage sludge they produce BIOGAS, a mixture of",
             "methane, carbon dioxide and hydrogen, which is",
             "used as a fuel."],
      why="The same bacteria doing the same chemistry are a digestive aid in one place and a fuel source "
          "in the other, which is why the question pairs the two habitats.",
      mistakes=["Saying biogas is pure methane. It is a MIXTURE, mostly methane.",
                "Leaving out the rumen role. In cattle they digest cellulose."],
      tip="One process, two useful outcomes.",
      note="What they produce, and what it is used for in each place.")])

vs('penicillin_scientists','vsaq11',145,49,
   "Name the scientists who were credited for showing the role of penicillin as an antibiotic.",
   [("Who discovered it",1),("Who established its role",1)],
   "Three names and they must be split correctly: Fleming DISCOVERED it, Chain and Florey ESTABLISHED "
   "its role. The question asks about the second pair.",
   [S('s1_discovered','text','Who discovered it',1,'Discovery',
      lines=["ALEXANDER FLEMING discovered PENICILLIN in 1928.",
             "He noticed that a mould growing accidentally on an",
             "unwashed culture plate had stopped the growth of",
             "Staphylococcus bacteria around it."],
      why="Fleming saw the effect but could not purify enough of the substance to test it as a medicine, "
          "which is why the story does not end with him.",
      mistakes=["Crediting Fleming with establishing its role as an antibiotic. He DISCOVERED it; "
                "others proved its use.",
                "Saying he made it deliberately. The mould arrived by accident."],
      tip="Fleming saw it; he did not prove it.",
      note="Name, year, and what he actually observed."),
    S('s2_established','boxed_final','Who established its role',1,'Role',
      lines=[{"text":"Ernest Chain and Howard Florey established","style":"boxed"},
             {"text":"penicillin as an antibiotic","style":"boxed"},
             "ERNEST CHAIN and HOWARD FLOREY established the",
             "role of penicillin as an ANTIBIOTIC.",
             "All THREE shared the Nobel Prize in 1945.",
             "Penicillin was used extensively to treat wounded",
             "soldiers in the Second World War."],
      why="Turning an observation into a medicine needed purification and clinical testing, which is the "
          "work Chain and Florey did.",
      mistakes=["Naming only Fleming. The question asks who showed its ROLE — that is Chain and Florey.",
                "Naming Waksman. Waksman worked on streptomycin."],
      tip="Fleming found it; Chain and Florey made it a medicine.",
      note="Both names, the shared Nobel, and the wartime use.")],
   years=[('ts',2019)])

vs('microbes_in_biotechnology','vsaq12',146,49,
   "Give any two microbes that are used in biotechnology.",
   [("Escherichia coli",1),("Agrobacterium tumefaciens",1)],
   "Two organisms and what each is used FOR. Do not just name them — the use is half the question.",
   [S('s1_ecoli','text','Escherichia coli',1,'E. coli',
      lines=["ESCHERICHIA COLI is a bacterium used as the HOST",
             "organism in recombinant DNA technology.",
             "Its PLASMIDS — pBR322 and pUC19 — are used as",
             "CLONING VECTORS.",
             "It multiplies quickly, so a cloned gene is copied",
             "many times in a few hours."],
      why="A host that divides every twenty minutes turns one recombinant cell into millions overnight, "
          "which is what makes gene cloning practical.",
      mistakes=["Saying E. coli IS a plasmid. It is a BACTERIUM; its plasmids are the vectors. The "
                "guide's printed answer makes this mistake.",
                "Giving the name with no use. The use is what the mark is for."],
      tip="The bacterium is the host; its plasmid is the vector.",
      note="Name it, say it is the host, and name its plasmids as the vectors."),
    S('s2_agro','boxed_final','Agrobacterium tumefaciens',1,'Agrobacterium',
      lines=[{"text":"E. coli hosts the gene; Agrobacterium carries","style":"boxed"},
             {"text":"it into a plant","style":"boxed"},
             "AGROBACTERIUM TUMEFACIENS is a soil bacterium that",
             "naturally infects plants.",
             "Its TI PLASMID is used as a GENE TRANSFER VECTOR",
             "in plants.",
             "It has been disarmed, so it carries the gene in",
             "without causing disease."],
      why="Agrobacterium already had a natural mechanism for pushing its own DNA into plant cells, so "
          "genetic engineers borrowed it rather than inventing one.",
      mistakes=["Saying Agrobacterium is used as a host. It is a VECTOR for plants; E. coli is the host.",
                "Saying the Ti plasmid still causes tumours. It is DISARMED before use."],
      tip="Ti stands for tumour inducing, and it is disarmed before use.",
      note="Name it, name the Ti plasmid, and say it is the PLANT vector."),
    ],
   note_extra="DUPLICATE IN THE SOURCE: this exact question, with the same printed answer, appears "
              "TWICE in the book — as global 146 and again as global 150, both on book p.49. One card "
              "is authored, from the first occurrence. BOOK ERROR corrected here: the printed answer "
              "reads \"Escherichia coli: It is a plasmid used as a cloning vector\". E. coli is a "
              "BACTERIUM; its plasmids are the cloning vectors, and it is itself the host organism.")

vs('lactic_acid_bacteria','vsaq13',147,49,
   "In which food do you find lactic acid bacteria? Name the bacterium.",
   [("The food",1),("The bacterium",1)],
   "Milk and Lactobacillus. Adding what the bacteria do to the milk fills the answer out.",
   [S('s1_food','text','The food',1,'Food',
      lines=["Lactic acid bacteria are found in MILK.",
             "They convert milk into CURD.",
             "They also improve its nutritional quality by",
             "increasing the vitamin B12 content."],
      why="The bacteria turn lactose into lactic acid, and it is the acid that curdles the milk protein.",
      mistakes=["Naming bread. Bread uses YEAST, not lactic acid bacteria.",
                "Saying they spoil the milk. They convert it into curd, which is the point."],
      tip="Milk into curd, and more vitamin B12 with it.",
      note="The food, the product, and the nutritional benefit."),
    S('s2_bacterium','boxed_final','The bacterium',1,'Bacterium',
      lines=[{"text":"Lactobacillus turns milk into curd","style":"boxed"},
             "The bacterium is LACTOBACILLUS, also called LAB —",
             "lactic acid bacteria.",
             "A small amount of curd added to warm milk acts as",
             "the STARTER, which contains millions of them.",
             "They also check disease causing microbes in the",
             "stomach."],
      why="The acid the bacteria produce is what curdles the milk and also what makes the gut a hostile "
          "place for harmful microbes.",
      mistakes=["Naming Propionibacterium. That is the Swiss cheese bacterium.",
                "Leaving out the starter. It is how curd is actually made."],
      tip="A spoonful of curd is a spoonful of Lactobacillus.",
      note="The name, the starter, and the second benefit. Six lines.")])

vs('antibiotic_fungi','vsaq14',148,49,
   "Name any two fungi which are used in the production of antibiotics.",
   [("Two fungi",1),("The antibiotic each gives",1)],
   "Two fungi, two antibiotics. Watch the spelling: Penicillium is the fungus, penicillin is the drug.",
   [S('s1_fungi','text','Two fungi',1,'Fungi',
      lines=["Two fungi used to produce antibiotics:",
             "1. PENICILLIUM NOTATUM",
             "2. PENICILLIUM GRISEOFULVUM",
             "Note the spelling: PenicilliUM is the fungus,",
             "penicillIN is the drug."],
      why="Both are Penicillium species, which is why the fungus and the drug have such similar names "
          "and are so easily confused.",
      mistakes=["Writing 'Pencillium'. It is PENICILLIUM, with an i after the P-e-n.",
                "Naming Aspergillus niger. That produces CITRIC ACID, not an antibiotic."],
      tip="The fungus ends in -ium; the drug ends in -in.",
      note="Both names spelled correctly, plus the spelling note."),
    S('s2_antibiotics','boxed_final','The antibiotic each gives',1,'Antibiotics',
      lines=[{"text":"Penicillin and griseofulvin","style":"boxed"},
             "PENICILLIUM NOTATUM gives PENICILLIN.",
             "PENICILLIUM GRISEOFULVUM gives GRISEOFULVIN.",
             "Griseofulvin is an ANTIFUNGAL antibiotic, used",
             "against fungal infections of skin and nails."],
      why="A fungus producing an antifungal antibiotic is not a contradiction: it is competing with "
          "other fungi for the same food.",
      mistakes=["Matching the wrong drug to the wrong species. Notatum gives penicillin; griseofulvum "
                "gives griseofulvin.",
                "Saying griseofulvin is antibacterial. It is ANTIFUNGAL."],
      tip="Each species is named after what it makes.",
      note="Both pairs, and one line on what griseofulvin treats.")],
   note_extra="BOOK NOTE: the guide prints \"Pencillium notatum\" and \"Pencillin griseoflavus\". The "
              "correct names are PENICILLIUM NOTATUM and PENICILLIUM GRISEOFULVUM. Corrected here.")

vs('antibiotics_in_medicine','vsaq15',149,49,
   "How has the discovery of antibiotics helped mankind in the field of medicine?",
   [("What antibiotics do",1),("Which diseases they defeated",1)],
   "The named diseases are the second mark. Plague, whooping cough, diphtheria and leprosy — write "
   "all four.",
   [S('s1_what','text','What antibiotics do',1,'Action',
      lines=["ANTIBIOTICS are chemical substances produced by",
             "some microbes that KILL or RETARD the growth of",
             "other disease causing microbes.",
             "They act on the microbe without harming the",
             "patient."],
      why="An antibiotic attacks something a bacterium has and a human cell does not, which is why it "
          "can kill the microbe and leave the patient alone.",
      mistakes=["Saying antibiotics kill viruses. They act on BACTERIA and some fungi, not viruses.",
                "Leaving out 'produced by microbes'. That is where antibiotics come from."],
      tip="Made by microbes, used against microbes.",
      note="Definition with both kill and retard, plus the selectivity."),
    S('s2_diseases','boxed_final','Which diseases they defeated',1,'Diseases',
      lines=[{"text":"Plague, whooping cough, diphtheria, leprosy","style":"boxed"},
             "Antibiotics greatly increased our capacity to",
             "treat deadly diseases such as PLAGUE, WHOOPING",
             "COUGH, DIPHTHERIA and LEPROSY.",
             "These used to kill MILLIONS all over the globe.",
             "Antibiotics are one of the reasons average human",
             "life expectancy rose sharply in the last century."],
      why="These four were among the great killers before antibiotics, so naming them measures the size "
          "of the change rather than just asserting it.",
      mistakes=["Naming no disease. The four named ones are the second mark.",
                "Saying antibiotics eliminated all disease. Resistance is now a serious problem."],
      tip="Four names that used to mean death.",
      note="All four diseases, the scale, and the effect on life expectancy.")])

main(C, U)
