# -*- coding: utf-8 -*-
"""Unit 11 — Biotechnology: Principles and Processes. Book LAQ ch.2 (pp.14-16) + VSAQ
ch.18 (p.45). Globals 3, 4 (LAQ) and 107-117 (VSAQ). The blue print gives this unit 10
marks — one 8-mark Section-C question plus one VSAQ — the joint largest in the paper."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main
import figs_u11 as G

U = 11
C = []

C.append(Q(U, 'laq_rdna_processes', 'LAQ', 'laq1', 3, 14,
    "Explain briefly the various processes of recombinant DNA technology.",
    years=[('ap',2016),('ap',2017),('ap',2019),('ap',2022),('ts',2016),('ts',2017),('ts',2019)],
    split=[("Isolation of DNA",1),("Fragmentation of DNA",1),("Isolating the desired fragment",1),
           ("Amplification by PCR",1),("Ligation into a vector",1),("Insertion into the host",1),
           ("Obtaining the product",1),("Downstream processing",1)],
    note_extra="Three slips corrected on this card: the guide writes \"cellulose\" for the enzyme "
               "CELLULASE (cellulose is what the enzyme digests), \"powered detergents\" for POWDERED, "
               "and \"resoluting enzyme digestion\" for RESTRICTION enzyme digestion.",
    insider="Eight steps, eight marks — one mark per step, so the safest structure is eight numbered "
            "headings with two or three lines under each. Never merge two steps to save time; you lose "
            "a whole mark to save four lines.",
    steps=[
      S('s1_isolation','text','Isolation of DNA',1,'Isolation',
        lines=["1. ISOLATION OF DNA",
               "The DNA is enclosed by membranes and surrounded",
               "by other cell contents, so it must be freed.",
               "The cell wall is digested by enzymes:",
               "LYSOZYME for bacteria, CELLULASE for plant",
               "cells, CHITINASE for fungi.",
               "RNA is removed by RIBONUCLEASE and protein by",
               "PROTEASE.",
               "Adding chilled ETHANOL precipitates the DNA as",
               "fine threads, which are collected by SPOOLING."],
        why="Each enzyme is chosen for the wall it has to digest, which is why the three organisms need "
            "three different ones.",
        mistakes=["Writing 'cellulose' as the enzyme. CELLULOSE is the wall material; CELLULASE is the "
                  "enzyme. The guide misprints this.",
                  "Naming one wall-digesting enzyme. Lysozyme, cellulase and chitinase are all expected.",
                  "Leaving out spooling. It is the named step that collects the DNA."],
        tip="One enzyme per wall: lysozyme, cellulase, chitinase.",
        note="Name all three wall enzymes, both cleaning enzymes, ethanol and spooling. This step alone "
             "can be a full mark if the enzymes are right."),
      S('s2_fragmentation','text','Fragmentation of DNA',1,'Fragmentation',
        lines=["2. FRAGMENTATION OF DNA",
               "The purified DNA is cut into fragments by",
               "RESTRICTION ENZYMES.",
               "This process is called RESTRICTION ENZYME",
               "DIGESTION.",
               "The vector and the source DNA are cut with the",
               "SAME enzyme, so their sticky ends match."],
        why="Cutting both molecules with the same enzyme produces complementary sticky ends, which is "
            "the only reason ligase can later join them.",
        mistakes=["Using different enzymes on the two DNAs. They must be cut with the SAME one.",
                  "Writing 'resoluting enzyme digestion'. It is RESTRICTION enzyme digestion."],
        tip="Same enzyme, matching ends.",
        note="Name the enzyme class, name the process, and say why the SAME enzyme is used."),
      S('s3_isolate_fragment','text','Isolating the desired fragment',1,'Separation',
        lines=["3. ISOLATION OF THE DESIRED DNA FRAGMENT",
               "The fragments are separated by AGAROSE GEL",
               "ELECTROPHORESIS.",
               "DNA is NEGATIVELY charged, so it moves towards",
               "the ANODE, the positive electrode.",
               "Smaller fragments travel further.",
               "The band wanted is cut out of the gel and the",
               "DNA recovered by ELUTION."],
        why="Fragments separate by size because the gel resists larger molecules more, so a mixture "
            "becomes a ladder of bands.",
        mistakes=["Saying DNA moves to the cathode. DNA is NEGATIVE, so it moves to the ANODE.",
                  "Leaving out elution. It is the named step that recovers the DNA from the gel."],
        tip="Negative DNA runs to the positive end.",
        note="The technique, the direction and why, and the recovery step."),
      S('s4_pcr','text','Amplification by PCR',1,'PCR',
        lines=["4. AMPLIFICATION BY PCR",
               "PCR is the POLYMERASE CHAIN REACTION.",
               "Multiple copies of the gene of interest are made",
               "in vitro, using two sets of PRIMERS and the",
               "enzyme DNA POLYMERASE.",
               "TAQ POLYMERASE is used because it stays active",
               "at the high temperatures of the cycle.",
               "About 30 cycles produce roughly a BILLION",
               "copies."],
        why="An ordinary DNA polymerase would be destroyed by the heating step, so PCR only became "
            "practical when a heat-stable one was found.",
        mistakes=["Saying PCR uses ordinary DNA polymerase. It uses TAQ polymerase, which survives heat.",
                  "Leaving out the primers. Two sets of primers define which stretch is copied."],
        tip="A heat-proof enzyme is what makes the cycling possible.",
        note="Expand PCR, name the primers and Taq polymerase, and give the billion-copies figure."),
      S('s5_ligation','text','Ligation into a vector',1,'Ligation',
        lines=["5. LIGATION OF THE FRAGMENT INTO A VECTOR",
               "The vector DNA and the source DNA, both cut",
               "with the same endonuclease, have matching",
               "STICKY ENDS.",
               "They are mixed with the enzyme DNA LIGASE.",
               "Ligase joins the two by covalent bonds, giving",
               "a circular hybrid called RECOMBINANT DNA."],
        why="Sticky ends hold the two pieces together by base pairing first; ligase then seals the joint "
            "permanently.",
        mistakes=["Naming the wrong enzyme. Ligase JOINS; restriction enzymes CUT.",
                  "Not naming the product. The product is RECOMBINANT DNA."],
        tip="Restriction enzymes cut, ligase joins.",
        note="Sticky ends, the enzyme, the bond, and the name of the product."),
      S('s6_insertion','text','Insertion into the host',1,'Insertion',
        lines=["6. INSERTION OF rDNA INTO THE HOST CELL",
               "The host is first made COMPETENT by treating it",
               "with divalent calcium (Ca2+) ions.",
               "Three methods are used:",
               "(i) HEAT SHOCK: the cells are incubated with the",
               "rDNA on ice, then briefly heated, so they take",
               "it up.",
               "(ii) MICROINJECTION: the rDNA is injected",
               "directly into the nucleus of an animal cell.",
               "(iii) GENE GUN (biolistics): cells are bombarded",
               "with high velocity gold particles coated with",
               "DNA."],
        why="A bacterial cell wall does not normally let DNA through, so every method is a different way "
            "of forcing or persuading it across.",
        mistakes=["Naming one method. Three are expected: heat shock, microinjection, gene gun.",
                  "Leaving out the calcium treatment. Making the cell COMPETENT comes first."],
        tip="Make it competent, then shock, inject or shoot.",
        note="The competence step and all three methods. This is the longest step; give it the room."),
      S('s7_product','text','Obtaining the product',1,'The product',
        lines=["7. OBTAINING THE FOREIGN GENE PRODUCT",
               "Inside the host, the alien DNA is multiplied",
               "every time the host divides.",
               "The recombinant DNA is EXPRESSED, so the host",
               "makes the desired protein.",
               "Large scale production is carried out in",
               "BIOREACTORS, which may hold 100 to 1000 litres."],
        why="One transformed cell is useless; the value comes from the host dividing until there are "
            "enough of them to make the product in quantity.",
        mistakes=["Saying the gene is expressed outside the cell. It is expressed INSIDE the host.",
                  "Leaving out the bioreactor. It is the named vessel for large scale production."],
        tip="The host does the work; the bioreactor does it at scale.",
        note="Multiplication, expression, and the bioreactor with its volume."),
      S('s8_downstream','boxed_final','Downstream processing',1,'Downstream',
        lines=[{"text":"Isolate, cut, separate, amplify, ligate,","style":"boxed"},
               {"text":"insert, express, purify","style":"boxed"},
               "8. DOWNSTREAM PROCESSING",
               "After the biosynthetic stage, the product must",
               "be processed before it can be sold.",
               "It is SEPARATED from the culture and PURIFIED.",
               "Suitable preservatives are added, and the",
               "product passes clinical trials and quality",
               "control before release."],
        why="A protein sitting in a tank of bacteria is not yet a medicine, so the last step is what "
            "turns a laboratory result into a product.",
        mistakes=["Ending at 'the protein is made'. Downstream processing is the eighth mark.",
                  "Saying downstream processing means growing more cells. It means SEPARATION and "
                  "PURIFICATION of the finished product."],
        tip="Nothing is a product until it has been purified and tested.",
        note="Name the two operations, then the testing. Finish with the eight-step list if there is room."),
      S('s9_diagram','diagram','Diagram — recombinant DNA technology',0,None,
        figure=G.RDNA,
        why="Drawing it makes the one point the eight written steps can hide: the vector and the source "
            "DNA are cut with the SAME enzyme, which is why their ends fit together at all.",
        mistakes=["Drawing the two DNAs cut with different enzymes. They must be cut with the SAME one.",
                  "Drawing the gene inserted without opening the plasmid. The plasmid is CUT open first.",
                  "Drawing the whole recombinant molecule as new. Most of the circle is still the "
                  "original vector; only a short stretch is the inserted gene."],
        tip="Two molecules, one enzyme, one circle, one host.",
        note="No diagram mark — the question says 'explain'. It is worth sketching in the margin: the "
             "picture is what makes the same-enzyme point impossible to forget.")]))

C.append(Q(U, 'laq_rdna_tools', 'LAQ', 'laq2', 4, 16,
    "Give a brief account of the tools of recombinant DNA technology.",
    years=[('ts',2017),('ts',2019),('ts',2020),('ap',2015),('ap',2017),('ap',2019)],
    split=[("The five tools",1),("Restriction enzymes",2),("Polymerase enzymes",1),
           ("Ligases",1),("Vectors",2),("Host organisms",1)],
    insider="Five tools. List all five in the first four lines, then take them in turn — an examiner "
            "scanning for five headings finds them immediately, and the list alone protects a mark.",
    steps=[
      S('s1_five','text','The five tools',1,'The list',
        lines=["Recombinant DNA technology uses FIVE tools:",
               "1. Restriction enzymes",
               "2. Polymerase enzymes",
               "3. Ligases",
               "4. Vectors",
               "5. Host organisms"],
        why="Naming all five first turns the rest of the answer into five labelled sections, which is "
            "exactly how the marks are split.",
        mistakes=["Naming three tools. There are FIVE.",
                  "Calling gel electrophoresis a tool. It is a TECHNIQUE used in the process, not one "
                  "of the five tools."],
        tip="Cut, copy, join, carry, host.",
        note="All five, numbered, before anything is explained. Six lines."),
      S('s2_restriction','equation','Restriction enzymes',2,'Restriction enzymes',
        lines=[{"text": "1. RESTRICTION ENZYMES belong to a larger", "style": "normal"},
               {"text": "class called NUCLEASES. They are of two kinds:", "style": "normal"},
               "(i) EXONUCLEASES remove nucleotides from the",
               "ENDS of a DNA molecule.",
               "(ii) ENDONUCLEASES cut at specific positions",
               "WITHIN the DNA.",
               "Each restriction endonuclease recognises a",
               "specific PALINDROMIC sequence.",
               "A palindrome in DNA reads the same on both",
               "strands, in the same 5' to 3' direction.",
               {"text": "EcoRI recognises the palindrome GAATTC:", "style": "normal"},
               {"text":"5'  G A A T T C  3'","style":"eq"},
               {"text":"3'  C T T A A G  5'","style":"eq"},
               "and cuts between G and A on each strand,",
               "leaving STICKY ENDS."],
        why="Cutting at a palindrome off-centre leaves short single-stranded overhangs on both pieces, "
            "and those overhangs are what make the ends sticky.",
        mistakes=["Saying EcoRI recognises GAA. It recognises the SIX-base palindrome GAATTC. The "
                  "guide's VSAQ answer prints the short version, and it is wrong.",
                  "Swapping exo- and endonucleases. EXO cuts from the ends, ENDO cuts within.",
                  "Not explaining the palindrome. The definition is part of these two marks."],
        tip="Endo cuts inside; exo nibbles the ends.",
        note="Two marks here. Both nuclease types, the palindrome definition, and the EcoRI sequence "
             "written on two lines."),
      S('s3_polymerase','text','Polymerase enzymes',1,'Polymerases',
        lines=["2. POLYMERASE ENZYMES build new DNA strands.",
               "In the POLYMERASE CHAIN REACTION, many copies of",
               "the gene of interest are made using PRIMERS and",
               "DNA polymerase.",
               "TAQ POLYMERASE is used because it remains active",
               "at high temperature.",
               "Repeating the cycle about 30 times gives roughly",
               "a BILLION copies.",
               "The amplified fragment can then be ligated into",
               "a vector for cloning."],
        why="Amplification comes before cloning because a single copy of a gene is too little to work "
            "with reliably.",
        mistakes=["Saying polymerase joins two DNA molecules. That is LIGASE.",
                  "Leaving out Taq polymerase by name. It is the answer to why PCR works."],
        tip="Polymerase copies; it does not join.",
        note="What it does, the PCR link, Taq, and the billion copies."),
      S('s4_ligase','text','Ligases',1,'Ligases',
        lines=["3. LIGASES join two pieces of DNA.",
               "DNA LIGASE joins the ends of the plasmid DNA to",
               "the ends of the desired gene by COVALENT bonds.",
               "It regenerates a circular hybrid molecule, the",
               "RECOMBINANT DNA.",
               "Ligase is often called MOLECULAR GLUE, as",
               "restriction enzymes are called molecular",
               "scissors."],
        why="The sticky ends only hold the two pieces together loosely by base pairing; the covalent "
            "bond ligase makes is what turns them into one molecule.",
        mistakes=["Saying ligase cuts DNA. It JOINS.",
                  "Leaving out the covalent bond. The kind of bond is the point."],
        tip="Scissors cut, glue joins.",
        note="The action, the bond, the product, and the scissors-and-glue pairing."),
      S('s5_vectors','text','Vectors',2,'Vectors',
        lines=["4. A VECTOR is the DNA used as a CARRIER, to",
               "transfer a fragment of foreign DNA into a",
               "suitable host.",
               "Vectors used to multiply foreign DNA are called",
               "CLONING VECTORS.",
               "Common cloning vectors are PLASMIDS,",
               "BACTERIOPHAGES, COSMIDS, BAC and YAC.",
               "PROPERTIES a cloning vector must have:",
               "(i) LOW molecular weight, so it is easy to",
               "handle;",
               "(ii) a UNIQUE cleavage site for a restriction",
               "enzyme, so it opens at one place only;",
               "(iii) the ability to REPLICATE inside the host",
               "after it is introduced;",
               "(iv) a SELECTABLE MARKER, which identifies and",
               "eliminates the non-transformants."],
        why="A vector must open at exactly one place, or the gene could be inserted anywhere and the "
            "vector might be cut into useless pieces.",
        mistakes=["Giving fewer than four properties. All four are expected for two marks.",
                  "Leaving out the selectable marker. Without it there is no way to tell which cells "
                  "took up the vector.",
                  "Saying a vector must be large. It must have LOW molecular weight."],
        tip="Small, one cut site, self-copying, and it flags the cells that took it.",
        note="Two marks. Definition, examples, then all four properties numbered."),
      S('s6_host','boxed_final','Host organisms',1,'Hosts',
        lines=[{"text":"Cut, copy, join, carry, host: five tools","style":"boxed"},
               "5. HOST ORGANISMS are the cells in which the",
               "recombinant DNA is multiplied and expressed.",
               "ESCHERICHIA COLI is the commonest host.",
               "A host is made COMPETENT for transformation by",
               "treating it with divalent calcium (Ca2+) ions,",
               "which makes its wall permeable to DNA.",
               "Yeast and plant and animal cells are also used."],
        why="A host cell has to be persuaded to let DNA through its wall, and the calcium treatment is "
            "the standard way of doing it.",
        mistakes=["Saying E. coli is a plasmid. It is a BACTERIUM; its plasmids are the vectors.",
                  "Leaving out the calcium treatment. Making the cell competent is what this mark is for."],
        tip="Calcium makes the wall leaky enough to let DNA in.",
        note="Definition, the named host, the competence treatment, and one closing list.")]))

# ═══════════════════ VSAQ (Section A, 2 marks) ═══════════════════
def vs(slug, ref, gno, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, 45, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('define_biotechnology','vsaq1',107,
   "Define biotechnology.",
   [("Definition",1),("What it produces",1)],
   "A long definition to write nearly word for word. The phrase to include is 'at the industrial level'.",
   [S('s1_define','text','Biotechnology defined',1,'Definition',
      lines=["BIOTECHNOLOGY is the science that uses MICRO",
             "ORGANISMS, or exploits CELLS and CELL",
             "CONSTITUENTS, at the INDUSTRIAL LEVEL, to make",
             "products useful to life and human welfare."],
      why="The words 'industrial level' are what separate biotechnology from ordinary biology: the same "
          "processes, run at scale for a product.",
      mistakes=["Leaving out 'industrial level'. Brewing beer in a kitchen is not biotechnology.",
                "Saying biotechnology means genetic engineering only. Genetic engineering is one part of it."],
      tip="Living things put to work, at industrial scale.",
      note="The full definition. Five lines, and it is most of the answer."),
    S('s2_products','boxed_final','What it produces',1,'Products',
      lines=[{"text":"Medicines, vaccines, enzymes, GM crops","style":"boxed"},
             "Its products include antibiotics, vaccines,",
             "hormones such as insulin, industrial enzymes,",
             "and genetically modified crops.",
             "Genetic engineering and the maintenance of",
             "sterile conditions are its two core techniques."],
      why="Listing what it produces is the shortest way to show the definition was understood rather "
          "than memorised.",
      mistakes=["Giving no examples. The second mark is for what it actually makes.",
                "Naming only medicines. Crops and industrial enzymes are equally central."],
      tip="If a living thing made it and it is sold, it is biotechnology.",
      note="Four or five named products, then the two core techniques.")],
   years=[('ts',2018)])

vs('molecular_scissors','vsaq2',108,
   "What are molecular scissors? Where are they obtained from?",
   [("What they are",1),("Where they come from",1)],
   "Two halves and the second is one word: bacteria. Say WHY bacteria have them if you have room.",
   [S('s1_what','text','What they are',1,'What they are',
      lines=["MOLECULAR SCISSORS are the RESTRICTION ENZYMES,",
             "which cut DNA at specific locations.",
             "They recognise a particular palindromic sequence",
             "and cut only there."],
      why="They are called scissors because they cut, and because they cut only at one recognised "
          "sequence rather than anywhere.",
      mistakes=["Saying molecular scissors are ligases. Ligase is the GLUE; restriction enzymes are the "
                "scissors.",
                "Saying they cut anywhere. They cut only at SPECIFIC sequences."],
      tip="Scissors cut, and these ones cut only where told.",
      note="Name the enzyme class and say the cut is sequence specific."),
    S('s2_where','boxed_final','Where they come from',1,'Source',
      lines=[{"text":"From BACTERIA, where they destroy","style":"boxed"},
             {"text":"the DNA of invading phages","style":"boxed"},
             "They are usually obtained from BACTERIA.",
             "In the bacterium they are a defence: they cut up",
             "the DNA of any invading bacteriophage.",
             "The bacterium's own DNA is protected by",
             "methylation."],
      why="A bacterium needs a way to destroy viral DNA without destroying its own, which is why these "
          "enzymes both cut precisely and spare methylated sites.",
      mistakes=["Saying they come from plants. They come from BACTERIA.",
                "Giving the source with no reason. Their natural job is worth one line."],
      tip="A bacterial defence, borrowed as a laboratory tool.",
      note="The source, the natural job, and how the bacterium protects itself.")],
   years=[('ap',2017),('ts',2017)])

vs('artificial_plasmids','vsaq3',109,
   "Name any two artificially restructured plasmids.",
   [("Two plasmids",1),("What the names mean",1)],
   "Two names is the mark. The origin of each name is a cheap and memorable second half.",
   [S('s1_two','text','Two plasmids',1,'Names',
      lines=["Two artificially restructured plasmids are:",
             "1. pBR322",
             "2. pUC19"],
      why="Both were built in the laboratory from natural plasmids, which is what 'artificially "
          "restructured' means.",
      mistakes=["Naming Ti plasmid. Ti is a NATURAL plasmid of Agrobacterium, not an artificial one.",
                "Naming one plasmid. The question asks for two."],
      tip="pBR322 and pUC19: the two standard laboratory plasmids.",
      note="Both names, spelled exactly. Three lines."),
    S('s2_names','boxed_final','What the names mean',1,'Origins',
      lines=[{"text":"Named after the people and the place that","style":"boxed"},
             {"text":"built them","style":"boxed"},
             "pBR322 is named after BOLIVAR and RODRIGUEZ,",
             "who constructed it. The p stands for plasmid.",
             "pUC19 is named after the UNIVERSITY OF",
             "CALIFORNIA, where it was made."],
      why="Both names encode who made them, which is why they look arbitrary until the origin is known.",
      mistakes=["Saying pBR stands for a property of the plasmid. It stands for the two makers' names.",
                "Leaving out the second half. The origins are the easiest mark in the question."],
      tip="p for plasmid, then the initials of whoever built it.",
      note="Both origins, one line each. Six lines.")],
   years=[('ap',2022),('ts',2019)])

vs('ecori','vsaq4',110,
   "What is EcoRI? How does it function?",
   [("What it is",1),("How it cuts",1)],
   "GAATTC, not GAA. Write the six bases out, on two strands, and the cut position is obvious.",
   [S('s1_what','text','What EcoRI is',1,'What it is',
      lines=["EcoRI is a RESTRICTION ENDONUCLEASE.",
             "It is obtained from the bacterium ESCHERICHIA",
             "COLI, strain RY13.",
             "The name is read: E from the genus Escherichia,",
             "co from the species coli, R from the strain, and",
             "I because it was the first such enzyme isolated",
             "from that strain."],
      why="The naming convention says exactly where an enzyme came from, so a name like EcoRI is a "
          "short address rather than an arbitrary label.",
      mistakes=["Saying EcoRI is an exonuclease. It is an ENDOnuclease — it cuts WITHIN the DNA.",
                "Not explaining the name. The convention is worth one line."],
      tip="Genus, species, strain, order of discovery.",
      note="The enzyme class, the source, and the naming convention."),
    S('s2_how','equation','How it cuts',1,'How it cuts',
      lines=[{"text":"5'  G ↓ A A T T C  3'","style":"eq"},
             {"text":"3'  C T T A A ↑ G  5'","style":"eq"},
             {"text": "EcoRI recognises the palindrome GAATTC.", "style": "normal"},
             "It cuts between G and A on BOTH strands.",
             "The cuts are staggered, so each piece is left",
             "with a short single stranded overhang — a",
             "STICKY END."],
      why="Cutting off-centre on both strands leaves overhangs that can base pair with any other "
          "fragment cut by the same enzyme, which is what makes joining possible.",
      mistakes=["Writing GAA as the recognition site. It is GAATTC, six bases. The guide's VSAQ answer "
                "is wrong here.",
                "Saying the cut is straight across. It is STAGGERED, which is what makes the ends sticky."],
      tip="Six bases, cut off-centre, sticky ends both sides.",
      note="Write both strands with the cut marked, then say sticky ends.")],
   years=[('ts',2022)],
   note_extra="BOOK ERROR, corrected on this card: the guide says EcoRI \"recognises GAA sites\". "
              "EcoRI recognises the SIX-base palindrome GAATTC and cuts between G and A. The guide's "
              "own LAQ answer on p.16 prints GAATTC correctly, so it contradicts itself.")

vs('cloning_vectors','vsaq5',111,
   "What are cloning vectors? Give an example.",
   [("Definition",1),("Examples",1)],
   "Definition plus at least two examples. Plasmids and bacteriophages are the safe pair.",
   [S('s1_define','text','Cloning vectors defined',1,'Definition',
      lines=["A CLONING VECTOR is a DNA molecule used to CARRY",
             "a foreign DNA fragment into a host cell, where it",
             "is MULTIPLIED.",
             "It must be able to replicate inside the host."],
      why="A carrier that could not replicate would deliver the gene once and no more, so self "
          "replication is part of the definition.",
      mistakes=["Saying a vector is the host. The vector is the CARRIER; the host is the cell.",
                "Leaving out replication. A vector must copy itself inside the host."],
      tip="It carries the gene in and then copies it.",
      note="Definition with both the carrying and the copying."),
    S('s2_examples','boxed_final','Examples',1,'Examples',
      lines=[{"text":"Plasmids, phages, cosmids, BAC and YAC","style":"boxed"},
             "Examples of cloning vectors:",
             "PLASMIDS (pBR322, pUC19), BACTERIOPHAGES,",
             "COSMIDS, bacterial artificial chromosomes (BAC)",
             "and yeast artificial chromosomes (YAC).",
             "The Ti plasmid of Agrobacterium tumefaciens is",
             "the vector used for PLANTS."],
      why="Different vectors carry different sizes of insert, which is why several kinds are kept rather "
          "than one.",
      mistakes=["Naming one example. The question asks for at least one but a list scores better.",
                "Leaving out the Ti plasmid. It is the plant vector, and this is a botany paper."],
      tip="Small inserts go in plasmids; large ones need artificial chromosomes.",
      note="A list, then the Ti plasmid named for plants.")])

vs('recombinant_dna','vsaq6',112,
   "What is recombinant DNA?",
   [("Definition",1),("How it is made",1)],
   "Two halves: what it is, and the enzyme that makes it. Naming ligase is the second mark.",
   [S('s1_define','text','Recombinant DNA defined',1,'Definition',
      lines=["RECOMBINANT DNA is a HYBRID DNA molecule formed",
             "by joining a desired gene from one organism to",
             "the DNA of a vector.",
             "It contains DNA from two different sources."],
      why="The molecule is called recombinant because it combines DNA that was never together in nature.",
      mistakes=["Saying recombinant DNA is a mutated DNA. It is a JOINED molecule, not a changed one.",
                "Leaving out the two sources. That is what makes it recombinant."],
      tip="Two DNAs from two organisms, joined into one.",
      note="Definition naming both sources. Four lines."),
    S('s2_how','boxed_final','How it is made',1,'How',
      lines=[{"text":"Restriction enzyme cuts, DNA ligase joins","style":"boxed"},
             "Both DNAs are cut with the SAME restriction",
             "enzyme, so their sticky ends match.",
             "The enzyme DNA LIGASE then joins them by covalent",
             "bonding, regenerating a circular molecule.",
             "The product is the recombinant DNA."],
      why="The same enzyme on both molecules is what makes the ends complementary, and ligase seals what "
          "the sticky ends have already brought together.",
      mistakes=["Naming only one enzyme. BOTH the restriction enzyme and ligase are needed.",
                "Saying different enzymes are used on the two DNAs. The SAME one must be used."],
      tip="One enzyme to cut both, one to join them.",
      note="Both enzymes, and the same-enzyme point. Five lines.")])

vs('palindromic_sequence','vsaq7',113,
   "What is a palindromic sequence?",
   [("Definition",1),("An example",1)],
   "The definition must say 'in the same 5' to 3' direction' — without it, the sentence is not quite "
   "true and examiners know the phrase.",
   [S('s1_define','text','Palindromic sequence defined',1,'Definition',
      lines=["A PALINDROME in DNA is a sequence of base pairs",
             "that reads the SAME on both strands, when both",
             "are read in the same 5' to 3' direction."],
      why="Reading both strands in the same direction is what makes them identical; read the other way "
          "they are complements, not palindromes.",
      mistakes=["Saying it reads the same backwards. That is a word palindrome; a DNA palindrome is "
                "about TWO strands.",
                "Leaving out the 5' to 3' condition. Without it the definition is wrong."],
      tip="Same reading on both strands, both read the same way round.",
      note="The full definition with the direction condition. Three lines."),
    S('s2_example','boxed_final','An example',1,'Example',
      lines=[{"text":"5'-GAATTC-3' reads the same on both strands","style":"boxed"},
             "Example, the EcoRI site:",
             "5'  G A A T T C  3'",
             "3'  C T T A A G  5'",
             "Read the lower strand 5' to 3' — that is, right",
             "to left — and it also reads GAATTC.",
             "Restriction enzymes recognise such sequences."],
      why="Writing both strands out is the only way to show the property, because it is a relationship "
          "between two strands rather than a feature of one.",
      mistakes=["Giving a single strand. A palindrome needs BOTH strands written.",
                "Giving no example at all. The example is half the answer."],
      tip="Write both strands and read the bottom one backwards.",
      note="Both strands, then the check spelled out. This is what earns the mark.")])

vs('pcr','vsaq8',114,
   "What is the full form of PCR? How is it useful in biotechnology?",
   [("The full form",1),("Its uses",1)],
   "Three uses are printed in the book. Give all three — the list is the second mark.",
   [S('s1_full','text','The full form',1,'Full form',
      lines=["PCR stands for POLYMERASE CHAIN REACTION.",
             "It makes many copies of a chosen DNA fragment,",
             "in vitro, using primers and Taq polymerase."],
      why="Chain reaction is literal: each cycle doubles what the last one made, which is how thirty "
          "cycles reach a billion copies.",
      mistakes=["Expanding it as 'protein chain reaction'. It is POLYMERASE chain reaction.",
                "Saying it happens in a cell. PCR is done IN VITRO, in a tube."],
      tip="Each cycle doubles what the last one made.",
      note="The expansion plus one line on what it does."),
    S('s2_uses','boxed_final','Its uses',1,'Uses',
      lines=[{"text":"Cloning, gene amplification, DNA","style":"boxed"},
             {"text":"fingerprinting","style":"boxed"},
             "PCR is used in:",
             "1. DNA cloning",
             "2. gene amplification",
             "3. DNA fingerprinting",
             "It is also used to detect a disease before its",
             "symptoms appear."],
      why="All four uses need many copies of one small piece of DNA, which is exactly what PCR supplies.",
      mistakes=["Giving one use. Three are printed in the book.",
                "Confusing PCR with ELISA. PCR amplifies DNA; ELISA detects antigen-antibody binding."],
      tip="Anything that needs more DNA than you have.",
      note="All three named uses, then the diagnostic one. Seven lines.")],
   years=[('ts',2015),('ap',2018)])

vs('downstream_processing','vsaq9',115,
   "What is down-stream processing?",
   [("Definition",1),("What it includes",1)],
   "One of the most repeated VSAQs in the paper — six printed appearances. Two words carry it: "
   "separation and purification.",
   [S('s1_define','text','Downstream processing defined',1,'Definition',
      lines=["DOWNSTREAM PROCESSING is everything done to a",
             "biotechnology product AFTER the biosynthetic",
             "stage, before it is ready for marketing.",
             "Its two main operations are SEPARATION and",
             "PURIFICATION."],
      why="A product made inside a tank of cells is mixed with everything else in the tank, so it has to "
          "be separated out before it is of any use.",
      mistakes=["Saying downstream processing is part of making the product. It comes AFTER.",
                "Naming one operation. Separation AND purification are both needed."],
      tip="Everything after the making, before the selling.",
      note="Definition with both operations named. Five lines."),
    S('s2_includes','boxed_final','What it includes',1,'Includes',
      lines=[{"text":"Separate, purify, preserve, test","style":"boxed"},
             "Downstream processing also includes:",
             "adding suitable PRESERVATIVES,",
             "CLINICAL TRIALS for a drug,",
             "and strict QUALITY CONTROL testing.",
             "Only then is the product released for sale."],
      why="A biological product has to be proved both pure and safe, which is why testing is part of the "
          "process rather than an afterthought.",
      mistakes=["Stopping at purification. Preservatives, trials and quality control are all part of it.",
                "Saying it applies only to medicines. Every biotechnology product goes through it."],
      tip="Nothing is released until it has been tested.",
      note="The additional stages listed. Six lines.")],
   years=[('ap',2016),('ap',2017),('ap',2019),('ap',2019),('ts',2016),('ts',2017)])

vs('visualise_dna_on_gel','vsaq10',116,
   "How does one visualise DNA on an agarose gel?",
   [("The stain",1),("The light",1)],
   "Two things: a dye and ultraviolet light. Both are needed — DNA stained but not lit shows nothing.",
   [S('s1_stain','text','The stain',1,'Stain',
      lines=["The separated DNA fragments are stained with",
             "ETHIDIUM BROMIDE.",
             "Ethidium bromide slots itself between the base",
             "pairs of the DNA."],
      why="The dye binds only to DNA, so only the DNA bands will glow and the rest of the gel stays dark.",
      mistakes=["Naming a different stain. It is ETHIDIUM BROMIDE.",
                "Saying the gel is stained before the run. The DNA is stained after separation."],
      tip="One dye that sticks only to DNA.",
      note="Name the stain and say what it binds to."),
    S('s2_light','boxed_final','The light',1,'UV light',
      lines=[{"text":"Ethidium bromide plus UV light: orange bands","style":"boxed"},
             "The stained gel is then exposed to ULTRAVIOLET",
             "(UV) radiation.",
             "The DNA appears as bright ORANGE coloured bands.",
             "Without the UV light the stained DNA cannot be",
             "seen at all."],
      why="The dye fluoresces only under ultraviolet light, so the light is as necessary as the stain.",
      mistakes=["Leaving out the UV light. Staining alone shows nothing.",
                "Saying the bands are blue. They fluoresce ORANGE."],
      tip="Stain it, then shine ultraviolet on it.",
      note="The light, the colour, and why both steps are needed.")],
   years=[('ap',2015),('ap',2020)])

vs('exo_vs_endonucleases','vsaq11',117,
   "How can you differentiate between exonucleases and endonucleases?",
   [("Exonucleases",1),("Endonucleases",1)],
   "Ends against inside. The prefixes say it, and pointing that out is a good way to remember which is "
   "which.",
   [S('s1_exo','text','Exonucleases',1,'Exonucleases',
      lines=["EXONUCLEASES cut DNA by removing nucleotides from",
             "the ENDS of the molecule, one at a time.",
             "They shorten the DNA but do not cut it in two.",
             "EXO means outside."],
      why="Working only from the ends means an exonuclease can trim a molecule but never divide it.",
      mistakes=["Saying exonucleases cut within the DNA. They work from the ENDS.",
                "Saying they cut DNA into fragments. They shorten it; they do not fragment it."],
      tip="EXO works from the ends, from the outside in.",
      note="Where it cuts, what that means, and the prefix. Four lines."),
    S('s2_endo','boxed_final','Endonucleases',1,'Endonucleases',
      lines=[{"text":"Exo trims the ends; endo cuts inside","style":"boxed"},
             "ENDONUCLEASES make cuts at specific positions",
             "WITHIN the DNA molecule.",
             "They cut the DNA into fragments.",
             "ENDO means inside.",
             "Restriction endonucleases are the endonucleases",
             "used in genetic engineering."],
      why="Only a cut made inside the molecule can produce two separate fragments, which is why genetic "
          "engineering uses endonucleases and not exonucleases.",
      mistakes=["Saying endonucleases work from the ends. They cut WITHIN.",
                "Not linking to restriction enzymes. Restriction enzymes are endonucleases, and that is "
                "why this question is asked."],
      tip="ENDO cuts inside, and that is the one used to make fragments.",
      note="Mirror the exo lines, then link to restriction enzymes.")],
   years=[('ts',2019)])

main(C, U)
