# -*- coding: utf-8 -*-
"""Unit 12 — Biotechnology and its Applications. Book SAQ ch.12 (pp.35-36) + VSAQ ch.19
(p.46). Globals 45-48 (SAQ) and 118-124 (VSAQ)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main

U = 12
C = []

C.append(Q(U, 'transgenic_plant_benefits', 'SAQ', 'saq1', 45, 35,
    "List out the beneficial aspects of transgenic plants.",
    years=[('ts',2017),('ts',2022),('ap',2017),('ap',2019)],
    split=[("Resistance to pests and pathogens",1),("Food processing",1),
           ("Nutritional value",1),("Hybrid seed and stress tolerance",1)],
    insider="Five headings, and each needs a NAMED crop. A benefit without a named plant is half a "
            "point; Bt cotton, Flavr Savr and golden rice are the three that must appear.",
    steps=[
      S('s1_resistance','text','Resistance to pests and pathogens',1,'Resistance',
        lines=["1. TRANSGENIC CROPS RESISTANT TO PATHOGENS AND",
               "PESTS:",
               "(i) Transgenic PAPAYA is resistant to papaya",
               "    ring spot virus.",
               "(ii) BT COTTON is resistant to insects, chiefly",
               "     the bollworm.",
               "(iii) Transgenic TOMATO resists the bacterial",
               "      pathogen Pseudomonas.",
               "(iv) Transgenic POTATO resists the fungus",
               "     Phytophthora."],
        why="One transgene can replace repeated spraying, so the benefit is measured in pesticide not "
            "used as much as in yield gained.",
        mistakes=["Naming benefits with no crops. Each example needs its plant AND its pest.",
                  "Saying Bt cotton resists viruses. It resists INSECTS."],
        tip="Four crops, four different enemies: virus, insect, bacterium, fungus.",
        note="All four examples with crop and pathogen. This heading alone is a full mark."),
      S('s2_processing','text','Food processing',1,'Processing',
        lines=["2. TRANSGENIC PLANTS SUITABLE FOR FOOD",
               "PROCESSING:",
               "The transgenic tomato FLAVR SAVR is bruise",
               "resistant, because its ripening is DELAYED.",
               "So it can be stored and transported without",
               "spoiling."],
        why="A tomato that ripens slowly can be picked ripe and still survive transport, which is what "
            "makes delayed ripening commercially useful.",
        mistakes=["Saying Flavr Savr ripens faster. Its ripening is DELAYED.",
                  "Not naming the variety. Flavr Savr is the named example."],
        tip="Delayed ripening means it survives the journey.",
        note="Name the variety, the property, and why it matters."),
      S('s3_nutrition','text','Nutritional value',1,'Nutrition',
        lines=["3. TRANSGENIC PLANTS WITH IMPROVED NUTRITIONAL",
               "VALUE:",
               "GOLDEN RICE, developed from the Taipei rice",
               "variety, is rich in beta-carotene, the",
               "precursor of VITAMIN A.",
               "It helps prevent blindness caused by vitamin A",
               "deficiency."],
        why="Rice grain normally carries no beta-carotene at all, so adding the pathway addresses a "
            "deficiency in the crop people already eat.",
        mistakes=["Saying golden rice contains vitamin A itself. It contains BETA-CAROTENE, which the "
                  "body converts to vitamin A.",
                  "Not saying what deficiency it addresses. Blindness from vitamin A deficiency is the point."],
        tip="Golden because of the carotene, and carotene becomes vitamin A.",
        note="The crop, the compound, and the deficiency it prevents."),
      S('s4_hybrid','boxed_final','Hybrid seed and stress tolerance',1,'Hybrid, stress',
        lines=[{"text":"Pest resistant, storable, more nutritious,","style":"boxed"},
               {"text":"easier to breed, and stress tolerant","style":"boxed"},
               "4. FOR HYBRID SEED PRODUCTION:",
               "MALE STERILE plants of Brassica napus remove the",
               "need for manual emasculation, and so cut the",
               "cost of hybrid seed.",
               "5. TOLERANT TO ABIOTIC STRESS — cold, drought,",
               "salt and heat:",
               "The BASMATI rice variety was made resistant to",
               "both biotic and abiotic stresses.",
               "ROUND-UP READY SOYABEAN is herbicide tolerant."],
        why="Emasculating flowers by hand is the single most expensive step in hybrid seed production, "
            "so a male sterile plant removes the cost rather than reducing it.",
        mistakes=["Leaving out male sterility. It is one of the five named headings.",
                  "Saying herbicide tolerance kills weeds. It lets the CROP survive the herbicide that "
                  "kills the weeds."],
        tip="Male sterile means no hand emasculation, and that is where the money is.",
        note="Both remaining headings with their named crops. Five headings in total.")]))

C.append(Q(U, 'gm_biosafety_issues', 'SAQ', 'saq2', 46, 35,
    "What are some bio-safety issues concerned with genetically modified crops?",
    years=[('ap',2016),('ap',2017),('ap',2019),('ap',2022),('ts',2016)],
    split=[("Risk to human and animal health",1),("Risk to food and biodiversity",1),
           ("Risk to evolution",1),("Gene pollution and super weeds",1)],
    insider="Five issues in the book. The one an examiner most wants is GENE POLLUTION leading to super "
            "weeds — write it even if the others are brief.",
    steps=[
      S('s1_health','text','Risk to human and animal health',1,'Health',
        lines=["1. ALLERGIES AND TOXINS:",
               "There is a fear that a transferred gene may",
               "produce a protein that acts as an ALLERGEN or a",
               "TOXIN in humans and animals.",
               "The effect may appear only as a long term side",
               "effect, after years of consumption."],
        why="A gene moved into a food crop makes a protein people have never eaten before, and its "
            "effects can only be established over time.",
        mistakes=["Saying GM crops are known to be toxic. The issue is a RISK, not a proven harm.",
                  "Leaving out allergies. Allergenicity is the first named concern."],
        tip="A new protein in an old food is the first worry.",
        note="Name both allergens and toxins, and say the effect may be long term."),
      S('s2_food','text','Risk to food and biodiversity',1,'Food, biodiversity',
        lines=["2. CHANGE TO THE FOOD ITSELF:",
               "There is a risk of changing the fundamental",
               "nature of vegetables and other foods.",
               "3. HARM TO BIODIVERSITY:",
               "GM crops may harm biodiversity and have an",
               "adverse impact on the environment, for example",
               "by killing non-target insects."],
        why="A toxin meant for one pest is present in every cell of the plant, so insects that were never "
            "the target meet it too.",
        mistakes=["Saying GM crops affect only the target pest. Non-target insects may be affected too.",
                  "Giving one issue where the question asks for several."],
        tip="A toxin in every cell meets more than the pest it was meant for.",
        note="Both issues numbered, with one concrete mechanism."),
      S('s3_evolution','text','Risk to evolution',1,'Evolution',
        lines=["4. CHANGES TO EVOLUTIONARY PATTERNS:",
               "GM crops may bring about changes in natural",
               "evolutionary patterns.",
               "Pests exposed continuously to one toxin may",
               "evolve RESISTANCE to it, so the crop stops",
               "working."],
        why="Constant exposure to a single toxin is the strongest possible selection pressure, so "
            "resistant pests are the expected outcome rather than a surprise.",
        mistakes=["Saying evolution is not affected. Continuous selection pressure is exactly what "
                  "drives resistance.",
                  "Giving no mechanism. Resistance evolving in the pest is the concrete case."],
        tip="A toxin used everywhere selects for pests that survive it.",
        note="The general issue plus the resistance mechanism."),
      S('s4_pollution','boxed_final','Gene pollution and super weeds',1,'Gene pollution',
        lines=[{"text":"Transgenes escaping into wild relatives can","style":"boxed"},
               {"text":"produce weeds nothing kills","style":"boxed"},
               "5. GENE POLLUTION:",
               "New genes may be transferred into related WILD",
               "species by natural out-crossing.",
               "This can produce SUPER WEEDS, which grow faster",
               "than the crop and are resistant to weedicides.",
               "This is why the GEAC must approve any GM release."],
        why="Pollen does not respect field boundaries, so a herbicide-tolerance gene can move into the "
            "very weeds the herbicide was meant to kill.",
        mistakes=["Leaving out super weeds. It is the named consequence and the most memorable issue.",
                  "Saying gene pollution means chemical pollution. It means GENES escaping into wild "
                  "relatives."],
        tip="The escaped gene ends up in the weed.",
        note="Name gene pollution, the mechanism, the consequence, and GEAC. This is the strongest mark.")]))

C.append(Q(U, 'bt_cotton', 'SAQ', 'saq3', 47, 36,
    "Give a brief account of Bt cotton.",
    years=[('ap',2015),('ap',2020),('ts',2016),('ts',2017),('ts',2018),('ts',2020),('ts',2022)],
    split=[("What Bt cotton is",1),("The Bt toxin crystal",1),
           ("How the toxin kills the insect",1),("The cry genes",1)],
    note_extra="BOOK NOTE: the guide's opening line reads \"Bt cotton is a GMO cotton variety, which "
               "produces an insecticide bollworm\", which is garbled — the plant produces an "
               "insecticidal protein that kills the bollworm. Written correctly here.",
    insider="The mechanism is where the marks are: protoxin, alkaline gut, activation, pores, lysis. "
            "Write those five words in order and the third mark is safe.",
    steps=[
      S('s1_what','text','What Bt cotton is',1,'What it is',
        lines=["BT COTTON is a genetically modified (GM) cotton",
               "variety that makes its own INSECTICIDAL PROTEIN,",
               "which kills the cotton bollworm.",
               "It was created using genes from the bacterium",
               "BACILLUS THURINGIENSIS — Bt for short.",
               "The bacterium's proteins kill certain insects:",
               "lepidopterans (tobacco budworm), coleopterans",
               "(beetles) and dipterans (flies, mosquitoes)."],
        why="The plant makes the insecticide itself, so the toxin is present in every cell and cannot be "
            "washed off or rained away.",
        mistakes=["Saying Bt cotton is sprayed with an insecticide. The plant MAKES the insecticidal "
                  "protein itself.",
                  "Expanding Bt wrongly. It is Bacillus thuringiensis."],
        tip="Bt is the bacterium; the cotton carries its gene.",
        note="Definition, the bacterium in full, and the three insect groups."),
      S('s2_crystal','text','The Bt toxin crystal',1,'Crystal',
        lines=["Bacillus thuringiensis forms PROTEIN CRYSTALS",
               "during a particular phase of its growth.",
               "These crystals contain a toxic INSECTICIDAL",
               "PROTEIN.",
               "The toxin exists in the crystal as an INACTIVE",
               "PROTOXIN.",
               "The bacterium itself is not killed by it,",
               "because the toxin is inactive while stored."],
        why="Storing the toxin in an inactive form is how the bacterium avoids poisoning itself, and it "
            "is also why the toxin is harmless until eaten.",
        mistakes=["Saying the crystal is active toxin. It is an INACTIVE PROTOXIN.",
                  "Not saying why the bacterium survives. The inactive form is the reason."],
        tip="Stored inactive, so it harms nothing until it is eaten.",
        note="The crystal, the protoxin, and why the bacterium is safe."),
      S('s3_mechanism','text','How the toxin kills the insect',1,'Mechanism',
        lines=["1. The insect EATS the inactive protoxin.",
               "2. The ALKALINE pH of the insect gut dissolves",
               "the crystals.",
               "3. The protoxin is converted into the ACTIVE",
               "form of the toxin.",
               "4. The active toxin binds to the surface of the",
               "MIDGUT EPITHELIAL cells.",
               "5. It creates PORES in those cells, so they",
               "swell and burst (LYSE).",
               "6. The insect dies."],
        why="Human and most animal stomachs are acidic, so the protoxin is never activated in them — "
            "which is the whole basis of the claim that Bt crops are safe to eat.",
        mistakes=["Saying the toxin is active when eaten. It is activated by the insect's ALKALINE gut.",
                  "Leaving out the alkaline pH. It is what makes the toxin specific to insects.",
                  "Saying it kills by poisoning the blood. It makes PORES in the midgut cells."],
        tip="Alkaline gut switches it on; acid stomachs do not.",
        note="Six numbered steps. The alkaline pH is the step examiners look for."),
      S('s4_cry','boxed_final','The cry genes',1,'Cry genes',
        lines=[{"text":"Cry I Ac and Cry II Ab for bollworm;","style":"boxed"},
               {"text":"Cry I Ab for corn borer","style":"boxed"},
               "The toxin is coded by genes named CRY.",
               "Most Bt toxins are INSECT GROUP SPECIFIC, so a",
               "different cry gene is needed for each pest.",
               "The proteins of CRY I Ac and CRY II Ab control",
               "the cotton bollworms.",
               "The protein of CRY I Ab controls the CORN BORER.",
               "Specific cry genes were isolated from Bacillus",
               "thuringiensis and put into crop plants."],
        why="Each cry protein binds only to receptors present in certain insect guts, which is why the "
            "gene has to be matched to the pest.",
        mistakes=["Swapping the genes. Cry I Ac and Cry II Ab are for BOLLWORM; Cry I Ab is for CORN BORER.",
                  "Saying one cry gene works on all pests. They are insect group SPECIFIC."],
        tip="Ac and Ab for cotton; Ab alone for corn.",
        note="Both gene sets with their pests, and the specificity point.")]))

C.append(Q(U, 'pest_resistant_plants', 'SAQ', 'saq4', 48, 36,
    "Give a brief account of pest resistant plants.",
    years=[('ts',2019)],
    split=[("The problem",1),("RNA interference",1),
           ("Making the transgenic plant",1),("How the parasite is defeated",1)],
    note_extra="BOOK NOTE: the guide spells the nematode \"Meloidegyne incognitia\". The correct name "
               "is MELOIDOGYNE INCOGNITA.",
    insider="This is the RNAi question in disguise. Getting to double stranded RNA and gene silencing is "
            "where three of the four marks are.",
    steps=[
      S('s1_problem','text','The problem',1,'The problem',
        lines=["A nematode parasite, MELOIDOGYNE INCOGNITA,",
               "infects the ROOTS of tobacco plants.",
               "The infestation greatly reduces the yield of",
               "tobacco.",
               "Pest resistant plants are developed by",
               "biotechnology to stop this."],
        why="A root parasite cannot be reached by spraying, so a solution built into the plant is the "
            "only practical one.",
        mistakes=["Saying the nematode attacks the leaves. It infects the ROOTS.",
                  "Misspelling the name. It is Meloidogyne incognita; the guide misprints it."],
        tip="A root parasite that spraying cannot reach.",
        note="The parasite, the host, the part attacked, and the loss."),
      S('s2_rnai','text','RNA interference',1,'RNAi',
        lines=["The strategy adopted is RNA INTERFERENCE (RNAi).",
               "RNAi is a method of CELLULAR DEFENCE found in",
               "all eukaryotic organisms.",
               "It works by SILENCING a specific mRNA, so that",
               "mRNA is never translated into protein.",
               "The silencing is triggered by DOUBLE STRANDED",
               "RNA."],
        why="A cell that meets double stranded RNA treats it as a sign of viral infection, and RNAi is "
            "the defence it already has — the technique borrows it.",
        mistakes=["Saying RNAi cuts DNA. It silences mRNA; the DNA is untouched.",
                  "Saying RNAi is artificial. It is a NATURAL cellular defence that is being used."],
        tip="Silence the message and the protein is never made.",
        note="Expand RNAi, say it is natural, and name the double stranded trigger."),
      S('s3_transgenic','text','Making the transgenic plant',1,'The method',
        lines=["1. Nematode specific genes are introduced into",
               "the tobacco plant, using AGROBACTERIUM as the",
               "vector.",
               "2. The host tobacco plant is now a TRANSGENIC",
               "plant.",
               "3. The introduced DNA is designed so that BOTH",
               "a SENSE RNA and an ANTI-SENSE RNA are produced",
               "in the host cells."],
        why="Making both strands in the same cell is what allows them to pair, and the pairing is what "
            "triggers the whole defence.",
        mistakes=["Saying only one RNA is made. BOTH sense and anti-sense are produced.",
                  "Naming the wrong vector. Agrobacterium is the standard plant vector."],
        tip="Two RNAs made in the same cell, so they can find each other.",
        note="The vector, the transgenic plant, and both RNAs. Three numbered steps."),
      S('s4_defeat','boxed_final','How the parasite is defeated',1,'The result',
        lines=[{"text":"The parasite's own mRNA is silenced inside","style":"boxed"},
               {"text":"the plant","style":"boxed"},
               "4. The two RNAs are COMPLEMENTARY, so they pair",
               "and form a DOUBLE STRANDED RNA.",
               "5. This initiates RNAi and silences the specific",
               "nematode mRNA.",
               "6. The parasite can no longer make the protein",
               "it needs, so it cannot survive in the",
               "transgenic plant.",
               "7. The plant is therefore protected."],
        why="The plant is not made poisonous; it simply switches off a gene the parasite cannot do "
            "without, which is why nothing else is harmed.",
        mistakes=["Saying the plant poisons the nematode. It SILENCES a nematode gene.",
                  "Stopping at 'RNAi happens'. The consequence for the parasite is the last mark."],
        tip="The plant does not kill it; it just switches off a gene it needs.",
        note="The pairing, the silencing, and the consequence. Four numbered steps.")]))

# ═══════════════════ VSAQ (Section A, 2 marks) ═══════════════════
def vs(slug, ref, gno, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, 46, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('cry_genes','vsaq1',118,
   "Give different types of cry genes and the pests which are controlled by the proteins encoded by these genes.",
   [("Cry I Ac and Cry II Ab",1),("Cry I Ab",1)],
   "Three gene names, two pests. Get Ac and Ab the right way round — that is the whole question.",
   [S('s1_bollworm','text','Cry I Ac and Cry II Ab',1,'Bollworm',
      lines=["The proteins of CRY I Ac and CRY II Ab control",
             "the COTTON BOLLWORMS.",
             "These are the genes carried by Bt cotton."],
      why="Cotton's main pest is the bollworm, so these are the genes that made Bt cotton worth "
          "developing at all.",
      mistakes=["Giving Cry I Ab for bollworm. Cry I Ab controls the CORN BORER.",
                "Naming one gene. TWO control the bollworm."],
      tip="Two genes for cotton's bollworm.",
      note="Both genes and the pest. Three lines."),
    S('s2_corn','boxed_final','Cry I Ab',1,'Corn borer',
      lines=[{"text":"Ac and Ab for cotton; Ab alone for corn","style":"boxed"},
             "The protein of CRY I Ab controls the CORN BORER.",
             "Each cry gene is insect group SPECIFIC, so a",
             "different gene is needed for each pest."],
      why="Each Cry protein binds only to receptors in certain insect guts, which is why one gene cannot "
          "serve every crop.",
      mistakes=["Saying one cry gene controls all pests. They are group SPECIFIC.",
                "Confusing corn borer with bollworm."],
      tip="Different pest, different gene.",
      note="The gene, the pest, and the specificity point.")],
   years=[('ts',2016)])

vs('early_disease_detection','vsaq2',119,
   "Can a disease be detected before its symptoms appear? Explain the principle involved.",
   [("The two techniques",1),("Their principles",1)],
   "Yes, then two techniques with their two principles. Four facts in four lines.",
   [S('s1_yes','text','The two techniques',1,'Techniques',
      lines=["YES. A disease can be detected before its symptoms",
             "appear.",
             "Two techniques are used:",
             "(i) PCR  (ii) ELISA"],
      why="Both techniques detect the pathogen itself rather than the body's reaction to it, which is "
          "why they work before any symptom shows.",
      mistakes=["Answering with a bare yes. The techniques are half the mark.",
                "Naming only one technique. Both PCR and ELISA are expected."],
      tip="Detect the pathogen, not the symptom.",
      note="Yes, then both named techniques."),
    S('s2_principles','boxed_final','Their principles',1,'Principles',
      lines=[{"text":"PCR amplifies the gene; ELISA binds antigen","style":"boxed"},
             {"text":"to antibody","style":"boxed"},
             "The principle of PCR is GENE AMPLIFICATION: even",
             "a very small amount of pathogen DNA is copied",
             "until it can be detected.",
             "The principle of ELISA is ANTIGEN-ANTIBODY",
             "INTERACTION: the pathogen's antigen binds a",
             "specific antibody."],
      why="A tiny amount of pathogen is invisible until it is either multiplied or made to bind "
          "something detectable, which is exactly what the two techniques do.",
      mistakes=["Swapping the principles. PCR is amplification; ELISA is antigen-antibody.",
                "Giving the names with no principles. The question asks for the PRINCIPLE."],
      tip="One multiplies the evidence; the other makes it stick to something.",
      note="Both principles named, one line of explanation each.")],
   years=[('ts',2019),('ts',2019),('ap',2017),('ap',2019)])

vs('geac','vsaq3',120,
   "What is GEAC and what are its objectives?",
   [("What GEAC stands for",1),("Its objectives",1)],
   "The expansion is the first mark. Get all four words: Genetic Engineering Approval Committee.",
   [S('s1_what','text','What GEAC stands for',1,'Expansion',
      lines=["GEAC stands for the GENETIC ENGINEERING APPROVAL",
             "COMMITTEE.",
             "It is the regulatory body set up by the",
             "government for genetic engineering work."],
      why="Genetic modification carries the biosafety risks listed elsewhere in this chapter, so a body "
          "with the power to approve or refuse is needed.",
      mistakes=["Expanding it as 'Genetic Engineering Advisory Committee'. It is APPROVAL Committee.",
                "Saying GEAC is an international body. It is a national regulatory body."],
      tip="Approval, not advice: it can say no.",
      note="The four words in full, then what kind of body it is."),
    S('s2_objectives','boxed_final','Its objectives',1,'Objectives',
      lines=[{"text":"It decides whether GM research and GM releases","style":"boxed"},
             {"text":"are valid and safe","style":"boxed"},
             "Its objectives are:",
             "1. to make decisions on the VALIDITY of GM",
             "   research;",
             "2. to judge the SAFETY of introducing GM organisms",
             "   for public services."],
      why="Both objectives are about permission: nothing may be researched or released without GEAC's "
          "decision.",
      mistakes=["Giving one objective. There are two.",
                "Saying GEAC develops GM crops. It APPROVES or refuses them."],
      tip="Two questions it asks: is the research sound, and is the release safe.",
      note="Both objectives numbered. Six lines.")],
   years=[('ts',2022),('ap',2015),('ap',2017),('ap',2018)])

vs('tobacco_nematode','vsaq4',121,
   "Name the nematode that infects the roots of tobacco plants. Name the strategy adopted to prevent this infestation.",
   [("The nematode",1),("The strategy",1)],
   "One species name and one technique. Spell Meloidogyne incognita carefully — the guide misspells it.",
   [S('s1_nematode','text','The nematode',1,'Nematode',
      lines=["The nematode is MELOIDOGYNE INCOGNITA.",
             "It infects the ROOTS of tobacco plants and",
             "reduces the yield."],
      why="A parasite living inside the root is out of reach of anything sprayed on the plant, which is "
          "why a biotechnological answer was needed.",
      mistakes=["Writing 'Meloidegyne incognitia'. The correct name is Meloidogyne incognita; the guide "
                "misprints it.",
                "Saying it infects the leaves. It infects the ROOTS."],
      tip="Meloidogyne incognita, in the roots.",
      note="The full species name and where it lives."),
    S('s2_strategy','boxed_final','The strategy',1,'Strategy',
      lines=[{"text":"RNA interference silences a nematode gene","style":"boxed"},
             "RNA INTERFERENCE (RNAi) is adopted to prevent the",
             "infestation.",
             "Nematode specific genes are introduced into the",
             "tobacco plant using Agrobacterium.",
             "Both sense and anti-sense RNA are made, they pair",
             "into double stranded RNA, and the nematode's own",
             "mRNA is silenced."],
      why="Silencing a gene the parasite needs kills it without making the plant toxic to anything else.",
      mistakes=["Naming a pesticide. The strategy is RNA INTERFERENCE.",
                "Not expanding RNAi. RNA interference is the full name."],
      tip="Switch off a gene the parasite cannot live without.",
      note="Name RNAi, the vector, and the double stranded RNA. Seven lines.")],
   years=[('ts',2018),('ts',2020),('ap',2016),('ap',2019)])

vs('basmati_patent','vsaq5',122,
   "For which variety of Indian rice has a patent been filed by a USA company?",
   [("The variety",1),("Why it matters",1)],
   "One word answers the question. The second mark comes from saying what a biopiracy case is.",
   [S('s1_variety','text','The variety',1,'Variety',
      lines=["A patent was filed by an American company on",
             "BASMATI rice.",
             "Basmati is a long grained, aromatic rice grown",
             "for centuries in the Indian subcontinent."],
      why="Basmati was already a traditional crop, so a patent on it claimed ownership of something that "
          "had been developed communally over centuries.",
      mistakes=["Naming Jaya or Ratna. Those are semi-dwarf HIGH YIELDING varieties, not the patent case.",
                "Giving the name with no context. One line on what basmati is helps."],
      tip="Basmati: the aromatic one, and the patented one.",
      note="Name the variety and say what it is. Four lines."),
    S('s2_why','boxed_final','Why it matters',1,'Biopiracy',
      lines=[{"text":"Patenting a traditional variety is BIOPIRACY","style":"boxed"},
             "Patenting a variety that a country has developed",
             "and used for centuries is called BIOPIRACY.",
             "It is the use of bio-resources or traditional",
             "knowledge without proper authorisation or",
             "payment to the country concerned."],
      why="A patent gives exclusive rights, so patenting a traditional variety would let one company "
          "charge for something a whole region already owned.",
      mistakes=["Not naming biopiracy. It is the term the case is famous for.",
                "Saying a patent was granted permanently. The case was contested."],
      tip="Taking what was already communally owned.",
      note="Name biopiracy and define it. Six lines.")],
   years=[('ap',2022)])

vs('transgenic_examples','vsaq6',123,
   "Give one example each of a transgenic plant suitable for food processing and one with improved nutritional quality.",
   [("Food processing",1),("Nutritional quality",1)],
   "Two names, one line each. Flavr Savr and golden rice — both need the property that makes them the answer.",
   [S('s1_processing','text','Food processing',1,'Processing',
      lines=["Transgenic plant suitable for food processing:",
             "the FLAVR SAVR variety of TOMATO.",
             "Its ripening is DELAYED, so it is bruise resistant",
             "and survives storage and transport."],
      why="Delayed ripening is exactly what a food-processing crop needs: time between harvest and use.",
      mistakes=["Naming golden rice here. Golden rice is the NUTRITION example.",
                "Giving the name with no property. Delayed ripening is why it qualifies."],
      tip="Flavr Savr ripens slowly, so it travels well.",
      note="The variety, the crop, and the property. Four lines."),
    S('s2_nutrition','boxed_final','Nutritional quality',1,'Nutrition',
      lines=[{"text":"Flavr Savr for processing; golden rice for","style":"boxed"},
             {"text":"nutrition","style":"boxed"},
             "Transgenic plant with improved nutritional value:",
             "GOLDEN RICE, from the Taipei rice variety.",
             "It is rich in beta-carotene, which the body turns",
             "into VITAMIN A, and so helps prevent blindness."],
      why="Rice grain carries no beta-carotene naturally, so adding it changes the nutritional value of "
          "the staple food itself.",
      mistakes=["Saying golden rice is bruise resistant. That is Flavr Savr.",
                "Saying it contains vitamin A. It contains BETA-CAROTENE, the precursor."],
      tip="Golden from the carotene, and carotene becomes vitamin A.",
      note="The variety, the compound, and what it prevents.")],
   years=[('ap',2020)])

vs('green_revolution','vsaq7',124,
   "What is green revolution? Who is regarded as the Father of the green revolution?",
   [("What it is",1),("Who it is credited to",1)],
   "A definition and a name. Norman Borlaug is the world answer; if you add M. S. Swaminathan as the "
   "Indian one, say which is which.",
   [S('s1_what','text','What it is',1,'Definition',
      lines=["The GREEN REVOLUTION was the creation and",
             "widespread use of HIGH YIELDING VARIETIES in",
             "agriculture, which produced a substantial and",
             "dramatic increase in food production.",
             "It relied on semi-dwarf, disease resistant",
             "varieties, fertiliser and irrigation."],
      why="Semi-dwarf varieties could carry a heavy head of grain without falling over, which is what "
          "allowed heavy fertiliser use to translate into yield.",
      mistakes=["Saying it was about growing more land area. It was about higher YIELD from the same land.",
                "Leaving out high yielding varieties. They are the heart of the definition."],
      tip="Same land, far more grain.",
      note="Definition with high yielding varieties named, plus what it depended on."),
    S('s2_who','boxed_final','Who it is credited to',1,'Father',
      lines=[{"text":"Norman Borlaug, worldwide","style":"boxed"},
             "NORMAN BORLAUG is regarded as the Father of the",
             "green revolution.",
             "M. S. SWAMINATHAN is regarded as the Father of",
             "the green revolution IN INDIA."],
      why="Two names are correct at two different scales, so saying which is which shows the distinction "
          "was understood.",
      mistakes=["Giving only one name with no scale. Say whether you mean worldwide or in India.",
                "Naming a different scientist. Borlaug worldwide, Swaminathan in India."],
      tip="Borlaug for the world, Swaminathan for India.",
      note="Both names, each labelled with its scale.")],
   years=[('ts',2015),('ts',2017),('ts',2020)])

main(C, U)
