# -*- coding: utf-8 -*-
"""Unit 8 — Viruses. Book SAQ ch.9 (pp.28-29) + Star Q Plus (p.51).
Globals 26-30 (SAQ) and 163-165 (VSAQ)."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from emit import Q, S, main
import figs_u8

U = 8
C = []

C.append(Q(U, 'ictv_and_naming', 'SAQ', 'saq1', 26, 28,
    "What is ICTV? How are viruses named?",
    years=[('ts',2019)],
    split=[("What ICTV is",1),("The three levels",1),("The naming rules",1),("The worked example",1)],
    note_extra="BOOK NOTE: the guide prints \"Genes: Lentivirus\" in its worked example, where the "
               "hierarchy level is GENUS. Corrected on the card.",
    insider="The suffixes are the marks: -viridae for a family, -virus for a genus. Write both in "
            "capitals or underline them so the examiner cannot miss them.",
    steps=[
      S('s1_what','text','What ICTV is',1,'ICTV',
        lines=["ICTV stands for the INTERNATIONAL COMMITTEE ON",
               "TAXONOMY OF VIRUSES.",
               "It lays down the rules for the classification",
               "and the naming of viruses."],
        why="Viruses are not living cells, so the ordinary rules of biological nomenclature do not fit "
            "them and a separate committee sets their own.",
        mistakes=["Expanding ICTV wrongly. It is International Committee on TAXONOMY of Viruses.",
                  "Saying ICTV names bacteria too. It names VIRUSES only."],
        tip="One committee, one job: naming viruses.",
        note="The full expansion and what the committee does. Four lines."),
      S('s2_levels','text','The three levels',1,'Hierarchy',
        lines=["ICTV uses THREE hierarchical levels:",
               "1. FAMILY   2. GENUS   3. SPECIES",
               "This is shorter than the seven levels used for",
               "plants and animals."],
        why="Three levels rather than seven is enough because viruses are far less diverse in structure "
            "than cellular organisms.",
        mistakes=["Giving seven levels. Viral classification uses THREE.",
                  "Naming order or class. ICTV works with family, genus and species."],
        tip="Family, genus, species: three levels and no more.",
        note="Name all three in order. Three lines."),
      S('s3_rules','text','The naming rules',1,'Suffixes',
        lines=["The FAMILY name ends in the suffix -VIRIDAE.",
               "The GENUS name ends in the suffix -VIRUS.",
               "The SPECIES name is a common English expression",
               "describing the virus.",
               "Sometimes a virus is named after the DISEASE it",
               "causes."],
        why="Each suffix marks its level unambiguously, so the rank of a name can be read off its "
            "ending without knowing anything else about the virus.",
        mistakes=["Swapping the suffixes. -viridae is the FAMILY; -virus is the GENUS.",
                  "Saying species names are Latin. They are common ENGLISH expressions."],
        tip="Viridae for the family, virus for the genus.",
        note="Both suffixes, spelled out. This is the mark most often lost."),
      S('s4_example','boxed_final','The worked example',1,'Example',
        lines=[{"text":"HIV: Retroviridae / Lentivirus / HIV","style":"boxed"},
               "The virus that causes AIDS in man is classified",
               "as:",
               "Family : RETROVIRIDAE",
               "Genus  : LENTIVIRUS",
               "Species: Human Immunodeficiency Virus (HIV)"],
        why="Working one real name through all three levels shows both suffixes doing their job in the "
            "same example.",
        mistakes=["Writing 'Genes' for GENUS. The level is genus. The guide misprints this.",
                  "Giving the example with no levels labelled. The labels are what earn the mark."],
        tip="Retroviridae is the family because it ends in viridae.",
        note="Set the three levels out on their own lines. This is a full mark on its own.")]))

C.append(Q(U, 'chemical_structure_of_viruses', 'SAQ', 'saq2', 27, 28,
    "Explain the chemical structure of viruses.",
    years=[('ap',2020)],
    split=[("The two basic components",1),("The capsid and capsomeres",1),
           ("The genome",1),("Number and form of the nucleic acid",1)],
    note_extra="BOOK ERROR, corrected on this card: the guide says the viral genome is \"either single "
               "stranded DNA (or) double stranded DNA\" and then, one line later, that plant viruses "
               "have ssRNA — which its own sentence has just excluded. A viral genome may be ssDNA, "
               "dsDNA, ssRNA or dsRNA; the card gives all four. The guide's flat claim that plant "
               "viruses have ssRNA and animal viruses dsDNA is also an over-generalisation and is "
               "written here as the usual case, not the rule.",
    insider="Core and capsid. Say those two words first, then everything else hangs off them. The "
            "capsomere is the word the examiner is scanning for.",
    steps=[
      S('s1_two','text','The two basic components',1,'Two parts',
        lines=["Every virus consists of TWO basic components:",
               "a) the CORE — the nucleic acid, which forms the",
               "   genome;",
               "b) the CAPSID — the protein coat that surrounds",
               "   the core.",
               "A complete virus particle is called a VIRION."],
        why="A virus is nothing but genetic material in a protein box, which is why two components are "
            "enough to describe every one of them.",
        mistakes=["Saying viruses have a cell membrane and cytoplasm. They have only a core and a capsid.",
                  "Calling the capsid the genome. The CORE is the genome; the capsid is protein."],
        tip="Core inside, capsid outside, virion is the whole thing.",
        note="Both components named and defined. Add the word virion."),
      S('s2_capsid','text','The capsid and capsomeres',1,'Capsid',
        lines=["The CAPSID gives the virus its shape and",
               "protects the core.",
               "It is made of protein subunits called",
               "CAPSOMERES.",
               "The NUMBER of capsomeres is a characteristic",
               "feature of each type of virus.",
               "In TMV there are 2,130 capsomeres."],
        why="Because the capsomere count is fixed for each virus, it is one of the features used to "
            "identify and classify them.",
        mistakes=["Calling the subunits capsids. The subunits are CAPSOMERES; the whole coat is the capsid.",
                  "Saying the capsid carries the genetic information. The CORE does."],
        tip="Capsid is the coat; capsomeres are the bricks it is built from.",
        note="Function, the subunit name, and the fact that the count is characteristic."),
      S('s3_genome','text','The genome',1,'Genome',
        lines=["The genome of a virus may be:",
               "single stranded DNA, double stranded DNA,",
               "single stranded RNA, or double stranded RNA.",
               "NO virus has both DNA and RNA.",
               "Most PLANT viruses have single stranded RNA.",
               "Many ANIMAL viruses have double stranded DNA."],
        why="A virus carries only one kind of nucleic acid, which is the single sharpest chemical "
            "difference between a virus and a cell.",
        mistakes=["Saying a virus can have both DNA and RNA. It has ONE of them, never both.",
                  "Giving only DNA. RNA viruses include TMV, polio and HIV. The guide's own answer "
                  "contradicts itself here."],
        tip="One virus, one kind of nucleic acid.",
        note="All four possibilities, then the usual cases for plants and animals."),
      S('s4_form','boxed_final','Number and form of the nucleic acid',1,'Form',
        lines=[{"text":"One kind of nucleic acid, never both","style":"boxed"},
               "The nucleic acid molecule may be CIRCULAR or",
               "LINEAR.",
               "Most viruses have a SINGLE nucleic acid",
               "molecule.",
               "A few have more than one: HIV has TWO identical",
               "molecules of RNA."],
        why="HIV carrying two copies of its RNA is the standard exception, which is why the question is "
            "worth asking at all.",
        mistakes=["Saying every virus has one molecule. HIV has TWO identical RNA molecules.",
                  "Leaving out the shape. Circular or linear is part of this mark."],
        tip="Usually one molecule; HIV carries two.",
        note="Shape, number, and the named exception. Four lines.")]))

C.append(Q(U, 'tmv_structure', 'SAQ', 'saq3', 28, 28,
    "Explain the structure of TMV.",
    years=[('ap',2017),('ap',2018),('ap',2022),('ts',2017),('ts',2017)],
    split=[("What TMV is",1),("Shape and size",1),("The capsid",1),("The RNA core",1)],
    insider="This answer is a list of numbers: 300 nm, 18 nm, 2130 capsomeres, 158 amino acids, "
            "6500 nucleotides, 4 nm core. Write every one you remember — each is worth credit.",
    steps=[
      S('s1_what','text','What TMV is',1,'What it is',
        lines=["TMV stands for TOBACCO MOSAIC VIRUS.",
               "It is a plant virus that infects tobacco plants",
               "and causes a mosaic pattern of light and dark",
               "patches on the leaves.",
               "It is a single stranded RNA virus.",
               "It was the FIRST virus ever discovered."],
        why="TMV was the first virus isolated and the first whose structure was worked out, which is why "
            "it is the standard example in every syllabus.",
        mistakes=["Saying TMV is a DNA virus. Its genetic material is single stranded RNA.",
                  "Saying it infects animals. TMV is a PLANT virus."],
        tip="Tobacco, mosaic pattern, RNA.",
        note="Expansion, host, symptom, nucleic acid type. Five lines."),
      S('s2_size','text','Shape and size',1,'Shape, size',
        lines=["TMV is ROD SHAPED.",
               "It is about 300 nm long and 18 nm in diameter.",
               "Its molecular weight is about 39 million",
               "daltons (39 x 10 to the power 6)."],
        why="The rod shape follows from the helical arrangement of its capsomeres, so shape and internal "
            "structure are the same fact described twice.",
        mistakes=["Calling TMV spherical. It is ROD shaped.",
                  "Swapping the two dimensions. 300 nm is the LENGTH; 18 nm is the diameter."],
        tip="Three hundred long, eighteen across: a long thin rod.",
        note="Shape and both numbers. The molecular weight is a bonus."),
      S('s3_capsid','text','The capsid',1,'Capsid',
        lines=["The capsid is made of 2,130 protein subunits",
               "called CAPSOMERES.",
               "The capsomeres are arranged in a HELICAL manner",
               "around a central hollow core of 4 nm.",
               "Each protein subunit is made of 158 amino",
               "acids."],
        why="A helical stack of identical subunits is what makes a rod rather than a sphere, so the "
            "arrangement explains the shape given in the step above.",
        mistakes=["Saying the capsomeres are arranged in a sphere. They are HELICAL.",
                  "Leaving out the hollow core. The 4 nm channel runs down the middle."],
        tip="Two thousand one hundred and thirty bricks, wound in a helix.",
        note="Number, arrangement, core width, subunit size. All four numbers count."),
      S('s4_rna','boxed_final','The RNA core',1,'RNA',
        lines=[{"text":"One spiral RNA strand, 6500 nucleotides","style":"boxed"},
               "Inside the capsid lies a SINGLE STRANDED RNA,",
               "spirally coiled along the hollow core.",
               "It has about 6,500 nucleotides.",
               "The RNA is the infective part: it alone can",
               "infect a tobacco plant."],
        why="The RNA follows the same helix as the protein, so the coat and the genome are wound "
            "together rather than the genome sitting loose inside.",
        mistakes=["Saying the RNA is double stranded. TMV RNA is SINGLE stranded.",
                  "Saying the protein is the infective part. The RNA alone can infect."],
        tip="The RNA follows the same spiral as the coat.",
        note="Strandedness, the coil, the nucleotide count, and what is infective."),
      S('s5_diagram','diagram','Diagram — TMV',0,None,
        figure=figs_u8.TMV,
        why="The drawing makes one point the words cannot: the RNA and the protein subunits follow the "
            "same helix, so the coat and the genome are wound together.",
        mistakes=["Drawing TMV as a sphere. It is a ROD.",
                  "Drawing the RNA as a straight line down the middle. It is SPIRALLY coiled.",
                  "Drawing a solid rod with no hollow core. The 4 nm channel runs the whole length."],
        tip="A stack of discs with a hole down the middle and a coil inside it.",
        note="No diagram mark — the question says 'explain'. Sketch it anyway; the hollow core and the "
             "coil are two of the four written marks and the drawing fixes both.")]))

C.append(Q(U, 't_even_phage_structure', 'SAQ', 'saq4', 29, 29,
    "Explain the structure of T-even bacteriophages.",
    years=[('ap',2017),('ap',2019),('ts',2018),('ts',2019),('ts',2020)],
    split=[("What a bacteriophage is",1),("The head",1),("The tail",1),("The base plate and fibres",1)],
    insider="Tadpole shaped. That one word sets the whole picture up, and examiners look for it in the "
            "first line.",
    steps=[
      S('s1_what','text','What a bacteriophage is',1,'Definition',
        lines=["Viruses that attack BACTERIA are called",
               "BACTERIOPHAGES, or phages.",
               "T-even phages are the T2, T4 and T6 phages that",
               "infect Escherichia coli.",
               "A bacteriophage is TADPOLE SHAPED: a large head",
               "and a narrow tail."],
        why="The head holds the genome and the tail delivers it, so the tadpole shape is a division of "
            "labour rather than a coincidence.",
        mistakes=["Saying a bacteriophage is a bacterium. It is a VIRUS that attacks bacteria.",
                  "Leaving out the shape. Tadpole shaped is the phrase that carries this mark."],
        tip="A virus that eats bacteria, shaped like a tadpole.",
        note="Definition, which phages are T-even, and the shape. Five lines."),
      S('s2_head','text','The head',1,'Head',
        lines=["The HEAD is HEXAGONAL and is capped by a",
               "hexagonal pyramid.",
               "It is made of protein capsomeres.",
               "The head encloses the phage's DNA, which is",
               "double stranded and tightly coiled.",
               "The head is joined to the tail by a COLLAR."],
        why="The head is only a container: everything it does at the moment of infection is done by what "
            "is packed inside it.",
        mistakes=["Saying the head is round. It is HEXAGONAL, capped by a pyramid.",
                  "Saying the head contains RNA. T-even phage DNA is double stranded DNA."],
        tip="A six sided box with a pointed cap, full of DNA.",
        note="Shape, what it is made of, what it holds, and the collar."),
      S('s3_tail','text','The tail',1,'Tail',
        lines=["The TAIL is made of:",
               "1. a hollow CORE, down the middle;",
               "2. a contractile SHEATH around the core;",
               "3. a BASE PLATE at the far end.",
               "The tail injects the viral DNA into the host",
               "cell.",
               "The sheath contracts and drives the core",
               "through the bacterial cell wall, like the",
               "plunger of a syringe."],
        why="A contracting sheath around a rigid core is a syringe, which is exactly the job the tail "
            "has to do.",
        mistakes=["Saying the whole phage enters the bacterium. Only the DNA is injected; the coat stays outside.",
                  "Leaving out the core. The DNA travels down the HOLLOW CORE, not down the sheath."],
        tip="The sheath is the plunger, the core is the needle.",
        note="All three parts of the tail, then how it works. The syringe comparison is worth one line."),
      S('s4_plate','boxed_final','The base plate and fibres',1,'Base plate',
        lines=[{"text":"Six fibres find the host; the tail does the","style":"boxed"},
               {"text":"injecting","style":"boxed"},
               "At the tip of the tail is a HEXAGONAL BASE",
               "PLATE.",
               "It bears SIX TAIL PINS and SIX TAIL FIBRES.",
               "The tail fibres attach the virus to specific",
               "receptor sites on the bacterial cell wall.",
               "The pins hold the phage in place while the DNA",
               "is injected."],
        why="The fibres decide which bacterium the phage can infect, because they only stick to matching "
            "receptor sites — which is why each phage attacks one host.",
        mistakes=["Giving the wrong count. There are SIX tail pins and SIX tail fibres.",
                  "Saying the fibres inject the DNA. The FIBRES attach; the tail CORE injects."],
        tip="Six and six: pins to grip, fibres to find.",
        note="Plate shape, both counts, and what each part does."),
      S('s5_diagram','diagram','Diagram — T-even bacteriophage',0,None,
        figure=figs_u8.PHAGE,
        why="Drawing it shows why the phage never enters the cell: everything below the collar is a "
            "delivery device, and only what is inside the head goes in.",
        mistakes=["Drawing a round head. The head is HEXAGONAL with a pyramidal cap.",
                  "Drawing four tail fibres. There are SIX fibres and SIX pins.",
                  "Drawing the core outside the sheath. The core runs INSIDE the sheath."],
        tip="Head, collar, sheath, core, plate, pins, fibres: seven parts, top to bottom.",
        note="No diagram mark — the question says 'explain'. It is still the fastest way to check you "
             "have all seven named parts in the written answer.")]))

C.append(Q(U, 'lytic_cycle', 'SAQ', 'saq5', 30, 29,
    "Explain the lytic cycle with reference to certain viruses.",
    years=[('ts',2019),('ap',2016),('ap',2019)],
    split=[("What the lytic cycle is",1),("Attachment and penetration",1),
           ("Biosynthesis and maturation",1),("Release",1)],
    note_extra="BOOK ERROR, corrected on this card: the guide's release step calls lysozyme \"the HOST "
               "enzyme\". It is encoded by the PHAGE, not the host — and the guide's own Star Question "
               "165 on p.51 calls it \"the VIRAL enzyme\", so it contradicts itself between two pages.",
    insider="Five named steps for four marks. Name all five even if two share a line — a missing step "
            "name is the commonest way marks go here.",
    steps=[
      S('s1_what','text','What the lytic cycle is',1,'Definition',
        lines=["The LYTIC CYCLE is one of the two cycles of",
               "viral reproduction.",
               "It ends in the destruction, or LYSIS, of the",
               "infected host cell.",
               "Viruses that cause lysis are called VIRULENT",
               "phages. Example: the T-even phages.",
               "The cycle has FIVE steps: attachment,",
               "penetration, biosynthesis, maturation, release."],
        why="Naming all five steps in the first block means the rest of the answer only has to fill them "
            "in, and the examiner can see the shape immediately.",
        mistakes=["Confusing it with the lysogenic cycle. The LYTIC cycle destroys the host at once.",
                  "Naming fewer than five steps. All five have names and each is expected."],
        tip="Attach, penetrate, build, assemble, burst.",
        note="Definition, the word virulent, and the five step names in order."),
      S('s2_attach','text','Attachment and penetration',1,'Attach, penetrate',
        lines=["1. ATTACHMENT: the TAIL FIBRES attach to",
               "complementary receptor sites on the bacterial",
               "cell wall.",
               "2. PENETRATION: the tail core is driven through",
               "the cell wall and the phage DNA passes into",
               "the bacterial cell.",
               "The phage works like a hypodermic syringe.",
               "The empty capsid left outside is called the",
               "GHOST."],
        why="Only the DNA goes in, so the coat is left behind as a ghost — which is the observation the "
            "Hershey and Chase experiment later turned into proof.",
        mistakes=["Saying the whole virus enters the cell. Only the DNA enters; the capsid stays outside.",
                  "Leaving out the ghost. It is the named term for the empty coat."],
        tip="The needle goes in, the syringe stays outside.",
        note="Both steps, and the word GHOST. Seven lines."),
      S('s3_biosynthesis','text','Biosynthesis and maturation',1,'Build, assemble',
        lines=["3. BIOSYNTHESIS: once the phage DNA reaches the",
               "cytoplasm, the host's own machinery is used to",
               "make many copies of phage DNA, enzymes and",
               "capsid proteins.",
               "During this stage no complete phage can be",
               "found inside the cell.",
               "4. MATURATION: the DNA and capsids are assembled",
               "into complete VIRIONS.",
               "The time between infection and the appearance",
               "of mature virus is the ECLIPSE PERIOD."],
        why="Parts are made separately and only assembled at the end, which is exactly why no whole "
            "virus can be found during the eclipse period.",
        mistakes=["Saying the virus builds its own machinery. It uses the HOST cell's machinery.",
                  "Leaving out the eclipse period. It is the named term for this stage."],
        tip="Parts first, assembly last: that is why nothing is found in between.",
        note="Both steps, and the term ECLIPSE PERIOD. This is a named-term mark."),
      S('s4_release','boxed_final','Release',1,'Release',
        lines=[{"text":"The phage makes the enzyme that bursts the","style":"boxed"},
               {"text":"cell open","style":"boxed"},
               "5. RELEASE: the phage-coded enzyme LYSOZYME",
               "breaks down the bacterial cell wall.",
               "The cell bursts, or LYSES, and the newly made",
               "phage particles are set free.",
               "About 100 to 200 phages are released from one",
               "bacterial cell, and each can infect another."],
        why="The virus destroys the cell only at the end, after it has finished using it — the machinery "
            "has to survive long enough to build the new particles.",
        mistakes=["Calling lysozyme a host enzyme. It is coded by the PHAGE. The guide says host here "
                  "and viral two pages later.",
                  "Saying the cell survives. The lytic cycle ends in the DEATH of the host cell."],
        tip="The last thing the phage builds is the tool that lets it out.",
        note="Name the enzyme, say whose it is, and give the burst size. That number impresses.")]))

# ── VSAQ from Star Questions Plus (p.51) ────────────────────────────────────
def vs(slug, ref, gno, text, split, insider, steps, years=None, note_extra=None):
    C.append(Q(U, slug, 'VSAQ', ref, gno, 51, text, years=years, split=split,
               insider=insider, steps=steps, note_extra=note_extra))


vs('virulent_vs_temperate_phages','vsaq1',163,
   "Mention the differences between virulent phages and temperate phages.",
   [("Virulent phages",1),("Temperate phages",1)],
   "One cycle against two. That is the difference, and each half needs its named example.",
   [S('s1_virulent','text','Virulent phages',1,'Virulent',
      lines=["VIRULENT PHAGES replicate only through the LYTIC",
             "cycle.",
             "They always destroy the host cell.",
             "Example: the T-even phages (T2, T4, T6)."],
      why="A phage with only one cycle available has no way to wait, so it must kill the host every time.",
      mistakes=["Saying virulent phages can go lysogenic. They cannot; only the lytic cycle is open to them.",
                "Naming no example. The T-even phages are the standard one."],
      tip="Only one cycle, so the host always dies.",
      note="One cycle, the outcome, one example. Four lines."),
    S('s2_temperate','boxed_final','Temperate phages',1,'Temperate',
      lines=[{"text":"Virulent phages have one cycle; temperate","style":"boxed"},
             {"text":"phages have two","style":"boxed"},
             "TEMPERATE PHAGES replicate through BOTH the lytic",
             "and the LYSOGENIC cycles.",
             "In the lysogenic cycle the phage DNA joins the",
             "bacterial chromosome and is copied with it, so",
             "the host survives.",
             "Example: coliphage lambda."],
      why="Joining the host chromosome lets the phage be copied for generations without killing anything, "
          "so it can wait for better conditions before turning lytic.",
      mistakes=["Saying temperate phages never lyse the host. They CAN — they have both cycles.",
                "Naming a T-even phage. Coliphage lambda is the temperate example."],
      tip="Temperate means it can wait.",
      note="Both cycles, what lysogeny does, one example. The word lysogenic is the mark.")],
   years=[('ap',2015)])

vs('tmv_shape_and_genome','vsaq2',164,
   "What is the shape of TMV? What is its genetic material?",
   [("Shape",1),("Genetic material",1)],
   "Two short facts. Add the nucleotide count if you remember it; it costs one line and reads as "
   "precise knowledge.",
   [S('s1_shape','text','Shape',1,'Shape',
      lines=["TMV stands for TOBACCO MOSAIC VIRUS.",
             "Its shape is a ROD."],
      why="The rod shape comes from its capsomeres being stacked in a helix rather than packed into a "
          "sphere.",
      mistakes=["Saying TMV is spherical or polyhedral. It is ROD shaped.",
                "Not expanding TMV. The full name is part of a complete answer."],
      tip="A rod, because the coat is a helix.",
      note="Expansion plus the shape. Two lines."),
    S('s2_genome','boxed_final','Genetic material',1,'Genome',
      lines=[{"text":"Single stranded RNA, about 6500 nucleotides","style":"boxed"},
             "Its genetic material is SINGLE STRANDED RNA.",
             "The strand has about 6,500 nucleotides.",
             "It lies spirally coiled inside the hollow core."],
      why="TMV is one of the standard examples of an RNA virus, which is why this fact is asked so often.",
      mistakes=["Saying TMV has DNA. Its genetic material is RNA.",
                "Saying the RNA is double stranded. It is SINGLE stranded."],
      tip="RNA, single stranded, coiled.",
      note="Type, strandedness, count. Four lines.")],
   years=[('ts',2015)])

vs('lysozyme','vsaq3',165,
   "What is lysozyme and what is its function?",
   [("What it is",1),("Its function",1)],
   "The word to get right is VIRAL. The guide itself calls it a host enzyme on one page and a viral "
   "enzyme on another; the phage codes it.",
   [S('s1_what','text','What lysozyme is',1,'What it is',
      lines=["LYSOZYME is an enzyme coded by the VIRUS, not by",
             "the host.",
             "It is produced inside the infected bacterial cell",
             "during the lytic cycle."],
      why="The phage has to bring its own way out, because a bacterium would not make an enzyme that "
          "destroys itself.",
      mistakes=["Calling it a host enzyme. It is VIRAL — the phage codes it. The guide contradicts "
                "itself on this between p.29 and p.51.",
                "Saying it is made before infection. It is made INSIDE the host cell during the cycle."],
      tip="The phage brings its own key to the door.",
      note="Say VIRAL and say when it is made. Four lines."),
    S('s2_function','boxed_final','Its function',1,'Function',
      lines=[{"text":"It breaks the cell wall so the new phages","style":"boxed"},
             {"text":"can escape","style":"boxed"},
             "Lysozyme breaks down the BACTERIAL CELL WALL.",
             "The cell bursts, or lyses, and the newly made",
             "phage particles (virions) are released.",
             "This is the last step of the lytic cycle."],
      why="Without it the finished virions would stay trapped inside a dead cell, so the enzyme is what "
          "turns a successful infection into a spreading one.",
      mistakes=["Saying lysozyme breaks the plasma membrane only. It breaks the CELL WALL.",
                "Saying it acts at the start of the cycle. It acts at the END, in the release step."],
      tip="Last enzyme made, last step of the cycle.",
      note="What it breaks, what follows, and where it sits in the cycle.")],
   years=[('ts',2016)])

main(C, U)
