/**
 * Re-scope the 4 engine_bug_queue rows whose prevention_rule still instructs the
 * pre-Rule-31 Socratic behaviour (predict-pauses / pause_after_ms / pause-before-
 * resolution). The 2026-07-03 queue audit found these are the only rows an
 * architect/json-author reading the queue blind could follow into a Rule 31
 * violation on a NEW concept. Rows are NOT deleted (the queue is the scar-list
 * moat; Gate 8 keys off bug_class) — each prevention_rule gets a LEGACY banner
 * scoping it to legacy retrofits only.
 *
 * Idempotent: sets the full new text (re-running is a no-op).
 * Run: npx tsx --env-file=.env.local src/scripts/_rescope_legacy_socratic_bug_rows.ts
 */
import '@/lib/loadEnvLocal';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { supabaseAdmin } from '@/lib/supabaseAdmin';

interface Rescope {
  bug_class: string;
  prevention_rule: string;
}

const BANNER = 'LEGACY (pre-Rule-31, retrofit-only — NEVER apply to NEW concepts; Rule 31 / Gate 3e forbids predict-pauses and pause_after_ms on new authoring): ';

const rescopes: Rescope[] = [
  {
    bug_class: 'solenoid_dropped_prediction_pauses_x4',
    prevention_rule:
      BANNER +
      'When retrofitting/porting a LEGACY Socratic field_3d JSON, carry every pause_after_ms from its physics block; field_3d DOES consume pause_after_ms via deriveStateMeta. On NEW concepts there are no prediction pauses to carry — author straightforward distinct-motion beats instead (Rule 31; exemplars faraday_law_induction, magnetisation_and_intensity).',
  },
  {
    bug_class: 'crossagent_jsonauthor_drops_pause_after_ms_cloning_electric_flux',
    prevention_rule:
      BANNER +
      'The durable cross-agent lesson is strategy-neutral: when json_author clones/ports an existing JSON, it MUST carry every timing field the physics block authored — dropped fields are silent regressions. The specific field here (pause_after_ms) exists only on LEGACY Socratic JSONs; carry it only when retrofitting those. On NEW Rule-31 concepts never author pause_after_ms at all.',
  },
  {
    bug_class: 'gate3c_does_not_run_on_field3d_use_gate15',
    prevention_rule:
      BANNER +
      'Gate 3c (Socratic-reveal) is legacy-only and never fires on field_3d (no teaching_method). Gate 15 (Pass-2 four-question) remains the cognitive-flow gate for field_3d — but on NEW Rule-31 concepts it audits straightforward distinct-motion beats + motion-before-words + per-state contextual controls (Gate 3e), and must NOT require pause-before-resolution: predict-pauses are forbidden on new concepts. Audit pause-before-resolution only on legacy Socratic retrofits.',
  },
  {
    bug_class: 'solenoid_state5_gesture_sequencing_absent',
    prevention_rule:
      'Add a gesture-sequencing primitive so the narrated grip cross-fade actually animates — bind it to the sentence that narrates it via the scenario_cue channel (SET_CUE_TIME + cueTriggerMs, *_at_ms as THE-EYE fallback), never a bare fixed-ms trigger. NOTE (2026-07-03 re-scope): the original phrasing said "lands after the prediction pause (reveal after the question)" — that framing is LEGACY pre-Rule-31; solenoid is a Socratic-era JSON, and on NEW concepts no predict-pause exists (Rule 31 / Gate 3e). The underlying bug (narrated gesture never animates) is strategy-neutral and still OPEN.',
  },
];

function sqlStr(s: string): string { return `'${s.replace(/'/g, "''")}'`; }

function emitSql(): string {
  const stmts = rescopes.map(
    (r) =>
      `UPDATE engine_bug_queue SET prevention_rule = ${sqlStr(r.prevention_rule)}\nWHERE bug_class = ${sqlStr(r.bug_class)};`,
  );
  return (
    `-- 2026-07-03: re-scope the 4 pre-Rule-31 Socratic prevention rules in engine_bug_queue\n` +
    `-- (queue audit: only rows whose prevention_rule instructs predict-pause/pause_after_ms\n` +
    `-- behaviour that Rule 31 / Gate 3e forbids on NEW concepts). Rows kept, text re-scoped\n` +
    `-- with a LEGACY retrofit-only banner. Generated by\n` +
    `-- src/scripts/_rescope_legacy_socratic_bug_rows.ts — idempotent.\n\n` +
    stmts.join('\n\n') +
    '\n'
  );
}

async function main(): Promise<void> {
  const sqlPath = join(
    process.cwd(),
    'supabase_2026-07-03_rescope_legacy_socratic_bug_rows_migration.sql',
  );
  writeFileSync(sqlPath, emitSql(), 'utf-8');
  console.log(`Wrote archival SQL: ${sqlPath} (${rescopes.length} UPDATEs)`);

  for (const r of rescopes) {
    const { data, error } = await supabaseAdmin
      .from('engine_bug_queue')
      .update({ prevention_rule: r.prevention_rule })
      .eq('bug_class', r.bug_class)
      .select('bug_class');
    if (error) { console.error(`✗ ${r.bug_class}: ${error.message}`); process.exit(1); }
    if (!data || data.length === 0) { console.error(`✗ ${r.bug_class}: no row matched`); process.exit(1); }
    console.log(`✓ re-scoped ${r.bug_class}`);
  }

  const { data, error } = await supabaseAdmin
    .from('engine_bug_queue')
    .select('bug_class, status, prevention_rule')
    .in('bug_class', rescopes.map((r) => r.bug_class));
  if (error) { console.error('verify query failed:', error.message); process.exit(1); }
  console.log('\nVerification:');
  for (const row of data ?? []) {
    const banner = row.prevention_rule.startsWith('LEGACY') || row.prevention_rule.includes('LEGACY pre-Rule-31');
    console.log(`  [${row.status}] ${row.bug_class} — legacy-scoped: ${banner ? 'YES' : 'NO'}`);
  }
}

main().catch((err) => { console.error('💥 re-scope failed:', err instanceof Error ? err.stack : err); process.exit(1); });
