/**
 * engine_bug_queue row for the 6th finding surfaced by eye-walker's CONFIRMATION pass
 * (run 20260708-022026, after the first 5 defects were fixed) — the magnetic_flux_loop
 * mesh's own on-screen footprint is WIDEST at theta=90deg (edge-on/zero-flux) and
 * NARROWEST at theta=0deg (face-on/max-flux), which reads backwards on the S4 PRIMARY
 * aha frame. The companion A.cos(theta) shadow and the Phi=0.00 readout both behave
 * correctly, so this is flagged OPEN/ambiguous pending a founder call on whether the
 * loop's rotation.y = (90 - thetaDeg) convention in mflApplyPose is deliberate
 * (kept so the theta-arc/label stays legible) or an inversion defect.
 *
 * Per the "recording -> engine_bug_queue" protocol: log every eye-walker finding, even
 * ones held for founder judgment rather than auto-fixed.
 *
 * Idempotent: upsert onConflict 'bug_class'. Also writes the archival SQL.
 * Run: npx tsx --env-file=.env.local src/scripts/_seed_engine_bug_queue_mfl_loop_footprint_vs_theta.ts
 */
import '@/lib/loadEnvLocal';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { supabaseAdmin } from '@/lib/supabaseAdmin';

const SESSION = 'session_2026-07-08_magnetic_flux_loop_confirmation_pass';

const row = {
  bug_class: 'mfl_loop_footprint_inverted_vs_theta',
  title:
    'magnetic_flux_loop S4/S5/S6: the loop mesh\'s own on-screen footprint is WIDEST at theta=90deg (edge-on/zero-flux) and NARROWEST at theta=0deg (face-on/max-flux) — visually backwards for "edge-on" on the S4 PRIMARY aha frame. The A.cos(theta) shadow and the Phi=0.00 readout both behave correctly, so the aha still lands through those, but the loop\'s own silhouette may contradict them.',
  severity: 'MODERATE' as const,
  owner_cluster: 'peter_parker:renderer_primitives' as const,
  root_cause:
    'mflApplyPose() sets grp.rotation.y = radians(90 - thetaDeg) against a base loop-mesh geometry apparently authored face-on-to-camera at rotation=0 — this makes the mesh\'s apparent screen width track (90-theta) rather than theta directly, so the mesh looks MORE open exactly when theta -> 90 (zero flux) and MORE tilted/narrow when theta -> 0 (max flux). NOT YET CONFIRMED as a defect vs a deliberate convention (possibly chosen so the theta-arc/normal-vector label stays legible against the camera) — eye-walker flagged this as genuinely ambiguous on the confirmation pass, pending founder/renderer_primitives review of whether the rotation formula should be inverted (e.g. rotation.y = radians(thetaDeg)) so the loop\'s own footprint shrinks toward edge-on in the same direction as the shadow and the flux readout.',
  prevention_rule:
    'When a tilt mechanic drives a companion 2D shadow/projection specifically because the 3D mesh\'s own screen footprint doesn\'t legibly convey the tilt, verify the mesh\'s own apparent size ALSO tracks the taught angle in the SAME direction as the shadow and the numeric readout — don\'t rely on the shadow alone to carry the "edge-on" read. On any state combining a rotating mesh with a companion projection value, sample the mesh\'s own screen-space bounding width at theta_range.min and theta_range.max and confirm it moves the same direction as the projection\'s.',
  probe_type: 'manual' as const,
  probe_logic:
    'On magnetic_flux_loop S4 dense frames, compare the loop mesh\'s on-screen bounding-box width at theta=0 (theta_range.min) against theta=90 (theta_range.max) — founder/reviewer call: does "wider at edge-on" read as correct (deliberate camera framing) or backwards (rotation inversion)? If backwards, the fix is inverting the rotation.y formula in mflApplyPose so the loop\'s own footprint collapses toward theta=90, matching the A.cos(theta) shadow and the Phi readout.',
  concepts_affected: ['magnetic_flux'],
  fixed_in_files: [] as string[],
  row_type: 'incident' as const,
};

function sqlStr(s: string): string { return `'${s.replace(/'/g, "''")}'`; }
function sqlArr(a: string[]): string { return a.length === 0 ? `ARRAY[]::text[]` : `ARRAY[${a.map(sqlStr).join(', ')}]`; }

async function main(): Promise<void> {
  const sqlPath = join(
    process.cwd(),
    'supabase_migrations',
    'supabase_2026-07-08_seed_engine_bug_queue_mfl_loop_footprint_vs_theta_open_migration.sql',
  );
  const cols = 'bug_class, title, severity, owner_cluster, root_cause, prevention_rule, probe_type, probe_logic, status, concepts_affected, fixed_in_files, discovered_in_session, row_type';
  const sql =
    `-- 2026-07-08: eye-walker confirmation-pass finding #6 on magnetic_flux_loop (status=OPEN, ambiguous pending founder call).\n` +
    `-- Generated by src/scripts/_seed_engine_bug_queue_mfl_loop_footprint_vs_theta.ts — idempotent.\n\n` +
    `INSERT INTO engine_bug_queue (${cols}) VALUES\n` +
    `(${sqlStr(row.bug_class)}, ${sqlStr(row.title)}, ${sqlStr(row.severity)}, ${sqlStr(row.owner_cluster)}, ` +
    `${sqlStr(row.root_cause)}, ${sqlStr(row.prevention_rule)}, ${sqlStr(row.probe_type)}, ${sqlStr(row.probe_logic)}, ` +
    `'OPEN', ${sqlArr(row.concepts_affected)}, ${sqlArr(row.fixed_in_files)}, ${sqlStr(SESSION)}, ${sqlStr(row.row_type)})\n` +
    `ON CONFLICT (bug_class) DO UPDATE SET status = EXCLUDED.status, root_cause = EXCLUDED.root_cause,\n` +
    `  prevention_rule = EXCLUDED.prevention_rule, probe_logic = EXCLUDED.probe_logic,\n` +
    `  title = EXCLUDED.title, severity = EXCLUDED.severity, owner_cluster = EXCLUDED.owner_cluster;\n`;
  writeFileSync(sqlPath, sql, 'utf-8');
  console.log(`Wrote archival SQL: ${sqlPath}`);

  const { error } = await supabaseAdmin.from('engine_bug_queue').upsert(
    {
      bug_class: row.bug_class,
      title: row.title,
      severity: row.severity,
      owner_cluster: row.owner_cluster,
      root_cause: row.root_cause,
      prevention_rule: row.prevention_rule,
      probe_type: row.probe_type,
      probe_logic: row.probe_logic,
      status: 'OPEN',
      concepts_affected: row.concepts_affected,
      fixed_in_files: row.fixed_in_files,
      discovered_in_session: SESSION,
      row_type: row.row_type,
      fixed_at: null,
    },
    { onConflict: 'bug_class' },
  );
  if (error) { console.error(`✗ upsert failed: ${error.message}`); process.exit(1); }
  console.log(`✓ upserted engine_bug_queue row at status=OPEN`);
}

main();
