/**
 * engine_bug_queue rows from the eye-walker frame walk of kinetic_particle_theory
 * (run .visual_runs/kinetic_particle_theory/20260728-004421, 2026-07-28).
 *
 * The load-bearing lesson of this run: THE EYE reported 31/31 deterministic
 * checks passed, TWICE, over frames generated by the WRONG stepper. A green
 * deterministic gate certifies that frames are reproducible, not that they are
 * correct — reproducibly wrong passes it. Only reading pixels caught it.
 *
 * All five are FIXED and re-verified.
 * Run: npx tsx --env-file=.env.local src/scripts/_seed_engine_bug_queue_gas_box_eyewalker.ts
 */
import '@/lib/loadEnvLocal';
import { supabaseAdmin } from '@/lib/supabaseAdmin';

const SESSION = 'session_2026-07-28_gas_box_eyewalker_walk';
const RENDERER = 'src/lib/renderers/particle_field_renderer.ts';
const RUN = '.visual_runs/kinetic_particle_theory/20260728-004421';
const CONCEPT = 'kinetic_particle_theory';

type Owner = 'peter_parker:renderer_primitives' | 'peter_parker:visual_validator' | 'ambiguous';
type Severity = 'CRITICAL' | 'MAJOR' | 'MODERATE';
interface Row {
  bug_class: string; title: string; severity: Severity; owner_cluster: Owner;
  root_cause: string; prevention_rule: string; probe_type: 'sql' | 'js_eval' | 'manual' | 'vision_model';
  probe_logic: string; status: 'OPEN' | 'FIXED' | 'DEFERRED';
  concepts_affected: string[]; fixed_in_files: string[]; row_type: 'incident' | 'directive';
}

const rows: Row[] = [
  {
    bug_class: 'gas_box_freeze_resim_uses_wrong_stepper',
    title: 'SET_TIME_FREEZE re-sim ran the electron-drift stepper over gas particles — every frozen and dense EYE frame was corrupt, and the gate passed 31/31 anyway',
    severity: 'CRITICAL',
    owner_cluster: 'peter_parker:renderer_primitives',
    root_cause:
      `VERIFIED + FIXED 2026-07-28 (found by eye-walker on ${RUN}). The SET_TIME_FREEZE handler ` +
      `stepped with "if (isCircuitFamily()) stepCircuit(st); else stepPhysics(st);" — the gas_box ` +
      `family got its branch in draw()/pmStepTicks but NOT at the freeze re-sim call site. So every ` +
      `deterministic capture beyond t=0 advanced gas discs using the free-drift lattice physics, ` +
      `which knows nothing of gasBoxL/R/T/B: particles walked straight through the walls (clean at ` +
      `t=0, ~15 escaped by t=4000ms, ~45+ scattered across the reserved graph pane by t=14000ms), ` +
      `and gasCollide/gasSampleStats never ran so P and collisions/s stayed pinned at 0.000 in ` +
      `every frozen frame. Isolated to the capture path by the KEYFRAMES capture (continuous Rule-37 ` +
      `clock), which showed correct containment, P=0.063 and 71 collisions/s. FIXED by extracting a ` +
      `single stepFor(state) dispatcher used by BOTH the live loop and the freeze re-sim, so the two ` +
      `paths cannot diverge again. Re-verified: pinned at 0/4000/9000/14000 ms, escaped particles ` +
      `0/0/0/0 and P 0/0.065/0.060/0.065.`,
    prevention_rule:
      'A scenario family that ships its own step function must be dispatched from ONE shared helper ' +
      'used by every stepping call site (live loop AND SET_TIME_FREEZE re-sim). Never duplicate the ' +
      'family branch. Corollary, and the bigger lesson: a green deterministic gate proves frames are ' +
      'REPRODUCIBLE, not correct — reproducibly-wrong physics passes every check. Any new scenario ' +
      'family must have at least one frozen frame read by eyes before its baselines are trusted.',
    probe_type: 'js_eval',
    probe_logic:
      'Pin SET_TIME_FREEZE at several times across a state and assert particles remain inside the ' +
      'scenario bounds and that accumulated stats (pressure, collision rate) are non-zero.',
    status: 'FIXED',
    concepts_affected: [CONCEPT],
    fixed_in_files: [RENDERER],
    row_type: 'incident',
  },
  {
    bug_class: 'pf_readout_ohms_branch_keys_on_bare_slider_name',
    title: 'A slider named "V" for Volume triggered the Ohm\'s-law readout — a gas box printed "V = 1.00 V / i = 59.71 A / R = 0.02 Ohm" in the live product',
    severity: 'CRITICAL',
    owner_cluster: 'peter_parker:renderer_primitives',
    root_cause:
      `VERIFIED + FIXED 2026-07-28 (eye-walker). updateReadouts() branches on ` +
      `"hasSlider('V') || hasSlider('R')" as a proxy for "this is an Ohm's-law circuit", with no ` +
      `scenario-family gate. kinetic_particle_theory declares a Volume slider keyed 'V', so every ` +
      `state showing any slider row (S2/S4/S6/S7) rendered electrical voltage, current and ` +
      `resistance under a kinetic-theory gas panel. updateReadouts is called unconditionally from ` +
      `applyStateVisuals on every SET_STATE, so this shipped to the teacher surface, not just to ` +
      `captures — confirmed in the KEYFRAMES live-clock frame. FIXED with a gasMode() early-out ` +
      `above the Ohm's-law branch (the gas instruments live on canvas, so the DOM readout is hidden).`,
    prevention_rule:
      'Never infer a scenario from a bare slider key. Every branch in updateReadouts (and any ' +
      'similar shared dispatcher) must be gated on the owning scenario family first — the same ' +
      'discipline draw() already applies. Single-letter slider ids are shared namespace across every ' +
      'concept on the renderer.',
    probe_type: 'vision_model',
    probe_logic:
      'For each concept, assert the DOM readout text contains only quantities that concept teaches; ' +
      'flag any electrical units rendered by a non-circuit scenario.',
    status: 'FIXED',
    concepts_affected: [CONCEPT],
    fixed_in_files: [RENDERER],
    row_type: 'incident',
  },
  {
    bug_class: 'pf_slider_dom_value_ignores_authored_state_value',
    title: 'Slider thumb and label showed the build-time default while the canvas honoured the state\'s authored value — panel read "Volume 1" over a box compressed to 0.5',
    severity: 'MAJOR',
    owner_cluster: 'peter_parker:renderer_primitives',
    root_cause:
      `VERIFIED + FIXED 2026-07-28 (eye-walker; recurrence of the known indicator/DOM-desync scar ` +
      `class). Slider inputs are built once with value = def.default and never re-synced on state ` +
      `entry. The drag-seize fix had already made the PHYSICS read the authored per-state value, so ` +
      `STATE_4 compressed correctly to piston_frac 0.5 while the teacher's only numeric handle on ` +
      `that variable displayed 1 — the control contradicted the picture. FIXED: on each state apply, ` +
      `unseized gas sliders are re-synced to the effective authored value.`,
    prevention_rule:
      'Before a control is seized by the teacher, its DOM thumb and value label must display the ' +
      'same live/authored value the canvas is using. Re-sync on every state apply, never only at ' +
      'build time.',
    probe_type: 'js_eval',
    probe_logic:
      'On entering each state, assert every visible slider input value equals the effective authored ' +
      'value for that variable.',
    status: 'FIXED',
    concepts_affected: [CONCEPT],
    fixed_in_files: [RENDERER],
    row_type: 'incident',
  },
  {
    bug_class: 'gas_box_compression_ghost_outline_illegible',
    title: 'The ghost outline marking the uncompressed box compounded to ~7.7% opacity — the Rule-32c delta marker was present in pixels but invisible',
    severity: 'MODERATE',
    owner_cluster: 'peter_parker:renderer_primitives',
    root_cause:
      `VERIFIED + FIXED 2026-07-28 (eye-walker). The ghost stroke used 0.22 * dimFor('box'); in ` +
      `STATE_4 the focal is the piston, so dimFor('box') returns the non-focal 0.35 and the two ` +
      `multiplied to ~0.077. The marker exists solely to keep the swept volume visible, and focal ` +
      `dimming erased exactly the thing it had to show. FIXED with an alpha FLOOR rather than a ` +
      `plain multiply.`,
    prevention_rule:
      'A stroke whose job is to make a Rule-32c delta visible must have a minimum alpha exempt from ' +
      'focal-dim compounding. Emphasis dimming (Rule 29) may not be allowed to erase the delta cue.',
    probe_type: 'vision_model',
    probe_logic: 'Confirm the ghost outline is discernible in the state where the piston is compressed.',
    status: 'FIXED',
    concepts_affected: [CONCEPT],
    fixed_in_files: [RENDERER],
    row_type: 'incident',
  },
  {
    bug_class: 'gas_box_home_pose_reads_as_grid_not_gas',
    title: 'The frozen opening frame showed visible row/column lattice structure — an "arranged" pose opening a lesson whose claim is random motion',
    severity: 'MODERATE',
    owner_cluster: 'peter_parker:renderer_primitives',
    root_cause:
      `VERIFIED + FIXED 2026-07-28 (eye-walker). gasPlaceSpecies seeds a jittered grid to guarantee ` +
      `no initial overlap; jitter was widened from +-0.30 to +-0.44 of a cell during bring-up but ` +
      `lattice structure still read clearly. It matters more here than it looks: the review player ` +
      `holds a FROZEN opening frame until Play, so this arranged pose is the first — and, until the ` +
      `teacher presses Play, the only — thing seen of STATE_1 "Particles never stop". FIXED by ` +
      `running 55 collision-resolving settle ticks at init, which scramble the lattice without ` +
      `advancing the clock, firing a cue, or changing the energy.`,
    prevention_rule:
      'When particle placement uses a lattice for overlap-safety, relax it before display. Any pose ' +
      'held frozen before playback must already look like what the state claims to show.',
    probe_type: 'vision_model',
    probe_logic: 'Inspect the t=0 frame of each state for residual row/column structure.',
    status: 'FIXED',
    concepts_affected: [CONCEPT],
    fixed_in_files: [RENDERER],
    row_type: 'incident',
  },
];

async function main(): Promise<void> {
  let ok = 0;
  for (const r of rows) {
    const res = await supabaseAdmin
      .from('engine_bug_queue')
      .upsert({ ...r, discovered_in_session: SESSION }, { onConflict: 'bug_class' });
    if (res.error) console.error(`  x ${r.bug_class}: ${res.error.message}`);
    else { ok++; console.log(`  ok ${r.severity.padEnd(8)} ${r.bug_class}`); }
  }
  console.log(`\n${ok}/${rows.length} eye-walker rows upserted (run ${RUN}).`);
}
main().catch((e) => { console.error('seed failed:', e); process.exit(1); });
