/**
 * Seed engine_bug_queue with the founder-review scar(s) for
 * current_loop_acts_as_dipole. Founder screenshot (review site) showed the
 * simulation canvas rendered on a WHITE background instead of the dark
 * #0A0A1A all other field_3d diamonds use.
 *
 * Workflow (per the standing rule): log OPEN first, then fix, then flip FIXED.
 * Flip STATUS to 'FIXED' and re-run once the fix is applied + verified.
 *
 * Idempotent: upsert onConflict 'bug_class'. Also (re)writes the archival SQL.
 *
 * Run: npx tsx --env-file=.env.local src/scripts/_seed_engine_bug_queue_current_loop_dipole_review.ts
 */
import '@/lib/loadEnvLocal';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { supabaseAdmin } from '@/lib/supabaseAdmin';

const SESSION = 'session_2026-06-26_current_loop_dipole_review';

type Owner =
  | 'alex:architect' | 'alex:physics_author' | 'alex:json_author'
  | 'peter_parker:renderer_primitives' | 'peter_parker:runtime_generation'
  | 'peter_parker:visual_validator' | 'ambiguous';
type Severity = 'CRITICAL' | 'MAJOR' | 'MODERATE';
type Status = 'OPEN' | 'FIXED' | 'DEFERRED' | 'NOT_REPRODUCING' | 'FALSE_POSITIVE';
type ProbeType = 'sql' | 'js_eval' | 'manual' | 'vision_model';
type RowType = 'incident' | 'directive';

interface Row {
  bug_class: string;
  title: string;
  severity: Severity;
  owner_cluster: Owner;
  root_cause: string;
  prevention_rule: string;
  probe_type: ProbeType;
  probe_logic: string;
  status: Status;
  concepts_affected: string[];
  fixed_in_files: string[];
  row_type: RowType;
}

// ── Flip to 'FIXED' after the fix is applied + verified, then re-run. ──
const STATUS: Status = 'FIXED';

const R = 'peter_parker:renderer_primitives';
const RENDERER = ['src/lib/renderers/field_3d_renderer.ts'];

const incidents: Row[] = [
  {
    bug_class: 'field3d_scene_background_white_when_pvl_colors_lacks_background',
    title: 'field_3d scene renders on WHITE when pvl_colors is set but omits the background key',
    severity: 'MAJOR',
    owner_cluster: R,
    root_cause:
      'scene.background was set with a ternary: new THREE.Color(config.pvl_colors ? config.pvl_colors.background : "#0A0A1A"). ' +
      'When a concept declares pvl_colors (e.g. positive/negative for a bar-magnet compare) but omits the background key, ' +
      'config.pvl_colors is truthy so config.pvl_colors.background is undefined → THREE.Color(undefined) defaults to WHITE. ' +
      'The CSS body background (line ~798) used ?? and was correct, but the THREE scene background used the unsafe ternary — ' +
      'so the canvas went white. current_loop_acts_as_dipole was the first concept to set pvl_colors without a background key ' +
      '(all 23 other pvl_colors concepts include one).',
    prevention_rule:
      'Engine: read scene background with null-coalescing so a missing key falls back to the dark default — ' +
      'new THREE.Color((config.pvl_colors && config.pvl_colors.background) || "#0A0A1A"). ' +
      'JSON: when a concept sets field_3d_config.pvl_colors, always include "background" (#0A0A1A) like every sibling.',
    probe_type: 'manual',
    probe_logic:
      'Seed any field_3d concept whose pvl_colors omits background; the rendered canvas background must be dark (#0A0A1A), not white.',
    status: STATUS,
    concepts_affected: ['current_loop_acts_as_dipole'],
    fixed_in_files: [...RENDERER, 'src/data/concepts/current_loop_acts_as_dipole.json'],
    row_type: 'incident',
  },
];

function sqlStr(s: string): string { return `'${s.replace(/'/g, "''")}'`; }
function sqlArr(a: string[]): string {
  if (a.length === 0) return `ARRAY[]::text[]`;
  return `ARRAY[${a.map(sqlStr).join(', ')}]`;
}
function sqlRow(r: Row): string {
  return `(${sqlStr(r.bug_class)}, ${sqlStr(r.title)}, ${sqlStr(r.severity)}, ${sqlStr(r.owner_cluster)}, ` +
    `${sqlStr(r.root_cause)}, ${sqlStr(r.prevention_rule)}, ${sqlStr(r.probe_type)}, ${sqlStr(r.probe_logic)}, ` +
    `${sqlStr(r.status)}, ${sqlArr(r.concepts_affected)}, ${sqlArr(r.fixed_in_files)}, ${sqlStr(SESSION)}, ${sqlStr(r.row_type)})`;
}
function emitSql(all: Row[]): string {
  const cols = 'bug_class, title, severity, owner_cluster, root_cause, prevention_rule, probe_type, probe_logic, status, concepts_affected, fixed_in_files, discovered_in_session, row_type';
  return `-- ============================================================================
-- 2026-06-26: engine_bug_queue scar — current_loop_acts_as_dipole founder review.
-- field_3d scene background went WHITE because pvl_colors was set without a
-- background key and scene.background used an unsafe ternary (not ??).
-- Generated by src/scripts/_seed_engine_bug_queue_current_loop_dipole_review.ts — idempotent.
-- ============================================================================

INSERT INTO engine_bug_queue (${cols}) VALUES
${all.map(sqlRow).join(',\n')}
ON CONFLICT (bug_class) DO UPDATE SET
  status = EXCLUDED.status, root_cause = EXCLUDED.root_cause,
  prevention_rule = EXCLUDED.prevention_rule, fixed_in_files = EXCLUDED.fixed_in_files;
`;
}

async function main(): Promise<void> {
  const sqlPath = join(process.cwd(), 'supabase_migrations', 'supabase_2026-06-26_seed_engine_bug_queue_current_loop_dipole_review_migration.sql');
  writeFileSync(sqlPath, emitSql(incidents), 'utf-8');
  console.log(`Wrote archival SQL: ${sqlPath}`);

  const payload = incidents.map((r) => ({ ...r, discovered_in_session: SESSION }));
  const { error } = await supabaseAdmin.from('engine_bug_queue').upsert(payload, { onConflict: 'bug_class' });
  if (error) { console.error(`✗ upsert failed: ${error.message}`); process.exit(1); }
  console.log(`✓ ${incidents.length} row(s) upserted at status ${STATUS}`);
}

main().catch((err) => {
  console.error('💥 seed failed:', err instanceof Error ? err.stack : err);
  process.exit(1);
});
