-- session_2026-07-09_current_loop_acts_as_dipole_legibility_from_eye_walk
-- current_loop_acts_as_dipole legibility gaps surfaced by eye-walker (run 20260710-001743).
-- Full context: docs/notes/biot_savart_law-engine-fix-spec.md

INSERT INTO engine_bug_queue
  (bug_class, title, severity, owner_cluster, root_cause, prevention_rule, probe_type, probe_logic, status, concepts_affected, fixed_in_files, row_type)
VALUES ('loop_dipole_couple_simultaneous_reveal', 'current_loop_acts_as_dipole STATE_6 shows external B, the force couple, and τ all at once — no cause-before-effect beat (Rule 32a); force_vectors/mu_vector/tau_vector extras have no reveal_at_ms hook', 'MODERATE', 'peter_parker:renderer_primitives', 'STATE_6 caption narrates three sequential clauses ("Uniform B switched on. Opposite sides feel opposite forces — a couple. τ = m × B appears.") but B, the two force arrows, and τ are all fully rendered at dense_t00000. In the renderer, setVisibleWithFade sets fadeStartTime = state entry for f_left/f_right/mu_arrow/tau_arrow with no stagger, and the mu_vector/tau_vector/force_vectors extras carry no reveal_at_ms field, so cause (B) and effect (forces→torque) appear simultaneously with no readable beat.', 'The loop-in-field couple/torque extras (force_vectors, mu_vector, tau_vector) need an authorable reveal_at_ms/stagger hook so the cause (external B on) can visibly precede the effect (opposite forces → τ) by a readable beat (Rule 32a). Applies to any concept on this couple-rendering path (current_loop_acts_as_dipole; check torque_on_current_loop_in_field siblings). Fixed-identity vector colours (m yellow, τ magenta, B blue) are an acceptable alternate to brighten/dim single-focal — 32e is not the issue here; the sequencing is.', 'vision_model', 'eye-walker pixel-diff of STATE_6 dense frames (run 20260710-001743): B/forces/τ pixel-identical from t=0 to t=20000; all change confined to the loop current-dot flow, never touching the B-arrow or vector-label regions. Post-fix: B appears first, then after a beat the force pair + τ fade in.', 'OPEN', ARRAY['current_loop_acts_as_dipole'], ARRAY['src/lib/renderers/field_3d_renderer.ts'], 'incident')
ON CONFLICT (bug_class) DO UPDATE SET
  title = EXCLUDED.title, severity = EXCLUDED.severity, owner_cluster = EXCLUDED.owner_cluster,
  root_cause = EXCLUDED.root_cause, prevention_rule = EXCLUDED.prevention_rule,
  probe_type = EXCLUDED.probe_type, probe_logic = EXCLUDED.probe_logic, status = EXCLUDED.status,
  concepts_affected = EXCLUDED.concepts_affected, fixed_in_files = EXCLUDED.fixed_in_files, row_type = EXCLUDED.row_type;

INSERT INTO engine_bug_queue
  (bug_class, title, severity, owner_cluster, root_cause, prevention_rule, probe_type, probe_logic, status, concepts_affected, fixed_in_files, row_type)
VALUES ('loop_dipole_micro_claim_without_micro_visual', 'current_loop_acts_as_dipole STATE_8 narrates the atomic/electron origin of magnetism but the frame reuses the macro-loop pose from STATE_2/3 pixel-for-pixel — no micro visual (Rule 32c delta / Rule 33 spirit)', 'MODERATE', 'ambiguous', 'STATE_8 caption ("Electrons orbiting in atoms are tiny current loops. All magnetism is built from loops like this one.") promises a scale shift to the microscopic, but field_3d_config STATE_8 reuses the same loop+field-line extras as STATE_2/STATE_3 — the rendered frame is visually indistinguishable (masked pixel-diff vs STATE_2 ≈ current-dot-phase difference only). No atom/electron/lattice visual, no zoom-lens connector.', 'When a state caption references a microscopic mechanism (electrons/atoms), the rendered frame must show a micro-scale visual distinct from the macro apparatus already on screen (Rule 32c delta cue must be met by the picture; Rule 33 dual-level spirit). Two fix paths: (json_author) give STATE_8 a distinct field_3d_config visual/camera so it is not a pixel-repeat of STATE_2/3; or (renderer_primitives) add a small atom/orbiting-electron micro primitive with a zoom-lens link. Never let the "origin" state silently reuse an earlier frozen pose.', 'vision_model', 'eye-walker: STATE_8__frozen.png vs STATE_2__frozen.png near-identical (run 20260710-001743). Post-fix: STATE_8 shows a micro-scale (atom/electron-loop) visual distinct from the macro loop.', 'OPEN', ARRAY['current_loop_acts_as_dipole'], ARRAY[]::text[], 'incident')
ON CONFLICT (bug_class) DO UPDATE SET
  title = EXCLUDED.title, severity = EXCLUDED.severity, owner_cluster = EXCLUDED.owner_cluster,
  root_cause = EXCLUDED.root_cause, prevention_rule = EXCLUDED.prevention_rule,
  probe_type = EXCLUDED.probe_type, probe_logic = EXCLUDED.probe_logic, status = EXCLUDED.status,
  concepts_affected = EXCLUDED.concepts_affected, fixed_in_files = EXCLUDED.fixed_in_files, row_type = EXCLUDED.row_type;
