-- ============================================================================
-- 2026-06-26: engine_bug_queue scar — current_loop_acts_as_dipole founder review.
-- field_3d scene background went WHITE because pvl_colors was set without a
-- background key and scene.background used an unsafe ternary (not ??).
-- Generated by src/scripts/_seed_engine_bug_queue_current_loop_dipole_review.ts — idempotent.
-- ============================================================================

INSERT INTO engine_bug_queue (bug_class, title, severity, owner_cluster, root_cause, prevention_rule, probe_type, probe_logic, status, concepts_affected, fixed_in_files, discovered_in_session, row_type) VALUES
('field3d_scene_background_white_when_pvl_colors_lacks_background', 'field_3d scene renders on WHITE when pvl_colors is set but omits the background key', 'MAJOR', 'peter_parker:renderer_primitives', 'scene.background was set with a ternary: new THREE.Color(config.pvl_colors ? config.pvl_colors.background : "#0A0A1A"). When a concept declares pvl_colors (e.g. positive/negative for a bar-magnet compare) but omits the background key, config.pvl_colors is truthy so config.pvl_colors.background is undefined → THREE.Color(undefined) defaults to WHITE. The CSS body background (line ~798) used ?? and was correct, but the THREE scene background used the unsafe ternary — so the canvas went white. current_loop_acts_as_dipole was the first concept to set pvl_colors without a background key (all 23 other pvl_colors concepts include one).', 'Engine: read scene background with null-coalescing so a missing key falls back to the dark default — new THREE.Color((config.pvl_colors && config.pvl_colors.background) || "#0A0A1A"). JSON: when a concept sets field_3d_config.pvl_colors, always include "background" (#0A0A1A) like every sibling.', 'manual', 'Seed any field_3d concept whose pvl_colors omits background; the rendered canvas background must be dark (#0A0A1A), not white.', 'FIXED', ARRAY['current_loop_acts_as_dipole'], ARRAY['src/lib/renderers/field_3d_renderer.ts', 'src/data/concepts/current_loop_acts_as_dipole.json'], 'session_2026-06-26_current_loop_dipole_review', 'incident')
ON CONFLICT (bug_class) DO UPDATE SET
  status = EXCLUDED.status, root_cause = EXCLUDED.root_cause,
  prevention_rule = EXCLUDED.prevention_rule, fixed_in_files = EXCLUDED.fixed_in_files;
