-- 2026-07-03: re-scope the 4 pre-Rule-31 Socratic prevention rules in engine_bug_queue
-- (queue audit: only rows whose prevention_rule instructs predict-pause/pause_after_ms
-- behaviour that Rule 31 / Gate 3e forbids on NEW concepts). Rows kept, text re-scoped
-- with a LEGACY retrofit-only banner. Generated by
-- src/scripts/_rescope_legacy_socratic_bug_rows.ts — idempotent.

UPDATE engine_bug_queue SET prevention_rule = 'LEGACY (pre-Rule-31, retrofit-only — NEVER apply to NEW concepts; Rule 31 / Gate 3e forbids predict-pauses and pause_after_ms on new authoring): When retrofitting/porting a LEGACY Socratic field_3d JSON, carry every pause_after_ms from its physics block; field_3d DOES consume pause_after_ms via deriveStateMeta. On NEW concepts there are no prediction pauses to carry — author straightforward distinct-motion beats instead (Rule 31; exemplars faraday_law_induction, magnetisation_and_intensity).'
WHERE bug_class = 'solenoid_dropped_prediction_pauses_x4';

UPDATE engine_bug_queue SET prevention_rule = 'LEGACY (pre-Rule-31, retrofit-only — NEVER apply to NEW concepts; Rule 31 / Gate 3e forbids predict-pauses and pause_after_ms on new authoring): The durable cross-agent lesson is strategy-neutral: when json_author clones/ports an existing JSON, it MUST carry every timing field the physics block authored — dropped fields are silent regressions. The specific field here (pause_after_ms) exists only on LEGACY Socratic JSONs; carry it only when retrofitting those. On NEW Rule-31 concepts never author pause_after_ms at all.'
WHERE bug_class = 'crossagent_jsonauthor_drops_pause_after_ms_cloning_electric_flux';

UPDATE engine_bug_queue SET prevention_rule = 'LEGACY (pre-Rule-31, retrofit-only — NEVER apply to NEW concepts; Rule 31 / Gate 3e forbids predict-pauses and pause_after_ms on new authoring): Gate 3c (Socratic-reveal) is legacy-only and never fires on field_3d (no teaching_method). Gate 15 (Pass-2 four-question) remains the cognitive-flow gate for field_3d — but on NEW Rule-31 concepts it audits straightforward distinct-motion beats + motion-before-words + per-state contextual controls (Gate 3e), and must NOT require pause-before-resolution: predict-pauses are forbidden on new concepts. Audit pause-before-resolution only on legacy Socratic retrofits.'
WHERE bug_class = 'gate3c_does_not_run_on_field3d_use_gate15';

UPDATE engine_bug_queue SET prevention_rule = 'Add a gesture-sequencing primitive so the narrated grip cross-fade actually animates — bind it to the sentence that narrates it via the scenario_cue channel (SET_CUE_TIME + cueTriggerMs, *_at_ms as THE-EYE fallback), never a bare fixed-ms trigger. NOTE (2026-07-03 re-scope): the original phrasing said "lands after the prediction pause (reveal after the question)" — that framing is LEGACY pre-Rule-31; solenoid is a Socratic-era JSON, and on NEW concepts no predict-pause exists (Rule 31 / Gate 3e). The underlying bug (narrated gesture never animates) is strategy-neutral and still OPEN.'
WHERE bug_class = 'solenoid_state5_gesture_sequencing_absent';
