// =============================================================================
// physicsValidator.ts
// Pure, synchronous physics validation for SimulationConfig objects.
// Zero external dependencies — runs in <1ms with no I/O, no AI calls.
//
// Called BEFORE a config is assembled into HTML so that:
//   1. Physically wrong simulations are caught before students see them.
//   2. Failures can trigger a Sonnet retry or fallback config.
//
// Usage:
//   import { validatePhysics } from "@/lib/simulation/physicsValidator";
//   const result = validatePhysics(config, STANDARD_CONSTANTS);
//   if (!result.valid) { console.warn(result.errors); }
// =============================================================================

import type { SimulationConfig, StateConfig } from "./rendererSchema";

// ---------------------------------------------------------------------------
// PhysicsConstants — locked NCERT/SI values injected by the caller
// ---------------------------------------------------------------------------

/**
 * Fundamental physical constants used during validation.
 * These values are locked — never generated by AI.
 * Pass `STANDARD_CONSTANTS` for production use.
 */
export interface PhysicsConstants {
  /**
   * Elementary charge of one electron in Coulombs.
   * NCERT value: 1.6 × 10⁻¹⁹ C
   */
  electron_charge: number; // 1.6e-19

  /**
   * Rest mass of one electron in kilograms.
   * NCERT value: 9.1 × 10⁻³¹ kg
   */
  electron_mass: number; // 9.1e-31
}

/**
 * Standard SI / NCERT constants for Class 12 Current Electricity.
 * Use this as the default second argument to `validatePhysics`.
 */
export const STANDARD_CONSTANTS: PhysicsConstants = {
  electron_charge: 1.6e-19,
  electron_mass:   9.1e-31,
};

// ---------------------------------------------------------------------------
// ValidationResult — returned by validatePhysics
// ---------------------------------------------------------------------------

/**
 * Result object returned by `validatePhysics`.
 *
 * - `valid: true`  → config is safe to assemble into HTML for students.
 * - `valid: false` → `errors` lists every violated rule; caller should retry
 *                    generation or substitute a fallback config.
 */
export interface ValidationResult {
  /** True only when every physics rule passes. */
  valid: boolean;

  /**
   * Human-readable error strings, one per violated rule.
   * Empty array when `valid` is true.
   * Suitable for injection into a Sonnet retry prompt.
   */
  errors: string[];
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Collect all StateConfig objects that are present in the config.
 * Returns STATE_1–STATE_4 in order, skipping undefined entries.
 */
function collectStates(config: SimulationConfig): Array<{ id: string; state: StateConfig }> {
  const entries: Array<{ id: string; state: StateConfig }> = [
    { id: "STATE_1", state: config.states.STATE_1 },
    { id: "STATE_2", state: config.states.STATE_2 },
    { id: "STATE_3", state: config.states.STATE_3 },
  ];
  if (config.states.STATE_4) {
    entries.push({ id: "STATE_4", state: config.states.STATE_4 });
  }
  return entries;
}

// ---------------------------------------------------------------------------
// validatePhysics — main export
// ---------------------------------------------------------------------------

/**
 * Validates a `SimulationConfig` against fundamental physics rules.
 *
 * Rules checked (in order):
 *
 * **Rule 1 — Drift-field opposition**
 * Electrons drift OPPOSITE to the applied electric field.
 * `electron_drift_direction !== field_arrow_direction` must hold.
 *
 * **Rule 2 — Thermal speed dominance**
 * At room temperature, thermal speed (~10⁶ m/s) vastly exceeds drift speed
 * (~10⁻³ m/s). In animation units: every state's `drift_speed` must be
 * strictly less than `particles.thermal_speed`.
 *
 * **Rule 3 — Formula anchor consistency**
 * If a `formula_anchor` with a `live_calculation` is present, the validator
 * performs a basic sanity check: the `formula_anchor.formula_string` must
 * contain at least one of the key physics symbols expected for the drift
 * velocity formula derivation (`e`, `E`, `tau`, `m`, `vd`, `v_d`).
 * A formula string that contains none of these is likely a placeholder or AI
 * hallucination and should be flagged.
 *
 * **Rule 4 — Spotlight state exists**
 * If any state uses `highlight_particle: true`, STATE_3 MUST be defined
 * (by convention, STATE_3 is the "aha moment" spotlight state).
 * Having a spotlight state without STATE_3 breaks the 4-step lesson arc.
 *
 * @param config    The simulation config produced by Claude Sonnet.
 * @param constants Fundamental physical constants (use `STANDARD_CONSTANTS`).
 * @returns         `{ valid: true }` or `{ valid: false, errors: string[] }`.
 *
 * @example
 * const result = validatePhysics(rendererConfig, STANDARD_CONSTANTS);
 * if (!result.valid) {
 *   console.warn("[Validator] Failures:", result.errors);
 *   // retry or use fallback
 * }
 */
export function validatePhysics(
  config: SimulationConfig,
  constants: PhysicsConstants,
): ValidationResult {
  const errors: string[] = [];

  // ── EPIC-C bypass — STATE_1 intentionally shows a student misconception ────
  const epicC = config.epic_mode === 'EPIC_C' && config.state1_is_wrong_belief === true;
  if (epicC) {
    console.log(
      '[physicsValidator] EPIC_C mode detected — STATE_1 validation SKIPPED ' +
      '(intentional wrong-belief demonstration). STATE_2–STATE_4 will be validated normally.'
    );
  }

  // ── Rule 1: Drift direction must OPPOSE field direction ───────────────────
  //
  // Physics: F = qE. For electrons q < 0, so force is anti-parallel to E.
  // Therefore electron drift direction is always opposite to field arrow direction.
  //
  // Opposite-direction pairs (each maps to its own opposite):
  const OPPOSITES: Record<string, string> = {
    left:  "right",
    right: "left",
    up:    "down",
    down:  "up",
  };

  if (config.electron_drift_direction === config.field_arrow_direction) {
    errors.push(
      "Electrons must drift OPPOSITE to electric field direction " +
      `(got drift="${config.electron_drift_direction}", field="${config.field_arrow_direction}"; ` +
      `expected drift="${OPPOSITES[config.field_arrow_direction] ?? "opposite"}")`,
    );
  }

  // ── Rule 2: Max drift speed must be LESS THAN thermal speed ──────────────
  //
  // Physics: vd ≈ 10⁻³ m/s vs vthermal ≈ 10⁶ m/s (ratio ~10⁹).
  // In animation px/frame units the absolute values differ but the ordering
  // MUST be preserved — drift < thermal — or the animation lies to students.
  //
  const allStates = collectStates(config);
  const thermalSpeed = config.particles.thermal_speed;

  let maxDriftSpeed = 0;
  let maxDriftStateId = "STATE_1";

  for (const { id, state } of allStates) {
    // EPIC-C: skip STATE_1 — it intentionally has wrong drift values for pedagogy.
    if (epicC && id === 'STATE_1') continue;
    if (state.drift_speed > maxDriftSpeed) {
      maxDriftSpeed = state.drift_speed;
      maxDriftStateId = id;
    }
  }

  if (maxDriftSpeed >= thermalSpeed) {
    errors.push(
      `Drift speed cannot equal or exceed thermal speed ` +
      `(${maxDriftStateId}.drift_speed=${maxDriftSpeed} >= particles.thermal_speed=${thermalSpeed}). ` +
      `Drift must remain orders of magnitude slower than thermal motion.`,
    );
  }

  // ── Rule 3: Formula anchor consistency ───────────────────────────────────
  //
  // If a formula anchor with a live_calculation block is provided, the formula
  // string must contain at least one canonical drift-velocity physics symbol.
  // An empty string or generic placeholder ("result", "value") is caught here.
  //
  // Note: we do NOT evaluate E or tau because the validator has no simulation
  // context for those — we only check structural presence of known symbols.
  //
  if (config.formula_anchor?.live_calculation) {
    const { formula_string } = config.formula_anchor;
    const { formula: calcFormula } = config.formula_anchor.live_calculation;

    // Known physics symbols that should appear somewhere in the formula strings
    // for drift velocity derivation (vd = eEτ/m or vd = I/neA).
    const KNOWN_DRIFT_SYMBOLS = ["e", "E", "tau", "m", "vd", "v_d", "I", "n", "A"];

    const formulaHasSymbol = KNOWN_DRIFT_SYMBOLS.some(
      (sym) => formula_string.includes(sym),
    );
    const calcHasSymbol = KNOWN_DRIFT_SYMBOLS.some(
      (sym) => calcFormula.includes(sym),
    );

    if (!formulaHasSymbol) {
      errors.push(
        `formula_anchor.formula_string "${formula_string}" contains none of the expected ` +
        `drift-velocity physics symbols (${KNOWN_DRIFT_SYMBOLS.join(", ")}). ` +
        `Verify this is the correct formula and not a placeholder.`,
      );
    }

    if (!calcHasSymbol) {
      errors.push(
        `formula_anchor.live_calculation.formula "${calcFormula}" contains none of the expected ` +
        `drift-velocity physics symbols (${KNOWN_DRIFT_SYMBOLS.join(", ")}). ` +
        `The live calculation expression may be incorrect or empty.`,
      );
    }

    // Cross-check: the electron_charge constant used must match NCERT convention.
    // If the formula string literally includes a numeric value where 1.6e-19 is
    // expected, check it's in the right ballpark (between 1e-20 and 1e-18).
    const numericLiterals = calcFormula.match(/[\d.]+e[-+]?\d+/g) ?? [];
    for (const literal of numericLiterals) {
      const parsed = parseFloat(literal);
      // If the literal looks like it's in the electron-charge range but doesn't
      // match constants.electron_charge within 0.1%, it's a suspicious value.
      if (parsed > 1e-20 && parsed < 1e-18) {
        const percentDiff = Math.abs(parsed - constants.electron_charge) / constants.electron_charge;
        if (percentDiff > 0.001) {
          errors.push(
            `formula_anchor.live_calculation.formula uses electron charge value "${literal}" ` +
            `which differs from the locked NCERT constant ${constants.electron_charge} by ${(percentDiff * 100).toFixed(2)}%. ` +
            `Use e=${constants.electron_charge} exactly.`,
          );
        }
      }
      // Similarly for electron mass (1e-32 to 1e-29 range).
      if (parsed > 1e-32 && parsed < 1e-29) {
        const percentDiff = Math.abs(parsed - constants.electron_mass) / constants.electron_mass;
        if (percentDiff > 0.001) {
          errors.push(
            `formula_anchor.live_calculation.formula uses electron mass value "${literal}" ` +
            `which differs from the locked NCERT constant ${constants.electron_mass} by ${(percentDiff * 100).toFixed(2)}%. ` +
            `Use m=${constants.electron_mass} exactly.`,
          );
        }
      }
    }
  }

  // ── Rule 4: STATE_3 must exist if any state spotlights a particle ─────────
  //
  // The TeacherPlayer lesson arc convention is:
  //   STATE_1 = baseline, STATE_2 = concept activated,
  //   STATE_3 = spotlight / "aha" moment, STATE_4 = interactive.
  //
  // If highlight_particle is used in ANY state, STATE_3 must be defined so
  // the lesson arc has a proper spotlight step for students to land on.
  //
  const anyStateUsesSpotlight = allStates.some(({ state }) => state.highlight_particle === true);

  if (anyStateUsesSpotlight && !config.states.STATE_3) {
    errors.push(
      "STATE_3 must be defined when highlight_particle is used in any state. " +
      "STATE_3 is the designated spotlight / 'aha moment' step in the lesson arc. " +
      "Add a STATE_3 entry with highlight_particle: true and a spotlight caption.",
    );
  }

  // ── Result ────────────────────────────────────────────────────────────────
  return errors.length === 0
    ? { valid: true,  errors: [] }
    : { valid: false, errors };
}
