graph TD
  c0["structure of the eye"]
  c1["least distance of clear vision"]
  c2["near point far point definitions"]
  c3["visual angle apparent size"]
  c4["simple microscope magnifier"]
  c5["compound microscope construction"]
  c6["compound microscope magnifying power"]
  c7["astronomical telescope construction"]
  c8["astronomical telescope magnifying power"]
  c9["terrestrial telescope"]
  c10["galilean telescope"]
  c11["reflecting telescope cassegrain newton"]
  c12["resolving power telescope"]
  c13["resolving power microscope"]
  c14["myopia nearsightedness correction"]
  c15["hyperopia farsightedness correction"]
  c16["presbyopia age related"]
  c17["astigmatism cylindrical lens"]
  c18["periscope TIR prisms"]
  c19["optical fibre endoscope"]
  c20["binocular construction"]
  c21["camera lens aperture relation"]
  c22["human eye vs camera"]
  c23["magnifying glass practical use"]
  c0 --> c1
  c0 --> c2
  c3 --> c4
  c1 --> c4
  c4 --> c5
  c5 --> c6
  c1 --> c6
  c3 --> c7
  c7 --> c8
  c8 --> c9
  c8 --> c10
  c7 --> c11
  c7 --> c12
  c5 --> c13
  c0 --> c14
  c0 --> c15
  c15 --> c16
  c0 --> c17
  c8 --> c20
  c0 --> c22
  c21 --> c22
  c4 --> c23
